### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by conartist6** [downshift-js/downshift#1000]
The assertion is that it "handles accessibility". Great! Could the README include even a short list of the high level features that you get if you use this implementation? I could find no mention of them anywhere.

**Comment by conartist6** [comment]
I infer that responsiveness to common keyboard shortcuts is one thing. I assume that specifying suitable `aria-...` attributes for screen readers is another.

**Comment by conartist6** [comment]
It looks like there are extensive ARIA specs about how certain input types should behave in terms of keyboard shortcuts and attributes, so linking the specs might be sufficient.

**Comment by silviuaavram** [comment]
We have an open PR to improve documentation https://github.com/downshift-js/downshift/pull/1001.

The Readme for both component and hooks point to the fact that we are following ARIA guidelines for select and combobox. I don't see any reason to add that information in the Readme itself.

We can probably add the link to ARIA combobox to the component, as it's done already in `useCombobox` but, as I said, we are already specifying what guidelines we follow.

**Comment by conartist6** [comment]
I think you're rather missing the point, which is that not everyone who lands on your github page or npm package is going to have the same perspective. Certainly some people may thinking "OK, I know what the ARIA spec says but I don't want to have to write that myself". They will not be confused. But other people may have arrived at your documentation other ways. I came across it in existing code and needed to understand what concrete behaviors it implied. Novice programmers may have found a link to your project somewhere and still have no idea whether they should try to use it. They probably also will not understand your usage example either, which is big and complex.

**Comment by conartist6** [comment]
Just for fun, I've tweaked the example to show how I think you could offer simple syntactic sugar over your existing code to make the tool and its concepts more accessible to developers, which I think in turn would help it reach more people in need of the accessibility features it provides:

```js
const MyCombobox = ({ className }) => (
  <Downshift
    onChange={(selection) =>
      alert(selection ? `You selected ${selection.value}` : "Selection Cleared")
    }
    itemToString={(item) => (item ? item.value : "")}
  >
    {({ Input, Item, Label, Menu, Root }) => (
      <div className={className}>
        <Label>Enter a fruit</Label>
        <Root style={{ display: "inline-block" }} suppressRefError={true}>
          <Input />
        </Root>
        <Menu>
          {({ inputValue }) =>
            items
              .filter((item) => !inputValue || item.value.includes(inputValue))
              .map((item, index) => (
                <Item
                  key={item.value}
                  index={index}
                  item={item}
                  style={{ backgroundColor: "white" }}
                  highlightedStyle={{ backgroundColor: "lightgray" }}
                  selectedStyle={{ fontWeight: "bold" }}
                >
                  {item.value}
                </Item>
              ))
          }
        </Menu>
      </div>
    )}
  </Downshift>
);

render(
  <MyCombobox />,
  document.getElementById("root")
);
```

For example the implementation of `Label` would just be `<label {...getLabelProps()} />`.

One other thing of note is that I made the assumption that the menu itself could be allowed to choose not to display itself (or render its children). I think this is what most developers expect.

If you're interested in what I'm proposing, I'm happy to make a PR for it.

**Comment by conartist6** [comment]
Also `Root` is weird name, since it isn't the root. It's more like an `InputWrapper`. I see discussion of its being necessary, but I see no link to a technical discussion of why.

**Comment by conartist6** [comment]
I guess the downside of giving components is that the tag name becomes hardcoded, and very few people probably want to use this with the default tags. It also them inserts those into the react component tree, which may not be desirable
