### ISSUE TITLE
useCombobox asynchronous items and initial value not setting properly

### ISSUE THREAD

**Issue by wsielskx** [downshift-js/downshift#1006]
downshift version: 5.1.1
    node version: codesandbox
    npm (or yarn) version: codesandbox

**What you did**:
I've tried to create controlled combobox using useCombobox with async loaded items.

**What happened**:
To help you understand the problem I've set the first dropdown with an async loaded item list, and the second one has item list immediately. Unfortunately, controlled value is not reflected on the first dropdown. 

![image](https://user-images.githubusercontent.com/32566644/79493039-30400700-8021-11ea-9ecb-fb9469994f1e.png)

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-q8wk2?file=/src/index.js

**Comment by silviuaavram** [comment]
It does have that selected value if you look in the component state.

The problem is that it's not reflecting it in `inputValue`. Related: https://github.com/downshift-js/downshift/issues/982

**Comment by wsielskx** [comment]
That's true I think we can close this in favor of #982
