### ISSUE TITLE
useComboBox does not reset on blur

### ISSUE THREAD

**Issue by valtism** [downshift-js/downshift#1011]
- `downshift` version: `5.2.0`
- `node` version: `12.16.2`
- `npm` (or `yarn`) version: yarn - `1.22.4`

**What you did**:
I am trying to create a combobox that only allows the selection of provided inputs, and resets the input to `selectedItem` on blur as occurs with the main Downshift component: https://downshift.netlify.app/downshift

**What happened**:
The hooks version does not reset the input on blur, allowing you to have free text in the input. https://downshift.netlify.app/use-combobox

**Suggested solution**:
Reset input on blur for combobox to match behaviour of Downshift.

**Comment by silviuaavram** [comment]
Workaround: via `stateReducer` prop, on `InputBlur` action, return no selection (or anything you want really).

Long story: I am not aiming for Downshift parity, I want to create a hook that provides a11y as accurate as possible to an established design pattern. In this case, ARIA combobox pattern: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

Also, I am not going to change anything in `Downshift` feature-wise. It's been there for some time, people are used to it, I will let it be and just maintain it like this.

Getting back to selection at blur. If you take a look at the examples from ARIA in the link, they perform selection at Blur as well. I feel that, on this matter, I would like to do more digging, research more patterns, talk to people, see what other libraries do, etc. If we are going to do a change on how this works, I am interested to keep it persistent.

To conclude, I will leave this open, and we can use it to share findings on this matter: combobox with highlighted item on blur.

**Comment by silviuaavram** [comment]
Tracking this here: https://github.com/downshift-js/downshift/issues/1010
