### ISSUE TITLE
[Typings] Field `type` missing from useCombobox / useSelect 's props.onStateChange

### ISSUE THREAD

**Issue by andrei-datcu** [downshift-js/downshift#1015]
- `downshift` version: 5.2.0

**Problem description**:
According to the docs:
> changes: These are the properties that actually have changed since the last state change. This also has a type property which you can learn more about in the stateChangeTypes section.

Yet in `index.d.ts`:
```
onStateChange?: (changes: Partial<UseComboboxState<Item>>) => void

export interface UseComboboxState<Item> {
  highlightedIndex: number
  selectedItem: Item
  isOpen: boolean
  inputValue: string
}
```
There's no `type` field

**Suggested solution**:
The field seems to be present for `useMultipleSelection`:

```
  onStateChange?: (changes: UseMultipleSelectionStateChange<Item>) => void

export interface UseMultipleSelectionStateChange<Item>
  extends Partial<UseMultipleSelectionState<Item>> {
  type: UseMultipleSelectionStateChangeTypes
}
```
So I guess creating two new interfaces that are extending the `Use.*State` interfaces seems the most consistent option.

**Comment by silviuaavram** [comment]
I took another look at https://github.com/downshift-js/downshift/pull/985 and I think it will fix this, am I right?

**Comment by kimroen** [comment]
> I took another look at #985 and I think it will fix this, am I right?

Yes, I believe so!
