### ISSUE TITLE
setHighlightedIndex appears to have no effect when called from onInputValueChange

### ISSUE THREAD

**Issue by martinpengellyphillips** [downshift-js/downshift#1018]
- `downshift` version: 5.2.2
- `node` version: 13.10.1
- `npm` (or `yarn`) version: 1.22.0 (yarn)

**Relevant code or config**

```javascript
onInputValueChange: () => {
    setHighlightedIndex(0)
}
```

**What you did**:
Tried to manage highlighted index using `setHighlightedIndex` based on input value change (`onInputValueChange`). 

**What happened**:
My component did not re-render with the updated index. Notably, `onHighlightedIndexChange` does get the updated value.

**Comment by silviuaavram** [comment]
Related to 5.2.1. There are two setState triggered (one for input change and one for the function that sets the index) before the render. That hooks state setter is killing me.

Use 5.2.0 for now. We are working on it. Maybe we will call the onChange handlers in a useEffect after all.

**Comment by martinpengellyphillips** [comment]
Thanks for quick reply! 

I had upgraded due to encountering #962 😆 

I'll stick on 5.2.2 for now and just work around this issue.

**Comment by silviuaavram** [comment]
Released 5.2.3-alpha.0 please see how it behaves.

**Comment by silviuaavram** [comment]
If you want to help, please help me test this with the new alpha release.

I am interested to add unit tests for these controlled and onChange cases. For instance calling an action from an onChange, we don't have unit test for that. Any other use cases published here would be very helpful.

Sorry that 5.2.1 broke things, it wasn't intentional, we just wanted to fix the controlled state handler, avoid the react warning and move forward. And we will, just bear with us a little bit more.

**Comment by valtism** [comment]
Ah, didn't see that other issue. Just updated to 5.2.3-alpha.0 and it all looks like it's working! Thank you so much for getting on top of this so quickly 😊

**Comment by martinpengellyphillips** [comment]
Tested `5.2.3-alpha.0` and it fixes this issue. Thank you for quick turnaround on this 😄

**Comment by silviuaavram** [comment]
Released 5.2.3-alpha.1 that should also fix the `inputValue` correctly being applied when `selectedItem` is controlled. Some unit tests should be added to https://github.com/downshift-js/downshift/pull/1020 before the actual release. Let me know if you have any unit test cases so we can add those as well.

**Comment by silviuaavram** [comment]
@martinpengellyphillips do you mind adding a codesandbox to reproduce this issue? I need it for some testing. Thank you!

**Comment by valtism** [comment]
Seems to be working for me 👍

**Comment by m4r35** [comment]
5.2.3 release re-introduced behavior mentioned in [#927](https://github.com/downshift-js/downshift/issues/927). This seem to be a breaking change happening between 5.2.2 and 5.2.3. - https://codesandbox.io/s/useselect-usage-f9pcd.
