### ISSUE TITLE
[useCombobox] submission with enter is prevented unconditionally

### ISSUE THREAD

**Issue by TrySound** [downshift-js/downshift#1019]
- `downshift` version: 5.2.2

**Relevant code or config**

https://github.com/downshift-js/downshift/blob/master/src/hooks/useCombobox/index.js#L257-L268

**What you did**:

Replaced `<Downshift />` with `useCombobox`

**What happened**:

When pressing "Enter" with closed menu form is not submitted.

**Problem description**:

Enter keydown should not be always prevented.

**Suggested solution**:

Copy logic from downshift component
https://github.com/downshift-js/downshift/blob/master/src/downshift.js#L581-L592

**Comment by silviuaavram** [comment]
Can you submit a PR for both hooks?

**Comment by TrySound** [comment]
Which the second hook do you mean?

**Comment by silviuaavram** [comment]
useSelect

**Comment by TrySound** [comment]
Does it make sense for useSelect? AFAIK this works only for inputs.

**Comment by TrySound** [comment]
Done

**Comment by silviuaavram** [comment]
Closing this.
