### ISSUE TITLE
Multiple breaking changes after 5.2.1

### ISSUE THREAD

**Issue by valtism** [downshift-js/downshift#1022]
- `downshift` version: `5.2.1`
- `node` version: `12.16.2`
- `npm` (or `yarn`) version: `yarn 1.22.4`

I was glad to see 5.2.1 fixed the render issue, but it has unfortunately introduced many breaking changes into my implementation.

I used to keep the first option highlighted for selection while typing by setting the highlighted index to `0` on input value change. It now seems setHighlighted fires, but by the time the menu is rendered, the highlighted value is back to `-1` and there is no selection

```javascript
onInputValueChange: ({ inputValue }) => {
  setInputItems(matchSorter(items, inputValue, { keys: [itemToString] }));
  setHighlightedIndex(0);
},
```

I also want to clear the input and open the menu on input focus, but now, strangely, only the function that is second fires. In this case, the input is set to `""`, but the menu does not open. If the order is switched, the menu opens, but the input is not reset.

```javascript
<input
  {...getInputProps()}
  onFocus={() => {
    openMenu();
    setInputValue("");
  }}
/>
```

I thought this ordering may affect the first example, but it seems that `setHighlightedIndex()` is not working regardless of order.

**Comment by silviuaavram** [comment]
Related to https://github.com/downshift-js/downshift/issues/1018. Don't update to 5.2.1 but definitely update to 5.2.3-alpha.0 and see if both the warning and the breaking change is fixed. Thank you!

**Comment by silviuaavram** [comment]
Let's use the issue above for tracking.

**Comment by valtism** [comment]
Ah, didn't see that other issue. Just updated to `5.2.3-alpha.0` and it all looks like it's working! Thank you so much for getting on top of this so quickly :)
