### ISSUE TITLE
ToggleButtonClick missing from UseSelectInterface

### ISSUE THREAD

**Issue by dandubz** [downshift-js/downshift#1025]
- `downshift` version: 5.2.2

**Relevant code or config**

https://github.com/downshift-js/downshift/blob/master/typings/index.d.ts#L342

**What you did**:
Tried to use `useSelect.stateChangeTypes.ToggleButtonClick` in a `stateReducer`

**What happened**:
Received a type error that 'Property 'ToggleButtonClick' does not exist on type'

**Problem description**:
`ToggleButtonClick` is missing from the `UseSelectInterface` interface.

**Suggested solution**:
Add `ToggleButtonClick: UseSelectStateChangeTypes.ToggleButtonClick` to `UseSelectInterface`—happy to create a PR

**Comment by silviuaavram** [comment]
Dammit, you're absolutely right! Please create a PR, thank you!

**Comment by silviuaavram** [comment]
Closing this as fixed.
