### ISSUE TITLE
Input and toggle button don't get focus in VoiceOver

### ISSUE THREAD

**Issue by tcas91** [downshift-js/downshift#1027]
- `downshift` version: 5.2.1
- `node` version:
- `npm` (or `yarn`) version:

**What you did**:
1. Turn VoiceOver on on iOS device
2. Open Safari and go to https://downshift.netlify.app/use-combobox
3. Navigate to example component

**What happened**:
1. Voiceover keeps repeating "Down arrow combobox listbox popup collapsed, double tap to expand" when double tapping on the combobox; expected behavior is to focus on input

2. After forcing focus on input with a long press, it skips accessibility focus on the toggle button on the right

3. There are also issues navigating to input when using Voiceover on desktop. 

**Problem description**:
The presence of container (that has combobox props) seems to prevent VoiceOver from properly navigating to/interacting with elements enclosed within the container. These issues get resolved when the extra combobox container was removed from the example. 

**Suggested solution**:
Change to example usage was made in response to https://github.com/downshift-js/downshift/issues/779 but it seems like ARIA 1.1 pattern has some issues (https://github.com/w3c/aria/wiki/Resolving-ARIA-1.1-Combobox-Issues) and it's been proposed to eliminate the container around `<input>` in ARIA 1.2.

Are there plans to enforcing ARIA 1.2 pattern? My current workaround is to merge `getInputProps` and `getComboxProps`, omit some attributes not required for ARIA 1.2 then passing them to `<input>`.

> The best part of this proposal to eliminate the container is that it is already functional using any screen reader on any desktop platform. There is no need for modification to current screen reader or browser implementations. It even enables access to popup elements that are grids, trees, and dialogs without additional work by screen reader developers.
>
> The ARIA 1.1 pattern is not yet fully functional with any screen reader on any platform. If this proposal to eliminate the container is not adopted in ARIA 1.2, other changes would need to be made to the ARIA specification to resolve the problems with the ARIA 1.1 pattern before screen reader developers can make comboboxes reliably functional.

**Comment by silviuaavram** [comment]
I would not recommend doing this if you are planning to use Windows screen readers (Jaws/NVDA). Last I checked the virtual cursor had no idea on how to interact with the combobox unless the input was wrapped within the combobox div.

As this library means to follow ARIA guidelines we will make the necessary updates once finalised. Until then do what you think it's best for your use cases.
