### ISSUE TITLE
Hook example of downshift checkbox

### ISSUE THREAD

**Issue by daphnesmit** [downshift-js/downshift#1029]
I have a small question:
Is there an example available of a working codesandbox of dowshiftcheckbox (https://codesandbox.io/s/5z711pmr3l?file=/DownshiftCheckbox.js:0-2003)

but then with the hooks version?

**Comment by silviuaavram** [comment]
There isn't but I think it's a great idea to add an example to the docsite! Interested in prototyping one? I can provide guidance if needed.
