### ISSUE TITLE
Menu doesn't close with useSelect in an iframe

### ISSUE THREAD

**Issue by moroshko** [downshift-js/downshift#1035]
- `downshift` version: 5.2.4
- `node` version: 12.6.0
- `npm` (or `yarn`) version: 6.14.4

**Relevant code or config**

```javascript
import React from "react";
import { render } from "react-dom";
import { useSelect } from "downshift";
import Frame from "react-frame-component";
import { items, menuStyles } from "./utils";

function DropdownSelect() {
  const {
    isOpen,
    selectedItem,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps
  } = useSelect({ items });
  return (
    <div>
      <label {...getLabelProps()}>Choose an element:</label>
      <button {...getToggleButtonProps()}>{selectedItem || "Elements"}</button>
      <ul {...getMenuProps()} style={menuStyles}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              {...getItemProps({ item, index })}
            >
              {item}
            </li>
          ))}
      </ul>
      {/* if you Tab from menu, focus goes on button, and it shouldn't. only happens here. */}
      <div tabIndex="0" />
    </div>
  );
}

render(
  <Frame style={{ height: 300 }}>
    <DropdownSelect />
  </Frame>,
  document.getElementById("root")
);
```

**What you did**:
1. Click on the button to reveal the items.
2. Click on the button again to hide the items.

**What happened**:
Items are hidden and immediately revealed again.

**Reproduction repository**: [Codesandbox](https://codesandbox.io/s/useselect-usage-5y2dt)

**Problem description**: The issue occurs only when rendering inside an `iframe`.

**Suggested solution**: 🤔

**Comment by silviuaavram** [comment]
Hey! I am glad you point that out, we should totally add an example in the docs with this. We have so much work to do there, damn ...

https://codesandbox.io/s/useselect-usage-l40g6

I am using the `FrameContextConsumer` and getting the iframe's `window`, then passing it down to `useSelect` via props.environment. I believe this is documented in our repo, but an example to show it off would be awesome. Will leave this open to track this!

**Comment by moroshko** [comment]
Thanks a lot @silviuaavram, you saved my day!
Do you think it's possible to detect that `environment` is expected and throw a warning?

**Comment by silviuaavram** [comment]
I don't know. Do you think it can be straightforward?

**Comment by moroshko** [comment]
@silviuaavram Very similar issue but without the `iframe`: #1037
