### ISSUE TITLE
Items stay open with useSelect in version 5.2.5

### ISSUE THREAD

**Issue by moroshko** [downshift-js/downshift#1037]
- `downshift` version: 5.2.5
- `node` version: 12.6.0
- `npm` (or `yarn`) version: 6.14.5

**Relevant code or config**

```javascript
import React from "react";
import { render } from "react-dom";
import { useSelect } from "downshift";
import { items, menuStyles } from "./utils";

function Dropdown() {
  const {
    isOpen,
    selectedItem,
    highlightedIndex,
    getToggleButtonProps,
    getMenuProps,
    getItemProps
  } = useSelect({
    items,
    onStateChange: changes => {
      console.log(changes);
    }
  });
  return (
    <div>
      <button {...getToggleButtonProps()}>{selectedItem || "Elements"}</button>
      <ul {...getMenuProps()} style={menuStyles}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              {...getItemProps({ item, index })}
            >
              {item}
            </li>
          ))}
      </ul>
      {/* if you Tab from menu, focus goes on button, and it shouldn't. only happens here. */}
      <div tabIndex="0" />
    </div>
  );
}

render(<Dropdown />, document.getElementById("root"));
```

**What you did**:
1. Click the button to reveal the items.
2. Click the button to hide the items.

**What happened**:
Items stay open. They should be hidden on second click.

**Reproduction repository**: [Codesandbox](https://codesandbox.io/s/useselect-usage-o9j4y)

**Problem description**:
In version `5.2.4`, on second click the following changes occur:
* on mouse down: nothing
* on mouse up:   `{type: "__togglebutton_click__", isOpen: false}`

In version `5.2.5`, however, on mouse down fires a change:
* on mouse down: `{type: "__menu_blur__", isOpen: false}`
* on mouse up:   `{type: "__togglebutton_click__", isOpen: true}`

**Suggested solution**: 🤔

**Comment by silviuaavram** [comment]
This makes me sad. I think I know why it's happening because of my previous refactoring, but this should have been caught by a unit test.

```js
      test('opens and closes menu at consecutive clicks', () => {
        const {clickOnToggleButton, getItems} = renderSelect()

        clickOnToggleButton()

        expect(getItems()).toHaveLength(items.length)

        clickOnToggleButton()

        expect(getItems()).toHaveLength(0)

        clickOnToggleButton()

        expect(getItems()).toHaveLength(items.length)

        clickOnToggleButton()

        expect(getItems()).toHaveLength(0)
      })
```

Thank you for reporting this. I will take a look, but I am very sad about the test part.

**Comment by silviuaavram** [comment]
Will augment the test with a state reducer check and submit it with the fix.
