### ISSUE TITLE
Items get automatically filtered when using onInputValueChange after first render

### ISSUE THREAD

**Issue by danisal** [downshift-js/downshift#1039]
- `downshift` version: 5.2.5
- `node` version: 12.16.1
- `npm` (or `yarn`) version: yarn 1.22.4

**Relevant code or config**

```javascript
function DropDownComboBox(props) {
  const { items, item, setSelectedItem } = props;
  const [inputItems, setInputItems] = useState(items);
  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    highlightedIndex,
    getItemProps,
    openMenu,
    selectedItem,
  } = useCombobox({
    items: inputItems,
    selectedItem: item,
    onSelectedItemChange: setSelectedItem,
    onInputValueChange: ({ inputValue }) => {
      setInputItems(items.filter(item => item.name.toLowerCase().startsWith(inputValue.toLowerCase())));
    },
    itemToString: item => item?.name ?? '',
  });

  return (
    <ComboBoxWrapper>
      <Label {...getLabelProps()}>Language</Label>
      <SearchWrapper {...getComboboxProps()}>
        <Search {...getInputProps({ onFocus: openMenu })} />
        <ChevronButton {...getToggleButtonProps()} aria-label="toggle menu" open={isOpen} />
      </SearchWrapper>
      <MenuWrapper>
        <Menu {...getMenuProps()}>
          {isOpen &&
            inputItems.map((item, index) => (
              <MenuItem
                isSelected={selectedItem?.code === item.code}
                active={highlightedIndex === index}
                {...getItemProps({ item, index, key: item.code })}
              >
                {item.name}
              </MenuItem>
            ))}
        </Menu>
      </MenuWrapper>
    </ComboBoxWrapper>
  );
}
```

**What you did**:
I've just made an implementation similar to the one found in the [useCombobox](https://downshift.netlify.app/use-combobox#controlling-state) example.

**What happened**:
Everything work just fine, except for the part that I would like to see the full list of items when opening the dropdown

**Problem description**:
Once an item is selected from the dropdown list, the second time that the dropdown is opened it only shows the selected item and I'm not sure how can I show entire list and the filtered list when using the input

Here are some screenshots

Initial state, when opening the dropdown for the first time
<img width="280" alt="image" src="https://user-images.githubusercontent.com/9869755/81322291-ab7a6300-908b-11ea-9e8a-fdef3c44c21c.png">

After selecting a new language, then the dropdown only shows the selected item, and I would like to show all items
<img width="282" alt="image" src="https://user-images.githubusercontent.com/9869755/81322379-cf3da900-908b-11ea-8f01-62edc39ded89.png">

**Comment by silviuaavram** [comment]
Hey :) this probably is against the whole idea of the combobox idea: filter options based on the text in the input.

If this is your use case, you need to handle this yourself as a custom scenario. Maybe in the filtering function, if selectedItem && selectedItem.name === inputValue, return the whole items. It might be a workaround, I cannot think of any better idea right now. But probably you can come up with something better.

**Comment by danisal** [comment]
Hi @silviuaavram thank for the feedback. I'll try something on my end. Will post the update, in case anyone want to take a look! 

Cheers!

**Comment by danisal** [comment]
Alright, follow your advice and works as expected! Thanks for the help!

Here is the solution:

```javascript
 onInputValueChange: ({ inputValue, selectedItem }) => {
      if (selectedItem?.name === inputValue) {
        setInputItems(items);
      } else {
        setInputItems(items.filter(item => item.name.toLowerCase().startsWith(inputValue.toLowerCase())));
      }
    },
```

**Comment by silviuaavram** [comment]
Awesome! Thank you for using downshift and we will always be happy to receive feedback in order to improve!
