### ISSUE TITLE
useCombobox is selecting the highlighted item on input blur

### ISSUE THREAD

**Issue by kentcdodds** [downshift-js/downshift#1040]
- `downshift` version: latest

**Relevant code or config**

https://codesandbox.io/s/usecombobox-usage-evufg

**What you did**:

1. Focus input
2. Arrow down
3. Tab (or blur input any other way)

**What happened**:

The highlighted item gets automatically selected.

**Problem description**:

I don't *think* this is the way most people would expect this to work, so I thought I'd bring this up.

**Suggested solution**:

Here's the code currently:

https://github.com/downshift-js/downshift/blob/d2b273c54cba3222eade9cf35a9fccc7db50be7d/src/hooks/useCombobox/reducer.js#L110-L119

I *think* the best way to change that would be:

```js
    case stateChangeTypes.InputBlur:
      changes = {
        isOpen: false,
        highlightedIndex: -1,
        inputValue: props.itemToString(state.selectedItem),
      }
      break
```

**Comment by TrySound** [comment]
Is this the same?
https://github.com/downshift-js/downshift/issues/1010

**Comment by kentcdodds** [comment]
I think so, yeah. Sorry I didn't review the issues very well 😬
