### ISSUE TITLE
default "type" to "text" in getInputProps (for web only)

### ISSUE THREAD

**Issue by kentcdodds** [downshift-js/downshift#1048]
What I have to do:

```javascript
<input {...getInputProps({type: 'text'})} />
```

I want to do:

```javascript
<input {...getInputProps()} />
```

If the `type` is not set, then there's no implicit `role` of `textbox` which is what I think we want in the default case. This should only apply to web, not native.

**Comment by kentcdodds** [comment]
Come to think of it, what does native do about all the `aria-` props? 🤔

**Comment by silviuaavram** [comment]
What if they use something other than `input`? We can assume the user wants to have attributes related to a11y, but not the element itself. Even if we have a div as an input (just saying) then all aria attributes should make sense, but the type text ... I don't know. What do you think?

**Comment by kentcdodds** [comment]
Ah, yeah, that's a fair point :+1:
