### ISSUE TITLE
calling selectItem should update the inputValue

### ISSUE THREAD

**Issue by kentcdodds** [downshift-js/downshift#1049]
Here's the current experience (without adding my own state reducer):

```
<div style={comboboxStyles} {...getComboboxProps()}>
  <input {...getInputProps()} />
  <button onClick={() => selectItem(null)} aria-label="clear selection">
    &#10005; <!-- this is an X -->
  </button>
</div>
```

When I click the "X" to clear the selection, the selection does clear, but the input value is unchanged which is a confusing default.

![Screen Recording 2020-05-14 at 12 00 34 PM](https://user-images.githubusercontent.com/1500684/81969175-c2184100-95da-11ea-96b7-f4a9afd93e13.gif)

Here's the implementation:

https://codesandbox.io/s/usecombobox-usage-lkrym?file=/src/index.js:538-858

And here's how I make this work with the state reducer

```javascript
// this is what I have to do to make it work
// but I think this should be the default
stateReducer(state, {type, changes}) {
  if (type === useCombobox.stateChangeTypes.FunctionSelectItem) {
    return {
      ...changes,
      inputValue: '',
    }
  }
  return changes
},
```

I'm pretty sure that the render prop component behaves as I want.

**Comment by silviuaavram** [comment]
Oups. I will update our reducer.

**Comment by kentcdodds** [comment]
Thanks!
