### ISSUE TITLE
Property 'type' does not exist on type 'Partial<UseComboboxState<unknown>>'

### ISSUE THREAD

**Issue by denchen** [downshift-js/downshift#1052]
In the [CodeSandbox example](https://codesandbox.io/s/2wqqxxw6kj?file=/index.js) from the [`useCombobox` page](https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox), I changed `index.js` to `index.tsx` just to check out the typings. And I see this error for `onStateChange`:

```
Property 'type' does not exist on type 'Partial<UseComboboxState<unknown>>'
```

- `downshift` version: 5.4.0
- `node` version: 12.13.0
- `npm` (or `yarn`) version: 6.14.5

**Relevant code or config**

From the official CodeSandebox example, changed to `.tsx` file but otherwise unchanged

```javascript
  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    highlightedIndex,
    getItemProps,
    selectItem
  } = useCombobox({
    inputValue,
    items: getFilteredItems(items),
    onStateChange: ({ inputValue, type, selectedItem }) => {
      switch (type) {
        case useCombobox.stateChangeTypes.InputChange:
          setInputValue(inputValue);
          break;
        case useCombobox.stateChangeTypes.InputKeyDownEnter:
        case useCombobox.stateChangeTypes.ItemClick:
        case useCombobox.stateChangeTypes.InputBlur:
          if (selectedItem) {
            setInputValue("");
            addSelectedItem(selectedItem);
            selectItem(null);
          }

          break;
        default:
          break;
      }
    }
  });
```

I noticed the problem because I was creating a multi-select dropbox following this example, and I got a similar error for `onStateChange()`, except that I have `items` typed to `string[]`:

```
Property 'type' does not exist on type 'Partial<UseComboboxState<string>>'
```

I'm not knowledgable enough with TypeScript to know if the problem lies with Downshift or if it's the example / my code itself.

**Comment by silviuaavram** [comment]
Same as https://github.com/downshift-js/downshift/issues/1015 ?
