### ISSUE TITLE
Function components cannot be given refs when using styled-components with multiSelect

### ISSUE THREAD

**Issue by ncesar** [downshift-js/downshift#1059]
- `downshift` version: 5.4.2
- `node` version: 10.16.3
- `npm` (or `yarn`) version: npm

**Relevant code or config**

```
const Token = React.forwardRef((props, ref) => {
  const { disabled, ...other } = props;
  return (
    <StyledToken disabled={disabled} {...other} ref={ref}>
      simple styled component
    </StyledToken>
  );
});

Token.displayName = 'Token';
```
And multiSelect(a different component from Token) behavior implementation:
```
      <MultiSelectTokenWrapper>
        {selectedItems.map((selectedItem, index) => (
          <Token
            key={`selected-item-${index}`}
            label={selectedItem}
            className="token-component"
            onClick={() => removeSelectedItem(selectedItem)}
            {...getSelectedItemProps({ selectedItem, index })}
        ))}
      </MultiSelectTokenWrapper>
```

**What you did**: Tried to use a styled component receiving `getSelectedItemProps`.

**What happened**: Received `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`
![image](https://user-images.githubusercontent.com/29064514/82586481-ff964480-9b6d-11ea-853b-77d22727d292.png)

**Problem description**: The multiSelect component itself works just fine, but I keep receiving this error in my console, which is driving me crazy because as we can see, I already tried using forwardRef but it doesn't work. If I remove the `Token` styled component and use the `span` from the example, it works just fine.
```
          <span
            key={`selected-item-${index}`}
            {...getSelectedItemProps({ selectedItem, index })}>
            {selectedItem}
            <span onClick={() => removeSelectedItem(selectedItem)}>
              &#10005;
            </span>
          </span>
```

**Comment by silviuaavram** [comment]
Hi! I don't think you need to do any additional magic.

https://codesandbox.io/s/usemultipleselection-combobox-usage-k1hj2

Styled component already has a `ref` prop applied (probably with forwardRef itself). So as long as the `ref` prop name is `ref` (which is what we use by default) everything should be fine.

Give it a spin and let us know if it works.

**Comment by ncesar** [comment]
The issue is that Token is a functional component that uses a styled-component. So I guess this is the problem?

**Comment by silviuaavram** [comment]
Then:
```js
const Label = styled.span``;

const LabelWrapper = React.forwardRef((props, ref) => {
  return <Label ref={ref} {...props} />;
});
```

**Comment by silviuaavram** [comment]
long story short: our getter props apply a ref prop to the element they are destructured upon. If it's a React component, then we must make sure that it has a ref prop and that ref ends up on the HTML element.

So, from our hook to Wrapper, we have forwardRef. From Wrapper to label, we pass directly the ref received from forwardRef to Label, because it's a styled component and it supports refs by default. It will know to use our ref and pass it down to the HTML node.
