### ISSUE TITLE
Is it possible to place selected items inside input using multiSelect?

### ISSUE THREAD

**Issue by ncesar** [downshift-js/downshift#1060]
- `downshift` version: 5.2.4
- `node` version: 10
- `npm` (or `yarn`) version: npm

**What you did**: Tried using `position: absolute` in the `<span>`(using a wrapper, so it will not place a span inside of each other) of the selectedItems to make it appear inside the input but using this way, the width/height of the input will not update according to children numbers.

**What happened**:

**Reproduction repository**: https://codesandbox.io/s/usemultipleselection-combobox-usage-7ljd9

**Problem description**: I'm not able to put selected values inside input without breaking the css

**Suggested solution**: This is what I'm trying to do:  
![image](https://user-images.githubusercontent.com/29064514/82674555-de8b2d80-9c19-11ea-8cd8-bb351aed48a7.png)

**Comment by ncesar** [comment]
I was able to make it work without using an input, just styling like one but I was trying to make the menu keep open until the user clicks outside.

```jsx
return (
  <div className="wrapper" {...other}>
    <div className="input-wrapper" {...getComboboxProps(getToggleButtonProps())}>
      <div className="token-wrapper"
        {...getInputProps(getDropdownProps({ preventKeyAction: isOpen }))}>
        {selectedItems.map((selectedItem, index) => (
          <div
            key={`selected-item-${index}`}
            label={selectedItem}
            className="token-component"
            closable
            onClose={() => removeSelectedItem(selectedItem)}
            {...getSelectedItemProps({ selectedItem, index })}
          />
        ))}
      </div>
    </div>
    <div {...getMenuProps({})}>
      {isOpen && (
        <ul style={customListItemStyle}>
          {!children
            ? getFilteredItems(items).map((item, index) => (
                <ListItem
                  style={setHighlightedIndex(highlightedIndex, index)}
                  key={`${item}${index}`}
                  {...getItemProps({ item, index })}>
                  {item}
                </ListItem>
              ))
            : childrenWithProps}
        </ul>
      )}
    </div>
  </div>
);
```

**Comment by silviuaavram** [comment]
What do you mean by keeping the menu open? Keep it open as a result of what?

**Comment by ncesar** [comment]
When clicking to select an item, usually the menu closes. What I was trying to do is to keep it open after adding.

**Comment by silviuaavram** [comment]
You can use stateReducer to see when a selection is performed, and return isOpen as true.
