### ISSUE TITLE
Render initialInputValue when exists and clearSelection is called

### ISSUE THREAD

**Issue by yudao** [downshift-js/downshift#1061]
- `downshift` version: **5.4.2**
- `node` version: **v12.11.1**
- `npm` version: **6.14.5**

Hi!

Firstly, thanks for your amazing work and for this great library!

I just want to know if there is a way to inject _initialInputValue_ again when the button _close_ is clicked and _clearSelection_ is called?

Thanks a lot!
Cheers,

Yu.

**Comment by silviuaavram** [comment]
Hi! Have you tried defaultInputValue ?

**Comment by yudao** [comment]
Hu @silviuaavram! Thanks for your answer.

Yes I've tested _**defaultInputValue**_ and nothing appear in the input. 

```
 <Downshift
        ref={ref}
        onChange={handleOnChange}
        itemToString={(item) => (item ? item[valueKey] : "")}
        // initialInputValue={initialInputValue}
        initialSelectedItem={initialSelectedItem}
        defaultInputValue={defaultInputValue}
      >
...
 </Downshift>
```
I'm just passing  the **Downshift** props directly by my parent component props. Maybe i'm doing something wrong...  Do I need to place it in input placeholder? or input value?

Cheers,

Yu.

**Comment by yudao** [comment]
Ok sorry I was so impressed by the magic of **Downshift**  that I completely forgot my HTML skills 🤣 

If I place the _**defaultInputValue**_ into the input placeholder everything works fine.

I close this ticket unless you have more tip about this subject.

Again thanks for the amazing work!

Cheers.
Yu.

**Comment by silviuaavram** [comment]
Awesome! Good luck!
