### ISSUE TITLE
[useSelect] Dropdownlist are not closed properly if wrapped by label tag.

### ISSUE THREAD

**Issue by AndreyLuzinov** [downshift-js/downshift#1064]
- `downshift` version: 5.4.2

**Relevant code or config**

`  <label>
    Select
    <DropdownSelect />
  </label>`

**What you did**:
Wrapped dropdownlist with label tag

**What happened**:
Dropdownlist are not closed with mouse (only keyboard works)

![image](https://user-images.githubusercontent.com/8442311/83168225-d5b6c200-a119-11ea-85df-f446c980ee72.png)

**Reproduction repository**:
https://codesandbox.io/s/useselect-usage-z8g1i?file=/index.js

**Problem description**:
According to standard its possible to wrap inputs with label tag but if I do this
for dropdownlist based on useSelect hook then dropdown part are not closed properly with mouse.
Somehow label tag forces dropdownlist to rerender.

**Comment by AndreyLuzinov** [comment]
Please note, I do not want to place label inside Dropdownlist component because I have to use dedicated FormField wrapper with label, tooltip and error message.

**Comment by silviuaavram** [comment]
I don't think adding all that HTML in the `<label>` is the way to go. And you don't need to add the label in the FormField either. Just add a `for` attribute to the label, with an ID, and pass that ID to useSelect labelId prop. Let me know how it goes.

**Comment by AndreyLuzinov** [comment]
I did that and this works.
