### ISSUE TITLE
Focus on item that is most similar to typed input

### ISSUE THREAD

**Issue by aancer-rca** [downshift-js/downshift#1069]
- `downshift` version: 5.2.7
- `node` version: 12.16.2
- `npm` (or `yarn`) version: 1.22.4 ( yarn )

**Relevant code or config**

Using the following sandbox provided on Downshift JS's website: https://codesandbox.io/s/simple-downshift-with-getrootprops-example-24s13

**What you did**:
Hi, I'm attempting to focus on the first item in the typeahead list as I filter with:

`items.filter(item => !inputValue || item.label.toLowerCase().includes(inputValue.toLowerCase()))`

**Problem description**:

The filter works, however, I'm unsure how to ensure that the item that most closely matches the input is focused on. I would like the user to be able to type in the input and be able to simply hit the 'enter' key to select the top most filtered item ( or closely matching item ) whilst typing. How would I do so?

**Comment by silviuaavram** [comment]
Can you use `defaultHighlightedIndex` prop set to 0?

Also please consider upgrading to latest version and switch from Downshift to useCombobox. Thanks and good luck!
