### ISSUE TITLE
method to clearSelection on 2 Select dropdown menus

### ISSUE THREAD

**Issue by kthrone28** [downshift-js/downshift#1070]
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```
 const clearMultiInput = (clearSelection)=>{
    let input1 = document.getElementById("downshift-0-input");
    let input2 = document.getElementById("downshift-1-input");
      //checks if value is not empty
      if(input1.value !== "" && input2.value !== "" ){
         console.log('both not empty input1')
         input1 = (input1 ? setIsClear(clearSelection) : input1)
         input2 = (input2 ? setIsClear(clearSelection) : input2)
      }
  }

       {selectedItem ? (
                <ControllerButton css={{ paddingTop: 4 }} onClick={clearMultiInput(clearSelection)} aria-label="clear selection">
                  <CloseIcon />
                </ControllerButton>
              ) : (
                <ControllerButton {...getToggleButtonProps()}>
                  <ArrowIcon isOpen={isOpen} />
                </ControllerButton>
              )}
**What you did**:

**What happened**:
before the x button is populated. should render as a callback after the x button is render so it can be clicked to  clear. it currently clear as soon as the second input is clicked.

**Reproduction repository**:

**Problem description**:
I am trying to clearSelection of two dropdown input fields. If one dropdown is selected an x is populated to clear, along with the second dropdown when selected. What has to happen is if I click the x on the first dropdown, it will clear the first and second dropdown simultaneously. having issues with my code executing the method. 

**Suggested solution**:

**Comment by silviuaavram** [comment]
Hi! Can you please create a code sandbox with this issue? Also maybe it will be better to just include in the github issue the steps you are performing, your expected result and what it actually happens. Thank you!
