### ISSUE TITLE
[useSelect] Focus is not set to dropdown part if it's open with transition using keyboard.

### ISSUE THREAD

**Issue by AndreyLuzinov** [downshift-js/downshift#1072]
- `downshift` version: 5.4.2
**Relevant code or config**

```javascript

const {
    isOpen,
    selectedItem,
    getToggleButtonProps,
    getMenuProps,
    highlightedIndex,
    getItemProps
  } = useSelect({ selectedItem: props.value, items, onSelectedItemChange });
  return (
    <div>
      <button type="button" {...getToggleButtonProps()}>
        {selectedItem || "Elements"}
      </button>
      <Collapse isOpen={isOpen} transition="height .3s ease-in-out">
        <ul {...getMenuProps()} style={menuStyles}>
          {items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              {...getItemProps({ item, index })}
            >
              {item}
            </li>
          ))}
        </ul>
      </Collapse>
    </div>
  );

```

**What you did**:
I try to add slide down\up animations to useSelect dropdown list implementation with nice
@kunukn/react-collapse library. It work quite well but there is one issue which I hope you can help me with:

- I hit 'Space' on toggle button and then trying to navigate dropdown using keyboard arrows.

**What happened**:
When dropdown is opened with keyboard focus is not set to dropdown part.

![image](https://user-images.githubusercontent.com/8442311/83955496-423d6980-a85c-11ea-9779-cd341304c791.png)

**Reproduction repository**:
https://codesandbox.io/s/useselect-usage-dy6zg?file=/index.js:219-224

**Problem description**:
As you can see focus stayed on toggle button and all keyboard shortcuts are not working.

**Suggested solution**:
My guess its better to wait until transition ends and then set focus but I'm not sure how to achieve this. Please help.

**Comment by AndreyLuzinov** [comment]
I fixed behavior with manual state controling using stateReducer but I'm not sure it's best approach.
`javascript 
  const stateReducer = (state: UseSelectState<any>,
    actionAndChanges: UseSelectStateChangeOptions<any>): UseSelectState<any>  => {
    const {type, changes} = actionAndChanges
    switch (type) {
      case useSelect.stateChangeTypes.ToggleButtonKeyDownArrowDown:
      case useSelect.stateChangeTypes.ToggleButtonKeyDownArrowUp:
      
      // This line might not compile because of https://github.com/downshift-js/downshift/issues/1074
      // replace for 
      // case "__togglebutton_click__" or add 
      // ToggleButtonClick: UseSelectStateChangeTypes.ToggleButtonClick, 
      // in index.d.ts
      case "__togglebutton_click__": //useSelect.stateChangeTypes.ToggleButtonClick:
      {
        if (!state.isOpen) {
          // state opening transition.
          startOpenning();

          return {
            ...changes, // leave all changes as is.
            isOpen: state.isOpen, // but keep dropdown state 'closed' until opening finished.
          }
        }
      }
    }
`

**Comment by silviuaavram** [comment]
Reducer should be a pure function. I don't recommend having side effects in it, they should be added to onStateChange or any other on change handler we provide.

I added a breakpoint in useSelect and the <ul> is focused when the menu opens. Maybe something happens as a result of the wrapper component you use for the animation. I did not dig any deeper.

**Comment by AndreyLuzinov** [comment]
I've pasted reproduction code where keyboard navigation doesn' work.
https://codesandbox.io/s/useselect-usage-dy6zg?file=/index.js:219-224

Have you tried?

**Comment by silviuaavram** [comment]
Why do you need that component anyway? Can't you just create an animation without it, using just CSS?

If you want to use it anyway then you need to figure out why the focus does not move to the menu, when it opens, like it should.
