### ISSUE TITLE
[docs]circularNavigation default is `true` while docs says its `false`

### ISSUE THREAD

**Issue by Puspendert** [downshift-js/downshift#1084]
The default value of `circularNavigation` is `true`, while the documentation says it is `false`. 
Tried the example mentioned for [useCombobox](https://codesandbox.io/s/usecombobox-usage-evufg).

Either need documentation correction or the implementation correction.

**Comment by silviuaavram** [comment]
Hi! Thanks for reporting this, it's a relevant issue. To fix it can you create a PR to update the documentation? The correct value, for combobox, is true.

**Comment by Puspendert** [comment]
Sure, I will.
