### ISSUE TITLE
[useCombobox] onSelectedItemChange never triggered when using controlled selectedItem in React.StrictMode

### ISSUE THREAD

**Issue by emroussel** [downshift-js/downshift#1092]
- `downshift` version: 5.4.5
- `node` version: 12.16.1
- `npm` version: 6.13.4

**What you did**:

Using `useCombobox` with controlled `selectedItem` while on `React.StrictMode`.

**What happened**:

`onSelectedItemChange` is never triggered, making it impossible to update the `selectedItem` in state.

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-ywyct?file=/src/index.js

**Problem description**:

This issue looks similar to #927, but seems to have been reintroduced in [5.2.3](https://github.com/downshift-js/downshift/releases/tag/v5.2.3).

The problem might be linked to [StrictMode double-invoking some functions to warn about side effects](https://github.com/downshift-js/downshift/issues/403#issuecomment-381830044).

**Comment by silviuaavram** [comment]
Hi! If someone wants to figure this one out, I'll be happy to review. Thank you!

**Comment by TrySound** [comment]
I faced this bug aswell. Though codesandbox breaks downshift completely for some reason so here's a better repro.
https://github.com/TrySound/downshift-bug

**Comment by silviuaavram** [comment]
@TrySound @jorgemoya @emroussel can I have a code review and a test of the fix above? Thank you @IwalkAlone !

**Comment by emroussel** [comment]
@silviuaavram I can confirm that it fixes the issue for me!
