### ISSUE TITLE
[useCombobox] No "changes.type" property on onInputValueChange

### ISSUE THREAD

**Issue by vvo** [downshift-js/downshift#1099]
- `downshift` version: 5.4.5
- `node` version: 12.18.1
- `npm` (or `yarn`) version: N/A

**Relevant code or config**

Just the basic example from the docs: https://codesandbox.io/s/usecombobox-usage-ocvnv?file=/src/index.js with:

```js
    onInputValueChange: (...args) => {
      console.log(args)
      // setInputItems(
      //   items.filter(item =>
      //     item.toLowerCase().startsWith(inputValue.toLowerCase()),
      //   ),
      // )
    },
```

**What happened**:

Here's the content of `args` passed to onInputValueChange
```txt
highlightedIndex: -1 // not documented
isOpen: false // not documented
selectedItem: "Fermium" // not documented
inputValue: "Fermium"
```

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-ocvnv?file=/src/index.js

**Problem description**:

Hi there, when using the basic example of useCombobox and reading the documentation at https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox#oninputvaluechange, there should be a changes.type value but there's none. Plus there are other properties not documented.

**Suggested solution**:

🤷‍♂️ Either add type or update documentation. Opinion: I believe it's valuable to have the type in changes object, so you can easily build a menu where selecting an item DOES NOT refines the list of items which is rarely what you want to do when selecting items maybe?

**Comment by silviuaavram** [comment]
Related to https://github.com/downshift-js/downshift/issues/1015.
