### ISSUE TITLE
[useComboBox] Regression in Menu Option Click 5.4.5

### ISSUE THREAD

**Issue by trevorwhealy** [downshift-js/downshift#1101]
**Version with Bug**
5.4.5

**How did you reproduce**
Using the provided codesandbox links, I switched between 5.4.3, 5.4.4, and 5.4.5

**What you did**:
Open the menu with mouse click and selected an item from the list with a mouse click.

**What actually happened**:
The menu stayed opened.

**What was expected**:
The menu would close on item select.

**Suggested solution**:
I recommend reverting this commit since it is the only change between 5.4.4. and 5.4.5:
- https://github.com/downshift-js/downshift/commit/19f6bc022746e859b2a2a98fc625eb3aa2882823#commitcomment-40201914

**Comment by silviuaavram** [comment]
Hi! This issue is only for the action example. Related to https://github.com/downshift-js/downshift/issues/1100. The other examples are not affected.

Will fix the example that is affected. Commit stays.
