### ISSUE TITLE
Usage with typescript Documentation

### ISSUE THREAD

**Issue by ahmad-reza619** [downshift-js/downshift#1102]
- `downshift` version: ^5.4.5
- `node` version: 10
- `npm` (or `yarn`) version: yarn 1.22.0

**Relevant code or config**

Nothing

**What you did**:

i was looking for example on using downshift with Typescript

**What happened**:

No documentation for typescript

**Problem description**:
Missing documentation

**Suggested solution**:
Add docs

**Comment by silviuaavram** [comment]
What specific documentation do you suggest? We have types.

**Comment by ahmad-reza619** [comment]
Oh yeah, my bad, i didn't realize it's already typed. I'm sorry
