### ISSUE TITLE
When opening the item list for the first time, the initially selected item is not scrolled into view

### ISSUE THREAD

**Issue by ddelbondio** [downshift-js/downshift#1106]
- `downshift` version: 5.4.5
- `node` version: N/A (codesandbox)
- `npm` (or `yarn`) version: N/A (codesandbox)

**Relevant code or config**
https://codesandbox.io/s/useselect-usage-53y36

**What you did**:
I configured the initialSelectedItem property in the useSelect hook. I expected the selected item to be scrolled into view automatically.

**What happened**:
The item was only scrolled into view on the second opening of the select.

**Reproduction repository**:
https://codesandbox.io/s/useselect-usage-53y36

**Problem description**:
There seems to be some internal confusion about the hightlighted item. In the first opening `onHighlightedIndexChange` is also not triggered. On subsequent close/open it does get triggerred with -1 / selectedIndex. 

**Suggested solution**:
N/A

**Comment by silviuaavram** [comment]
Hi! I think we missed this case in our function that returns the initial highlighted index. Can you create a PR to fix it please?
