### ISSUE TITLE
Cannot set inputValue state to empty

### ISSUE THREAD

**Issue by abhineettandon** [downshift-js/downshift#1111]
- `downshift` 3.2.10:
- `node` 12.18.1:
- `npm` 6.14.5:
- `yarn` 1.22.4:

First of all thanks for this library. It's awesome. Please consider the following case:

I have a state variable `const [inputValue, setInputValue] = React.useState('')`; passed to `Downshift` assigned to `inputValue` prop. `onChange` prop is handled by `handleChange` method. When is use `setInputValue('')` after pushing the selected item in another const, it doesn't update the state of `inputValue` at all. However if i crate a new state variable for testing purposes and try to set the state in the same method i.e `handleChange`, it updates the state without causing any issue.

My requirement is to empty the search phrase in input box when user select something from the suggestion list. An idea what's going wrong here?

Thanks.

**Comment by silviuaavram** [comment]
Hi, can we have a codesandbox please? Also why not join the cool kids from the future and migrate to `useCombobox`?

**Comment by MonaiThang** [comment]
I had a similar question earlier.

I put a URL to the example source code I did on converting from the old approach into useCombobox as below.
https://github.com/downshift-js/downshift/issues/1139#issuecomment-671001717
