### ISSUE TITLE
Integration with react-laag raises "you forgot to call the getMenuProps getter function" error

### ISSUE THREAD

**Issue by derekhubbard** [downshift-js/downshift#1119]
- `downshift` version: 5.4.6
- `node` version: v12.18.0
- `npm` (or `yarn`) version: 6.14.4 (npm)

**Relevant code or config**

```javascript
import PropTypes from 'prop-types';
import React from 'react';
import { ToggleLayer } from 'react-laag';
import ResizeObserver from 'resize-observer-polyfill';
import { useSelect } from 'downshift';
import Menu from '../../elements/Menu';
import MenuItem from '../../elements/MenuItem';

const Dropdown = ({ children, items, selectedItem }) => {
  const { getToggleButtonProps, getMenuProps, getItemProps } = useSelect({
    items,
    selectedItem,
  });

  return (
    <ToggleLayer
      renderLayer={({ isOpen, layerProps, arrowStyle, layerSide }) => {
        console.log('LOG: isOpen, layerProps, arrowStyle, layerSide', isOpen, layerProps, arrowStyle, layerSide);
        const menuProps = getMenuProps({ ref: layerProps.ref });
        console.log('LOG: menuProps', menuProps);
        return (
          <Menu
            {...menuProps}
            style={{
              ...layerProps.style,
              opacity: isOpen ? 1 : 0,
              transition: 'opacity 0.2s',
            }}
          >
            <>
              {items.map((option, index) => (
                <MenuItem {...getItemProps({ item: option.name, index })} key={`${option.name}${index}`}>
                  {option.content}
                </MenuItem>
              ))}
            </>
          </Menu>
        );
      }}
      ResizeObserver={ResizeObserver}
    >
      {({ triggerRef }) => <span {...getToggleButtonProps({ ref: triggerRef })}>{children}</span>}
    </ToggleLayer>
  );
};

Dropdown.propTypes = {
  children: PropTypes.node.isRequired,
  items: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired,
      content: PropTypes.node.isRequired,
    })
  ),
  selectedItem: PropTypes.any,
};
```

**What you did**:

We have a `Dropdown` component that is implemented using both `downshift` and `react-laag`, following an approach that is very similar to the examples outlined in this blog post: https://dev.to/everweij/accessible-and-adaptive-select-menu-s-using-react-laag-and-downshift-abn

**What happened**:

When using the current version of `downshift` (currently version `5.4.6`), this implementation is continually rendering console errors stating "downshift: You forgot to call the getMenuProps getter function on your component / element".

We were using a previous version of `downshift` when originally implementing this component and this error wasn't occurring at that time.

If we go back to version `5.4.0` of `downshift` the error message goes away, but obviously we'd like to be on the latest version. :) 

**Reproduction repository**:

TBD...

**Problem description**:

When using `downshift` (in our case, the `useSelect` hook) as the `renderLayer` for a `ToggleLayer` from `react-laag`, it seems like `downshift` is expecting that the appropriate prop functions are called _before_ `react-laag`'s `ToggleLayer` is rendering the `renderLayer`. 

I pulled out the call to `getMenuProps` and confirmed the function is actually being called as expected, but this seems to be too late in the rendering process - at this point, `downshift` has already assumed the function wasn't called. 

For example, here is the test output from rendering the `Dropdown` component above using Jest and `@testing-library/react`: 

```
 PASS  src/components/Dropdown/Dropdown.test.jsx
  Components > Dropdown
    ✓ renders and match snapshot (143 ms)
    ○ skipped should render dropdown items when open
    ○ skipped should return selected item
    ○ skipped does not render a menu title if title prop is not passed

  console.error
    downshift: You forgot to call the getMenuProps getter function on your component / element.

      at node_modules/downshift/dist/downshift.cjs.js:2057:19
          at Array.forEach (<anonymous>)
      at node_modules/downshift/dist/downshift.cjs.js:2054:49
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:19731:26)
      at commitPassiveHookEffects (node_modules/react-dom/cjs/react-dom.development.js:19769:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)

  console.log
    LOG: isOpen, layerProps, arrowStyle, layerSide false {
      ref: [Function: ref],
      style: {
        position: 'absolute',
        willChange: 'top, bottom, left, right, width, height'
      }
    } { position: 'absolute', willChange: 'top, bottom, left, right' } top

      at renderLayer (src/components/Dropdown/Dropdown.jsx:18:17)

  console.log
    LOG: menuProps {
      ref: [Function],
      id: 'downshift-0-menu',
      role: 'listbox',
      'aria-labelledby': 'downshift-0-label',
      tabIndex: -1,
      onMouseLeave: [Function],
      onKeyDown: [Function],
      onBlur: [Function]
    }

      at renderLayer (src/components/Dropdown/Dropdown.jsx:20:17)
```

**Suggested solution**:
```¯\_(ツ)_/¯```

Not sure at the moment, but it seems like the `useEffect` hook which is validating that the getter was called within the `useGetterPropsCalledChecker` hook is executing before the `ToggleLayer` actually mounts and renders its `renderLayer` prop. 

https://github.com/downshift-js/downshift/blob/master/src/hooks/utils.js#L409

**Comment by silviuaavram** [comment]
What if you move
```js
  const { getToggleButtonProps, getMenuProps, getItemProps } = useSelect({
    items,
    selectedItem,
  });
```
in the `renderLayer` prop?

**Comment by silviuaavram** [comment]
What if you move
```jsx
  const { getToggleButtonProps, getMenuProps, getItemProps } = useSelect({
    items,
    selectedItem,
  });
```
in the `renderLayer` callback?

I am not sure how `react-laag` works, but please make sure that the Menu is always rendered no matter if the select is open or closed (a11y reasons).

**Comment by derekhubbard** [comment]
Thanks for the suggestion @silviuaavram. 

Moving the use of the `useSelect` function inside the `renderLayer` callback seems to resolve the error. Unfortunately, `getToggleButtonProps`, which is returned by the `useSelect` hook, isn't accessible from the context of the `react-laag` children when rendering the `ToggleLayer`... 

> but please make sure that the Menu is always rendered no matter if the select is open or closed (a11y reasons).

I think that's the root of the challenge with combining the two libraries - the `Transition` wrapping the downshift components is keeping the menu from rendering all the time.

**Comment by silviuaavram** [comment]
Ok, then go back to the original implementation, call `getMenuProps` in `Dropdown` and use its result in `ToggleLayer`. It's an ugly hack but I was expecting for both Dropdown and ToggleLayer to render at the same time, so that's unfortunate.

As for the last part, it's ok to remove the items from the DOM when the menu is closed, just the menu element with no children should be kept. I cannot find the spec right now to give you a link, but in the ARIA page examples if you inspect, the `<ul>` elements are always in the DOM even when the menu is closed. https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html
