### ISSUE TITLE
Incompatible types in stateReducer for useComboBox

### ISSUE THREAD

**Issue by denchen** [downshift-js/downshift#1122]
I upgraded to Downshift 6.0.0, and my types broke with `useComboBox` & `stateReducer`. I looked at the release notes but didn't see anything specific to my setup, though it may be that I just didn't read it thoroughly enough, so if this has been covered already, please excuse me.

- `downshift` version: **6.0.0**
- `node` version: **v12.13.0**
- `npm` (or `yarn`) version: **6.14.6**

**Relevant code or config**

```typescript
function stateReducer(
  state: UseComboboxState<Option>,
  actionAndChanges: UseComboboxStateChangeOptions<Option>
): UseComboboxState<Option> {
  const { type, changes } = actionAndChanges;
  switch (type) {
    case useCombobox.stateChangeTypes.InputKeyDownEnter:
    case useCombobox.stateChangeTypes.ItemClick:
      return {
        ...changes, // default Downshift new state changes on item selection.
        isOpen: state.isOpen, // but keep menu open.
        highlightedIndex: state.highlightedIndex // with the item highlighted.
      };
    default:
      return changes; // otherwise business as usual.
  }
}
```

The above was mostly copied and pasted from the examples in the documentation, though I added what I _believe_ were the right types for `stateReducer()`

**What happened**:

My IDE complains on the two `case` lines as well as the `return changes` line:

```
Type 'UseComboboxStateChangeTypes.InputKeyDownEnter' is not comparable to type 'UseSelectStateChangeTypes'.
Type 'UseComboboxStateChangeTypes.ItemClick' is not comparable to type 'UseSelectStateChangeTypes'.
Type 'Partial<UseComboboxState<string>>' is not assignable to type 'UseComboboxState<string>'.
  Property 'highlightedIndex' is optional in type 'Partial<UseComboboxState<string>>' but required in type 'UseComboboxState<string>'.
```

Again, I looked through the release notes, but I didn't see notice anything relevant to the above that would require updating my types or updating the code itself.

**Comment by silviuaavram** [comment]
Hi! Maybe here https://github.com/downshift-js/downshift/pull/985/files#diff-494415c3af35245ecae73f5d42d8b331R457

I will take another look at the release notes maybe I can add more details about migrating this bit. Feedback is welcome.

**Comment by denchen** [comment]
Okay, if I'm understanding this correctly, `UseComboboxStateChangeOptions<Item>` no longer has a key `type` of type `UseComboboxStateChangeTypes`, but instead it's `UseSelectStateChangeTypes`. I'm not quite sure why this change was made, so if you can add the rationale in the release notes, and how to refactor existing code like the above (because I'm unclear what I should change).

**Comment by silviuaavram** [comment]
Oh found it! It's a bug, `UseSelectStateChangeTypes` should be `UseComboboxStateChangeTypes`. Will fix it.

**Comment by silviuaavram** [comment]
Please review the attached PR.

**Comment by limejoe** [comment]
Well, the issue is pretty clear - since changes become of a type Partial<State>, it li no longer possible to return changes directly like it is written in the docks, because, f.e. `highlightedIndex: number` is not compatible with `highlightedIndex: number | undefined`.
According to this to make this work again @denchen you should update the stateReducer function to something like this 
`
function stateReducer(
  state: UseComboboxState<Option>,
  actionAndChanges: UseComboboxStateChangeOptions<Option>
): UseComboboxState<Option> {
  const { type, changes } = actionAndChanges;
  switch (type) {
    case useCombobox.stateChangeTypes.InputKeyDownEnter:
    case useCombobox.stateChangeTypes.ItemClick:
      return {
        isOpen: state.isOpen, // but keep menu open.
        highlightedIndex: state.highlightedIndex // with the item highlighted.
        selectedItem: changes.selectedItem ?? null,
        inputValue: changes.inputValue ?? ""
      };
    default:
      return {
        highlightedIndex: changes.highlightedIndex ?? -1,
        inputValue: changes.inputValue ?? "",
        isOpen: changes.isOpen ?? false,
        selectedItem: changes.selectedItem ?? null
    };
  }
}
`

@silviuaavram btw, I doubt your PR will fix something because I face the same issue with `useSelect`. Probably the issue can be treated as a documentation bug.

**Comment by silviuaavram** [comment]
My PR will fix the issue with `UseSelectStateChangeTypes`. That was clearly a bug.

Can you help identifying the other issue you are having?

**Comment by limejoe** [comment]
The issue I have for now is that this code from `useSeelct` docs 

```javascript
import {useSelect} from 'downshift'
import {items} from './utils'

const {getMenuProps, getItemProps, ...rest} = useSelect({
  items,
  stateReducer,
})

function stateReducer(state, actionAndChanges) {
  const {type, changes} = actionAndChanges
  // this prevents the menu from being closed when the user selects an item with 'Enter' or mouse
  switch (type) {
    case useSelect.stateChangeTypes.MenuKeyDownEnter:
    case useSelect.stateChangeTypes.ItemClick:
      return {
        ...changes, // default Downshift new state changes on item selection.
        isOpen: state.isOpen, // but keep menu open.
        highlightedIndex: state.highlightedIndex, // with the item highlighted.
      }
    default:
      return changes // otherwise business as usual.
  }
}
```

will not work on TS anymore because changes become `Partial<>`. This is the issue @denchen was talking initially about. It is like breaking change for TS users and there was nothing about it in release notes

**Comment by silviuaavram** [comment]
I think I got it. Then 
```ts
  stateReducer?: (
    state: UseSelectState<Item>,
    actionAndChanges: UseSelectStateChangeOptions<Item>,
  ) => UseSelectState<Item>
```
 needs to return instead `Partial<UseSelectState<Item>>` am I right?

**Comment by silviuaavram** [comment]
Reopening until fixing the other issue.

**Comment by limejoe** [comment]
@silviuaavram , yes, this will definitely fix the issue

**Comment by silviuaavram** [comment]
I am a bit busy with a release atm, can you create a PR to fix for all 3 hooks? And maybe help us out with a better description for the Migration steps of the release. We should also mention people to update to 6.0.2. Thank you!
