### ISSUE TITLE
[useCombobox] How to programmatically focus input?

### ISSUE THREAD

**Issue by fabb** [downshift-js/downshift#1131]
How is it possible to focus the input via a programmatic action?

I didn‘t see an action that allows this: https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox

Also i cannot set a `ref` on the input since `getInputProps` already sets its own ref.

Any hints?

**Comment by silviuaavram** [comment]
Can you provide an sandbox example of what you try to do and does not work?

**Comment by fabb** [comment]
Will do tomorrow

**Comment by fabb** [comment]
Ok I just use `getElementsByTagName`. Would have been nicer via a `ref` but it's ok since I don't allow any children to be passed, so I know that there's only one `<input>` contained.

```
        <Box
            onClick={e => {
                e.currentTarget.getElementsByTagName('input')[0]?.focus()
                e.stopPropagation()
            }}
            css={css`
                cursor: text;

                :focus-within {
                    box-shadow: 0 0 0 3px ${p => p.theme.colors.palette.cyanblue};
                }
            `}
        >
...
        <input ... />
```

**Comment by silviuaavram** [comment]
What is stopping you from using a ref?

**Comment by fabb** [comment]
`getInputProps` returns a `ref` which is necessary for downshift to work correctly:
https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox

**Comment by silviuaavram** [comment]
`getInputProps` does not return any `ref`. It accepts one as a prop if you want to use the same reference as useCombobox.

`<input getInputProps={{ref: youInputRef}} />`

**Comment by silviuaavram** [comment]
You should be able to have your own ref as well. Just pass it to getInputProps as well.

```js
const yourRef = React.useRef()
// do whatever you want with yourRef
<input {...getInputProps({ref: yourRef})}
```

**Comment by fabb** [comment]
Actually the input `ref` stems from `getDropdownProps`. I do it like this example:

https://www.downshift-js.com/use-multiple-selection

The `ref` from `getDropdownProps` gets passed to the `getInputProps` which return it:

```
            <input
              {...getInputProps(
                getDropdownProps({ preventKeyAction: isOpen }),
              )}
            />
```

I'm not completely sure what the `useMultipleSelection` hook needs the `ref` from `getDropdownProps` for, but I'd rather not overwrite it.

**Comment by silviuaavram** [comment]
Focus management from last item to input.

Then pass yourRef to getDropdownProps.

```js
            <input
              {...getInputProps(
                getDropdownProps({ preventKeyAction: isOpen, ref: yourRef }),
              )}
            />
```

**Comment by fabb** [comment]
Ah ok, and then `useMultipleSelection` just uses my ref for its inner workings? Makes sense, that should work, thanks!

**Comment by silviuaavram** [comment]
It actually will pass to `input` as `ref` a function which takes the input element and puts it in your ref, useMultipleSelection ref, and useComboboxRef.😁

**Comment by fabb** [comment]
That sounds just a tad crazy 😅
