### ISSUE TITLE
[useCombobox] How to keep Menu open as long as Input is focused?

### ISSUE THREAD

**Issue by fabb** [downshift-js/downshift#1132]
I want to build a component that immediately shows suggestions in the menu as soon as the input is focused, and keeps showing them even when pressing Escape or selecting an item from the menu with the mouse or the arrow keys and pressing Enter.

I looked into `onStateChange` for achieving this, but unfortunately there is no `InputFocus` event. 

Probably I need to add an `onFocus` event to the input and call [`openMenu`](https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox) there, combined with preventing menu close on all events in `onStateChange` except `InputBlur`.

Or is there a better or recommended way to achieve it?

**Comment by silviuaavram** [comment]
https://www.downshift-js.com/use-combobox#using-action-props

**Comment by silviuaavram** [comment]
I don't think there is a better way, what is wrong with this one?

**Comment by fabb** [comment]
It just feels a bit hacky, but it seems this is the way 😅
I hope `onStateChange` covers all the cases to avoid hiding of the menu. I need to experiment with this.

Thanks for the quick help!

**Comment by silviuaavram** [comment]
`onStateChange` is going to be triggered every time the state changes. By default, useCombobox does not change the state on input blur, so you're not seeing anything as a result of that action.

using openMenu, you will going to have a onStateChange triggered, with a FunctionOpenMenu state change type.

**Comment by fabb** [comment]
I solved it like this:

```
const stateReducer = (state, actionAndChanges) => {
    switch (actionAndChanges.type) {
        case useCombobox.stateChangeTypes.InputBlur:
            return { ...actionAndChanges.changes, isOpen: false }
        case useCombobox.stateChangeTypes.FunctionOpenMenu:
            return actionAndChanges.changes
        default:
            return { ...actionAndChanges.changes, isOpen: state.isOpen }
    }
}

...

    const {
        getInputProps,
        openMenu,
    } = useCombobox({
        stateReducer: stateReducer,
    })

    const dropdownProps = getDropdownProps({
        preventKeyAction: isOpen,
        onFocus: () => {
            // the !isOpen check is necessary, otherwise items can no longer be selected from the menu, seems like openMenu() aborts other pending events inside downshift
            if (!isOpen) {
                openMenu()
            }
        },
    })
    const inputProps = getInputProps(dropdownProps)

...

    <input {...inputProps} />
```

**Comment by fabb** [comment]
The only thing I yet need to fix is that Backspace needs to be able to delete the last selected value, even when the menu is open when the input is focused.

**Comment by fabb** [comment]
Ah stupid me, I had set `preventKeyAction: isOpen`, which prevented Backspace deleting items. After removing that, it works as expected!

**Comment by fabb** [comment]
Btw. I like to blur and clear the input on Escape, this is how I do it:
```
    const dropdownProps = getDropdownProps({
        onFocus: () => {
            if (!isOpen) {
                openMenu()
            }
        },
        onKeyDown: (event) => {
            // needs to be done here since InputKeyDownEscape only triggers onStateChange in case an element from the menu is active
            if (event.key === 'Escape') {
                event.target.blur()
                setInputValue('')
            }
        },
    })
    const inputProps = getInputProps(dropdownProps)
```

**Comment by silviuaavram** [comment]
The input should be cleared automatically on escape by `useCombobox`. As for the blur, I do not recommend doing that, as you will lose the focus. And your users don't want that.

**Comment by fabb** [comment]
Somehow it does not clear on escape, maybe I have messed something up. As for UX of removing focus: good point, will discuss this with our UX designer.
