### ISSUE TITLE
Scrolling Jumpy With Virtualization and useComboBox

### ISSUE THREAD

**Issue by mike391** [downshift-js/downshift#1133]
Hi, I've followed the examples out there for react-virtual and have even tried using react-virtualized as well. I always have the same problem where the scrollbar jumps around as you scroll.  Not sure if this is a `useCombobox` issue or an issue with virtualisation, but Ive tried this with 2 virtualisation libraries and had the same result.

You can see what I mean from this example:

https://codesandbox.io/s/downshift-react-virtual-rmwc-dxmsc?file=/src/App.js

**Comment by ganeshmani** [comment]
@mike391 I am facing the same problem. did you find a fix?

**Comment by yyyyaaa** [comment]
Another issue I can reproduce in your codesandbox:
With the dropdown open, when you scroll down a bit then hover the mouse near the top of the dropdown, it will be scrolled to top abruptly.
![Kapture 2021-05-17 at 17 17 18](https://user-images.githubusercontent.com/16129111/118473211-ecdc2e80-b733-11eb-98a3-27565fed70f5.gif)
