### ISSUE TITLE
Cannot recreate the "complete autocomplete" example with hooks (reset to latest valid value on blur)

### ISSUE THREAD

**Issue by thobas-dnvgl** [downshift-js/downshift#1136]
- `downshift` version: 6.0.2
- `node` version: 10.21.0
- `npm` (or `yarn`) version:  6.14.4

**What you did**:

I am trying to implement a reusable component that behaves like the official example `02-complete-autocomplete.js` ([codesandbox](https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=/src/ordered-examples/02-complete-autocomplete.js&moduleview=1&file=/src/ordered-examples/02-complete-autocomplete.js)) but using the `useCombobox()` hook instead of the HOC.

**What happened**:

I can't get the same behavior as the official example (using the HOC) with hooks.

**Reproduction repository**:

https://codesandbox.io/s/lively-breeze-k8xyn

**Problem description**:

I have almost exactly the same behavior on my project ([codesandbox](https://codesandbox.io/s/lively-breeze-k8xyn?file=/src/styles.css)) except that if you enter a value that is NOT a valid item, it's not cleared/reset on blur.

In the [official codesandbox](https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=/src/ordered-examples/02-complete-autocomplete.js&moduleview=1&file=/src/ordered-examples/02-complete-autocomplete.js), try entering random text (or even a valid entry like "Boba Fett" for instance) and click outside: the content on the input is back to being empty. If you select an item, then enter random text, then click outside it will be back to the previously selected item.

In ([my codesandbox](https://codesandbox.io/s/lively-breeze-k8xyn?file=/src/styles.css) though, anything you type stays inside the input. I had a bug report where the user typed "Spain" (= the entire country name) and left the input by pressing the "Shift" key, which means WITHOUT clicking on any item. The input looked correct, with "Spain" but technically it hadn't been selected and `onChange` hadn't been called. If I could at least get the same behavior as your example, it would be clear to the user that something iswrong.

I tried being adding a `onBlur` event to the input, but I only created more issues.

Am I missing something?

**Comment by thobas-dnvgl** [comment]
I decided to give it a try again, and found that the issue when I use `onBlur` is that it's called even when I click to one of the suggested item. It looks like `onStateChange` + `useCombobox.stateChangeTypes.InputBlur` is called only when clicking outside the whole component or using "Shift".

Unless I am mistaken, adding the following code produces the same behavior as in `02-complete-autocomplete.js`.
```js
onStateChange: (state) => {
  // This is better than listening to onBlur on the input because this one is
  // NOT triggered after a click on an item in the list
  if (state.type === useCombobox.stateChangeTypes.InputBlur) {
    const validItem = options.find((item) => item.name === inputValue);
    if (validItem) {
      // Optimization: don't call selectItem() unless the one we have is different from the already selected one
      if (selectedItem?.value !== validItem.value) {
        selectItem(validItem);
      }
    } else {
      selectItem(selectedItem);
    }
  }
},

**Comment by silviuaavram** [comment]
Let's see what you actually want to achieve. Presumably you have a standard `useCombobox` usage as on https://www.downshift-js.com/use-combobox#basic-usage.

What is the scenario that is not covered by the standard usage and you'd like it implemented?

**Comment by thobas-dnvgl** [comment]
What I want to achieve is exactly the same behavior as in your [official example](https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=/src/ordered-examples/02-complete-autocomplete.js&moduleview=1&file=/src/ordered-examples/02-complete-autocomplete.js) named `02-complete-autocomplete.js` by using the `useCombobox()` hook instead of `<Downshift />`.

Where I struggled to implement was: When the user manually types a value and clicks outside the component (or presses "Shift"), the input is reverted back to it's previous value (as it was before the user started typing).

As a "bonus", (because I got bug reports from users), I wanted to select an item if the user typed entirely a valid option he could chose from. Turns out that we have users who do no like to click on the suggestions and would rather type everything.

It look like I can achieve both behaviors with the code above: https://github.com/downshift-js/downshift/issues/1136#issuecomment-668577208 If you don't think it's hack-ish, this issue ca  be closed :)

**Comment by silviuaavram** [comment]
For the first tissue, I am not sure what is your desired behavior. Using `Downshift` resets on blur, using `combobox` will keep the input value on blur. If you want the former behavior, I suggest using `stateReducer`, capture `useCombobox.stateChangeTypes.InputBlur` and return the state you want given the conditions.

As for the second "bonus" issue, you can probably use `stateReducer` here as well, check the `changes.inputValue` and return a selectedItem if it corresponds to what you want from the `items` prop. You have the `props` passed to stateReducer as well. https://www.downshift-js.com/use-combobox#state-reducer

I think using stateReducer is better because you don't want a side effect based on a state change, you want to actually control the state change itself.

**Comment by thobas-dnvgl** [comment]
That'll do it, thanks a lot for the information!
