### ISSUE TITLE
Initially trigger onChange function

### ISSUE THREAD

**Issue by DeadIine** [downshift-js/downshift#1137]
- `downshift` version: 6.0.2
- `node` version: 12.16.3
- `yarn` version: 1.22.4

**Relevant code or config**

https://codesandbox.io/s/react-final-form-downshift-example-n501d?file=/src/DownshiftInput.js

**What you did**:
I'm using the `selectedItem` prop to have a controlled Downshift input component. (see codesandbox). 
I'm using Downshift together with react-final-form. My goal is to use Downshift also to populate the (initial) values, as the items I use in Downshift are dynamically fetched from a backend and can't be set in the final-form initial values. 

**What happened**:

I was expecting, that the onChange function is triggered also when the component initially renders. But it seems like the item is only set internally in Downshift and does **not** trigger the onChange event.

**Problem description**:
The problem is, that the form values are still empty, although there is an item selected internally in the Downshift component. (see codesandbox)

**Suggested solution**:
I've tried all kinds of props and approaches to get the initial value set in final-form. But imho there should be a (new or existing) prop that sets the value and also initially triggers the `onChange` function

**Comment by silviuaavram** [comment]
Hi! First of all, you can try `useCombobox`.

Secondly, can you help me understand better the scenario? As in step - expectation. It's most probably achievable I just need to understand the workflow :)

**Comment by DeadIine** [comment]
Hi there! Thanks for you reply.

I've changed my implementation to useCombobox 😄 

Regarding the issue, let's say I have several Dropdowns to add a Product to an online store inventory (CMS).

You start with selecting a Hardware (e.g. iPhone), then once you've selected the Hardware, I use redux to filter selectable variants, that only apply to iPhone (gray, black, red, 64GB, 128GB, etc..). For those variants a second dropdown is rendered.

Once you've selected the variant, you'll continue to select accessories that are only available for the specifc hardware/variant combination (again filtered using redux). This could be a case for the phone, or smart watch etc. You can also click on (+) to add multiple accessories for each I render a Dropdown with the available accessories. 
_(in reality I have a couple more dropdowns also for special deals etc.)_

So initially I have all Dropdowns rendered and based on the users input, the available items change. I use the controlled downshift to select the value but also the initial value like:

```javascript
/* 
* items === {key: string, value: string}[]
* value === final-form value for the current dropdown
* items[0] is to select the first item in case there was nothing selected yet. 
* Also, sometimes the dropdown only has 1 item, then I also want item[0] to be pre-selected
*/
selectedItem: items.find((item) => item.key === value) || items[0]
```

and I also use the custom onStateChange prop to trigger the parent final-form `onChange`:

```javascript
// onChange === final-form onChange function for the current dropdown
onStateChange: ({ selectedItem }) => currentItem && onChange(selectedItem.key)
```

The issue now is, that `selectedItem` correctly shows the selected item or `item[0]` in the UI. But my form-values are still empty, this is because the `onStateChange` function was never fired with the initial `selectedItem`. Only once the user manually selects an item, `onStateChange` is triggered.

What I'd like to happen is that whenever `selectedItem` is set or changes, the `onStateChange` function should be triggered.

- Imho, even when the dropdown renders initially, a change from "nothing selected" to e.g. `items[0]` should trigger a stateChange
- When the dropdown only has 1 item, and I use `selectedItem: item[0]`, the user can't re-select the single item, making my form always invalid (cause `onStateChange` is not called, when the same item - `item[0]` - is clicked).

**Comment by silviuaavram** [comment]
So, if I understand, you will have a bunch of stateful data like: `deviceItems`, `variantItems` etc which will be fed to multiple useCombobox via `items` prop. You now want, when you select a device, to put the variant items in the second dropdown and also have the first item selected.

I am not using redux for long (maybe 2 month so I'm a newbie), but I think you will now get, on the next render, the new `variantItems` via props. They will be fed to the `useCombobox` of the variant dropdown, so that's done. Now you need to just use `setSelectedItem` with the first item, which is a method you also get from `useCombobox` (the variant one, not the device), and you're done, next render, your item is selected.

When to call `setSelectedItem` is something you can probably decide better, and the decision should be when the `variantItems` change. It can be in a useEffect, just make sure that it will get triggered only when the items change. Or, naively, you can do the comparison yourself using the previous variantItems held in a ref. Up to you, but maybe you can help us out by creating a codesandbox with a working solution (mocked, of course), so we can maybe put it on the docsite.

Good luck!

**Comment by DeadIine** [comment]
That's actually a very good idea and exactly what I'd need. Unfortunately though, the `setSelectedItem` method is not provided by `useCombobox`. When I destructure `setSelectedItem` it's always undefined. It's also not represented in the types: 
![image](https://user-images.githubusercontent.com/17340162/89449266-1efa4200-d759-11ea-82fd-3fdad531b9cc.png)

I found an example https://codesandbox.io/s/usecombobox-usage-x2hsf?file=/src/index.js where `setSelectedItem` is used as a `useState` hook. Which could actually also work. 

If I use `useCombobox` instead of `Downshift` I can also just trigger a useEffect hook in the beginning and call the `onChange` manually.. Which will change my form values but also the downshift internal value. 

I'll see if I can work something out and try to create a usable sandbox. Thanks!

**Comment by silviuaavram** [comment]
Then ‘selectItem’ instead of ‘setSelectedItem’. Apparently it’s the same
method as the one in Downshift. Let me know if it works for you.

**Comment by DeadIine** [comment]
I've achieved my goal using an `useEffect` hook. I still think though, that downshift should trigger the `onChange` or `onStateChange` on render when you have it as a controlled input.

**Comment by silviuaavram** [comment]
I don't think it should. It should trigger onChange callbacks after its internal state changes. There would be no point to have the onChange handlers called when you give it a different prop. It would be like, hey, I changed this prop, well duuh, I just passed it to you.

Going to close this, thanks for the feedback! You can post the sandbox link here so we can add it to the docsite.
