### ISSUE TITLE
useCombobox - prevent typing into input a value not in items

### ISSUE THREAD

**Issue by made-in-nz** [downshift-js/downshift#1145]
- `downshift` version: 5.4.5
- `node` version: 14.7.0
- `npm` version: 6.14.7

**Problem description**:

Wondering what the approach should be to have a useCombobox that filters as the user types, but I'd like to prevent the user from being able to type in a value into the input that would not match on of the available items.  Currently my useCombobox component will display the filtered items as the user types into the input, but will let the user type anything.  I'd like it to behave more like a select control that prevents the user entering arbitrary values.
I suspect that inputValue needs to be controlled but could not find an example of this.

**Comment by silviuaavram** [comment]
Not really, you probably can just use the `stateReducer` and prevent any input value that you don't want. Probably it's best to show a warning when this happens as well, since it's not really standard what you want to do.

https://www.downshift-js.com/use-combobox#state-reducer uppercases all the input value, so it's similar to what you want.

If you do wish to add a warning however, don't add side effects to the `stateReducer`. We probably need to think of another way, with onInputValueChange and controlled `inputValue`.

**Comment by ryexley** [comment]
@made-in-nz did you ever come up with a solution for this? I would like to be able to implement the same thing, and I've been struggling to figure out a good way to do it. @silviuaavram you mentioned the use of `stateReducer`, but I'm struggling to see how the example that changes the value to uppercase is similar to what we're looking for here, because we're not just looking to change the current input value, we're wanting to limit the user's ability to enter anything that's not in the given list of options. What would be the right way to accomplish that with the `stateReducer`? An example somewhere would be helpful.

Thank you.

**Comment by made-in-nz** [comment]
@ryexley - no I didn't come up with a solution, but would still be interested to know if this is possible with useCombobox.

**Comment by ryexley** [comment]
@made-in-nz thanks for the quick response.

This seems like a reasonable use case to me. Maybe I'm just thinking about it all wrong, but I've not been able to find a good example of this anywhere. At first I thought maybe `useSelect` would be more appropriate for this, but none of the examples I've found for that include the option to allow the user to enter input to filter the list of options. Maybe @kentcdodds knows of an example of something like this somewhere?

**Comment by silviuaavram** [comment]
If the option is not in the list of items, then you will not be able to change `selectedItem`, so that should cover it for you, right? The user will only update the `inputValue`, which is not the same as `selectedItem`. So I'm not sure if you need to do anything else, actually. Or maybe describe the use case again, with steps. Thanks!

**Comment by morganney-ps** [comment]
As [mentioned already](https://github.com/downshift-js/downshift/issues/1145#issuecomment-674144892), you can use `stateReducer` to prevent the user from entering characters that would cause the filtered items to be empty. Here is an example (remember the passed `state` contains the **previous** values):

```js
import { useState, useCallback } from 'react'
import { useCombobox } from 'downshift'
import { matchSorter } from 'match-sorter'

const matchSorterOptions = {
  threshold: matchSorter.rankings.CONTAINS
}
const getFilteredItemsSomehow = (itemsToFilter, textToFilterAgainst) => {
  // This example is using match-sorter but do whatever
  return matchSorter(itemsToFilter, textToFilterAgainst, matchSorterOptions)
}
const BoundedInputComboBox = ({ items }) => {
  const [inputItems, setInputItems] = useState(items ?? [])
  
  // Grab whatever vars you need from useCombobox to render
  useCombobox({
    items: inputItems,
    // This would supersede or possibly collaborate with onInputValueChange
    stateReducer: useCallback(
      (state, actionAndChanges) => {
        const { type, changes } = actionAndChanges

        switch (type) {
          case useCombobox.stateChangeTypes.InputChange: {
            const nextItems = getFilteredItemsSomehow(items, changes.inputValue)

            if (nextItems.length) {
              // If there are found items, update the filtered list and return the changes
              setInputItems(nextItems)

              return changes
            }

            // Otherwise, prevent the inputValue from changing by keeping it fixed on the previous value
            return {
              // Return the usual changes
              ...changes,
              // But override inputValue with previous inputValue, i.e. prevent it from changing
              inputValue: state.inputValue
            }
          }
          default:
            return changes
        }
      },
      [items]
    )
  })

  return (
    // Render
  )
}
```

**Comment by morganney** [comment]
As [mentioned already](https://github.com/downshift-js/downshift/issues/1145#issuecomment-674144892), you can use `stateReducer` to prevent the user from entering characters that would cause the filtered items to be empty. Here is an example (remember the passed `state` contains the **previous** values):

```js
import { useState, useCallback } from 'react'
import { useCombobox } from 'downshift'
import { matchSorter } from 'match-sorter'

const matchSorterOptions = {
  threshold: matchSorter.rankings.CONTAINS
}
const getFilteredItemsSomehow = (itemsToFilter, textToFilterAgainst) => {
  // This example is using match-sorter but do whatever
  return matchSorter(itemsToFilter, textToFilterAgainst, matchSorterOptions)
}
const BoundedInputComboBox = ({ items }) => {
  const [inputItems, setInputItems] = useState(items ?? [])
  
  // Grab whatever vars you need from useCombobox to render
  useCombobox({
    items: inputItems,
    // This would supersede or possibly collaborate with onInputValueChange
    stateReducer: useCallback(
      (state, actionAndChanges) => {
        const { type, changes } = actionAndChanges

        switch (type) {
          case useCombobox.stateChangeTypes.InputChange: {
            const nextItems = getFilteredItemsSomehow(items, changes.inputValue)

            if (nextItems.length) {
              // If there are found items, update the filtered list and return the changes
              setInputItems(nextItems)

              return changes
            }

            // Otherwise, prevent the inputValue from changing by keeping it fixed on the previous value
            return {
              // Return the usual changes
              ...changes,
              // But override inputValue with previous inputValue, i.e. prevent it from changing
              inputValue: state.inputValue
            }
          }
          default:
            return changes
        }
      },
      [items]
    )
  })

  return (
    // Render
  )
}
```

**Comment by silviuaavram** [comment]
It may work, but stateReducer function should be pure, it should not have
side effects. You should use onStateChange or some similar prop instead.

**Comment by morganney** [comment]
> It may work, but stateReducer function should be pure, it should not have
side effects.


Thanks for the reminder, it does definitely work this way, but forgot I was writing a reducer. The call to `setInputItems(nextItems)` is indeed a side-effect and could be done in `onInputValueChange`  instead.

> You should use onStateChange or some similar prop instead.

Yeah, that would help keep the reducer pure. Here's a general direction on preventing user input when the input value would represent an invalid item, i.e. not in the list to choose from:

```js
import { useState, useCallback } from 'react'
import { useCombobox } from 'downshift'
import { matchSorter } from 'match-sorter'

const itemToString = (item) => { /* return a string somehow */ }
const matchSorterOptions = {
  threshold: matchSorter.rankings.CONTAINS
}
const getFilteredItemsSomehow = (itemsToFilter, textToFilterAgainst) => {
  // This example is using match-sorter but do whatever
  return matchSorter(itemsToFilter, textToFilterAgainst, matchSorterOptions)
}
const BoundedInputComboBox = ({ items, initialValue }) => {
  const [inputText, setInputText] = useState(itemToString(initialValue))
  const [inputItems, setInputItems] = useState(items ?? [])
  
  // Grab whatever vars you need from useCombobox to render
  useCombobox({
    itemToString,
    items: inputItems,
    inputValue: inputText,
    // This would supersede or possibly collaborate with onInputValueChange
    onStateChange: useCallback(
      (changes) => {
        const { type } = changes

        switch (type) {
          case useCombobox.stateChangeTypes.InputChange: {
            const nextItems = getFilteredItemsSomehow(items, changes.inputValue)

            if (nextItems.length) {
              setInputText(changes.inputValue)
              setInputItems(nextItems)
            }

            break
          }
          case useCombobox.stateChangeTypes.ItemClick: {
            const nextItems = getFilteredItemsSomehow(items, changes.inputValue)

            if (changes.inputValue && changes.inputValue !== inputText) {
              setInputText(changes.inputValue)
            }

            break
          }
        }
      },
      [items, inputText]
    )
  })

  return (
    // Render
  )
}
```
