### ISSUE TITLE
useComboBox - selectHighlightedItem/selectItemAtIndex?

### ISSUE THREAD

**Issue by mike391** [downshift-js/downshift#1146]
Is it possible to use 'selectHighlightedItem' or 'selectItemAtIndex'? Im doing some custom key combos and want to be able to select an item based on the index.

**Comment by silviuaavram** [comment]
You can `selectItem(items[highlightedIndex])` or `selectItem(items[myIndex])`, `items` being also provided to `useCombobox`. Should work,
