### ISSUE TITLE
useMultipleSelection Example with controlled inputValue is problematic regarding deadkeys and editing in the middle of the input field

### ISSUE THREAD

**Issue by fabb** [downshift-js/downshift#1148]
- `downshift` version: 6.0.3
- `node` version: irrelevant
- `npm` (or `yarn`) version: irrelevant

**Relevant code or config**

This example: https://www.downshift-js.com/use-multiple-selection#usage-with-combobox

**What you did**:

There are 2 issues:

1. Editing something in the middle of the input makes the cursor jump to the end.
2. Entering special characters with deadkeys (e.g. for german umlauts typing `"` and then `o` should result in `ö`) inserts the deadkey as regular character (`"o`).

**What happened**:

1. ![cursor_jump](https://user-images.githubusercontent.com/153960/90221783-2087d200-de0b-11ea-8414-dee1a2e07676.gif)

2. ![deadkeys](https://user-images.githubusercontent.com/153960/90221797-24b3ef80-de0b-11ea-92e7-7db83ce9f8dd.gif)

**Reproduction repository**:

https://www.downshift-js.com/use-multiple-selection#usage-with-combobox

**Problem description**:

The problem in the example is that `setValue` is called too late on the `useCombobox.stateChangeTypes.InputChange` event. That prevents React ignoring the value update which would preserve the cursor position and deadkeys.

**Suggested solution**:

Instead of using `useCombobox.stateChangeTypes.InputChange`, use an `onChange` handler directly on the input:

```
          <input
            {...getInputProps(
              getDropdownProps({
                preventKeyAction: isOpen,
                onChange: e => {
                  setInputValue(e.target.value)
                },
              }),
            )}
          />
```

https://codesandbox.io/s/usemultipleselection-combobox-usage-forked-fixed-deadkeys-and-editing-middle-of-input-rnivj?file=/src/index.js:1094-1134

**Comment by silviuaavram** [comment]
We have a cursor position bug here: https://github.com/downshift-js/downshift/issues/1108 Is it something you want to help us fixing?

**Comment by fabb** [comment]
The question is if this is fixable at all when the requirement is to call `setValue` inside `onInputValueChange`. My guess is that downshift does some dispatching internally that causes `onInputValueChange` called asynchronously, which is too late since the input‘s value needs to be set synchronously for this to work correctly.

**Comment by silviuaavram** [comment]
The way it works: user executes action (input change), we execute dispatch, it executes state reducer, and if `inputValue` did change, we set state with that new value, and afterwards we call the `onInputValueChange`.

There is no async magic, just the fact that it executes on the next render. And if you call a setSomething in that handler, then another render. The cursor thing is something React related, one option is to keep track of the cursor position if you encounter this problem in your use case, and update it yourself. There were many examples on stackoverflow.

The deadkeys issue is something I don't know how to fix.

**Comment by fabb** [comment]
> There is no async magic, just the fact that it executes on the next render.

Yes, that‘s the problem since there is a render in-between that renders the input with the old value, and therefore resets it before it gets updated in the next render.
