### ISSUE TITLE
The form gets automatically submitted

### ISSUE THREAD

**Issue by fcrezza** [downshift-js/downshift#1152]
- `downshift` version: 6.0.3
- `node` version: 10.22.0
- `npm` (or `yarn`) version: 6.14.6

**Problem description**:
I am using useSelect hook inside form element, when I clicked the button to trigger open the menu, the page gets refreshed automatically, it looks like the button has default type to submit.
**Suggested solution**:
add `type="button"` on the element will fix this problem and I think it should be added to the docs, can I open PR for this?

**Comment by silviuaavram** [comment]
Hi! Sure you can, thank you! Please change every useSelect example, in the Readme and in the docsite examples. I will change the code sandboxes afterwards.

**Comment by fcrezza** [comment]
hai @silviuaavram, please check my PR #1153

**Comment by silviuaavram** [comment]
I saw it, the docs are going through some changes at the moment, I am moving them to https://github.com/downshift-js/downshift-docs. If you want to help even further can you please make the same changes to a PR in that repo? Only for the .mdx files. The Readme change stays here.

**Comment by fcrezza** [comment]
yup for sure

**Comment by silviuaavram** [comment]
Solved with PRs in downshift-docs and downshift-examples, closing.
