### ISSUE TITLE
TypeError in isOrContainsNode

### ISSUE THREAD

**Issue by apsavin** [downshift-js/downshift#1155]
- `downshift` version: 3.2.7
- `node` version: v12.13.0
- `npm` (or `yarn`) version: 1.22.4

**What you did**:

I use downshift and everything is great by my tests, but [Sentry](https://sentry.io/) sometimes reports errors

**What happened**:

TypeError downshift/dist/downshift.esm in isOrContainsNode
errorFailed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.

<img width="930" alt="Снимок экрана 2020-08-18 в 12 01 21" src="https://user-images.githubusercontent.com/632171/90472375-03b00f00-e129-11ea-91b7-c4e4fa9a4f65.png">
<img width="943" alt="Снимок экрана 2020-08-18 в 12 01 52" src="https://user-images.githubusercontent.com/632171/90472402-162a4880-e129-11ea-910e-8bc573d4307d.png">

**Problem description**:

When `event.target` is `Window` `isOrContainsNode` fails to execute.

**Suggested solution**:

`return parent === child || child instanceof Node && parent.contains && parent.contains(child);`

**Comment by silviuaavram** [comment]
Can you create a PR with this fix? Thank you!
