### ISSUE TITLE
`useMultipleSelection`: pressing backspace on a selected item can lead to browser navigating back

### ISSUE THREAD

**Issue by bnjmnt4n** [downshift-js/downshift#1160]
- `downshift` version: v6

**What you did**:
Click on an item displayed in a multi-selection list. Press backspace to try to delete the item.

**What happened**:
The browser navigates back to the previous page.

**Suggested solution**:
I would expect downshift to handle preventing browser navigation when an item is selected and the input is not focused.

**Comment by bnjmnt4n** [comment]
In any example using `useMultipleSelection`: for example https://www.downshift-js.com/use-multiple-selection. Click on a selected item and press backspace: the browser will travel back in history.

**Comment by Puspendert** [comment]
Which browser? Everything just working fine on Firefox 79.0

**Comment by bnjmnt4n** [comment]
I'm using Firefox 79.0 (64-bit) on Windows 10. I'm recommend making sure that your browser has click on the link without opening in a new tab to ensure that the browser has some prior history in the stack. Just clicking on the Neptunium multi-select item should do the trick.

**Comment by silviuaavram** [comment]
Managed to repro it on Firefox 80.0.1.

@bnjmnt4n can you create a PR to fix this in `useMultipleSelection` please?

**Comment by bnjmnt4n** [comment]
> @bnjmnt4n can you create a PR to fix this in `useMultipleSelection` please?

Sure I'll try to send in a PR soon.

**Comment by silviuaavram** [comment]
Could not repro this with the latest Firefox. Please re-open it if still an issue.
