### ISSUE TITLE
[useSelect] Typing to select multiple words with a space results in a premature selection

### ISSUE THREAD

**Issue by roypearce** [downshift-js/downshift#1163]
Related: https://github.com/downshift-js/downshift/issues/853

- `downshift` version: 6.0.5
- `node` version: 13.14.0
- `npm` (or `yarn`) version: 6.14.4

Demo https://codesandbox.io/s/useselect-usage-forked-muf3q?file=/index.js

**Problem description**:
While native selects do allow a user to use the space bar to select an option in a select when navigated with arrow keys there is an alternate behavior when typing to select something that includes a space where you can continue typing to further refine the selected option. Downshift's useSelect is selecting an option when the spacebar is pressed regardless of the context of why the spacebar was pressed.

eg Given the following options:
    South Carolina
    South Dakota

I should be able to type `South Dakota` to select that option, but as soon as I type `South ` the South Carolina option is selected.

**Suggested solution**:
The context of a current refinement should be checked before selecting an option with the spacebar, if one exists, continue refining and do not select the option.

**Comment by silviuaavram** [comment]
Hi! Fair point. We should treat this use case. If we have `inputValue` as non-empty string, we should dispatch `MenuKeyDownCharacter` instead of `MenuKeyDownSpaceButton`. Does it make sense? Are you up for a PR?

**Comment by roypearce** [comment]
Would you be okay with something like this? In the current pattern of the code the simplest way to avoid triggering the logic for `MenuKeyDownSpaceButton` is by putting it inside of a conditional so that execution can fall through to the `MenuKeyDownCharacter`. It seems a bit funky to me, but it should have the intended effect without rewriting a lot more.

<img width="494" alt="Screen Shot 2020-08-26 at 12 13 30 PM" src="https://user-images.githubusercontent.com/56841696/91346351-91c56e80-e795-11ea-9a33-37e8ca448412.png">

**Comment by silviuaavram** [comment]
Let me think. Maybe it's OK to trigger `MenuKeyDownSpaceButton`. But instead of returning a selection, it should return the augmented `inputValue` with the new space character.

We should try to make sure that the new changes still perform as we would expect, without some funky magic. What do you think about this approach?

**Comment by silviuaavram** [comment]
Related to https://github.com/downshift-js/downshift/issues/1339
