### ISSUE TITLE
[useCombobox] Blur will select highlighted item when menu is closed

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#1164]
- `downshift` version: 6.0.5

**What you did**:

Have `useCombobox` with `initialHighlightedIndex` or `defaultHighlightedIndex` passed as prop.
Focus input, then blur.

**What happened**:

Item at highlightedIndex gets selected, even though the menu is closed.

**Reproduction repository**:

useMultipleSelection example: https://www.downshift-js.com/use-multiple-selection#usage-with-combobox

**Problem description**:

Selection at blur (apart from clicking outside) should still work, but not in the case when the menu is closed.

**Suggested solution**:

`InputBlur` should also check if `isOpen === true` before selecting the item. If `false`, should do nothing.

**Comment by ndeom** [comment]
@silviuaavram I can take a look at this when I get the chance

**Comment by silviuaavram** [comment]
Yes please! To repro is easy, just go to that link with useMultipleSelection, click on input, hit ArrowLeft, and because of the Blur bug, the item will be added to the selection. Let me know how it goes!

**Comment by ndeom** [comment]
@silviuaavram I believe I've fixed the bug. Here is the change: 

![image](https://user-images.githubusercontent.com/56491159/91872752-d6418600-ec3d-11ea-85b6-65576efed2e8.png)

Both Jest and Cypress tests are passing and I've made a pull request ( #1170 ). There was a Flow test that did not pass for some reason, but it was for a file that I did not edit. I included a picture of the output in the pull request. The additional `else if` had to be added to get all Jest tests to pass, specifically this one: 

![image](https://user-images.githubusercontent.com/56491159/91881233-c9756000-ec46-11ea-939b-47a38ed16f54.png)

**Comment by silviuaavram** [comment]
Can you try to fix it in the reducer directly? I don't think it should be any need to have that condition in the hook directly.

Just look for `InputBlur` in the reducer and you can perform there the check if `state.isOpen` and return new state appropriately. And then see if the tests and your last problem are ok.

Let me know how it goes.

**Comment by ndeom** [comment]
@silviuaavram sure thing. Shouldn't take long.

**Comment by ndeom** [comment]
@silviuaavram I removed the extra `else if` statement and updated the reducer for useCombobox: 

![image](https://user-images.githubusercontent.com/56491159/92066615-f705fa80-ed67-11ea-8153-5d5e0d345f3c.png)

All tests are passing, and, after testing in the docs again, the bug seems to be fixed. The PR is updated. Should be good to go!

**Comment by silviuaavram** [comment]
Fixed in 6.0.6
