### ISSUE TITLE
[useComboBox] downshift: The ref prop "ref" from getInputProps was not applied correctly on your element. 

### ISSUE THREAD

**Issue by mr365** [downshift-js/downshift#1167]
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:

**What happened**:

**Reproduction repository**:

**Problem description**:
downshift: The ref prop "ref" from getInputProps was not applied correctly on your element. 
This is my input element 
```
<input
            className="search_input"
            placeholder={placeholder}
            {...getInputProps({
              ref: TripxInputRef,
              id: "tripx-search-INPro",
              "aria-controls": "downshift-tripx-menu",
              "aria-labelledby": "downshift-tripx-label",
              autoComplete: "on",
            })}
```
The component works fine but I get console error. Any help resolving this would be much appreciated
**Suggested solution**:

**Comment by silviuaavram** [comment]
Can you give us the whole sandbox? It may be something related to that ref
object you are passing.

**Comment by nandayonah** [comment]
Any updated solutions here? I faced the same problem.

**Comment by silviuaavram** [comment]
Can you repro in a sandbox?

**Comment by bhavik-tractable** [comment]
I have same errors.

**Comment by nacho-carnicero** [comment]
Hi, 

I got this error while trying to render a popover in a react portal. It does not happen when the popover is not rendered in the portal. You can see the code here: https://github.com/labelflow/labelflow/commit/a25f7e87aa0bc3ebaa2dc5cc7935af97c712cadb

Hope this helps, cheers!

**Comment by drichard-nexapp** [comment]
For people seeking answers like me. If your ul (where you call getMenuProps) must not be in a conditional render. You must always render it or you get the error.

**Comment by P45QU10U** [comment]
I returned something (a loading component) before my Downshift component. 
The loading component was triggered while my data in my Downshift changes, and I had this error. 
I included the loading in my Downshift and everything is better now.

**Comment by trainoasis** [comment]
Still get the same for getDropdownProps, getInputProps, getComboboxProps & getMenuProps but only when running Jest. Just wanna get rid of this or fix our code (which works). Nothing of the above was the solution in our case.

**Comment by cgarrovillo** [comment]
Do we have an explanation as to why this is happening when a popover is rendered inside a portal?
