### ISSUE TITLE
Add a `isItemDisabled` property to all the hooks

### ISSUE THREAD

**Issue by pedroapfilho** [downshift-js/downshift#1176]
Usually, I get to the point where I have to disable some items from the list, so I have to create a custom callback, that runs like this on the `getItemProps`

```ts
  {...getItemProps({
     disabled: isItemDisabled ? isItemDisabled(item) : false
  })}
```

I think that this should be added to the `hooks`, so it would be easier to add them..

Something like:

```ts
  const state = useSelect({
	isItemDisabled: (item: Item) => boolean;
  });
```

What do you guys think? I can implement it.

**Comment by silviuaavram** [comment]
I know that this can solve a corner case for `disabled` items, specifically on navigation action with the menu closed.

Apart from this is there any other advantage you can think of?

**Comment by pedroapfilho** [comment]
I had to use it to disable sizes out of stock, on a summary page that I'm building.

I'm taking this example from `react-select`, and they have it for `isOptionDisabled` and `isOptionSelected`, that are 2 little nice helpers, that can help a lot to migrate `react-select` components to `downshift`.

One thing that I have to mention is that this one could be just a documented example on the docs, and it would already work.

**Comment by silviuaavram** [comment]
Ok, then go for it. We used disabled in getItemProps back when we did not
navigate with the menu closed. By adding navigation in the combobox with
arrows up/down on closed menu, but also especially on the useSelect many
ways to navigate with the menu closed, we should have this prop.

Firstly we should support both this prop and disabled for getItemProps, and
we will mark it as deprecated in the future. Then remove it.

Do you have anything you need to code it?

**Comment by pedroapfilho** [comment]
Nope, I can do it here, so, the idea is to first implement the `isItemDisabled` and then the `isItemSelected`? Or create one PR for both together? (I think that I should create one for each)

If so, I'll create the PR this weekend.

**Comment by silviuaavram** [comment]
I can see the value for disabled, but why for selected?

**Comment by pedroapfilho** [comment]
Good question, tbh, idk, it's just something that exists on the `react-select`. Should we just skip it for now?

**Comment by silviuaavram** [comment]
I think so. The disabled part is helpful for item navigation and selection
with the menu closed. The selected part isn’t something that brings us a
benefit, or I am not seeing it at the moment.

**Comment by pedroapfilho** [comment]
Alright, so be it.

**Comment by connorProgrammes** [comment]
Hi @silviuaavram I have taken on this issue since it seems like it was never added. I opened a Pull Request here: https://github.com/downshift-js/downshift/pull/1194. It's not finished but I wanted to open it and see if you agree with the direction I am going with it.

**Comment by silviuaavram** [comment]
This has been added to 8.0.0.

**Comment by reverie** [comment]
Docs (is there a better link?)

https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V8.md#isitemdisabled
