### ISSUE TITLE
[useSelect] Dropdown doesn't get closed on selection change in case of defaultIsOpen.

### ISSUE THREAD

**Issue by AndreyLuzinov** [downshift-js/downshift#1177]
- `downshift` version: 6.0.6

**Relevant code or config**

```javascript
  const {
    isOpen,
    selectedItem,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps
  } = useSelect({ items, defaultIsOpen: true });
```

**What you did**:
Set defaultIsOpen to true

**What happened**:
Dropdownlist doesn't get closed on item select (by mouse or keyboard).
However I can still close it by click toggle button or click outside dropdown.

**Reproduction repository**:

https://codesandbox.io/s/loving-worker-sifxr?file=/src/index.js

**Comment by silviuaavram** [comment]
As per documentation:

This is the value to set the isOpen to anytime downshift is reset, when the the selection is cleared, or when an item is selected
