### ISSUE TITLE
Auto Placement?

### ISSUE THREAD

**Issue by mike391** [downshift-js/downshift#1183]
Is there a way to have the menu open upwards if it will overflow the bottom of the page?  I am using useCombobox and popperjs and cannot find a way to do this.

**Comment by silviuaavram** [comment]
Hi @mike391 ! This is a question related to popper, since that is used for the UI. I am not knowledgeable in popper but they should support placement options.

**Comment by silviuaavram** [comment]
From popper website (https://popper.js.org/) in the `FLIPPING` section they should already support this.
