### ISSUE TITLE
Examples in codesandbox don't work 

### ISSUE THREAD

**Issue by mgpGit** [downshift-js/downshift#1185]
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:
Clicked to see in a browser some of the examples

**What happened**:
A codesandbox opened up but w/ no example of a working autocomplete.

![image](https://user-images.githubusercontent.com/8506767/95354602-386b5780-088a-11eb-83b9-0b52cd955abc.png)

**Reproduction repository**:

**Problem description**:

**Suggested solution**:

**Comment by mgpGit** [comment]
demo examples have been moved to https://www.downshift-js.com/use-combobox.

Codesandbox examples still don't work though...

**Comment by silviuaavram** [comment]
Hi! Read what’s in that sandbox and you will find out how to get the view
to switch to the example. Thanks!

**Comment by clemwo** [comment]
I feel ultra retarded having to ask this but I cannot figure out how to open an example. Where exactly do I have to click? 
The browser preview is the window on the right half but there is no button "Project View"

![image](https://github.com/downshift-js/downshift/assets/86926547/2eb3bc57-05a9-4a6d-86db-d461dc4c936d)
