### ISSUE TITLE
[useMultipleSelection] `onSelectedItemsChange` doesn't fire when using controlled `selectedItems`

### ISSUE THREAD

**Issue by stevenocchipinti** [downshift-js/downshift#1188]
- `downshift` version: v6.0.5
- `node` version: v14.12.0
- `yarn` version: Yarn v1.22.4

**Relevant code or config**
```js
  const [options, setOptions] = useState([items[0], items[1]])

  const {
    getSelectedItemProps,
    getDropdownProps,
    addSelectedItem,
    removeSelectedItem, // This doesn't work well
    selectedItems,
  } = useMultipleSelection({
    selectedItems: options,
    onSelectedItemsChange: ({selectedItems}) => setOptions(selectedItems),
  })
```

**What you did**:
- Attempting to use an external `useState` as source of truth, being passed in as a control prop to `useMultipleSelection`.
- There are normally 3 ways of deleting a selected item:
  1. Press backspace from the `<input>`
  2. Select the option pill and press the `delete` key on the keyboard
  3. Press the close button (which calls `removeSelectedItem`)

**What happened**:
Pressing the close button on the option does not remove that option.
The other two methods (backspace, selecting and deleting) work fine.

**Reproduction repository**:
https://codesandbox.io/s/blissful-microservice-5j7do?file=/src/hooks/useMultipleSelection/combobox.js

**Problem description**:
Pressing the close button does call `removeSelectedItem` but the `onSelectedItemsChange` callback is not fired with the new state in response to this.

**Suggested solution**:
When calling `removeSelectedItem` with controlled `selectedItems`, it should fire the `onSelectedItemsChange` callback just like when backspace or selecting and deleting.

**Comment by silviuaavram** [comment]
Interesting, we should look into it. Thanks for reporting!

**Comment by silviuaavram** [comment]
use it like this
```jsx
              onClick={e => {
                e.stopPropagation();
                removeSelectedItem(selectedItem)
              }}
```

I cannot remember why you had to do this, but I will try to remember and mention it in the docs. Or fix it, I don't know.

**Comment by stevenocchipinti** [comment]
Thank you for the quick reply!
`e.stopPropagation();` works!
