### ISSUE TITLE
Newer Chrome versions ignore autocomplete=off

### ISSUE THREAD

**Issue by fabb** [downshift-js/downshift#1189]
- `downshift` version: 6.0.5
- `node` version: 12.18.4
- `npm` version: 6.14.6

**Relevant code or config**

See code for example here: https://www.downshift-js.com/use-multiple-selection.

**What you did**:

Click into the combobox of a multiselect combobox as the one here: https://www.downshift-js.com/use-multiple-selection.

**What happened**:

The native Chrome autofill menu appears above our custom downshift combobox menu.

![screenshot-1](https://user-images.githubusercontent.com/153960/96859807-3d233480-1462-11eb-97b4-581aff1d03ef.png)

**Reproduction repository**:

I couldn't reproduce it on https://www.downshift-js.com/use-multiple-selection yet, maybe I would need to submit a form with some value so Chrome stores it in its autofill cache.

**Problem description**:

Chrome chose to ignore `autocomplete="off"`: https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

**Suggested solution**:

According to the Chrome issue comment, a custom value should be used, e.g. `autocomplete="my-custom-field-type"`.

Not sure about cross-browser compatibility though.

**Comment by silviuaavram** [comment]
That thread is from 2016 🧐

**Comment by fabb** [comment]
Interesting, we just started noticing it recently. Maybe the issue existed previosly too, but we didn‘t run into a case that persisted the address to the chrome autofill cache.

**Comment by mglavall** [comment]
Hey! we are also experiencing this. I've tried to override the downshift autocomplete by `...getInputProps({  autocomplete: "nope" })` but didn't succeed. Any ideas on this?

**Comment by silviuaavram** [comment]
You can override by adding props after the getInputCall, but your example
should work as well. Can you check the code and see if there is a bug?
