### ISSUE TITLE
[useSelect] preventDownshiftDefault = true doesn't seem to be working with getToggleButtonProps

### ISSUE THREAD

**Issue by vtrpldn** [downshift-js/downshift#1196]
- `downshift` version: 4.0.2
- `node` version: 14.6.0
- ` yarn` version: 1.22.5

**Relevant code or config**

```javascript
      <button
        type="button"
        {...getToggleButtonProps({
          onKeyDown: (e) => {
            if (e.key === 'Enter') {
              e.nativeEvent.preventDownshiftDefault = true
            }
          },
        })}
      >
```

**What you did**:

I have a custom Select and need to make it so that an Enter keydown submits the form instead of opening the menu.

I tried adding the code below to my toggle button keydown event but it didn't work.

```js
if (e.key === 'Enter') {
  e.nativeEvent.preventDownshiftDefault = true
}
```

I even forked the example codesandbox and tried it there to the same result, so I'm at a loss here 😕

I feel like I'm missing something. Is this the correct way to do it?

**Reproduction repository**:

https://codesandbox.io/s/async-bird-vm5p6?file=/src/hooks/useSelect/basic-usage.js:522-631

**Comment by silviuaavram** [comment]
Hi @vtrpldn I cannot open the sandbox.
