### ISSUE TITLE
A11y-status-message is not clean up, when is created outside of default document

### ISSUE THREAD

**Issue by kolaps33** [downshift-js/downshift#1200]
- `downshift` version:  "5.0.5" and tested as well with the version "5.2.3" and could observe the same behavior
- `node` version: v12.14.1
-  `yarn` version: 1.22.0

Precondition: NVDA or JAWS screen reader is running

Repro steps:
1. Navigate to the example:
https://codesandbox.io/s/fluent-ui-example-forked-dicun?file=/example.js:859-873
2. Click "Open window" button
3. In new opened window into the input type some characters like "adfdsafdsafsa"
4. 'We couldn't find any matches' is visible in UI and screen reader narrates "No results are available."
5.  Press tab key navigate to the button "just to set focus"
6. Switch to virtual cursor mode(JAWS) or to browse mode(NVDA)  (is not required if reader did it automatically itself)
7. Keep press down arrow key to navigate in the reader mode
8. Observe screen reader narration 

Actual: screen reader navigate and narrate the message "No results are available."
![image](https://user-images.githubusercontent.com/22620150/100747711-b22f4580-33e2-11eb-92e6-81e9bbe789b9.png)

Expected: screen reader should not navigate to the message 

**Problem description**:
Issue is that a11y-status-message is not clean up after timeout. Message stays there and screen reader then navigate into the message. 
![image](https://user-images.githubusercontent.com/22620150/100747774-c410e880-33e2-11eb-985c-30eed5f114a7.png)

**Suggested solution**:
**Comment** 
cleanupStatus() always tries to remove the message from default document as getStatusDiv() is called without any arguments

**Comment by silviuaavram** [comment]
Thank you for posting this. When you have a fix please submit a PR.

**Comment by kolaps33** [comment]
@silviuaavram  please if you could see related PR
https://github.com/downshift-js/downshift/pull/1204/files

**Comment by silviuaavram** [comment]
Fixed by https://github.com/downshift-js/downshift/pull/1204
