### ISSUE TITLE
[useSelect] Trigger not focused when clicking outside the menu

### ISSUE THREAD

**Issue by mrodrigues95** [downshift-js/downshift#1206]
- `downshift` version: 6.0.7
- `node` version: 13.13.0
- `npm` (or `yarn`) version: 6.14.4

**Relevant code or config**
```javascript
  return (
    <>
      {React.cloneElement(menuButton, {
        ...triggerProps,
        ...getToggleButtonProps({ ref: triggerProps.ref }),
      })}
      {renderLayer(
        <ul
          className={clsx(
            'p-2 w-64 ml-8 bg-white font-medium border border-gray-200 rounded-md shadow-lg outline-none list-none',
            isOpen ? 'block' : 'hidden'
          )}
          {...layerProps}
          {...getMenuProps({ ref: layerProps.ref })}
        >
          {isOpen && (
            <>
              {(items as Item[]).map((item: Item, index: number) => (
                <li
                  className={clsx(
                    'block w-full px-4 py-2 text-sm leading-5 rounded-md text-left cursor-pointer truncate',
                    highlightedIndex === index
                      ? 'bg-blue-100 text-gray-900'
                      : 'text-gray-700'
                  )}
                  key={index}
                  {...getItemProps({ item: item, index })}
                >
                  {item.name}
                </li>
              ))}
            </>
          )}
          <Arrow {...arrowProps} />
        </ul>
      )}
    </>
  );
```
**Problem description**:
I'm currently using Downshfit with react-laag to create a menu that will be rendered within a React portal. 

The problem I am facing is when I click outside the menu and it closes, the focus isn't set back onto the button. But, when I select an item from the menu or hit escape, the focus is put back onto the button which is what I need.

Why would clicking outside the menu not focus the trigger?

**Comment by silviuaavram** [comment]
Hi!

When you click outside you are basically blurring the select. The focus goes, as in any other case, to the `<body>`, or if you click on a focusable element, on that element.

Escape / Selecting an item is different, it's not a blur action.

If you really want your behaviour to happen, you can use `onIsOpenChange`, capture the `MenuBlur` event, and focus the trigger button when `isOpen` is false.

Or in a `useEffect` every time `isOpen` is changed to false, check if triggerButton is focused and focus it if not.

Let me know what you think.

**Comment by mrodrigues95** [comment]
Hi,
Thanks for the response - that clears everything up. I just wasn't sure if this was default behavior or something that needed to be checked on a case by case basis.
Thanks.
