### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by talamcol** [downshift-js/downshift#1207]
- `downshift` version: `6.0.0`
- `node` version: `14.15.1`
- `npm` (or `yarn`) version: `npm 6.14.8`

**What you did**:
I am passing an `async` onChange() method to the downshift component.

**What happened**:

![image](https://user-images.githubusercontent.com/71456764/102767061-53c10b80-437f-11eb-9935-c6cce83f128c.png)

**Problem description**:
It is technically possible, that the promise of the async onChange function is resolved after the downshift component is unmounted. 

**Suggested solution**:
It is probably related to https://github.com/downshift-js/downshift/issues/476. The async calls must be canceled in the componentWillUnmount method

**Comment by silviuaavram** [comment]
I think it is up to you to not do a a state change if the component is un-mounted.
