### ISSUE TITLE
Question: using downshift pattern in vue3

### ISSUE THREAD

**Issue by youngboy** [downshift-js/downshift#1208]
Hi, I like the downshift's idea of simplify code experience for various complex select component. But unfortunately my job require me to code vue at the most time 😢

Then I saw theres other open source projects of vue+downshift, but there're either no longer to maintain or archived.

Since vue 3 is there and its composition-api share a lot of common with react hooks, i curious that if maintainer willing to support vue 3, or how is your think about it.

If no, i have interest to develop vue3 extension to adopt downshift, but want keep update with downshift-js, and unwilling to copy lot of code for just few custom modification😢. Any suggestion ? 

Thanks for your reading ~

**Comment by silviuaavram** [comment]
Hi! I think it's a great idea! I did not use vue at all, but I am happy to help out. The vue solution can be part of downshift-js.

When I wrote the hooks I started with useSelect, so I probably would do that in vue as well. What do you think?

**Comment by vincerubinetti** [comment]
An alternative for Vue seems to be [`vue-combo-blocks`](https://github.com/sssmi/vue-combo-blocks), though it doesn't seem as used and battle-tested as `downshift`.

Does anyone know of any other alternatives? The thing I'm particularly looking for is a library that does it in a similar "atomic" way -- i.e. `getLabelProps`, `getMenuProps`, etc -- so I can build the component exactly how I want to.

I agree it'd be great to have a first party Vue version of downshift.

**Comment by solamichealolawale** [comment]
> Does anyone know of any other alternatives? The thing I'm particularly looking for is a library that does it in a similar "atomic" way -- i.e. `getLabelProps`, `getMenuProps`, etc -- so I can build the component exactly how I want to.

There is another alternative [vue-multiselect](https://vue-multiselect.js.org/). Just that its not atomic like you're looking for. I am just putting it here just in case

**Comment by silviuaavram** [comment]
Closing as we will not have any action ourselves here. Not in the near future at least, but it's a great thing to do if someone is willing to!
