### ISSUE TITLE
onBlur and onSelectedItemChange order when using tab

### ISSUE THREAD

**Issue by tu4mo** [downshift-js/downshift#1220]
- `downshift` version: 6.0.15

**Reproduction repository**:

https://codesandbox.io/s/amazing-brown-8n10k?file=/src/hooks/useCombobox/basic-usage.js

**Problem description**:

Choosing an option with tab fires onBlur before the selection happens. This is causing problems if forms use the blur event to handle the value in someway.

Is there a way to fire onBlur after the change?

**Comment by silviuaavram** [comment]
I don't think so. The order of the event handlers being called should not matter. Here we call yours before our dispatch, but again, it should not matter.

If you need to invoke an action after the change, then use `onSelectedItemChange` and perform your form logic if `type` is `stateChangeTypes.InputBlur`. It's the proper way to do it.

More details in the documentation on the state change types and the callback prop. https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox#onselecteditemchange
