### ISSUE TITLE
Clicking outside Combobox with menu closed doesn't fire __input_blur__ event

### ISSUE THREAD

**Issue by devacc5566** [downshift-js/downshift#1221]
- `downshift` version: **v6.0.16**
- `node` version: **v14.15.4**
- `npm` (or `yarn`) version: **6.14.10**

**Relevant code or config**

Added `stateRedcuer` function to log all action types fired by Combobox:
```javascript
const stateReducer = (state, actionAndChanges) => {
  const { type, changes } = actionAndChanges;
  console.log('action type: ', type);
  return changes;
}
```

**What you did**:
Go to attached example and open console to track logged actions.

1. Type 'a' char
2. Hit escape key
3. `__input_keydown_escape__ ` action is logged (as expected)
4. Cursor is still inside input so user can type (it means that input is focused)
5. Click outside the Combobox 
6. Focus is moved somewhere else but `__input_blur__ ` type is not logged. I expected that `__input_blur__`  action would be fired.

I made additional change to check if native onBlur is fired:
`<input {...getInputProps({onBlur: () => console.log('native onBlur')})} />`
`native onBlur` is logged during above ☝️ scenario (6. point).

**What happened**:

`__input_blur__ ` action is not fired if combobox lost focus with closed menu.
![image](https://user-images.githubusercontent.com/74900043/105031217-487fff00-5a55-11eb-913a-37edca2beebf.png)

**Reproduction repository**:

https://codesandbox.io/s/jovial-driscoll-0b9nt?file=/src/index.js

**Problem description**:
I need to implement feature which clears input on blur if user didn't make any selection. Tried to use state reducer. 

**Suggested solution**:

Any suggestions? Is that issue or it works according the assumptions?

**Comment by silviuaavram** [comment]
The stateReducer should be called only before the state changes. Even though we have an __input_blur__ state change type, your use case will not trigger a state change in downshift, so no call.

If you have a highlighted item and press tab, the stateReducer will get called as downshift attempts to select the highlighted item, so there is a state change on the way.

In your case, you should probably use the `onBlur` function in `getInputProps` and `setInputValue` with a `''` parameter in the handler. Let me know if you solve your use case this way or if you have more questions. Thanks!

**Comment by devacc5566** [comment]
@silviuaavram Thanks for quick response.
Sorry I've missed that stateReducer is called only with state change, now it makes sense. 

Firstly I tried to implement that during onBlur event but that solution doesn't look so nice for me, I wanted keep that logic inside reducer so I've changed my requirements and input value is cleared when ESC key pressed, it works fine ;)
