### ISSUE TITLE
onSelectedItemChange is not fired if default highlighted index used

### ISSUE THREAD

**Issue by devacc5566** [downshift-js/downshift#1223]
- `downshift` version: **v6.0.16**
- `node` version: **v14.15.4**
- `npm` (or `yarn`) version: **6.14.10**

**Relevant code or config**

added props to `useCombobox`:

```javascript
    defaultHighlightedIndex: 0,
    onSelectedItemChange: (val) => console.log('onSelectedItemChanged', val),
```

https://codesandbox.io/s/green-rain-4zwzi?file=/src/hooks/useCombobox/basic-usage.js

**What you did**:

scenario:

1. type a
2. select Americium
3. ctrl+a
4. type ddd
5. click Tab

![image](https://user-images.githubusercontent.com/74900043/105418454-73c54280-5c3d-11eb-869e-763b9e85010b.png)
stateReducer `changes` object contains different value than `state` but `onSelectedItemChange` is not fired as I expected. is that designed behaviour?

**Comment by silviuaavram** [comment]
it behaves very unexpectedly with defaultHighlightedIndex as 0. it is a bug somewhere, for sure, as the selectedItem also becomes undefined. We should look into it.

**Comment by hampuslavin** [comment]
Hi! 👋 
I'm new to the repo, but it'd be lovely to lend a helping hand to this great package. At first glance this seems to do the trick; validating that the `highlightedIndex` is not set out of array bounds, which seems to be what's happening in the test case mentioned above.

```javascript
// helpers 

const validators = {
  defaultHighlightedIndex: props =>
    props.defaultHighlightedIndex < props.items.length,
}

function validateDefaultStateValue(props, defaultPropKey) {
  if (defaultPropKey in props) {
    return defaultPropKey in validators
      ? validators[defaultPropKey](props)
      : true
  } else {
    return false
  }
}

//  src/hooks/utils.js:223

function getDefaultValue(
  props,
  propKey,
  defaultStateValues = dropdownDefaultStateValues,
) {
  const defaultPropKey = `default${capitalizeString(propKey)}`

  if (validateDefaultStateValue(props, defaultPropKey)) {
  /* instead of 
    if (defaultPropKey in props) {
  */
    return props[defaultPropKey]
  }

  return defaultStateValues[propKey]
}
```
However, I'm not sure if I'm just curing a symtom or actually fixing the root problem 👨‍⚕️ Any thoughts?

**Comment by silviuaavram** [comment]
Interesting, thanks for looking into this @hampuslavin ! Can you create a PR and a test case that should fail without your changes? I'd like to see this fixes soon. Let me know if I can help out!

**Comment by hampuslavin** [comment]
@silviuaavram Sure, I'll try to help! I'll open a PR tonight or tomorrow if I manage to provoke it in a test 👍

**Comment by hampuslavin** [comment]
@silviuaavram It's easy to reproduce in a Cypress test, but I didn't manage to reproduce it in Jest. Is it okay with a failing Cypress test that is failing without the changes?

**Comment by silviuaavram** [comment]
Figured out what the issue is. There will be some changes done in the state reducers. Will create a PR with the fixes soon.
