### ISSUE TITLE
Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by rbalukja15** [downshift-js/downshift#1224]
- 'downshift' version: "downshift": "1.31.2",
- `node` version: v12.19.0
- `npm` (or `yarn`) version: v6.14.8

**Relevant code or config**

```javascript
```

**I try to search an item that is not on the list.

**The dropdown still shows some items. Then when i select an item it throws an error:
                Invariant Violation
                Unable to find node on an unmounted component.

**Reproduction repository**: https://codesandbox.io/s/downshift-material-ui-multi-select-with-autocomplete-forked-ook9t?file=/MultiChipSelect.js:2263-2267

**Problem description**: Unable to find node on an unmounted component error when selecting an item after searching.

**Suggested solution**:

**Comment by silviuaavram** [comment]
Your codesandbox doesn't work, you have a function `getSuggestions` that fails. Please fix it before creating an Issue here.
