### ISSUE TITLE
getA11ySelectionMessage is not called

### ISSUE THREAD

**Issue by devacc5566** [downshift-js/downshift#1227]
- `downshift` version: **v6.0.16**
- `node` version: **v14.15.4**
- `npm` (or `yarn`) version: **6.14.10**

**Relevant code or config**

a11y message functions overriden:

```javascript
    getA11ySelectionMessage: () => console.log('getA11ySelectionMessage'),
    getA11yStatusMessage: () => console.log('getA11yStatusMessage'),
   
```

Both functions don't return any value because I just wanted to check if when it is called.

https://codesandbox.io/s/clever-dream-v6o6s?file=/src/hooks/useCombobox/basic-usage.js:413-557

**What you did**:

Select item anyhow.
Check console logs and notice that `getA11ySelectionMessage` entry is not available despite item is selected.

**Problem description**:
useCombobox calls `useA11yMessageSetter` function two times: [first](https://github.com/downshift-js/downshift/blob/a13308910282c44ea2ebdcbc8a6dfee901df48a2/src/hooks/useCombobox/index.js#L73) and [second](https://github.com/downshift-js/downshift/blob/a13308910282c44ea2ebdcbc8a6dfee901df48a2/src/hooks/useCombobox/index.js#L86)
There is `updateA11yStatus` called which is debounced.
After seleted item change there is `getA11yStatusMessage` fuction called immediately and returns empty string so item change announcement is blocked.

**Suggested solution**

[Debounced updateA11yStatus ](https://github.com/downshift-js/downshift/blob/a13308910282c44ea2ebdcbc8a6dfee901df48a2/src/hooks/utils.js#L84) can be separately debounced for `getA11ySelectionMessage` and  `getA11yStatusMessage`.

Would you like me to propose a PR with solution?

**Comment by silviuaavram** [comment]
Yes please! Sorry I missed this issue.
