### ISSUE TITLE
API reference for hooks?

### ISSUE THREAD

**Issue by ianstormtaylor** [downshift-js/downshift#1231]
**Problem description**:

Is there no API reference that lists all of the options that can be passed to hooks? I'm specifically looking for the options that `useCombobox` takes. There's a list in the Readme but I'm not sure it's up to date? or maybe it varies by hook instead which is why some are missing? Not sure exactly.

**Comment by silviuaavram** [comment]
Hi! https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox should be up to date with what the hook does.
