### ISSUE TITLE
Unclear How to Change inputValue from Outside Downshift

### ISSUE THREAD

**Issue by neilchaudhuri** [downshift-js/downshift#1235]
- `downshift` version: 6.1.0
- `node` version: 12.18.3
- `npm` (or `yarn`) version: 6.14.6

**Relevant code or config**

```const {
		isOpen,
		selectedItem,
		highlightedIndex,
		setHighlightedIndex,
		getToggleButtonProps,
		getMenuProps,
		getItemProps,
		getComboboxProps,
		getInputProps,
		inputValue,
		reset,
		selectItem,
	} = useCombobox<Option>({
		items: filteredOptions,
		itemToString: item => (item ? item.label : ""),
		id: id,
		labelId: ariaLabelledby,
                 initialInputValue: value ?? "",
		initialSelectedItem: filteredOptions.find(opt => opt.value === value),

...

<Input id={`${id}-input`} value={inputValue} {...getInputProps()}/>
```

**What you did**:

I am wiring up React Hook Form to my autocomplete component. When I attempt to reset the component from RHF using its `Controller` capabilities, the `value` prop passed to my component is indeed set to `undefined`. However, the autocomplete is not reset. The last line in the first snippet is where the `value` prop is used. The `Input` line is where `inputValue`, provided by Downshift as you know, represents the textbox that maintains the original text from the previous pre-reset selection.

**What happened**:

<img width="1451" alt="Screen Shot 2021-02-10 at 4 48 20 PM" src="https://user-images.githubusercontent.com/1239158/107577069-fc415e00-6bbf-11eb-9cff-14832091646e.png">

**Reproduction repository**:

Not sure if I can but will look into it

**Problem description**:

This is not a bug report but rather a question. As you can see in the screenshot, the prop to my autocomplete component has been set to `undefined`, and I have enough logging to show that prop is percolating down into Downshift as expected. But `inputValue` won't change, and since it is managed by Downshift, I don't know how to manipulate it indirectly. It seems `onInputValueChange` is only called with manual entry into the textbox, and `stateReducer` doesn't fire either. In fact, according to my logs, none of the event handler methods get called on reset and subsequent `value` prop change.

I have tried things like `inputValue: selectedOption?.label ?? ""` (where `selectedOption` is derived from the `value` prop passed from outside) as a parameter to `useCombobox` but this renders the input "untypable." I also cannot find where to call `setInputValue` because, as I mentioned, none of the event handler methods get called on reset and subsequent `value` prop change.

Incidentally, I looked at this [Code Sandbox](https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/DonwShift.js:7-9) and found the same issue when changing the Downshift component from `apple` to `pear`.
 
**Suggested solution**:

N/A

**Comment by mayteio** [comment]
Did you find a solution? :)
