### ISSUE TITLE
useMultipleSelection: Eslint warnings about jsx-a11y

### ISSUE THREAD

**Issue by thalespiassi** [downshift-js/downshift#1236]
- `downshift` version: ^6.0.2
- `node` version: v14.15.0
- `npm` (or `yarn`) version: yarn 1.22.10

**Relevant code or config**

```javascript
<span onClick={() => removeSelectedItem(selectedItem)}>&#10005;</span>
```

**What you did**:
When building a multiselect using useSelect and useMultipleSelection I'm getting some eslint warnings about about jsx-a11y, the warning occurs on the remove selected item button.

**What happened**:

![Captura de Tela 2021-02-11 às 16 48 49](https://user-images.githubusercontent.com/74003642/107691127-d1234100-6c89-11eb-9fa8-158e7b78863f.png)

**Reproduction repository**:

**Problem description**:

**Suggested solution**:

Maybe useMultipleSelection could return some accessibility props to be spread on remove buttons.

**Comment by silviuaavram** [comment]
Add a`role="button"`, since your span is actionable. Or make it a `button` tag.

**Comment by piassi** [comment]
Hi @silviuaavram, thanks for your reply,

Actually adding the "button" role doesn't solve the problem, wouldn't make more sense "useMultipleSelection" export the remove button props with appropriated accessibility attributes?

![Captura de Tela 2021-02-15 às 08 59 58](https://user-images.githubusercontent.com/4440076/107944274-a88e9600-6f6c-11eb-87d7-162db5ee0067.png)

**Comment by silviuaavram** [comment]
The hooks are not responsible for providing any UI.

Having that `X` icon attached to the selected item is optional, specifically for mouse click. You can already remove the items by keyboard as the selected item is focusable and actionable with Delete / Backspace.

![Screenshot 2021-02-15 at 14 22 50](https://user-images.githubusercontent.com/11275392/107946148-4a2bdc80-6f99-11eb-8dcd-481fbeb17f96.png)

The jsx-a11y rule you are using asks to make your X icon tabbable, as it's now considered a button. Although the rule makes sense most of the time, in this case it's not needed, as you already can navigate between the items with arrow keys and remove them with the Backspace / Delete key.

It's up to you how you implement the UI. I'd just disable those 2 rules in this case as you are achieving what they require of you, but in a different way.

Let me know it's still not clear.
