### ISSUE TITLE
Prevent DataSearch / Downshift from generating a11y-status-message div

### ISSUE THREAD

**Issue by teemukostamo** [downshift-js/downshift#1238]
- `downshift` version: ReactiveSearch  3.4.1
- `node` version: 10.19.0
- `npm` (or `yarn`) version: 6.14.4

**Problem description**:
Using ReactiveSearch & Datasearch component, some unwanted html is generated at the bottom of the page:

`<div id="a11y-status-message" ...>`

I'm assuming that's because ReactiveSearch uses Downshift under the hood. How can I prevent that div from being generated?

**What you did**:
I've tried adding `downshiftProps `to `DataSearch `component:

```
      <DataSearch
        componentId="q"
        dataField={ELASTICSEARCH_SEARCH_FIELDS}
        ...
        downShiftProps={{
          getA11yStatusMessage: () => null,
        }}

```

**What happened**:
This only prevents the invisible divs from being generated inside the a11y-status-message div when user highlights the search field or starts typing. `<div id="a11y-status-message" ...>` still exists.

**Suggested solution**:
A way to configure DataSearch / Downshift so the `<div id="a11y-status-message" ...>` element is not generated. Any way to achieve this? I know I could remove the element with `document.getElementById("a11y-status-message").remove()` but that's a workaround, not a solution.

**Comment by silviuaavram** [comment]
There is no way to configure this in Downshift or in the hooks. It has been like this since the beginning. It's there for a11y reasons and I don't think we plan to remove it.

As a workaround you can probably pass `environment` as prop to downshift which will act as `window`, but you will tweak it to stop generating the status div. 

https://github.com/downshift-js/downshift/blob/master/src/set-a11y-status.js is where we have this implemented.

**Comment by teemukostamo** [comment]
Thank you for clarification!

**Comment by domantasjurkus** [comment]
I have an issue related to this: my combobox is making a network request, meaning results arrive shortly after starting to type. However, I get an announcement `No results are available` before the network request has finished. I wish there was a way to asynchronously update the live region after a request has finished.
