### ISSUE TITLE
question: How can i implememt compound components with downshift

### ISSUE THREAD

**Issue by HarelTussi** [downshift-js/downshift#1240]
- `downshift` version: v6.0.1
- `node` version: v12.13.1
- `npm` (or `yarn`) version: v6.14.8

**Relevant code or config**

```
import React from "react";
import { useSelect, UseSelectStateChange } from "downshift";

interface Option {
  value: string;
  label: string;
}

interface Props {
  selectedItem: Option | null;
  handleSelectedItemChange: (changes: UseSelectStateChange<Option>) => void;
  items: Option[];
}

function DropdownSelect({
  selectedItem,
  handleSelectedItemChange,
  items,
}: Props) {
  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps,
  } = useSelect<Option>({
    items,
    selectedItem,
    onSelectedItemChange: handleSelectedItemChange,
    itemToString: (item) => item.value,
  });
  return (
    <div>
      <label {...getLabelProps()}>Choose an element:</label>
      <button type="button" {...getToggleButtonProps()}>
        {selectedItem?.value || "Elements"}
      </button>
      <ul {...getMenuProps()}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item.value}${index}`}
              {...getItemProps({ item, index })}
            >
              {item.value}
            </li>
          ))}
      </ul>
    </div>
  );
}

export default DropdownSelect;
```

**What you did**:
Implement a basic select

**What happened**:
Everything works fine and as expected but Now I am trying to expand this component reusability
I want to implement something like that 

```
<Select>
<Select.Toggle> Toggle Select </Select.Toggle>
<Select.Menu> 
<Select.Item>Item 1 with icon</Select.Item>
<Select.Item>Item 1 without icon</Select.Item>
</Select.Menu>
</Select>
```

Is the right way is to create a SelectContext and pass to it as value all useSelect returned data?

**Comment by silviuaavram** [comment]
Once you're done can you add this as an example in downshift-exampes and downshift-docs? I think it will be great to share this knowledge!

Related to you context question yes, Select should have useSelect inside it, pass it as value to a Select context provider, so you can consume it from any of the compound components if needed.

**Comment by HarelTussi** [comment]
Yes, I will be happy to!
I'm just worried about unnecessary re-renders caused by passing a large object to the Context Provider.
Do you think it won't be a problem?

**Comment by silviuaavram** [comment]
I don't know, we can check that afterwards. But if you want to create compound components, you need to pass the information by context (or props but I assume you want context), so you can't avoid it.

Also, our functions returned are wrapped in useCallback. So they should be ready for memoization.
