### ISSUE TITLE
Upgrade @babel/runtime dependencies for old Node

### ISSUE THREAD

**Issue by santiagoprieto** [downshift-js/downshift#1241]
**Configuration**
- `downshift` version: 6.1.0
- `node` version: 15.5.0
- `npm` (or `yarn`) version: 1.22.10

**Relevant code or config**
<img width="499" alt="Screen Shot 2021-02-23 at 11 02 37 AM" src="https://user-images.githubusercontent.com/8649137/108894112-becccf80-75c6-11eb-9f71-79598b502091.png">

**What you did**:
```yarn upgrade```

**What happened**:
_Fails to compile with current babel runtime version:_
<img width="762" alt="Screen Shot 2021-02-23 at 10 56 54 AM" src="https://user-images.githubusercontent.com/8649137/108893355-d9527900-75c5-11eb-9256-4d1e66c7536a.png">

**Problem description**:
Based on the @babel [changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md) I noticed that they were having some issues with this and updating their versions all day yesterday (Feb 22, 2021).

**Suggested solution**:
Hopefully fixing this bug is probably as easy as updating your dependencies to the latest @babel/runtime (~7.13.0).
Maybe also need to update to the latest @babel/helpers but haven't fully checked into that one.

I did a patch in my code by adding a resolution to my package.json file and it works for now **if you use yarn**:
```
  "resolutions": {
    "@babel/runtime": "~7.12.0"
  }
```

**Comment by silviuaavram** [comment]
Hi! I will create a PR with dependencies update, thanks!
