### ISSUE TITLE
Is it possible prevent selection for metaKey + click?

### ISSUE THREAD

**Issue by everdimension** [downshift-js/downshift#1242]
Hi!

I'm making a combobox where results are links to other pages. Everything works great except for one case: when the user presses <kbd>metaKey + click</kbd> (on mac, or <kbd>ctrl + click</kbd> on other OSes), it is expected that the link opens in a new tab (which works) and also that the item is *not* selected in the current tab.

I'm having trouble finding a way to achieve this behavior. If the click event were passed to the stateReducer, I could prevent changes there, but it's not being passed.

How to I prevent an item being selected based on the click event?

Thank you!

**Comment by silviuaavram** [comment]
If you want to only open the link and leave the combobox untouched, you can probably have an onClick event passed to getItemProps, in which you check for the condition you want, and if it meets your condition, you can add event.preventDownshiftDefault as true. https://github.com/downshift-js/downshift#customizing-handlers

This means that in your link clicking case, downshift will not do anything, but will handle everything.

Is this what you are looking for?

**Comment by everdimension** [comment]
@silviuaavram Yes, this is exactly what I was looking for.
Thank you! What an awesome library.

**Comment by silviuaavram** [comment]
Great, happy that it works! Can you post the code you used here, for anyone else looking for something similar? Thanks!

**Comment by everdimension** [comment]
Oh, sure. Essentially it looks like this:

```jsx
import { useCombobox } from 'downshift';

function isModifiedEvent(event: React.MouseEvent): boolean {
  return event.metaKey || event.altKey || event.ctrlKey || event.shiftKey;
}

function guardModifiedEvent(event: React.MouseEvent) {
  if (isModifiedEvent(event)) {
    (event.nativeEvent as any).preventDownshiftDefault = true;
  }
}

function MyCombobox() {
  const {
    getInputProps,
    getItemProps,
    getMenuProps,
    getComboboxProps,
    /* other props... */,
  } = useCombobox<Item>({ items });

  return (
    <form {...getComboboxProps()}>
      <input {...getInputProps()} />
      <div {...getMenuProps()}>
         {items.map((item, index) => (
           <ResultLink
             key={getItemKey(item)}
             to={getItemLink(item)}
             {...getItemProps({ item, index, onClick: guardModifiedEvent })} // <-- solution
           >{item.name}</ResultLink>
         ))}
      </div>
    </form>
  );
}

```
