### ISSUE TITLE
Triggering an effect before the menu opens (i.e., before the DOM is updated)

### ISSUE THREAD

**Issue by GiacoCorsiglia** [downshift-js/downshift#1243]
- `downshift` version: 6.1.0
- `node` version: 12.20.0
- `yarn` version: 1.22.10

Hi, thanks for this great library!  It really seems like the perfect abstraction for building custom selects.

This isn't a bug report.  It's either a question or a feature request, depending on how well I understood the docs :)

## Problem description

I'm using `useSelect()`.  I want to render the dropdown either above or below the button depending on the position of my component in the page.  That is, I want the dropdown menu to "pop up" if there isn't enough space for it to "pop down."  I don't expect downshift to decide this for me, but I am having trouble cleanly implementing this logic using downshift.

Right _before_ the menu opens, I need to measure the `document.body.scrollHeight`* (and some other things).  I can't wait for `isOpen` to already be `true`, because by that time the document's scroll height will have adjusted to accommodate the now-open menu.  (I also don't want to measure DOM rectangles more often than necessary—and definitely not on every render.)

Is there a simple way to achieve this in downshift that I'm missing?

## Possible solutions (and why I don't think they work, or work well)

I cannot use `onIsOpenChange()`, because it (like related callbacks) runs _after_ the state has already changed.  It's too late at that point to measure the document's `scrollHeight`.  A `useEffect` along these lines has the same problem: 

```jsx
useEffect(() => {
  measureStuffAndUpdateState(document.body.scrollHeight)
}, [isOpen])
```

`useLayoutEffect` also fires after DOM mutations, so it's also too late. (I think because `document.body.scrollHeight` triggers a repaint?  I tested it in any case.)

I could do this in all the event handlers that trigger opening the dropdown (e.g., `onClick` on the button, and others).  However, the point of downshift is for me to not have to worry about getting all those event handlers right.  I'd rather not have to keep my logic in sync with downshift's internals (even if the list of event handlers is fairly stable).  Also, doing so would lead to some redundant code.

### One possible solution that avoids manual event handlers

I'm not sure this is a great idea, because the actual open state of the menu is potentially out of sync with downshift's internal state.  I also don't think it will work with `defaultIsOpen`.

```jsx
const Demo = ({ items }) => {
  const [isActuallyOpen, setIsActuallyOpen] = useState(false);
  const [shouldOpenAbove, setShouldOpenAbove] = useState(false);

  const ds = useSelect({
    items,
    onIsOpenChange(changes) {
      setIsActuallyOpen(changes.isOpen);
      if (!changes.isOpen) {
        return;
      }
      // Measure the position of the select, and the scroll height of the
      // document, **before** the select is actually opened.  Do this as
      // infrequently as possible, since measuring these things is not free.
      const isThereEnoughSpaceBelow = measureStuff(document.body.scrollHeight);
      setShouldOpenAbove(!isThereEnoughSpaceBelow);
    }
  });

  let menuClassName;
  if (isActuallyOpen) {
    menuClassName = shouldOpenAbove ? "menu-open-above" : "menu-open-below";
  } else {
    menuClassName = "menu-closed"
  }

  // There's nothing special about the HTML setup.
  return <div>
    {/* Label here... */}

    <button {...ds.getToggleButtonProps()}>Select…</button>

    <ul {...ds.getMenuProps({
      className: menuClassName
    })}>
      {isActuallyOpen && <>{/* Items here... */}</>}
    </ul>
  </div>
}
```

## Suggested solution

Ideally, I could pass a callback that would fire _before_ the menu is opened.  Downshift would call the callback in all the appropriate event handlers (and also accounting for `defaultIsOpen`, etc.).  It would be expected for this callback to trigger side effects (e.g., state change).   (Perhaps there is a general pattern of `onBeforeStateChange` callbacks here, but I'm not sure what the others would be needed for.)  

```jsx
const Demo = ({ items }) => {
  const [shouldOpenAbove, setShouldOpenAbove] = useState(false);

  const ds = useSelect({
    items,
    // HYPOTHETICAL FEATURE:
    onBeforeOpen() {
      // Measure the position of the select, and the scroll height of the
      // document, **before** the select is actually opened.
      const isThereEnoughSpaceBelow = measureStuff(document.body.scrollHeight);
      setShouldOpenAbove(!isThereEnoughSpaceBelow);
    }
    // END HYPOTHETICAL FEATURE
  });

  let menuClassName;
  if (ds.isOpen) {
    menuClassName = shouldOpenAbove ? "menu-open-above" : "menu-open-below";
  } else {
    menuClassName = "menu-closed"
  }

  // There's nothing special about the HTML setup.
  return <div>
    {/* Label here... */}

    <button {...ds.getToggleButtonProps()}>Select…</button>

    <ul {...ds.getMenuProps({
      className: menuClassName
    })}>
      {ds.isOpen && <>{/* Items here... */}</>}
    </ul>
  </div>
}
```

Thank you!

*FYI you can't just get away with `document.body.scrollHeight` due to browser incompatibilities: [see here](https://javascript.info/size-and-scroll-window#width-height-of-the-document)

**Comment by GiacoCorsiglia** [comment]
Well, sorry for the noise, but I realized I could achieve this with the following effect.  (Basically, I just temporarily set the menu's height to `0` to do the measurement.)

```jsx
const Demo = ({ items }) => {
  const menuRef = useRef(null);
  const [shouldOpenAbove, setShouldOpenAbove] = useState(false);

  const ds = useSelect({
    items,
  });

  // THE EFFECT
  useLayoutEffect(() => {
    if (!ds.isOpen) {
      return;
    }
    menuRef.current.style.height = "0";
    const isThereEnoughSpaceBelow = measureStuff(document.body.scrollHeight);
    setShouldOpenAbove(!isThereEnoughSpaceBelow);
    menuRef.current.style.height = "";
  }, [ds.isOpen]);
  // END EFFECT

  let menuClassName;
  if (ds.isOpen) {
    menuClassName = shouldOpenAbove ? "menu-open-above" : "menu-open-below";
  } else {
    menuClassName = "menu-closed"
  }

  // There's nothing special about the HTML setup.
  return <div>
    {/* Label here... */}

    <button {...ds.getToggleButtonProps()}>Select…</button>

    <ul {...ds.getMenuProps({
      className: menuClassName,
      ref: menuRef,
    })}>
      {ds.isOpen && <>{/* Items here... */}</>}
    </ul>
  </div>
}
```

This solution seems to be jank-free (which is part of what I was hoping to achieve with something like `onBeforeOpen()`—not bouncing between being visibly open/closed).  I'm going to close this issue, but would still be open to suggestions regarding my previous question.

**Comment by silviuaavram** [comment]
Hi! I'm happy that you solved your issue! Please let us know if you experience any other issues or need feedback.
