### ISSUE TITLE
Is this a Downshift Anomaly ?

### ISSUE THREAD

**Issue by VikR1000** [downshift-js/downshift#1248]
Chrome Lighthouse is dinging me for an aria label in these two elements:

<img width="1164" alt="Screen Shot 2021-03-10 at 5 47 31 PM" src="https://user-images.githubusercontent.com/18017954/110723464-ee83f600-81c8-11eb-87be-61b535fb902b.png">

<img width="1156" alt="Screen Shot 2021-03-10 at 5 47 44 PM" src="https://user-images.githubusercontent.com/18017954/110723368-cd230a00-81c8-11eb-87a0-660127e27883.png">

Is this a Material-UI anomaly or a Downshift anomaly?

**Comment by silviuaavram** [comment]
I ran Lighthouse on the useCombobox docsite and I did not get this error. If you can dig into this and find a problem related to downshift please re-open this ticket. Thanks!
