### ISSUE TITLE
multiselect: a bug in the official doc

### ISSUE THREAD

**Issue by NitsanBaleli** [downshift-js/downshift#1249]
when looking at the multiselect hook simple example (https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useMultipleSelection/select.js)
clicking the same items more than once selects different items from the list

https://user-images.githubusercontent.com/3227826/110759278-18cfc500-8256-11eb-8d73-cced358d0914.mp4

**Comment by silviuaavram** [comment]
Can you fix the example in downshift-examples? In https://www.downshift-js.com/use-multiple-selection it's implemented correctly, so the implementations should be the same.

Let me know if you need any help!

**Comment by NitsanBaleli** [comment]
I actually need help here -)
the example  you linked is using `useComboBox` while the doc example is using `useSelect` ?

**Comment by silviuaavram** [comment]
@NitsanBaleli it should be the same problem, the fact that you are using `items` instead of getFIlteredItems for rendering.

**Comment by NitsanBaleli** [comment]
@silviuaavram I've opened a PR here https://github.com/downshift-js/downshift-examples/pull/34, couldn't find a way to link it to this  issue

**Comment by silviuaavram** [comment]
Awesome @NitsanBaleli thank you! Take a look at your map issue as well, maybe it's related to the fact that you are not passing the `environment` prop. Check my response and the docs and you can also find more details on the downshift github.
