### ISSUE TITLE
How to test onStateChange with Jest & Enzyme?

### ISSUE THREAD

**Issue by seasoninthesky** [downshift-js/downshift#1252]
- `downshift` version: 6.1
- `node` version: 10.24
- `npm` (or `yarn`) version: 6.14
- `react` version: 16.14
- `jest` version: 26.6
- `enzyme` version: 3.11

**Relevant code**

```
const {
       //props
    } = useCombobox({
        items: fetchedData,
        itemToString: (item) => (item ? item.name : ''),
        onStateChange: (state) => {
            console.log('state changed');
            // do stuff
        },
    });
```
    
```
 it('calls onStateChange', () => {
        const component = shallow(<ComboBox field={field} key={field.name} />);
        const changeEvent = { target: { value: 'ab' } };
        component.find('Input').simulate('change', changeEvent);
        // expect console log to be called
        // do more stuff
    });
```

**Problem description**:

The onChangeState call works fine in the browser when changing input or selecting an item, but I can't simulate this when unit testing it with jest & enzyme. I also tried do it like this:
``` component.find('Input').props().onChange(function)```

Does anybody know how to test this?

**Comment by silviuaavram** [comment]
Switch to React Testing Library :D.

I don't know who's `Input` and what its `onChange` is doing. Maybe create a Codesandbox with this?
