### ISSUE TITLE
Enhancement: Add actions to the onStateChange handler arguments in useCombobox

### ISSUE THREAD

**Issue by slowselfip** [downshift-js/downshift#1254]
In the onStateChange handler it would be nice to have access to the action props like (reset, setInputValue, openMenu etc).

```javascript
const { reset } = useCombobox({
  onStateChange: (
    changes, 
    /* Here it would be nice to have access to the actions props
     * passed to the callback, instead of relying on hoisted closure 
     * from the return arguments from the useCombobox hook  */
  ) => {
  if (
    /* some state related condition that is not suitable 
     * to handle in the event handlers of the input element */
  ) {
    reset();
  }
}})
```

I think they are accessible from the onStateChanged stateAndHelper-argument in the original Downshift component.

**Comment by silviuaavram** [comment]
Thanks for the feedback! I did not feel the need to do that in the hooks since most cases were solvable via stateReducer.

Do you have a particular use case in mind? Usually when you want to alter the next state you are encouraged to do it in your stateReducer.

**Comment by slowselfip** [comment]
Thanks, the usecase is that I want to be able to reset the selectedItem by calling the reset action, when the input value turns into the empty string. If I put that logic into the onChange of the component the __function_reset__ was not dispatched and onSelectedItemChange did not trigger. When I put the reset call in the onStateChange it worked, so I stuck with that.

Like you say, I can probably achieve the same result in the stateReducer. Then I will not need to rely on any actions and will not have the ”hoist problem” described in my initial post. 

It was mostly me noticing the difference in the Downshift onStateChange api w.r.t. the useCombobox api. Had me wondering if that was intended or if it was possible to add the actions to the arguments of the onStateChange in useCombobox.

I’ll work with the stateReducer for now. Thanks again.
