### ISSUE TITLE
Having trouble with initialSelectedItem vs defaultSelectedItem with a shared component library

### ISSUE THREAD

**Issue by allison-palum** [downshift-js/downshift#1258]
- `downshift` version: 1.31.14
- `node` version: 14.15.1
- `npm` version: 6.13.7

**Relevant code or config**

```javascript
<Downshift
   onChange={selectedItem ? (_) => null : handleOnChange}
   itemToString={itemToString}
   itemToElement={itemToElement}
   defaultSelectedItem={defaultSelectedItem}
   selectedItem={selectedItem}
   ariaLabel={ariaLabel}
>
   {({
      isOpen,
      getToggleButtonProps,
      getItemProps,
      getLabelProps,
      getRootProps,
      selectedItem,
      ariaLabel,
   }) => (
      <ItemsContainer
         id={dropdownId}
         disabled={disabled}
	 light={light}
         isOpen={isOpen}
         invalid={invalid}
         invalidText={invalidText}
         selectedItem={selectedItem}
         {...getRootProps({ refKey: 'innerRef' })}
      >
         <ItemsContainer.Field
            id={dropdownId}
            tabIndex="0"
            {...getToggleButtonProps({ disabled })}
         >
            <span className={`rmp--items-container__label`} {...getLabelProps()}>
               {selectedItem ? itemToString(selectedItem) : label}
            </span>
            <div className="rmp--items-container__menu-icons">
               {invalid ? (
                  <div className="error-icon">
                     <Error16 />
                  </div>
               ) : null}
               <div className="menu-icon">{isOpen ? <CaretUp16 /> : <CaretDown16 />}</div>
            </div>
         </ItemsContainer.Field>
         {isOpen ? (
            <ItemsContainer.Menu aria-label={ariaLabel} id={dropdownId}>
               {items.map((item, index) => (
                  <ItemsContainer.MenuItem
                     key={itemToString(item)}
                     isActive={selectedItem === item}
                     {...getItemProps({ item, index })}
                  >
                     {itemToElement ? (
                        <ItemToElement key={itemToString(item)} {...item} />
                     ) : (
                        <>
                           <span>{itemToString(item)}</span>
                           {selectedItem === item ? (
                              <div className="rmp--items-container__menu-item__option__selected-icon">
                                 <Checkmark16 />
                              </div>
                           ) : null}
                        </>
                     )}
                  </ItemsContainer.MenuItem>
               ))}
            </ItemsContainer.Menu>
         ) : null}
      </ItemsContainer>
   )}
</Downshift>
```

**What I'm trying to do**:
I am in the process fo writing a shared UI component library for my company and utilizing the Downshift library for our dropdown related components. To test the components in the separate repository, I am using Storybook and jest testing. I want to include the ability for the developer to set a default (or initial) selected item.

**What happens**:

In the component library, when I set a defaultSelectedItem, the Dropdown successfully renders with the default selected item. However, when I publish the component library, and install the library into our application and send a defaultSelectedItem prop, it does _not_ render with that default selected item.

**Comment by silviuaavram** [comment]
First of all, I think you should use `initialSelectedItem` if you want to have the value only on the initial render. Check the docs for the difference between initial and default.

Secondly, you are using both default and controlling `selectedItem`, and this is a big no-no. You either control the state prop or you don't. If you need to control the prop, remove any default/initial and use the selectedItem prop to do whatever it is you want to do.

Let me know if I can help furher.

Further thoughts:
1. always render the menu, even when isOpen is true.
2. what's stopping you from usign useCombobox?

**Comment by allison-palum** [comment]
`initialSelectedItem` doesn't seem to work. `defaultSelectedItem` works, but not when the shared component library is published and imported.

could I do something like so...

```javascript
const [currentSelectedItem, setCurrentSelectedItem] = useState(selectedItem ? selectedItem : null);
...
const handleOnChange = (selectedItem) => {
   ...
   setCurrentSelectedItem(selectedItem);
   ...
}
...
<Downshift
   onChange={handleOnChange}
   itemToString={itemToString}
   itemToElement={itemToElement}
   selectedItem={currentSelectedItem}
   ariaLabel={ariaLabel}
>
```

**Comment by silviuaavram** [comment]
I was actually thinking this, since you plan to have the defaultSelectedItem as well.

```js
const [currentSelectedItem, setCurrentSelectedItem] = useState(defaultSelectedItem ?? null);
```

And keep what you did above.

This will control the selectedItem with your currentSelectedItem state variable, and update the currentSelectedItem when Downshift calls onChange. By giving currentSelectedItem the value of defaultSelectedItem as an initial value, you are also solving your use case.

**Comment by allison-palum** [comment]
awesome! thank you!
