### ISSUE TITLE
Question: How to customize the functionality of the keys events when fire?

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [downshift-js/downshift#1260]
I am trying to change the functionality of the key tab because I have a bug in my code "tab pressed causes the `inputValue` to disappear" and I checked the declaration file but I've not come up with anything relevant.
Thanks.

**Comment by silviuaavram** [comment]
Are we suppose to understand anything from this? There is an Issue template that you just delated before writing this message. Please start again, thanks.

**Comment by Ali-Hussein-dev** [comment]
it is not an issue from the lib side, it is just a general question about how to custom the functionality of keys events, that's why I start the title with "Question" because the "discussion" section is disabled.

**Comment by silviuaavram** [comment]
I got it, I just don't know how to help based on what you described. You must have a code example, something that explains what you are trying to do. How can anyone help based on your original question?
