### ISSUE TITLE
__menu_blur__ state change is not registered when isOpen is a controlled Prop in [useSelect hook]

### ISSUE THREAD

**Issue by recurx** [downshift-js/downshift#1262]
- `downshift` version: using downshift example codesandbox
- `node` version: using downshift example codesandbox
- `npm` (or `yarn`) version: using downshift example codesandbox

**Relevant code or config**

```
function stateReducer(state, actionAndChanges) {
    const {type, changes} = actionAndChanges
    switch (type) {
      case useSelect.stateChangeTypes.ToggleButtonClick:
        setIsOpen(!isOpen)
        return changes
      case useSelect.stateChangeTypes.MenuBlur:
        setIsOpen(false)
        return changes
      case useSelect.stateChangeTypes.ItemClick:
        if (changes.selectedItem === 'Plutonium') {
          setIsOpen(true)
        } else {
          setIsOpen(false)
        }
        return changes
      default:
        return changes
}
```

**What you did**:
I am using `isOpen` as a controlled prop and trying to use `stateReducer` to manipulate the state of `isOpen`. There is a usecase where I have to keep the dropdown open when user selects a particular option, then close it on `MenuBlur` state change. I have replicated the usecase in the attached codesandbox - follow the 'steps to reproduce'

**What happened**:

The `__menu_blur__` state change is not registered after clicking on the option which keeps the menu open and then clicking outside. In the sandbox, click on `Plutonium`, then click outside the menu - the `__menu_blur__` state change doesn't get logged.

**Reproduction repository**:

https://codesandbox.io/s/downshift-examples-forked-recurx-8yydv?file=/src/hooks/useSelect/state-reducer.js

Steps to reproduce:
1 - Go to the above link, click on the module view option in the preview browser
2 - Click on the dropdown and select 'Plutonium'
3 - Click outside the menu -> The menu doesn't close (`__menu_blur__` state change is not registered in `stateReducer`)
4 - Click on the toggle button to close the menu
5 - Re-open the menu -> The menu doesn't have focus

**Problem description**:

Controlled `isOpen` causes 2 issues when the menu is kept open on an option click:
1. `__menu_blur__` state change is not registered in `stateReducer` function
2. The menu doesn't have focus when you close and re-open the menu using toggle

**Suggested solution**:
I am not exactly sure if this is an issue or the consumer of downshift has to take care of 'focus' and 'menu blur scenario' when `isOpen` is controlled. I'd love to have `__menu_blur__` fired even if `isOpen` is a controlled prop. Let me know what you folks think.

**Comment by recurx** [comment]
Hey @silviuaavram ! Could you have a look at the sandbox ? Please let me know your thoughts.

**Comment by recurx** [comment]
So, I had a look at this issue: [handleStateChange confusion around controlling isOpen](https://github.com/downshift-js/downshift/issues/206) . It seems like the `downshift` component doesn't have a problem and it exposes a prop `onOuterClick` (have not verified it though). But for the `useSelect` hook, **__menu_blur__** event doesn't fire. 
Btw, for my use-case, I have found a way to implement the dropdown without controlling `isOpen` (not controlling this fires the events properly). I'm using an extra variable to control the menu open and close along with `isOpen`.
If you think this is not an issue and I'm doing something wrong, pls let me know and close the issue 😄 
Will be happy to submit a PR if you think this needs some fix. Cheers!

**Comment by silviuaavram** [comment]
Hi @recurx I don't know how I missed this, sorry.

The stateReducer is not the place to perform side effects. If you want to control isOpen properly, use onStateChange or onIsOpenChange if you are using one of the hooks.

Depending on your use case, you might not need to control isOpen at all. Just return the isOpen you want for the next state change using the stateReducer.

If there is nothing else I can close this one. Let me know how it goes!

**Comment by recurx** [comment]
Hey @silviuaavram . Thanks for the reply and suggestion. 

I tried to control isOpen using `onIsOpenChange`. I am facing a similar issue. Please have a look at the sandbox link attached. 

Here, I want to keep the menu open when someone clicks on 'Plutonium'. Now, once you click on 'Plutonium', the menu remains open but `onIsOpenChange` is not called when you click outside the menu - I've added a `console -> log` to verify this. The menu behaviour returns back to normal once you close and re-open the menu using the toggle button.
[sandbox - onIsOpenChange](https://codesandbox.io/s/downshift-examples-forked-recurx-8yydv?file=/src/hooks/useSelect/controlling-state.js)

Just for context, my actual usecase looks something like this, clicking on **_option 4_** opens the side menu:

<img width="587" alt="Screenshot 2021-05-04 at 1 33 03 AM" src="https://user-images.githubusercontent.com/71846122/116926990-afc66580-ac78-11eb-96a4-7c22a26f1efd.png">

**Comment by silviuaavram** [comment]
Since v7, focus is kept on the toggle button. If the problem still persist, please open another issue. Thank you!
