### ISSUE TITLE
Mouse clicks for Downshift inside custom component do not work

### ISSUE THREAD

**Issue by JochenDiekenbrock** [downshift-js/downshift#1273]
- `downshift` version: 6.1.3
- `node` version: 14.16.1
- `npm` (or `yarn`) version: 6.14.12

**Relevant code or config**
see repo https://github.com/JochenDiekenbrock/downshift

**What you did**:
I added the downshift example from the downshift readme to a react app and embedded this app into a custom web component.

**What happened**:
If this app is running inside a custom web component, mouse events do not work. Searching in the input field and selecting an entry in the result list with the keyboard displays the alert message. Clicking with the mouse in the result list will *not* show the alert and the onChange event does not fire.

**Reproduction repository**:
https://github.com/JochenDiekenbrock/downshift

**Problem description**:

**Suggested solution**:
Mouse should work

**Comment by AWood29** [comment]
I'm also having this issue, have you found any solution or workaround?

**Comment by JochenDiekenbrock** [comment]
No, I stopped using downshift

**Comment by silviuaavram** [comment]
Hi everyone! Thanks for submitting this issue.

First of all, try to submit code sandboxes of your apps/examples, as it helps us better to setup the repro environment. Cloning repos and checking them just takes too much time.

However, that being said, your repo is not a standard React app, I see a shadowRoot in your App and I believe you also need to make downshift aware of that, via [this documentation entry](https://github.com/downshift-js/downshift#environment). If the `document` is different from the standard one, Downshift should also have it. Here it will be explained better I think https://github.com/downshift-js/downshift/issues/536.

Also, please consider using `useCombobox` as React hooks are just so much better at sharing logic.

Hope this helps in the future and also others who stumble upon such problems. Thanks!
