### ISSUE TITLE
Unable to prevent onSelect

### ISSUE THREAD

**Issue by alexblack** [downshift-js/downshift#1275]
- `downshift` version: 6.1.3

https://codesandbox.io/s/simple-downshift-example-forked-cfsxk?file=/index.js

I've set this sample forked from an example.  It attempts to prevent item selection using the stateReducer, but onSelect still fires.

```
    stateReducer={(state, changes) => {
      if (changes.type === Downshift.stateChangeTypes.clickItem) {
        return {
          ...changes,
          selectedItem: null,
          inputValue: 'Foobar',
          type: Downshift.stateChangeTypes.changeInput
        };
      }
      return changes;
    }} 
```

Steps tp repro:
1. Run the sandbox: https://codesandbox.io/s/simple-downshift-example-forked-cfsxk?file=/index.js
2. Click in the input box
3. Press the downarrow to view the list of fruits
4. Click "Pear"
5. See "foobar" appear in the input box (as expected, due to the changes)
6. Look in the console, see "Selected {value: "pear"}"

Expected result: given that I stopped the state changing I didn't expect the selected item to change.

More generally: I'm trying to show a list of suggestions to the user, and when they pick one, I want to "apply" it to the current input, modifying the input, and I don't actually want the item to become selected.

![Screen Shot 2021-05-13 at 2 35 48 PM](https://user-images.githubusercontent.com/148930/118190823-8637d780-b3f8-11eb-9167-d76f9d01c18d.png)

**Comment by alexblack** [comment]
I've had more luck working with the hook `useCombobox`.  Some more info on my use case: I'm trying to help users get the right "text" into their input box, some users will use the autocomplete, other's won't, some will only use the autocomplete, some will add more text beyond what the autocomplete offers.

So the concept of a "selectedItem" doesn't exist in this scenario, instead I'm offering text completitions/suggestions to the user.

Example: the input takes a list of comma separated list of ticker symbols, and I want to suggest individual tickers to them.  So if they type "b" it should suggest things like `BTC` and `BCH`, and if they apply a suggestion they should get text `BTC`, but they might then extend it to be `BTC, BCH`

Is there a better approach to do this with downshift? Currently I'm resorting to things like:

```
    const downshiftOptions = useCombobox<Suggestion>({
      items,
      inputValue: value,
      onStateChange: handleStateChange,
      stateReducer: (state, actionAndChanges) => {
        const { changes } = actionAndChanges;
        // Prevent comboBox from remembering we selected an item
        if (changes.selectedItem) {
          // store it so we can fire onSelect on the next update
          setSelectedItem(changes.selectedItem);
          return {
            ...changes,
            selectedItem: null,
          };
        }
        return changes;
      },
    });
```

**Comment by silviuaavram** [comment]
you can control selectedItem to be null all the time. Also, you might want to use onSelectedItem change, as reducers are meant to be pure functions.

if you still need help let me know.
