### ISSUE TITLE
[Blocker] Infrastructure Issues

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#1276]
https://github.com/downshift-js/downshift/pull/1271
https://github.com/downshift-js/downshift/pull/1268

I keep getting build errors on both of these PRs. First one updates the node version on the CI. The other one kickstarts the use of TypeScript in Downshift.

Sadly I couldn't figure out what the problem is (some gatsby/docz issue as far as I could tell) and I don't have time at the moment to look into them.

If someone can pull those branches and fix them, they will be heroes! It's important to merge them as without them it is impossible to continue migrating to TS, keeping up-to-date and write other hooks (I would like to write other hooks directly with TS).

**Comment by DaveWelling** [comment]
FWIW,  I am also seeing this problem while trying to submit a PR for this problem: #1257 .  I also have no idea how to fix it.  Additionally I saw a linting issue in rollup.config.js that I can disable, but I'm not sure I should.  I don't know if there is some reason why the extension is included. 
```
// eslint-disable-next-line import/extensions
const config = require('kcd-scripts/dist/config/rollup.config.js')
```

**Comment by silviuaavram** [comment]
Should probably be fixed by now.
