### ISSUE TITLE
useCombobox when used with virtualization causes dropdown to scroll up abruptly

### ISSUE THREAD

**Issue by yyyyaaa** [downshift-js/downshift#1277]
- `downshift` version: 6.0.2
- `node` version: 12
- `npm` (or `yarn`) version: latest

**What you did**:
Create a basic combobox component with `useCombobox` with virtualization using `react-virtual`

**What happened**:
When the dropdown is open and scrolled, if the mouse hovers near the top of the dropdown, it is abruptly scrolled back up.

**Reproduction repository**:

https://codesandbox.io/s/downshift-react-virtual-rmwc-forked-8p0fk

**Problem description**:

When the dropdown is open and scrolled, if the mouse hovers near the top of the dropdown, it is abruptly scrolled back up.

**Suggested solution**:
Unfortunately I haven't been able to solve this myself, I'm looking for direction.

Added a screenshot to better explain the bug:

![Kapture 2021-05-17 at 17 17 18](https://user-images.githubusercontent.com/16129111/118474202-00d46000-b735-11eb-957b-6045ac30acf5.gif)

**Comment by yyyyaaa** [comment]
The official documentation example also has this behavior, I believe this is a legit bug, could anyone give me some direction? I could have some time to fix a create a PR this week
https://www.downshift-js.com/use-combobox#virtualizing-items-with-react-virtual

**Comment by daksh-sagar** [comment]
facing exactly same issue

**Comment by silviuaavram** [comment]
The official example works as expected as far as I can see. Maybe it was fixed in the meantime or there is something wrong in your example
