### ISSUE TITLE
useSelect should apply aria-disabled="true" when item is disabled

### ISSUE THREAD

**Issue by jdk243** [downshift-js/downshift#1279]
- `downshift` version: 6.1.0
- `node` version: 14.16.0
- `yarn` version: 1.22.10

**Relevant code or config**

https://github.com/downshift-js/downshift/blob/master/src/hooks/useSelect/index.js#L506
```javascript
const itemProps = {
        role: 'option',
        'aria-selected': `${itemIndex === latestState.highlightedIndex}`,
        'aria-disabled': rest.disabled, // add in this property here
        id: elementIds.getItemId(itemIndex),
        [refKey]: handleRefs(ref, itemNode => {
                  if (itemNode) {
                              itemRefs.current[elementIds.getItemId(itemIndex)] = itemNode
                  }
        }),
        ...rest,      
}
```

**What you did**:
passed `disabled: true` in the argument to `getItemProps`

**What happened**:
`getItemProps` returned as expected

**Problem description**:
When interacting with a disabled select item with a mouse and keyboard the behavior is as expected. However, when inspecting the accessibility properties of a disabled select item, `disabled: true` is not specified. 

**Suggested solution**:
Provide `'aria-disabled': rest.disabled` in the itemProps returned by `useSelect`

**Comment by silviuaavram** [comment]
Hi! Thanks for using useSelect!

According to https://codepen.io/stevef/post/short-note-on-the-disabled-attribute and https://stackoverflow.com/questions/38059140/when-to-use-the-disabled-attribute-vs-the-aria-disabled-attribute-for-html-eleme it might not make sense to have both. If you have `disabled` then you don't need `aria-disabled`. You could have only `aria-disabled` but that's only affecting the a11y tree, no css change, no functional change. But having both is not required as far as I can tell.

**Comment by jdk243** [comment]
Thanks for the reply @silviuaavram! From what I understand, the props returned by `getItemProps` from `useSelect` should be provided to a `li`. These props include `role="option"`, which allows us to apply properties like `disabled`, but since the element itself is not a proper `option` element, accessibility tools may not understand that they are actually disabled. Applying the `aria-disabled` as well provides that extra information.

**Comment by silviuaavram** [comment]
You can override what getItemProps returns if you really need it. Will close this.
