### ISSUE TITLE
Error throws on disabled item with virtualization

### ISSUE THREAD

**Issue by danielstreit** [downshift-js/downshift#1281]
When using a virtualized list of items where some are disabled, useCombobox and useSelect will throw an error when the _rest_ of the items are disabled such that it can't find a _mounted_ enabled item in the DOM below the current one.

- `downshift` version: 6.1.3
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

**Relevant code or config**

See repro below.

**What you did**:

* Using the react-virtual example for useCombox in the code sandbox examples, I've updated the 8th - 11th items to be disabled.
* Focus the input and press the down arrow 9 times (to, theoretically, navigate to the 12th 0-indexed item)

**What happened**:

![CleanShot 2021-05-27 at 12 47 04](https://user-images.githubusercontent.com/6923694/119889809-e5631500-beeb-11eb-9752-581385d5f1cb.gif)

**Reproduction repository**:

https://codesandbox.io/s/nice-smoke-inv2z?file=/src/hooks/useCombobox/react-virtual.js

**Problem description**:

The crux of the issue appears to be when there are no enabled items in the current, virtualized window.

If I only disable one or two items or I bump up the overscan value passed to `useVirtual` so that it is greater than the number of disabled items in a row, there is no error. The error only occurs when the _rest_ of the items in the current virtual window are disabled.

**Suggested solution**:

Not sure. It looked like there was some discussion of adding a prop to the hooks to tell downshift which items are disabled so it doesn't need to read this attribute from the DOM as it does today. That sounds like a potentially promising solution.

**Comment by silviuaavram** [comment]
Will prioritise the prop, since it helps here as well. Thanks!
