### ISSUE TITLE
Lazy loading dropdown options only when open

### ISSUE THREAD

**Issue by aleksandrlat** [downshift-js/downshift#1282]
Sorry I could not find an example or existing issue about this. Google also didn't help :( 

I want to implement lazy dropdown with infinite scroll. I want to load options only when dropdown is open. I'm using `useCombobox` hook.

An example of how to implement this would really be appreciated.

I struggle with the problem that `useCombobox` hook needs `items` to be passed to it even if dropdown is not open yet.

Thanks in advance!

**Comment by silviuaavram** [comment]
https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useCombobox/apollo-useCombobox/index.js this?
