### ISSUE TITLE
Inconsistency between Downshift render-prop component and useCombobox

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [downshift-js/downshift#1284]
- `downshift` version: 6.1.3
- `node` version: N/A? Running in Firefox 89
- `npm` (or `yarn`) version: 1.22.5

**What you did**: Refactoring my Autocomplete Dropdown from Downshift render-prop component to useCombobox hook

**What happened**: When a value not present in the items list is entered, the hook accepts that input whereas the Downshift component discards the selection and reverts to showing the placeholder text.

**Problem description**: It seems like these two behaviors should be consistent. Is it expected that they differ?

**Suggested solution**: I'm not sure what the right behavior is--I think it would depend on the use case. I know the point of comboboxes is sometimes to offer the option to add new items, though in my case I'm only using it as an autocomplete dropdown. It's not valid to add options in my case, but there may be thousands of options, so a plain HTML `<select>` is not a good fit.

**Comment by silviuaavram** [comment]
Hi @uhoh-itsmaciek ! When does it discard the option? When you blur?

If so, then it's a difference between handling the input value, and I believe that `useCombobox` does it better according to the combobox pattern https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html.

Both Downshift and useCombobox keep `selectedItem` unchanged as long as you don't have an option highlighted before blur.

Let me know if I can offer more help. Thanks for using downshift!
