### ISSUE TITLE
inputValue destructured from useCombobox is taking the previous props

### ISSUE THREAD

**Issue by ThomasQuan** [downshift-js/downshift#1285]
- `downshift` version: ^6.0.6
- `node` version: v14.16.1
- `npm` (or `yarn`) version: 6.14.12

**Relevant code or config**

```javascript
const Search = () => {
  const router = useRouter();
  const [
    findItems,
    { loading, data, error },
  ] = useLazyQuery(SEARCH_PRODUCTS_QUERY, { fetchPolicy: "no-cache" });
  const items = data?.searchTerm || [];
  const delayFindItem = debounce(findItems, 350);
  resetIdCounter();
  const {
    isOpen,
    inputValue,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    getItemProps,
    highlightedIndex,
  } = useCombobox({
    items,
    onInputValueChange(props) {
      //  NOTE: DO NOT USE "useCombobox inputValue" because it's taking the previous state
      //         USE props.inputValue as it take the current state
        console.log(
          `useCombobox inputValue is ${inputValue} while onInputValueChange inputValue is ${props.inputValue}`
        );
        delayFindItem({
        variables: {
          searchTerm: inputValue,
        },
      });
    },
    onSelectedItemChange({ selectedItem }) {
      router.push({
        pathname: `/product/${selectedItem.id}`,
      });
    },
    itemToString: (item) => item?.name || "",
  });

```

**What you did**: I am using the inputValue that has been de structured from useCombobox to get the input so that I can search for it via GraphQL query

**What happened**:  The inputValue being pass by the de structured useCombobox isn't returning the latest state when typing in 

**Reproduction repository**:

**Problem description**: The problem is that inputValue from useCombobox is displaying the previous state which causes the problem of it rendering the search result 1 character late whereas onInputValueChange inputValue display the correct current state

Example : useCombobox inputValue is fa while onInputValueChange inputValue is fan

The img bellow show that the second result have no result containing word "fan"
![downshift-problem-result](https://user-images.githubusercontent.com/54914152/121112759-de3ae180-c7de-11eb-9fa6-e3960db9c06d.PNG)

**Suggested solution**: I think this has something to do with how React handle useState and asynchronous

**Comment by silviuaavram** [comment]
Hi @ThomasQuan ! I think the behaviour makes sense, unless I am missing something.

So, you changed the text in your input. The context in which your onInputValueChange is called is in the previous render, so the useCombobox inputValue has the previous render value.

The fresh inputValue from useCombobox is available when the hook is called on the next render. But in this case, the inputValueChange has not been called yet, it's a new callback that has just been attached to useCombobox.

At least that's how I think it happens, I may be wrong. Take a look at this sandbox where I used getDate to try to prove my idea.

https://codesandbox.io/s/romantic-silence-2egfp?file=/src/hooks/useCombobox/basic-usage.js
