### ISSUE TITLE
useSelect accessibility issue with NVDA screen reader

### ISSUE THREAD

**Issue by AndreyLuzinov** [downshift-js/downshift#1287]
**What you did**:
- Install and run NVDA screen reader
- navigate to any select example from https://www.downshift-js.com/use-select page
- select new item from dropdown list

**What happened**:
When you choose new item from list, screen reader voices the following sequence:
[label], [previous value] menu button expanded submenu, [new value] has been selected

**Problem description**:
Screen reader always voices previos value before saying '[new value] has been selected'.
This might be confusing for users.
'expanded ' word is also confusing, because I've closed submenu by choosing new element

I think problem is here:

```
    if (environment.document.activeElement === menuRef.current) {
      // istanbul ignore else
      if (toggleButtonRef.current) {
        shouldBlurRef.current = false;
        toggleButtonRef.current.focus();
      }
    }
```

We set focus to button which is not updated yet, so screen reader voices previous button aria-label value.

**Comment by silviuaavram** [comment]
Thanks for the bug! Nice catch!

What do you think about fixing it?

**Comment by silviuaavram** [comment]
This should not happen anymore after v7.
