### ISSUE TITLE
Axe acccessibility violation when using `useSelect` example from docs ("scrollable-region-focusable")

### ISSUE THREAD

**Issue by wheelmaker24** [downshift-js/downshift#1293]
- `downshift` version: 6.1.3
- `node` version: 14.6.0
- `npm` (or `yarn`) version: 1.22.10
- `axe-core` version: 4.1.1

**Relevant code or config**

The issue below happens when using the markup from the `useSelect` example in the downshift docs:
https://www.downshift-js.com/use-select#basic-usage

**What you did**:

I created a select dropdown with the code example from the `useSelect` documentation page (see link above) and testet it with axe (`axe-core` or `jest-axe`).

**What happened**:

`axe-core` throws an error regarding an accessibility violation:

> "Elements that have scrollable content should be accessible by keyboard"
> Ensure that scrollable region has keyboard access
> https://dequeuniversity.com/rules/axe/4.1/scrollable-region-focusable?application=axeAPI

Full error message below:

```
"violations": [
    {
      "id": "scrollable-region-focusable",
      "impact": "moderate",
      "tags": [
        "cat.keyboard",
        "wcag2a",
        "wcag211"
      ],
      "description": "Elements that have scrollable content should be accessible by keyboard",
      "help": "Ensure that scrollable region has keyboard access",
      "helpUrl": "https://dequeuniversity.com/rules/axe/4.1/scrollable-region-focusable?application=axeAPI",
      "nodes": [
        {
          "any": [
            {
              "id": "focusable-content",
              "data": null,
              "relatedNodes": [],
              "impact": "moderate",
              "message": "Element should have focusable content"
            },
            {
              "id": "focusable-element",
              "data": null,
              "relatedNodes": [],
              "impact": "moderate",
              "message": "Element should be focusable"
            }
          ],
          "all": [],
          "none": [],
          "impact": "moderate",
          "html": "<ul id=\"downshift-49-menu\" role=\"listbox\" aria-labelledby=\"downshift-49-label\" tabindex=\"-1\" style=\"\n      max-height: 180px;\n      overflow-y: auto;\n      margin: 0px;\n      border-top: 0px;\n      background: white;\n      position: absolute;\n      z-index: 1000;\n      list-style: none;\n      padding: 0px;\n      left: 185px;\n      min-width: 200px;\n    \">",
          "target": [
            "#downshift-49-menu"
          ],
          "failureSummary": "Fix any of the following:\n  Element should have focusable content\n  Element should be focusable"
        }
      ]
    }
  ],
```

**Reproduction repository**:

I've created a codepen by copying the markup from the docs example and checking it against `axe-core`:
https://codepen.io/wheelmaker24/pen/dyWRemR

**Problem description**:

Axe thinks that the select dropdown is not scrollable via keyboard as it seems not to be recognising it as a listbox. Instead it thinks it's just overflow content and suggests to add a `tabIndex` to one of its element in order to make it accessible via keyboard.

**Suggested solution**:

The code example here might be fine and the issue may be with axe. However I wondered whether there might be additional aria roles that may appease axe tooling as both, `axe` and `downshift` state to be fully WAI-ARIA compliant.

**Comment by silviuaavram** [comment]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html we are following this focus pattern. I think axe does have a point, but I also think that our use case over here should be an exception.

Yeah, we could also have the options directly focusable, but it will require a big change on how useSelect works. At the moment it's not something that's on the roadmap.
