### ISSUE TITLE
aria-selected on Option is true only when highlighted

### ISSUE THREAD

**Issue by aleksandrlat** [downshift-js/downshift#1299]
aria-selected is true only when option is highlighted https://github.com/downshift-js/downshift/blob/master/src/hooks/useCombobox/index.js#L312

But what about the case when option is selected not just highlighted?
Is this possible to determine some how?

**Comment by silviuaavram** [comment]
Hi! Determining if the option is selected is up to you, this is a custom use case.

If you need to override our highlighted default logic you could just add `aria-selected` as a prop to `getItemProps` and make it false or true if the item is selected.

However the pattern is to have `aria-selected` for the highlighted items: https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html. It informs screen readers what option is currently highlighted. So if you do want to make changes, make sure your screen readers still know how to pick up that information.
