### ISSUE TITLE
[6.1.4] TS compile problem - broken storybook build

### ISSUE THREAD

**Issue by elodszopos** [downshift-js/downshift#1303]
- `downshift` version: 6.1.4
- `node` version: v14.16.1
- `npm` version: 6.14.12

**Relevant code or config**

Just a regular Storybook setup.

```javascript

    "@storybook/addon-actions": "^6.2.9",
    "@storybook/addon-controls": "^6.2.9",
    "@storybook/addon-docs": "^6.2.9",
    "@storybook/addon-info": "5.3.21",
    "@storybook/addon-postcss": "2.0.0",
    "@storybook/addon-viewport": "6.2.9",
    "@storybook/addons": "6.2.9",
    "@storybook/builder-webpack5": "6.2.9",
    "@storybook/preset-scss": "1.0.3",
    "@storybook/react": "6.2.9",
```

**What you did**:

Storybook build broke.

**What happened**:

```
92% sealing asset processing TerserPluginERR! => Failed to build the manager
ERR! ./node_modules/downshift/dist/downshift.esm.js 2268:25
ERR! Module parse failed: Unexpected token (2268:25)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! |                 .startsWith(lowerCasedKeysSoFar)) {
ERR! |             const element = getItemNodeFromIndex(offsetIndex);
ERR! >             if (!element?.hasAttribute('disabled')) {
ERR! |                 return offsetIndex;
ERR! |             }
ERR!  @ ./node_modules/@storybook/react/node_modules/@storybook/ui/dist/esm/components/sidebar/Search.js 43:0-34 258:11-20 269:11-20 275:11-20 294:11-20 295:11-20 335:11-20 346:42-51
ERR!  @ ./node_modules/@storybook/react/node_modules/@storybook/ui/dist/esm/components/sidebar/Sidebar.js
ERR!  @ ./node_modules/@storybook/react/node_modules/@storybook/ui/dist/esm/containers/sidebar.js
ERR!  @ ./node_modules/@storybook/react/node_modules/@storybook/ui/dist/esm/app.js
ERR!  @ ./node_modules/@storybook/react/node_modules/@storybook/ui/dist/esm/index.js
ERR!  @ ./node_modules/@storybook/react/node_modules/@storybook/core-client/dist/esm/manager/index.js
ERR!  @ multi ./node_modules/@storybook/react/node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./node_modules/@storybook/react/node_modules/@storybook/core-client/dist/esm/manager/index.js @storybook/addon-viewport/register @storybook/addon-controls/register @storybook/addon-actions/register ./.storybook/generated-refs.js
```

**Reproduction repository**:

Unable to provide at this time.

**Problem description**:

```
ERR! >             if (!element?.hasAttribute('disabled')) {
```

What looks to be a minor version bump suddenly swapped TS compile target to es2020. 

[`v6.1.3...v6.1.4`#diff-b55cdbef49](https://github.com/downshift-js/downshift/compare/v6.1.3...v6.1.4#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0)

**Suggested solution**:

Probably target shouldn't be es2020? Unless I'm missing something.

**Comment by silviuaavram** [comment]
I think the problem is here https://github.com/downshift-js/downshift/pull/1268/files. Let me try to remove it.

**Comment by victordcq** [comment]
Ah seems we were making the same bug report at the same time xd

**Comment by silviuaavram** [comment]
Could you try version 6.1.5-alpha.0?

**Comment by victordcq** [comment]
downshift@6.1.5-alpha.0 seems to have resulted in the same:/

**Comment by elodszopos** [comment]
Yeah - IMO a minor release umbrella definitely does not cover the changes introduced in 6.1.4. This change alone warrants a major version bump (React peer dep major version up - there's a _lot_ of people not using React 17 yet, you'd be surprised):

https://github.com/downshift-js/downshift/pull/1268/files#r680798786

Either way, I've downgraded to 6.1.3 for now and locked down npm module resolution to only use 6.1.3.

All is well again.

Appreciate jumping on this quick @silviuaavram. Mersi mult!

**Comment by victordcq** [comment]
i do use react17+ tho.
Ill downgrade downshift aswell for now

**Comment by silviuaavram** [comment]
The 6.1.4 fixed the peerdependencies issue since I didn't mean to do a breaking change just yet, 16.12.0 is ok.

I also want to fix this compile issue and I thought that removing the 2020 target in tsconfig fixed things, but apparently not?

**Comment by victordcq** [comment]
huh reverting back to 6.1.3 didnt even help for me:( how can that even happen

**Comment by silviuaavram** [comment]
Can you remove your node modules, cache clean, then try 6.1.5-alpha.0 again please? Just to be sure.

**Comment by elodszopos** [comment]
I'll check 6.1.5-alpha.0 and get back to you.

**Comment by victordcq** [comment]
@silviuaavram a clean install on 6.1.5-alpha.0 did not help. still getting the same error

**Comment by victordcq** [comment]
story book didnt upgrade over a week so, idk what else it could be

**Comment by thecodejack** [comment]
Hi @silviuaavram 

As @elodszopos pointed out, bumping versions of React to 17 will still be an issue for a minor release. Can we revert the dep changes for now along with es2020? It would be very helpful

**Comment by elodszopos** [comment]
React 17 version bump has been eliminated already, rolled back - no need to worry about that guys!

@silviuaavram 6.1.5-alpha.0 works. My assumption was correct. Can be published - Thanks! 

@victordcq `@storybook/ui` depends on `downshift`, if you simply add `"downshift": 6.1.3"` to your package.json, it won't help you. Underneath `@storybook/ui` will still install `6.1.4` version of `downshift`. NPM won't update transitive dependencies for you. Run `npm ls downshift` to see for yourself, I suspect that's what's happening on your end.

You need to use either:

a) yarn with yarn.lock
b) npm with shrinkwrap 
c) npm with package.lock
d) perhaps a tool like https://github.com/rogeriochaves/npm-force-resolutions

**Comment by silviuaavram** [comment]
Thanks for confirming it!

**Comment by thecodejack** [comment]
Thanks. Will `6.1.5` be released now?

**Comment by silviuaavram** [comment]
Let me know how it works with 6.1.5. Should be out in a jiffy.

Is there any way to test this in the future? I don't want this to bite us again.

Thanks for your patience and help everyone, sorry for the issue! I am going to refactor Downshift with TS in preparation for other features, and the PR with the issue was the one with the setup part (lint, rollup, tsconfig, etc.)

**Comment by thecodejack** [comment]
> Is there any way to test this in the future? I don't want this to bite us again.

Not straight forward I guess. Test having a babel compiler setup with minimum browser support on js file which is importing downshift as a node module should fix it.

**Comment by victordcq** [comment]
> add `"downshift": 6.1.3"` to your package.json,

Ahh that is indeed what i did, i guess it didnt register the 6.1.5alpha either, my bad
