### ISSUE TITLE
Version 6.1.5 has broken types

### ISSUE THREAD

**Issue by emmenko** [downshift-js/downshift#1307]
- `downshift` version: `6.1.5`

**What happened**:

The latest version of Downshift has the `typings` file with a broken import, as the bundled package obviously does not contain the `src` folder. The change was introduced in #1268 

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/1110551/128195869-10dc94d5-e3fe-4dfe-ac96-d47b6dba50be.png">

**Comment by silviuaavram** [comment]
Rats. We need this fixes asap.

In our project we have both manually written types in `typings/index.d.ts` and generated types (since the migration). These should be merged in the dist output.

Any idea how to fix this quickly @emmenko ?
