### ISSUE TITLE
Screen dictation in multiselect mode pronounce selected items incorrectly

### ISSUE THREAD

**Issue by amabunny** [downshift-js/downshift#1312]
- `downshift` version: 6.1.7
- `node` version:  14.16.1
- `npm` (or `yarn`) version: 7.15.0

**What you did**: just played with example on https://www.downshift-js.com/use-multiple-selection

**What happened**: in multiselect mode screen dictation doesnt pronounce selected options correctly (macOS system voiceover)

https://vimeo.com/manage/videos/586281652

**Reproduction repository**:
https://www.downshift-js.com/use-multiple-selection

**Problem description**:
As you can see in the video, when I pressed Enter button the first active option pronounced, but it's not that I actually selected. And the others options I selected didn't pronounced at all.

**Suggested solution**:
Maybe there's solution about "getA11yStatusMessage" prop. Any ideas?

**Comment by silviuaavram** [comment]
I think the video is unavailable. Feel free to open a new issue with steps, expected action and actual result if the problem still persists. Thank you!
