### ISSUE TITLE
useMultipleSelection hook's `removeSelectedItem` incorrectly adds an item

### ISSUE THREAD

**Issue by blovato** [downshift-js/downshift#1316]
Hey! Love the library! I noticed an issue with `removeSelectedItem` that I wanted to notify you of and possibly contribute a fix for:

- `downshift` version: 6.1.7
- `node` version: 14.17
- `yarn` version: 1.22.10

**Overview**:
I was using `useMultipleSelection` with `useCombobox` and I had two items selected [A, B]. When I called `removeSelectedItem` with undefined as the first argument, my selected items changed to [A, A, B].

**Reproduction repository**:
You can see the bug at play in this [sandbox](https://codesandbox.io/s/downshift-usemultipleselection-remove-item-bug-wolws?file=/src/App.js).

**Problem description**:
If we look at the reducer for useMultipleSelection and step through the [`FunctionRemoveSelectedItem`](https://github.com/downshift-js/downshift/blob/master/src/hooks/useMultipleSelection/reducer.js#L70-L88) case we can see how this bug might arise. 
We don't need to pay attention to the `activeIndex` here because it's not used in this block to compute the `selectedItems` array.

```js
// globals
selectedItems = ['test1', 'test2']
selectedItem = undefined

case stateChangeTypes.FunctionRemoveSelectedItem: {
    //let newActiveIndex = activeIndex
    const selectedItemIndex = selectedItems.indexOf(selectedItem) // = -1

    //if (selectedItems.length === 1) { // false, doesn't enter
    //  newActiveIndex = -1
    //} else if (selectedItemIndex === selectedItems.length - 1) { // false, doesn't enter
    //  newActiveIndex = selectedItems.length - 2
    //}

  changes = {
    selectedItems: [
      ...selectedItems.slice(0, selectedItemIndex), // slice(0, -1) = ['test1']
      ...selectedItems.slice(selectedItemIndex + 1), // slice(0) = ['test1', 'test2']
    ], // = ['test1', 'test1', 'test2']
    ...{activeIndex: newActiveIndex},
  }
  break
}
```

**Suggested solution**:
If we determine the `selectedItemIndex` is less than 0, we can break out of this case early.

**Comment by linda-rian** [comment]
I have the same problem when set `initialSelectedItems`—trying to remove any of the initial items is just adding them to selected array.

**Comment by silviuaavram** [comment]
Hi! Thanks for reporting this! Could you go ahead and also submit a PR to fix it? It will help a lot!

**Comment by linda-rian** [comment]
I'll try to find time to submit a PR, would love to help!

**Comment by RoyalHunt** [comment]
> I have the same problem when set `initialSelectedItems`—trying to remove any of the initial items is just adding them to selected array.
> 
> UPD. In my case the problem was with the `indexOf`. My items are objects and _selected item_ object link was different from the object link of the same item in the `initialSelectedItems` so `indexOf` wasn't working. Having persistent object links helped.

Hello, Linda.
Do you have any examples of what you've had and done? It will be greatly appreciated.
