### ISSUE TITLE
useCombobox example on github page only reads the part of the selected word on select

### ISSUE THREAD

**Issue by jg123** [downshift-js/downshift#1318]
- `downshift` version: 6.1.7
- `node` version: 14
- `npm` (or `yarn`) version: 6.14.13

**Relevant code or config**

Used the useCombobox example here with Talkback for Android: https://www.downshift-js.com/use-combobox#basic-usage

**What you did**:

Samsung A71 5G/ Android 11/Talkback

Typed "nob" into the input field.
Double tapped "Nobelium".

**What happened**:

Talkback says, "ellium"
https://user-images.githubusercontent.com/693277/134219981-ad7081c9-5a1b-49f6-a2bf-46f6b1ccb9c1.mp4

**Problem description**:

useCombobox is reading the added part of the text when adding it to input, not the full amount of text.

**Suggested solution**:

Read "Nobellium".

**Comment by silviuaavram** [comment]
Hi! Thanks for reporting! Our combobox should work similarly to https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html.

If the ARIA example works with your use case, could you help us with a fix for `useCombobox`? Thanks!

**Comment by jg123** [comment]
The ARIA example does the same  thing, so not a bug. Type in "ban", double-tap banana, and Talkback reads, "ana". Thanks for your guidance!
