### ISSUE TITLE
Form is submitted on keydown Enter when combobox menu is open

### ISSUE THREAD

**Issue by alveshelio** [downshift-js/downshift#1319]
Versions:
chakra-ui 1.6.7
downshift 6.1.7
node: 16.6.2
yarn 1.22.11

I'm building a multiselect component with charkra-UI and downshift and I have a weird behaviour. When the combobox is open and hit Enter the form is submitted.

I was looking at this PR: https://github.com/downshift-js/downshift/pull/1150 which seemed to fix the issue but in my case it's not working.

I've recorded the behaviour: https://www.loom.com/share/83645002d10745efa867b248a4a39fbe
I've also created this codesandbox: https://codesandbox.io/s/multiselect-chakra-ui-downshift-em5u7?file=/src/components/Multiselect.tsx

Actual behaviour:
Select one or more items, then click in the input and hit Enter and you'll see that the form get submitted

Expected behaviour:
The form should not be submitted when the menu is open. When the focus is on the combobox, the form should never be submitted.

**Comment by silviuaavram** [comment]
Hi! From reading that PR description, `Prevent event default (form submission) if menu is open.`

So when the menu is closed, then I expect the form to be submitted on Enter. I think it's correct behaviour, right?

**Comment by alveshelio** [comment]
> Hi! From reading that PR description, `Prevent event default (form submission) if menu is open.`
> 
> So when the menu is closed, then I expect the form to be submitted on Enter. I think it's correct behaviour, right?

Yes if the menu is closed it should submit the form, however, in my case the menu is open.

**Comment by alveshelio** [comment]
@silviuaavram Do you need more information? I'm wondering if this is only me or it's an actual bug. In the codesandbox I've created it does not behave as it should (it should not submit the form if the menu is open)
