### ISSUE TITLE
useCombobox react-virtual example crashes when searching for items

### ISSUE THREAD

**Issue by Haemoglobin** [downshift-js/downshift#1323]
In this example here: https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useCombobox/react-virtual.js 

If I type "am" (i.e searching for America), it crashes with the error: _Cannot read properties of undefined (reading 'id')_
on line 62 of react-virtual.js:  _key={items[virtualRow.index].id}_

I'm not sure if this is just a coding problem with the example, or a bigger issue with virtualization in general? 
 
Thanks, 
Hamish

**Comment by Haemoglobin** [comment]
It seems this is to do with some empty virtualItems of the rowVirtualizer that just have a measureRef property and nothing else. 

I can get it working by adding the following filter to ensure the item has an index, is this the right thing to do? 
```
{rowVirtualizer.virtualItems.filter(r => "index" in r).map((virtualRow) => (
```

Thanks

**Comment by piecyk** [comment]
@Haemoglobin updating react-virtual fixes the issue

https://codesandbox.io/s/busy-thompson-j22fw?file=/src/hooks/useCombobox/react-virtual.js
