### ISSUE TITLE
feat: Allow string highlightedIndex in fully controlled environment

### ISSUE THREAD

**Issue by haxxxton** [downshift-js/downshift#1324]
I have a scenario where i have nested selection options within collapsible regions of the Downshift menu. To facilitate full keyboard control of this component, i have created an index scheme like `0-1` to indicate the first collapsible region, and the second item within that. Highlighting of just the collapsible title/control has an index like `0`. I am using the stateAndReducer prop to fully control the changing of the highlight index via keyboard controls, and selection of items. However, my defaultHighlightedIndex is then a string; which produces a propTypes warning of:
![image](https://user-images.githubusercontent.com/743105/135706429-21b678ff-470b-4974-856a-6a39feff70c5.png)

Would it be possible to change this property to accept either a number or a string? or even an option to suppress this warning?

**Comment by silviuaavram** [comment]
We can't change that, as it will break our own logic. Try to make a mapping yourself. The stateReducer is not usable for controlling stuff, make sure you use onStateChange for that. Also defaultHighlightedIndex is not used to control the prop, that's highlightedIndex.

There are probably many things wrong with your usage, please review the documentation, docsite, usage examples, and consider using useCombobox. Then if you still have questions, open a new issue with a sandbox / code example of your usage. Thank you!
