### ISSUE TITLE
useSelect MultiSelect with Save Button Inside Menu

### ISSUE THREAD

**Issue by wluisi** [downshift-js/downshift#1330]
- `downshift` version: 6.1.3
- `node` version: latest
- `npm` (or `yarn`) version: latest

**Problem description**:
I'm trying to create a MutliSelect component using downshift's `useSelect` hook, that has a "Save" button inside the menu, below the checkboxes. I'm having an issue getting the "save" button to be reachable by keyboard navigation (down arrow). Currently, I can't navigate with down arrow past the last item in the multiselect.

Is this possible?

**Reproduction repository**:
Example of the problem is here in this simple code sandbox:
https://codesandbox.io/s/downshift-multiselect-nested-save-button-jygob?file=/src/MultiSelect.js

**Comment by silviuaavram** [comment]
useSelect is used for a `<select>` equivalent element. Yes, it supports multiple selection (with the example shown by you or with a taglist via useMultipleSelection). However, keep in mind that the items in the menu are just for the purpose of being selected, not actioned upon. It's not a menu, or a actionable list. If useSelect helps you get the job done, that's fine, but it's not it's main purpose, which is to create a accessible single selection combobox (select element equivalent).
