### ISSUE TITLE
feat: Support more keyboard event meta in reducers

### ISSUE THREAD

**Issue by essmahr** [downshift-js/downshift#1332]
### Use Case

I am hoping to implement different behaviour on `cmd`/`ctrl` + `Enter` and plain `Enter` keydowns. For example, with `useMultipleSelection`, `Enter` would select an item but leave the menu open for further selection, and `cmd + Enter` would "Submit" by both selecting the item and closing the menu.

Ideally this could be accomplished this in `stateReducer` on `useCombobox.stateChangeTypes.InputKeyDownEnter`, but of course we don't have access to anything beyond the action type:

https://github.com/downshift-js/downshift/blob/a6bcd2247f4757b9a6c4077fdd9cf07554049054/src/hooks/useCombobox/index.js#L218-L221

### Implementation

I see that for arrow events, we are passing a `shiftKey` bool with the action:

https://github.com/downshift-js/downshift/blob/a6bcd2247f4757b9a6c4077fdd9cf07554049054/src/hooks/useCombobox/index.js#L155-L170

I see value in passing more meta with key events: either `ctrlKey` and `metaKey` to `Enter` events to fulfill my use case, or making inclusion of `ctrlKey`, `ctrlKey` and `shiftKey` the default for all dispatches in `inputKeyDownHandlers`.

Off the top of my head, another use case here is command + arrow in conjunction with useMultipleSelection to mark the next or previous item as selected.

Open to suggestions on other ways to achieve the use case I've outlined. Otherwise, happy to sumbit a PR for this. Thanks!

**Comment by silviuaavram** [comment]
If it's not standard pattern for combobox or taglist, we are not going to include anything by default. If you need custom events, add them manually as argument to the getter props functions:
`getInputProps({onKeyDown: e => {//magic}})`
