### ISSUE TITLE
How to set initial selected items Asynchronously

### ISSUE THREAD

**Issue by alveshelio** [downshift-js/downshift#1338]
- `downshift` version: 6.1.7
- `node` version: 16.13.0
- `npm` (or `yarn`) version: yarn 1.22.15

**What you did**:
I've created a `Multiselect` component with Chakra-ui and downshift using `useCombobox` and `useMultipleSelection`, and I'm trying to set `initialSelectedItems` Asynchronously, however, it never gets set.

**What happened**:
`initialSelectedItems` never get set asynchronously

I've created this codesandbox https://codesandbox.io/s/downshift-chakra-ui-xf3wq?file=/src/App.tsx where I'm just using a simple `setTimeout()` to set the `initialSelectedItems` at a later time.

How can `setSelectedItems` be set asynchronously?

Thank you

**Comment by silviuaavram** [comment]
Hi! `initialSelectedItems` should be set at first render, as it acts as an initial/default prop that you don't mean to control directly, just once at the start.

However, since you are getting the items asynchronously, I suggest either controlling `selectedItems` or, maybe better for your use case, use `setSelectedItems` in the callback of you async call, and call it with your items. And it should work.

Let me know if you need further help. Thanks!

**Comment by aaronnuu** [comment]
Because your `Multiselect` is it's own component you can force the component into re-rendering by adding a key.

```js
<Multiselect
  key={initialSelectedItems.length}
  id="countries"
  name="countries"
  placeholder="Select one or more countries"
  initialSelectedItems={initialSelectedItems}
  onChange={handleOnChange}
  options={options}
/>
```

I wouldn't always recommend doing this, and you have to make sure to never update the `initialSelectedItems` again otherwise you lose state, but it's a useful trick for some occasions.

**Comment by alveshelio** [comment]
> Because your `Multiselect` is it's own component you can force the component into re-rendering by adding a key.
> 
> ```js
> <Multiselect
>   key={initialSelectedItems.length}
>   id="countries"
>   name="countries"
>   placeholder="Select one or more countries"
>   initialSelectedItems={initialSelectedItems}
>   onChange={handleOnChange}
>   options={options}
> />
> ```
> 
> I wouldn't always recommend doing this, and you have to make sure to never update the `initialSelectedItems` again otherwise you lose state, but it's a useful trick for some occasions.

I've actually ended up using this approach . Thank you
