### ISSUE TITLE
VoiceOver on Chrome reads option twice

### ISSUE THREAD

**Issue by tu4mo** [downshift-js/downshift#1343]
- `downshift` version: 6.1.7

**What you did**:

Select second item from a list with keyboard.

**What happened**:

VoiceOver stops reading in the middle of the option and starts again from the beginning, discarding the "selected, x of x".

**Reproduction repository**:

Basic usage example from https://downshift.netlify.app/use-select.

**Comment by silviuaavram** [comment]
It worked before :(. It's a VO update, as far as I can tell. https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html has the same issue, and this also worked before. Maybe they should fix it, or ARIA should adapt their pattern.
