### ISSUE TITLE
Passing Floating UI reference to getComboboxProps causes a crash

### ISSUE THREAD

**Issue by tu4mo** [downshift-js/downshift#1350]
- `downshift` version: 6.1.7

**Relevant code or config**

```javascript
const { floating, reference, strategy, x, y } = useFloating({ placement: 'bottom-start' })

<div style={comboboxStyles} {...getComboboxProps({ ref: reference })}>
```

**What happened**:

Infinite loop. Browser crashes.

**Reproduction repository**:

https://codesandbox.io/s/great-bash-5ilf1?file=/src/hooks/useCombobox/basic-usage.js:754-758

**Comment by atomiks** [comment]
You probably want to pass Floating UI's internal refs is from the `refs` property that gets returned instead:

```js
const { floating, reference, strategy, x, y, refs } = useFloating({ placement: 'bottom-start' })

<div style={comboboxStyles} {...getComboboxProps({ ref: refs.reference })}>
```

The `floating` and `reference` are callback refs that internally call `update()` and should probably only be passed to a DOM node's actual `ref` prop.

**Comment by JuanM04** [comment]
Works like a charm.

The only caveat it that you may need to do some casting in TypeScript:

```tsx
import type { MutableRefObject } from 'react'

<input
  {...getInputProps({ ref: refs.reference as MutableRefObject<HTMLInputElement | null> })}
/>
```

**Comment by tu4mo** [comment]
Thanks @atomiks! ❤️

**Comment by denchen** [comment]
One note: You don't need to cast. `useFloating()` accepts a generic

```tsx
const { refs } = useFloating<HTMLInputElement>({ placement: 'bottom-start' })
```

This will set `ref.reference` to `React.MutableRefObject<HTMLDivElement | null>`

I'm currently experiencing a different issue where my Floating UI dropdown menu is not updating its position when scrolling, even with `autoUpdate` set, but I don't know if it's a Floating UI or Downshift issue or a mix of the two (I'll create a new issue if it is related to Downshift).
