### ISSUE TITLE
Can't import DownshiftInterface from 'downshift'

### ISSUE THREAD

**Issue by caroline-niesen** [downshift-js/downshift#1352]
- `downshift` version: 6.1.7
- `node` version: v16.13.1
- `npm` (or `yarn`) version: yarn 1.22.17

**Relevant code or config**

```
import Downshift, { DownshiftInterface } from 'downshift';
```

<img width="569" alt="Screen Shot 2022-01-05 at 3 17 38 PM" src="https://user-images.githubusercontent.com/95655071/148290758-10fa4faa-387e-4fb4-9798-95cf6618960c.png">

**Problem description**:
Adding ts typing to a dropdown and I cannot import the DownshiftInterface type from my 6.1.7 install of downshift. 

Am I missing something?

**Comment by silviuaavram** [comment]
It does not exist. Where did you find it?

**Comment by caroline-niesen** [comment]
@silviuaavram https://github.com/downshift-js/downshift/issues/693 last seen in 2019
