### ISSUE TITLE
Readme code example doesn't work.

### ISSUE THREAD

**Issue by swbrenneis** [downshift-js/downshift#1354]
- `downshift` version: 6.1.7
- `node` version: 16.11.0
- `npm` (or `yarn`) version: yarn 1.22.15

**Relevant code or config**

The code is from the example in the readme

**What you did**:

Tried to use the example code

**What happened**:

Does not compile. 
{...getRootProps({}, {suppressRefError: true})} is invalid since the first argument has a required field, refKey.
The argument seems to be a GetRootPropsOptions interface, but there is no documentation of what is
in that interface or what the required field is.

**Reproduction repository**:

**Problem description**:

Unable to use the readme example as a starter.

**Suggested solution**:

Document the GetRootPropsOptions interface. Fix the readme example.

**Comment by evenfrost** [comment]
Any update on this? Just stumbled upon this when trying Downshift in my TS project.

**Comment by silviuaavram** [comment]
Why not use `useCombobox`?

**Comment by silviuaavram** [comment]
https://github.com/downshift-js/downshift#getrootprops The documentation is here. The type not being optional in TS is relevant and should be fixed. Thank you!

On the other hand, you should use `useCombobox` since it aims to provide ARIA 1.2 combobox pattern support.
