### ISSUE TITLE
`highlightedIndex` is not preserved when using objects

### ISSUE THREAD

**Issue by tu4mo** [downshift-js/downshift#1359]
- `downshift` version: 6.1.7

**Reproduction repository**:

https://codesandbox.io/s/ancient-silence-3mk5u?file=/src/hooks/useCombobox/basic-usage.js

**Problem description**:

When using array of objects as options, highlightedIndex is not preserved if options are updated and menu is opened again.

**Comment by silviuaavram** [comment]
Why should it be? You have new objects, so whatever object you highlighted previously is, theoretically, obsolete. It works as expected.

You have multiple ways to influence the update of the highlightedIndex if you need a custom behaviour, such as control props, defaultHighlightedIndex, setHighlightedIndex, etc. You can check them in the documentation and use what is best for you.

Thanks!

**Comment by tu4mo** [comment]
In my app, I'm passing the new object (using `options.find`) to `selectedItem`. It shows as selected, but highlighting starts from the first item. I guess I'll have to dig deeper.

**Comment by silviuaavram** [comment]
Or you could update the codesandbox with this detail from your app and we can try to figure out what's the issue.
