### ISSUE TITLE
[useMultipleSelection] onSelectedItemsChange fires only with the last update if `addSelectedItem` is called in a loop

### ISSUE THREAD

**Issue by Gusis93** [downshift-js/downshift#1360]
- `downshift` version: latest
- `node` version: 14.18.1
- `npm` (or `yarn`) version: 1.22.15

**Relevant code or config**

```javascript
const {
    getSelectedItemProps,
    getDropdownProps,
    addSelectedItem,
    removeSelectedItem,
    selectedItems,
  } = useMultipleSelection({
    selectedItems: options,
    onSelectedItemsChange: ({selectedItems}) => setOptions(selectedItems),
  })

```

**What you did**:
- Using an external source for the selected items and sending it to the `useMultipleSelection` hook
- Create a "Select All" button that selects all the options in the select

**What happened**:
Only the last option is set as selected. `onSelectedItemsChange` is only called with the last option from the loop

**Reproduction repository**:
https://codesandbox.io/s/rough-moon-167st?file=/src/hooks/useMultipleSelection/combobox.js

**Problem description**:
- When looping trough options and adding them 1 by 1 with `addSelectedItem`, `onSelectedItemsChange` is only called on the last loop iteration thus adding only the last option.

**Suggested solution**:
- `onSelectedItemsChange` should be called with every item and every item should be selected.

Extra notes:
- Cannot be reproduced without  `selectedItems` being controlled.
- If I use `setSelectedItems` with an Array instead of looping trough each option then it works fine, tough there is no way of bulk removing them the same way and the same issue is present with `removeSelectedItem`

**Comment by silviuaavram** [comment]
Hi! You are using both `addSelectedItem` and also control the `selectedItems` directly, which is probably why this inconsistency happens. Please choose only one approach, either control `selectedItems` and setOptions with all the options on that button click, or remove the `selectedItems` controlled prop and continue to use `addSelectedItem`.

Below I chose the second approach and clicked on the button.

<img width="1328" alt="Screenshot 2022-02-10 at 11 02 12" src="https://user-images.githubusercontent.com/11275392/153373293-19e11ba6-41c7-43f9-ace6-ba3bc18f7adc.png">

**Comment by Gusis93** [comment]
Thank you so much ! Seemed obvious when you pointed it out...works as expected now. Thank you!
