### ISSUE TITLE
Changing selectedItem programmatically makes screen reader announce it

### ISSUE THREAD

**Issue by tu4mo** [downshift-js/downshift#1362]
- `downshift` version: 6.1.7

**Reproduction repository**:

https://codesandbox.io/s/jolly-mendeleev-qxzry?file=/src/hooks/useSelect/controlling-state.js

1. Turn on VoiceOver
2. Click "Set manually"

**Problem description**:

If selectedItem is changed programmatically, screen reader (VoiceOver on Mac) will read selection like it was made by the user.

**Comment by silviuaavram** [comment]
I think it's working as expected. If you change the item, it should be announced, unless you explicitly do not want to do that. Why should useSelect differentiate between these two types of changing the item? If you choose to change it, in any way, shape or form, then the end user with a screen reader needs to know about it.

**Comment by tu4mo** [comment]
It's completely different thing for an app to change the value than when user knows the element exists, has focus on it and changes it. Now it's just a distraction. Changing a value of `<select>` doesn't announce anything. Why not just follow native behavior as closely as possible?
