### ISSUE TITLE
Cannot re-select item without completely clearing inputValue

### ISSUE THREAD

**Issue by keighleymcf** [downshift-js/downshift#1363]
- `downshift` version: 6.1.7
- `node` version: 15.14.0
- `npm` (or `yarn`) version: 7.15.1

**Relevant code or config**
Here is my useCombobox, which is used inside of a Formik form in a react functional component

```
export const AutoSuggestInput = ({
  items,
  name,
  ...props
}) => {
  const [{ value }, , { setValue }] = useField({name}) // to use and set formik field value
  const [inputItems, setInputItems] = useState(items);

  const {
    isOpen,
    inputValue,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    highlightedIndex,
    getItemProps,
  } = useCombobox({
    items: inputItems,
    itemToString: (item: Item | null) => {
      return item ? item.label : "";
    },
    onInputValueChange: ({ inputValue }) => {
      // when inputValue is changed, this resets the formik value (value stored/sent in form values)
      // so an outdated value is not accidentally kept in formik without the user seeing
      value && setValue("");
      setInputItems(getFilteredItems(inputValue));
    },
    onSelectedItemChange: ({ selectedItem }) => {
      if (selectedItem) {
        // sets formik value
        setValue(selectedItem.id);
      }
    },
  });

const getFilteredItems = (inputValueString: string | undefined) => {
    return inputValueString
      ? items.filter((item) =>
          item.label.toLowerCase().startsWith(inputValueString.toLowerCase())
        )
      : items;
  };

...... 

```

**What you did**:
1. Enter a value in the combobox field
2. Choose an item from the dropdown with mouse click or enter keypress
3. Change the inputValue in the field (e.g. delete a character)
4. Select the same item in the dropdown with mouse click or keypress

**What happened**:

5. onSelectedItemChange is not called, even though selectedItem is actually updated

**Reproduction repository**:

The issue can be seen in the code example in the Controlling State section of the useCombobox downshift docs: https://www.downshift-js.com/use-combobox#controlling-state
1. Enter a value in the top combobox
2. Select an option from the top dropdown
3. Delete some characters from the value in the first box
4. Enter the same value in the bottom box
5. Select the same option from the bottom dropdown
6. The value in the top box, which is supposed to be connected via a shared selectedItem, is not updated

**Problem description**:
If the user deletes character(s) from the input field and tries to reselect the same item, the dropdown visually behaves as if the item is selected (dropdown closes, inputValue is set to the selectedItem (or the selectedItem toString)) and selectedItem is actually updated, BUT onSelectedItemChange is not called.

**Suggested solution**:

onSelectedItemChange should be called whenever an item is selected from the drop down, regardless of whether the item was selected before and/or if an inputValue is present

It seems like this might be a similar problem as this issue: https://github.com/downshift-js/downshift/issues/232 which was fixed in the Downshift component, but the problem is unfortunately present again in the useCombobox hook.

Right now, I had to implement this as a workaround:

```
const {
    isOpen,
    inputValue,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    highlightedIndex,
    getItemProps,
  } = useCombobox({
    items: inputItems,
    itemToString: (item: Item | null) => {
      return item ? item.label : "";
    },
    onInputValueChange: ({ inputValue }) => {
      // when inputValue is changed (text the user sees in the input), reset the formik value (value stored/sent in form values)
      // so an outdated value is not accidentally kept without the user seeing
      value && setValue("");
      setInputItems(getFilteredItems(inputValue));
    },
    // we need to use the stateReducer to handle the change to selected value
    // instead of using onSelectedItemChange
    stateReducer: (_state, actionAndChanges) => {
      const { type, changes } = actionAndChanges;
      // set formik value to selectedItem
      switch (type) {
        case useCombobox.stateChangeTypes.ItemClick:
        case useCombobox.stateChangeTypes.InputKeyDownEnter:
          if (changes.selectedItem) {
            setValue(changes.selectedItem.id);
          }
          return changes;
        default:
          return changes; // otherwise business as usual.
      }
    },
  });
```
I supposed it might also just work to see if `changes`has selectedItem, but I didn't have time to look under the hood and check it

**Comment by silviuaavram** [comment]
Hi @keighleymcf ! It works as expected, as the selectedItem does not change. It's the same one. If we want to add an improvement, we can create the `onChange` prop for the hooks, to be called on every selection, even when the item is the same. If you feel like contributing, we can create a new issue to add onChange on both useSelect and useCombobox. I did not add it myself as I did not find much use for it, as I am generally interested to know if the selectedItem changes. But I can agree that the onChange use case is also useful.

You should also alter your workaround to use `onStateChange` instead of `stateReducer`, since the latter should only return state, without performing any side effects (setValue).

Let me know what you think!

**Comment by keighleymcf** [comment]
This seems to work great! Thank you. It would be great if you could add this to the docs. 🙏

**Comment by keighleymcf** [comment]
@silviuaavram  `onStateChange` does not work in this case, because it has the same issue as `onSelectedItemChange`. `onStateChange` does not recognize when the `selectedItem` is selected a second time after changing the `inputValue`, since it again reacts only to _changes_ in the `selectedItem`. 

If the `selectedItem` got automatically de-selected/set to undefined when the `inputValue` changes, this would not be a problem. But this isn't the case.

I also tried to add a line to `onInputValueChange` to set the `selectedItem` to undefined if the `inputValue` is changed:
```onInputValueChange: ({ inputValue }) => {
      // when inputValue is changed (text the user sees in the input), reset the formik value (value stored/sent in form values)
      // so an outdated value is not accidentally kept without the user seeing
      value && setValue("");
      selectedItem && selectItem(undefined);
      setInputItems(getFilteredItems(inputValue));
      validateField(name);
    },```
 but `selectItem` cannot accept undefined, so this does not work.

So I have to stick with my workaround.

There are actually a few possible solutions:
1.  add `onChange` as you suggest above
2. change functionality to de-select a `selectedItem`/change `selectedItem` to undefined if the `inputValue` changes after a selection
3. Allow `selectItem` to accept `undefined`

If you have a preference for any of them, I would be happy to collaborate on an issue/PR.
