### ISSUE TITLE
Aria 1.2 support for useSelect

### ISSUE THREAD

**Issue by tu4mo** [downshift-js/downshift#1365]
Migrate useSelect from 1.1 to 1.2 ARIA pattern.

**Comment by silviuaavram** [comment]
Are you talking about https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-select-only.html ?

**Comment by silviuaavram** [comment]
The reason for this behaviour is that we currently follow https://www.w3.org/TR/wai-aria-practices-1.2/examples/listbox/listbox-collapsible.html. We should update our hooks to reflect this. I will keep this issue open to track it.

**Comment by tpict** [comment]
The new spec seems to shed some light on #935, too!
