### ISSUE TITLE
[Hooks] Passing value as undefined and defaultValue and non-undefined will result in undefined

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#1370]
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
const {selectedItem} = useSelect({selectedItem: undefined, defaultSelectedItem: 'hello'})
console.log(selectedItem) // undefined
```

It should be `'hello'`. We probably need to remove or change how the function returning the value from initial/default/controlled works.

**Comment by gynekolog** [comment]
@silviuaavram There exists the issue: #1331 

Possible workaround is 
```ts
const {selectedItem} = useSelect({
    ...(option ? { selectedItem: option } : {}),
    defaultSelectedItem: 'hello'
})
```

**Comment by silviuaavram** [comment]
It should be fixed, for sure.

This is a very rare corner case. If you control the selectedItem then we expect you to pass a non-undefined value. I probably expect that in your use case you have a component that can have its own selectedItem controlled or not.

**Comment by silviuaavram** [comment]
I will take this one to fix, unless someone else wants to.
