### ISSUE TITLE
Qurstion/request: Browser support documentation

### ISSUE THREAD

**Issue by mirajac** [downshift-js/downshift#1375]
Question: is there existing documentation of browser support? 

If not: would it be possible to document the browser support? I'm trying to compare different solutions and I'm not clear if this supports my use case. Much appreciated!

- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:

**What happened**:

**Reproduction repository**:

**Problem description**:

**Suggested solution**:

**Comment by silviuaavram** [comment]
There is not. Theoretically, it should be supported by all browser and screen reader combinations, as we follow the ARIA patterns and the browsers + screen readers should also follow that in order to work.
