### ISSUE TITLE
Getting ref prop not applied correctly in getMenuProps function

### ISSUE THREAD

**Issue by naveenkash** [downshift-js/downshift#1376]
- `downshift` version: "^6.1.7"
- `node` version: v17.8.0
- `yarn` version: 1.22.18

**Relevant code or config**

```javascript


export const SingleSelect: FC<ISingleSelectProps> = ({
  options,
  labelText,
  placeholder,
  onChange,
}: ISingleSelectProps) => {
  const [searchValue, setSearchValue] = useState<string>('');
  const [activeItem, setActiveItem] = useState<IOptionProps>();

  const getFilteredItems = () =>
    options.filter((item) => item.id !== activeItem?.id);

  const getSearchFilteredItems = () =>
    getFilteredItems().filter((item) =>
      item?.text?.toLowerCase().includes(searchValue.toLowerCase())
    );

  const items = getSearchFilteredItems();
  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps,
    getComboboxProps,
    getInputProps,
    setInputValue,
  } = useCombobox({
    items,
    onStateChange: ({ inputValue, type, selectedItem }) => {
      switch (type) {
        case useCombobox.stateChangeTypes.InputChange:
          setSearchValue(inputValue ?? '');
          break;
        case useCombobox.stateChangeTypes.InputKeyDownEnter:
        case useCombobox.stateChangeTypes.ItemClick:
        case useCombobox.stateChangeTypes.InputBlur:
          if (selectedItem) {
            setSearchValue('');
            setActiveItem(selectedItem);
            setInputValue(selectedItem?.text ?? '');
            onChange(selectedItem);
          }
          break;
        default:
          break;
      }
    },
  });

  return (
    <div className="w-full">
      {labelText ? (
        <label
          className={`block body-sm whitespace-nowrap mb-1`}
          {...getLabelProps()}
        >
          {labelText}
        </label>
      ) : null}
      <div className="relative" {...getComboboxProps()}>
        <input
          className={`${DEFAULT_INPUT_CLASSNAMES} ${
            isOpen ? 'rounded-b-none' : ''
          }`}
          {...getToggleButtonProps()}
          {...getInputProps()}
          placeholder={placeholder}
        />
        {isOpen ? (
          <ul
            {...getMenuProps()}
            style={{
              maxHeight: 345,
            }}
            className="absolute top-10 left-0 bg-white w-full rounded-b-lg overflow-hidden px-4 py-1 mt-0 shadow-xl border-2 border-t-0 overflow-y-scroll border-grey-200 focus:outline-none focus:ring-0"
          >
            {items.map((item, index) => (
              <li
                style={
                  highlightedIndex === index
                    ? { backgroundColor: '#EFF3FE' }
                    : {}
                }
                key={`${item.id}${index}`}
                {...getItemProps({ item, index })}
                className={`cursor-pointer ${
                  index !== items.length - 1 ? 'border-b border-grey-200' : ''
                }`}
              >
                <div className="hover:bg-grey-50">{item.label}</div>
              </li>
            ))}

            {!items.length ? <div>No options available</div> : null}
          </ul>
        ) : null}
      </div>
    </div>
  );
};


```

**What you did**:

**What happened**: <img width="425" alt="Screenshot 2022-04-28 at 1 15 02 AM" src="https://user-images.githubusercontent.com/31365913/165619328-8aa2889b-9773-403c-83e4-3e2f0af57cdc.png">

**Reproduction repository**:

**Problem description**: Getting the error in console ref prop was not applied correctly from getMenuProps function

**Suggested solution**:

**Comment by trainoasis** [comment]
I get the same errors for all downshift components we use, but only when running Storybook-Jest tests. It's pretty annoying but cannot figure out how to get rid of it except doing this, which doesn't seem like something I'd wanna do. Similar question [here](https://github.com/downshift-js/downshift/issues/1167).

**Comment by romgrk** [comment]
I think the error message should go. I'm getting the same message. The cause seems to be that the menu element isn't rendered until it's opened, but that's an important feature. In my case, the popup element only renders to the DOM on the initial open, not before; this improves performance when there are lots of dropdowns.

cc @silviuaavram

**Comment by silviuaavram** [comment]
The error comes from the fact that you are conditionally rendering the menu based on isOpen. In all our examples, and in the documentation, we clearly specify that the menu needs to always be in the DOM, and only conditionally render the items.

https://github.com/downshift-js/downshift#getmenuprops

**Comment by romgrk** [comment]
Is there an accessibility reason why the element needs to be in the DOM at all times, or is this just an API choice to simplify things on your side?

**Comment by silviuaavram** [comment]
Accessibility. https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/combobox/aria1.1pattern/listbox-combo.html https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html

Up you if you want to conditionally render the items or make the menu display none, but make sure you render it.
