### ISSUE TITLE
Unnecessary rerenders from getItemProps

### ISSUE THREAD

**Issue by osdiab** [downshift-js/downshift#1377]
- `downshift` version: 6.1.7
- `node` version: 14.16.1
- `npm` (or `yarn`) version: 3.1.1

**What you did**:
I use `useCombobox` and get `getItemProps()` from it, and apply those to individual list items. I also memoize the component that renders a single list item. It feels sluggish.

 When i mouse around, every list item rerenders due to changes to the `onMouseMove()` and `onClick()` props, even though conceptually speaking, nothing really ought to change about other list items. On a long list, this gets quite slow.

**What happened**:

[Eyeballing the code](https://github.com/downshift-js/downshift/blob/master/src/hooks/useCombobox/index.js#L260), it seems that while `getItemProps()` itself is memoized, it creates new functions for every item whenever it itself gets rerendered. But most of those functions will do the same thing as the old values, which makes children get unnecessarily rerendered even if they are memoized.

**Reproduction repository**:
ill do it if i have some extra time but might not come soon. but it seems to happen on the material ui example in the downshift website

**Problem description**:
not every item should be rerendering when unrelated items get hovered/focused

**Suggested solution**:
restructure/memoize code such that `onMouseMove` and `onClick` only get replaced if they absolutely need to.

**Comment by osdiab** [comment]
hm actually i guess they probably do need to be recreated since checking equality with the highlighted index will need to be updated. so yea guess this is invalid, closing!f

**Comment by osdiab** [comment]
hm, maybe it can be structured in such a way that doesn't cause rerenders if it did something similar to the `onClick` handler and just dispatched the event to something else that does the work. gonna potentially reopen this

**Comment by erikjalevik** [comment]
I'm not sure I fully understand your use case, but I just ran into the same issue, where hovering over items was causing re-renders, which I hadn't expected. It's because downshift updates its `highlightedIndex` also in response to mouse hover.

We don't need this, hover effects are handled via CSS, so I disabled it by not passing the `onMouseMove` from `getItemProps` to the list item. It seems to work.

**Comment by osdiab** [comment]
I think the reason it does need to happen in JS is because if you keyboard
navigate then hover effects won’t be triggered (which is part of the point
of the library, keyboard accessibility). So what I’m suggesting is
restructuring it in a way such that the actual event handler doesn’t need
to change but the state will get updated (by dispatching a generic event
that causes state to get changed)

Omar

**Comment by osdiab** [comment]
what i'm saying is that if you don't pass `onMouseMove` from `getItemProps` to the list item, then my expectation is that if you hover over a list item, sure you can make it highlight with CSS, but then if you press the down key, it won't continue from that element (since `highlightedIndex` won't be updated). Not the worst behavior, but definitely not the expected behavior.

**Comment by erikjalevik** [comment]
Ah fair enough. In the app I'm working on, we consider hover and selected as different states, so I don't want the mouse hovering over an item to have any effect on the selected item whatsoever. Only on click should the selection change.

**Comment by silviuaavram** [comment]
Theoretically speaking, your users will most of the time will use either mouse or keyboard.

Indeed, also on the ARIA WCAG examples for combobox, there are 2 different highlights, which act independent from one another. This will require additional changes to downshift, which will be quite significant. Not sure that's very pressing to be honest.

You can do something in your own implementation: control `highlightedIndex` which will only be the one changed by keyboard. Use `onHighlightedIndexChange` update the `highlightedIndex` only if it's from keyboard (check stateChangeTypes), and if there is an update from mouse move, get that into your own mouseHighlightedIndex and use it to style those items differently. You have the tools to do it, I think.

I know it would be great if downshift would handle them out of the box, but at this moment I don't think the changes are worth it, considering code, tests, documentation, bundle size etc.

Let me know what you think!
