### ISSUE TITLE
[Question] input get focused after every select item click, is this the normal behaviour?

### ISSUE THREAD

**Issue by FPorfirio** [downshift-js/downshift#1383]
- `downshift` version: ^6.1.7
- `node` version: 14.16.0
- `npm` (or `yarn`) version: 6-14-11

**Relevant code or config**

```javascript
```

**What you did**: 
Implemented a multiselect downshift following the website examples.

**What happened**:
Every time I click/select an option, the input gets focused. Which is good for desktop but annoying for mobile.
If this isn't the normal behaviour i'll create a sandbox trying to reproduce the error. Otherwise i'd like to know how to prevent input focus on option click/selection

**Reproduction repository**:

**Problem description**:

**Suggested solution**:

**Comment by silviuaavram** [comment]
I think it is normal. The input stays focused all the time, and once you blur it via element selection, then the focus needs to go somewhere, and in this case it goes on the input. Why is it annoying on mobile?

You can probably achieve your prevent input with a useEffect based on selectedItem. Not something that I would consider, but you do what you need.
