### ISSUE TITLE
Item highlighted when hovering another disabled item

### ISSUE THREAD

**Issue by moroshko** [downshift-js/downshift#1385]
**Problem description**:

Below is a little example where I render 2 sections by making the section label a disabled item.
When navigating the items using the keyboard, it does behave as expected by skipping the section labels.
However, the issue is when hovering over the items using the mouse. 
As you can see in the video below, when the section label (i.e. the disabled item) is hovered, the item next to it is still highlighted.
The expected behavior is: when the section label is hovered, **none of the items should be highlighted.**

What am I doing wrong?

https://user-images.githubusercontent.com/259753/175756961-e1277e6e-9dfb-4f88-8012-36c4bf0569e4.mov

- `downshift` version: 6.1.7

**Reproduction repository**:

[CodeSandbox](https://codesandbox.io/s/downshift-usecombobox-issue-forked-g4x8k6)

**Relevant code or config**

```javascript
const defaultItems = [
  "_Fruits",
  "Apple",
  "Banana",
  "_Vegetables",
  "Cucumber",
  "Tomato"
];

const renderItem = (item) => {
  if (item[0] === "_") {
    return <div style={{ backgroundColor: "#ccc" }}>{item.slice(1)}</div>;
  }

  return item;
};

export default function App() {
  const [items, setItems] = useState(defaultItems);
  const {
    isOpen,
    getLabelProps,
    getMenuProps,
    getInputProps,
    getComboboxProps,
    highlightedIndex,
    getItemProps,
    openMenu
  } = useCombobox({
    items,
    onInputValueChange: ({ inputValue }) => {
      setItems(
        items.filter((item) =>
          item.toLowerCase().startsWith(inputValue.toLowerCase())
        )
      );
    }
  });
  const inputProps = getInputProps({
    onFocus: () => {
      if (isOpen === false) {
        openMenu();
      }
    }
  });

  return (
    <div>
      <label {...getLabelProps()}>Choose an element:</label>
      <div {...getComboboxProps()}>
        <input {...inputProps} />
      </div>
      <ul {...getMenuProps()}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              {...getItemProps({ item, index, disabled: item[0] === "_" })}
            >
              {renderItem(item)}
            </li>
          ))}
      </ul>
    </div>
  );
}
```

**Comment by silviuaavram** [comment]
It's most likely a bug, we should probably set highlightedIndex to `-1` when a disabled item is hovered by mouse.
