### ISSUE TITLE
Is downshift still supported?

### ISSUE THREAD

**Issue by alveshelio** [downshift-js/downshift#1389]
First of all, I want to make it very clear, this is not an issue complaining about the maintainers or the contributors. I just want to know if the maintainers are still interested in maintaining the library or even have time to do it. I know this comes out of their free time and as for me I really appreciate their effort. So to ALL the contributors of this and any open source project, a BIG THANK YOU for your efforts.

The reason I'm asking this is because last meaningful commit as made on Aug 5, 2021 and there are issues that are open for more than two weeks without any response, others for way longer. There's a branch v7 but last commit has on April 18th 2021. 

I don't know whether I have enough experience to contribute to this project, maybe with some guidance I could contribute but right now I don't even know where to start.  

Would any of the contributors be willing to help others who might be willing to help but don't know where to start? You are probably thinking... if you don't know where to start then you should probably not contribute to this project :)

Thank you

**Comment by silviuaavram** [comment]
Done with the PR that was blocking the CI. https://github.com/downshift-js/downshift/pull/1388

Let's get things rolling again.
