### ISSUE TITLE
How do i handle selecting / unselecting checkbox? 

### ISSUE THREAD

**Issue by yuvi-pc** [downshift-js/downshift#1390]
`downshift` version: latest
`node` version: 16.13
`npm` (or `yarn`) version: 

I am trying to build a multiselect with checkbox variant. I made it work by adding a check on the selectedItems. Is this way to go?

Is there a way to find out if item clicked was checked to handle add / remove? 

**Reproduction repository**:

https://codesandbox.io/s/nifty-shamir-x4fb43?file=/src/hooks/useMultipleSelection/select.js

**Problem description**:

**Suggested solution**:

**Comment by silviuaavram** [comment]
Does https://www.downshift-js.com/use-select#basic-multiple-selection help?

**Comment by yuvi-pc** [comment]
perfect. thank you
