### ISSUE TITLE
[Documentation help] Why isOpen is inside the wrapper element and not outside of it?

### ISSUE THREAD

**Issue by bhargavcp** [downshift-js/downshift#1391]
- `downshift` version: 6.1.7
- `node` version: 16.13.1
- `npm` (or `yarn`) version: yarn 1.22.17

```javascript


```

**Problem description**:

In the existing example in the documentation at https://www.downshift-js.com/use-select/, I noticed that the `isOpen` bool is used inside the `ul` tag while rendering the books. As a result, when isOpen is false, it renders an empty `ul` with a certain width but **height of 0**. This also has a tabIndex of -1, which essentially means it cannot be reached by keyboard and also one cannot visually click on it as the height is 0. (MDN explanation for tabIndex -1: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex).

<img width="1011" alt="Screen Shot 2022-07-22 at 3 00 18 PM" src="https://user-images.githubusercontent.com/15369964/180574670-63c99103-ef3f-4bdc-967d-d66a9bada6a6.png">

Similar thing is done in the test cast here https://github.com/downshift-js/downshift/blob/f18b031644105e4046b361c4e0109ed5494fbf1e/src/hooks/useSelect/testUtils.js#L124

I am trying to understand if there is any reason behind this in terms of accessibility or something else that I am missing.

I changed the example to the following and it actually seemed better because now we don't render the empty ul element.
```javascript

    {isOpen && <ul
          {...getMenuProps()}
          className="absolute w-72 bg-white shadow-md max-h-80 overflow-scroll"
        >
          {books.map((item, index) => (
              ......
              ......
              ......
            ))}
        </ul>
     }
```

Any pointers/explanation would be greatly appreciated. Thank you!

**Comment by silviuaavram** [comment]
It is explained in the docs why the menu should always be rendered, even if it's empty. It's related to a11y.

https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html <- here, you can also check that the menu is always in the DOM.

The fact that it has tabindex -1 does not bother anyone I think.

**Comment by silviuaavram** [comment]
Do not use the above suggested implementation. Please stick to the guidelines in the documentation. Thank you!
