### ISSUE TITLE
prop-types should be a devDependency

### ISSUE THREAD

**Issue by RobinClowers** [downshift-js/downshift#1393]
- `downshift` version: 6.0.6 (appears to affect the most recent as well)
- `node` version: 16.14.2
- `npm` (or `yarn`) version: 1.22.17

**Issue**

I noticed the `prop-types` package in my bundle, and it looks like downshift is the culprit. I believe it should be a devDepenecy, so it doesn't end up in production bundles?

**Comment by silviuaavram** [comment]
I don't think it should. It's a dependency, not a dev dependency. It's not going to affect the production code, but it's not a dev dependency. 

https://www.reddit.com/r/reactjs/comments/qml74p/why_is_proptypes_not_a_dev_dependency/

**Comment by RobinClowers** [comment]
@silviuaavram why? It ends up in the production bundle but provides no value in production.
