### ISSUE TITLE
Can Downshift be used custom for building right click menus?

### ISSUE THREAD

**Issue by bhargavcp** [downshift-js/downshift#1394]
- downshift version: 6.1.7
- node version: 16.13.2
- npm (or yarn) version: 8.1.2

**Reproduction repository**:

I have a codesandbox where I have tried to make a simple example of what I'm trying to do. https://codesandbox.io/s/downshift-playground-forked-ehwg8w?file=/src/index.js

**Problem description**:
Hi! Following are the steps to reproduce the issue:

Steps:
1. Click anywhere on the red div to render the menu.
2. Press down arrow key, this will select the first item in the list.
3. Press the down arrow key again - nothing happens.
 
My question is:
Do you think Downshift should be used for building such a custom right click menu a.k.a context menu.

I am not exactly sure because there isn't a 'Toggle button' as such. It's only rendered when the user right clicks on the screen.  I am confused with things like where should the `getToggleButtonProps` be used? Usually, we use `getToggleButtonProps` on a toggle button like shown in the Basic usage example here: https://www.downshift-js.com/use-select. But in my codesandbox, I am just putting it on the parent div which doesn't seem right.

Could you please suggest if using Downshift for a custom right click menu is the right thing to do? My reasons for not doing so are:
1. There isn't a 'Toggle button' as such that triggers the menu. It happens only when the user right clicks.
2. I don't want the menu to open with just a normal 'left click' like it happens in my codesandbox. I want it to be triggered only with a right click.

**Thank you for your help!**

**Comment by silviuaavram** [comment]
I believe that https://www.npmjs.com/package/@szhsin/react-menu may be a better solution for your component.

Downshift can help you with Select, ComboBox or Taglist. But for menus, there are other libraries. The one above is something we use at my company and we are happy with it.

Good luck!
