### ISSUE TITLE
How do I reset selectedItems ? 

### ISSUE THREAD

**Issue by yuvigrg** [downshift-js/downshift#1399]
- `downshift` version:  6.1.7
- `node` version: 16.3
- `npm` (or `yarn`) version: 1.22.19

**Reproduction repository**:
https://codesandbox.io/s/young-snow-fvj8qk?file=/src/hooks/useSelect/controlling-state.js

**Problem description**:
I have a controlled MultiSelect component which i am using with Formik. When the form is reset or submitted, I would like to reset the component and ensure only the default value is selected. However, I am not able to achieve it. 

From what i can see, when resetting, Formik passes the default value correctly on reset but the selectedItems is not cleared. 

**What you did**:
I tried adding another intermediate state and using the useEffect but it did not work. Also that does not feel correct as now I am storing the the selectedItems state in two places.

**What happened**:

**Suggested solution**:

**Comment by silviuaavram** [comment]
Does `reset` returned by `useMultipleSelection` work?

**Comment by yuvigrg** [comment]
Whilst `reset` removes the selectedItems, I will need a trigger for reset. The problem that I think I am trying solving is when `initialSelectedItems` change, I want to set the `SelectedItems` which right now can only be set with the `onSelectedItemChange` In hindsight, I also feel that that it is not a problem with the library.

**Comment by silviuaavram** [comment]
maybe you need to use `defaultSelectedItems` in this case. when you reset, the state values switch to the defaults, and in order to control the defaults, we have `defaultSelectedItems`. `initialSelectedItems` only give value on the first render.

**Comment by yuvigrg** [comment]
yah, i tried that. i have updated the repository to reflect it.

**Comment by yuvigrg** [comment]
I have managed to solve it by controlling the selectedItems and passing it as props rather than using the selectedItems returned by the mutliSelection hook. 
https://codesandbox.io/s/dreamy-feather-0ndwc8?file=/src/hooks/useSelect/controlling-state.js
