### ISSUE TITLE
How to prevent opening menu when hitting space?

### ISSUE THREAD

**Issue by npearson72** [downshift-js/downshift#1401]
- `downshift` version: 6.1.9
- `node` version: 16.15.1
- `npm` (or `yarn`) version: Yarn 1.22.19

**Relevant code or config**

Please see: https://www.downshift-js.com/use-multiple-selection#usage-with-combobox

**What you did**:
As I was playing with this code, I noticed that entering an empty string (i.e. Space) in the input field triggers the menu to open. Is there a way to prevent that?

I've tried modifying the `getFilteredBooks` function to return an empty array if the last character in the `inputValue` is a space:

```js
function getFilteredBooks(selectedItems, inputValue) {
    const lowerCasedInputValue = inputValue.toLowerCase()

    // Return an empty array if the last segment of the inputValue is an empty string
    const lastSegment = inputValue.toLowerCase().split(' ').at(-1);
    if ( lastSegment.length <= 0) return [];

    return books.filter(function filterBook(book) {
      return (
        !selectedItems.includes(book) &&
        book.title.toLowerCase().includes(lowerCasedInputValue) &&
        book.author.toLowerCase().includes(lowerCasedInputValue)
      )
    })
  }
```

While this does prevent the menu from opening when pressing the `Space` key, it also seems to disable/break the toggle button.

Is there some other (perhaps more elegant) way of dealing with this?

**Comment by silviuaavram** [comment]
Adding this to the start of the `getFilteredBooks` may be enough?

```js
  if (inputValue.length && !inputValue.trim().length) {
    return []
  }
```

**Comment by silviuaavram** [comment]
Will reopen this if there is further action required. Let us know!

**Comment by npearson72** [comment]
Perfect. Thank you.
