### ISSUE TITLE
Is it possible to blur the input on selecting an item with `useCombobox()`

### ISSUE THREAD

**Issue by ryanzec** [downshift-js/downshift#1404]
- `downshift` version: 6.1.9
- `node` version: 16.15.0
- `yarn` version: 3.2.1

**Problem description**:
I have tried a number of different things in an attempt to have the input blur upon selecting a value from the list of items however each time I select an item, the input still remains focused. I am using `useCombobox()` instead on `useSelect()` as I want the ability to do auto complete typing which I believe `useSelect()` does not support.

Am I missing something obvious to do this?

**Comment by silviuaavram** [comment]
Is there a particular reason why you want this to happen?

I am guessing that using `onSelectedItemChange` and executing a blur action there should work.
