### ISSUE TITLE
[useSelect] List scrolls to top on mouse leave

### ISSUE THREAD

**Issue by cgarrovillo** [downshift-js/downshift#1417]
- `downshift` version: `6.1.7`
- `node` version: `14.20.0`
- `npm` (or `yarn`) version: `6.14.17`

**Relevant code or config**

Basically any piece of code that uses `useSelect`

```javascript
function SelectExample() {
  const books = [
    {author: 'Harper Lee', title: 'To Kill a Mockingbird'},
    {author: 'Lev Tolstoy', title: 'War and Peace'},
    {author: 'Fyodor Dostoyevsy', title: 'The Idiot'},
    {author: 'Oscar Wilde', title: 'A Picture of Dorian Gray'},
    {author: 'George Orwell', title: '1984'},
    {author: 'Jane Austen', title: 'Pride and Prejudice'},
    {author: 'Marcus Aurelius', title: 'Meditations'},
    {author: 'Fyodor Dostoevsky', title: 'The Brothers Karamazov'},
    {author: 'Lev Tolstoy', title: 'Anna Karenina'},
    {author: 'Fyodor Dostoevsky', title: 'Crime and Punishment'},
  ]
  function itemToString(item) {
    return item ? item.title : ''
  }

  function Select() {
    const {
      isOpen,
      selectedItem,
      getToggleButtonProps,
      getLabelProps,
      getMenuProps,
      highlightedIndex,
      getItemProps,
    } = useSelect({
      items: books,
      itemToString,
    })

    return (
      <div>
        <div className="w-72 flex flex-col gap-1">
          <label {...getLabelProps()}>Choose your favorite book:</label>
          <button
            aria-label="toggle menu"
            className="p-2 bg-white flex justify-between"
            type="button"
            {...getToggleButtonProps()}
          >
            <span>{selectedItem ? selectedItem.title : 'Elements'}</span>
            <span className="px-2">{isOpen ? <>&#8593;</> : <>&#8595;</>}</span>
          </button>
        </div>
        <ul
          {...getMenuProps()}
          className="absolute w-72 bg-white shadow-md max-h-80 overflow-scroll"
        >
          {isOpen &&
            books.map((item, index) => (
              <li
                className={cx(
                  highlightedIndex === index && 'bg-blue-300',
                  selectedItem === item && 'font-bold',
                  'py-2 px-3 shadow-sm flex flex-col',
                )}
                key={`${item.value}${index}`}
                {...getItemProps({item, index})}
              >
                <span>{item.title}</span>
                <span className="text-sm text-gray-700">{item.author}</span>
              </li>
            ))}
        </ul>
      </div>
    )
  }

  return <Select />
}
```

**What you did**:

Opened the dropdown that sits at the very bottom of the page, causing the list to be outside the regular viewport.

**What happened**:

on mouse leave of the list, the list automatically scrolls to the top

https://user-images.githubusercontent.com/6688713/192873115-26680b99-34c1-4c71-b35b-10f74e43954c.mov

**Reproduction repository**:

**Problem description**:

Opening a dropdown that sits at the bottom of the page, whose list is large enough that it exceeds the viewports, unintentionally and automatically scrolls to the top when the list is no longer hovered (mouse leave).

**Suggested solution**:

**Comment by ShimantaBhuyan** [comment]
If you check the `onHighlightedIndexChange` function prop of the `useSelect` hook, we are asking the `rowVirtualizer` to scroll to the index every time an item gets highlighted. But when the mouse moves outside the list, the `highlightedIndex` resets to -1 and the list scrolls back to the top. 
We can disable this behaviour by explicitly checking for the `type` and/or 'highlightedIndex' of the `changes` value of the function, and then call the function to scroll to the highlighted index, only if the index is not -1, or even better, check for the type and scroll only if it is not of the type `__menu_mouse_leave__`.

You can check it out here in this codesandbox: https://codesandbox.io/s/damp-resonance-lubslb?file=/src/hooks/useSelect/react-virtual.js:616-640
Try putting a console.log and check the values to better understand it.

I've raised a PR to fix this, you can check it here: https://github.com/downshift-js/downshift-examples/pull/37

**Comment by ShimantaBhuyan** [comment]
@silviuaavram @kentcdodds Can you please assign the issue to me?
I have already created a PR : https://github.com/downshift-js/downshift-examples/pull/37
