### ISSUE TITLE
[useSelect] How to openMenu without focus?

### ISSUE THREAD

**Issue by punkpeye** [downshift-js/downshift#1418]
I am building a pretty advance version of `useMultipleSelection` and I am using `useSelect`.

I wish to open select (which I can do with `openMenu` action) without causing immediate focus on the menu, i.e. I want to control when to focus.

Is this doable?

**Comment by YaseenAlGailani** [comment]
My guess is no, at the moment it looks like it's handled internally by an effect depending on `isOpen` state and a couple of things. Here's what I found in useSelect/index.js

```
/* Controls the focus on the menu or the toggle button. */
  useEffect(() => {
    // Don't focus menu on first render.
    if (isInitialMountRef.current) {
      // Unless it was initialised as open.
      if ((initialIsOpen || defaultIsOpen || isOpen) && menuRef.current) {
        menuRef.current.focus()
      }
      return
    }
    // Focus menu on open.
    if (isOpen) {
      // istanbul ignore else
      if (menuRef.current) {
        menuRef.current.focus()
      }
      return
    }
    // Focus toggleButton on close, but not if it was closed with (Shift+)Tab.
    if (environment.document.activeElement === menuRef.current) {
      // istanbul ignore else
      if (toggleButtonRef.current) {
        shouldBlurRef.current = false
        toggleButtonRef.current.focus()
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen])
```

There's an update landing soon in #1402 where focus stays on the toggle button all the time.

**Comment by silviuaavram** [comment]
Try v7, as we keep focus on the select all the time, as per ARIA 1.2 recommendation. Let me know if it works.

**Comment by sgrund14** [comment]
should this be possible in v7.6.0? have a similar use case where I am doing a data fetch, then calling `openMenu` to show the results in the dropdown. it's part of a form with other inputs, and currently it takes away focus when the menu opens to put it on the downshift input. would be great to prevent this from happening... 

thanks!

cc @silviuaavram @punkpeye

**Comment by silviuaavram** [comment]
So what are you actually using, @sgrund14? useSelect, useCombobox, Downshift?

**Comment by sgrund14** [comment]
> So what are you actually using, @sgrund14? useSelect, useCombobox, Downshift?

useCombobox!

**Comment by sgrund14** [comment]
like so @silviuaavram 
```
const {
        openMenu,
    } = useCombobox({
       ...
    })
```

i was sort of half expecting there to be something I could tap into in the state reducer like so

```
case useCombobox.stateChangeTypes.FunctionOpenMenu:
      return {
          ...changes,
          inputFocused: false
      };
```

**Comment by sgrund14** [comment]
ah, it's just that it interrupts filing out the rest of the form which leads to a stunted UX, like you are typing in one input field and then all of a sudden you are typing in the combobox field. why do you have to be able to navigate/query the options as soon as they are rendered?

**Comment by silviuaavram** [comment]
Then why do you need to open the combobox menu while the user types into another input field? :D

**Comment by silviuaavram** [comment]
> like so @silviuaavram
> 
> ```
> const {
>         openMenu,
>     } = useCombobox({
>        ...
>     })
> ```
> 
> i was sort of half expecting there to be something I could tap into in the state reducer like so
> 
> ```
> case useCombobox.stateChangeTypes.FunctionOpenMenu:
>       return {
>           ...changes,
>           inputFocused: false
>       };
> ```

stateReducer only concerns itself with state stuff, no side effects (focus).

**Comment by sgrund14** [comment]
> Then why do you need to open the combobox menu while the user types into another input field? :D

Because while the user types, I am fetching the options for the drop-down. For context, it's generating tags for an image in the background, and once the tags are loaded I display the options (which looks nice in the form, and calls the users attention to the presence of the tags). Because it's more of a background process I want to let them keep typing in the other field they were already in.

**Comment by silviuaavram** [comment]
Then why not keep the tags menu closed until the user focuses themselves and start using it? To me it would be very confusing to type in a field and have a menu from another field just pop up out of nowhere.

**Comment by sgrund14** [comment]
> Then why not keep the tags menu closed until the user focuses themselves and start using it? To me it would be very confusing to type in a field and have a menu from another field just pop up out of nowhere.

It doesn't quite pop out of nowhere, we have a little "generating tags" loading animation. It's actually been getting people to use it more 🙏 I ended up getting it working by setting 'defaultIsOpen' to true, so that the isOpen state doesn't change when the tags load.
