### ISSUE TITLE
resetIdCounter for Next.js

### ISSUE THREAD

**Issue by lyqht** [downshift-js/downshift#1419]
- `downshift` version: 6.1.12
- `node` version: 16lts
- `npm` (or `yarn`) version: 8.15.0

**Relevant code or config**

```
next-dev.js?d49d:25 Warning: Prop `id` did not match. Server: "downshift-0-input" Client: "downshift-1-input"
```

**Problem description**:

I have a Next.js project where I'm encountering a checksum error. From the docs, I understand there's a `resetIdCounter` function that I can use, but I'm not too sure where to put it for a Next.js project.

**Comment by Zn4rK** [comment]
If you're on react 18 you could use the new `useId()`-hook instead.

```
const id = useId();
const selectStuff = useSelect({ items, id });
```
