### ISSUE TITLE
Screen reader reads inputValue before custom a11yStatusMessage is finished

### ISSUE THREAD

**Issue by LouiseReid** [downshift-js/downshift#1420]
- `downshift` version: 6.1.12
- `node` version:16.17.0
- `npm` (or `yarn`) version:8.15.0

**Relevant code or config**

```javascript
      getA11yStatusMessage({ resultCount }) {
        if (fetchingState === 'resolved') {
          return resultCount > 0
            ? `${resultCount} results are available, use up and down arrow keys to navigate. Press enter key to select.`
            : 'no results are available.';
        }

        return '';
      },
```

**What you did**: created custom a11y status message

**Reproduction repository**:

**Problem description**: I require the a11y message to be able to be translated so I am writing my own custom getA11yStatusMessage. However when using this the screen reader only gets about 2 words in before it reads out the input value. How can I prevent this from happening? I'm assuming its due to the state change?

**Suggested solution**:

**Comment by silviuaavram** [comment]
Can you give us a repro sandbox? It may be due to a focus switch, but it's impossible to tell without the repro env.

**Comment by LouiseReid** [comment]
> Can you give us a repro sandbox? It may be due to a focus switch, but it's impossible to tell without the repro env.

It happens with the example code in the docs
