### ISSUE TITLE
MultiSelect menu closes if any focusable element is used inside list item.

### ISSUE THREAD

**Issue by Dito-Orkodashvili** [downshift-js/downshift#1423]
- `downshift` version: 6.1.12
- `node` version: 14.18.3
- `yarn` version: 1.22.19

**Relevant code or config**

```javascript
<ul {...getMenuProps()}>
        {isOpen &&
          options.map((item, index) => (
            <li key={index} {...getItemProps({ item, index })}>
              <label>
                {/* This label causing menu to close when clicked on it */}
                <input type="checkbox" />
                {item.label}
              </label>
            </li>
          ))}
/ul>
```

**What you did**:
I use `useSelect` hook to build multi select component. 

**What happened**:
The issue is when I use checkbox element with label inside of the list item like shown above. When you click on the checkbox itself all is working fine (menu stays open) but if you click on the label, it triggers the MenuBlur event and closes the menu. Which is not correct.

Here is the reproduction on a Codesandbox:

[https://codesandbox.io/s/crimson-microservice-b5io0j?file=/src/App.js:2956-3363](https://codesandbox.io/s/crimson-microservice-b5io0j?file=/src/App.js:2956-3363)

**Comment by aaronmcadam** [comment]
I've just hit this issue, you can get around it by adding a click handler to the label to prevent the default action:
```tsx
<label onClick={(e) => e.preventDefault()} htmlFor={item.id}>
  {item.label}
</label>
```

**Comment by aaronmcadam** [comment]
Another workaround is to use `aria-label` on the input:

```tsx
                  <input
                    aria-label={item.label}
                    type="checkbox"
                    value={item.id}
                    /* This is required to avoid React warning about not passing an onChange handler: */
                    /* You provided a `checked` prop to a form field without an `onChange` handler. */
                    /* We want to set the state in the Downshift callback instead of a handler, so this works for now. */
                    onChange={() => null}
                    checked={selectedItems.byId[item.id] === 'CHECKED'}
                  />
                  {/* We can't use a label element because that will close the dropdown when selecting the option */}
                  {/* @see https://github.com/downshift-js/downshift/issues/1423 */}
                  <span>{item.label}</span>
```

**Comment by Dito-Orkodashvili** [comment]
@aaronmcadam Thanks for the replies. The thing is that I also use third party Checkbox component, so I don't control the structure of it. I could still prevent default of the label but in that case clicking on a label will not check the checkbox any more.

**Comment by aaronmcadam** [comment]
ah that makes sense! In my case, I control all markup, and I only want a label for testing so I can do `getByLabelText` to test my checkboxes are checked.

**Comment by silviuaavram** [comment]
@Dito-Orkodashvili you don't need label wrappers in your checkbox. You are not using a standard checkbox group here. The checkbox is used here for styling. To make sure the user knows your item is selected, make sure you are setting `aria-selected` as `true` on the item. Which brings me to the realisation that the example needs to be changed, will do that now!

```jsx
{...getItemProps({item, index, 'aria-selected': selectedItems.includes(item})}
```

**Comment by silviuaavram** [comment]
Can

**Comment by Dito-Orkodashvili** [comment]
> @Dito-Orkodashvili you don't need label wrappers in your checkbox. You are not using a standard checkbox group here. The checkbox is used here for styling. Consequently, I'd remove it. To make sure the user knows your item is selected, make sure you are setting `aria-selected` as `true` on the item. Which brings me to the realisation that the example needs to be changed, will do that now!
> 
> ```js
> {...getItemProps({item, index, 'aria-selected': selectedItems.includes(item)})}
> ```
> 
> Let me know if your problem gets solved as suggested above, and I will reopen this. Thanks!

@silviuaavram Thanks for the answer.
It's not about just labels. Any focusable element is doing the same. So basically you can not have any focusable element inside the menu. I think it should be fixed. If focus is inside the Menu it should not trigger the MenuBlur event.

**Comment by silviuaavram** [comment]
No, it should not, actually. We are providing logic to build comboboxes and selects. These are not menus or lists. They do not contain focusable and actionable elements inside the list. A select/combobox element is only used to search and select one/multiple elements from a list of options, nothing else.

You are fully welcome to use our solution if you consider it helpful to build a menu/list, but just keep in mind it's not used for that.
