### ISSUE TITLE
Examples do not hide menu

### ISSUE THREAD

**Issue by IanVS** [downshift-js/downshift#1425]
https://www.downshift-js.com/use-select

I'm trying to find a good way to hide menus when they're not open.  My current `.visually-hidden` class is resulting in extra scrollbars, so I looked at the examples to see how they're done, but found a problem.  In most of the examples, the menu isn't hidden when it is closed, resulting in a visible UI element, sometimes covering up what comes below:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/4616705/194563646-2ab3f549-aaa6-4236-bf87-dc45375a94ef.png">

**Comment by silviuaavram** [comment]
<img width="348" alt="Screenshot 2022-10-22 at 12 25 30" src="https://user-images.githubusercontent.com/11275392/197331927-58eccf88-fe36-4958-b8ef-c63d0fedf7c2.png">

This is an open menu with no items in it, on Chrome. Can you be more specific on the use case as I don't see the issue in your screenshot.

**Comment by IanVS** [comment]
I see this on both firefox and brave.  I think it might actually be a horizontal scrollbar, now that I look at it open.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/4616705/198636351-fc289cad-95b5-48e7-9de8-0f19d5a6c8c7.png">
