### ISSUE TITLE
Is downshift fully tree shake able?

### ISSUE THREAD

**Issue by thomasmattheussen** [downshift-js/downshift#1427]
- `downshift` version: 6.1.12
- `node` version: 16.14.2
- `npm` (or `yarn`) version: 8.5.0

**What you did**:
I'm creating a component library with an autocomplete component that uses downshift. Everything works great, except for thet fact that downshift doesn't seem 100% tree shake able.

**Problem description**:
My component library exports an autocomplete component with downshift. When consumers of my component library don't use this component, they get pieces of downshift included in their bundles. Which shouldn't happen after tree shaking.
Am I missing something?

**Comment by silviuaavram** [comment]
The library should be tree shake-able. What are you using from downshift?

**Comment by thomasmattheussen** [comment]
I'm importing Downshift like this: `import Downshift from 'downshift';` and then use it in JSX `<Downshift {...props}>...</Downshift>` in my component library's AutoComplete component. The thing is: **when my users don't import my AutoComplete component, there still seem to be traces of Downshift in their final bundles**. 
A rollup analysis with the visualizer plugin shows for example `compute-scroll-into-view/dist/index.module.js`, `tslib/modules/index.js` and `prop-types/index.js` as being imported by `downshift/dist/downshift.esm.js`

**Comment by silviuaavram** [comment]
Those are downshift's dependencies. Not sure why you get those in the bundle, even though Downshift is not there as you would expect.

I cannot look into this right now, but if you'd like to help, I'd be happy to review your work!
