### ISSUE TITLE
[useSelect] Does not open on space/enter in v7

### ISSUE THREAD

**Issue by mskelton** [downshift-js/downshift#1428]
- `downshift` version: 7.0.0
- `node` version: v16.18.0
- `npm` (or `yarn`) version: 3.2.1 

**Relevant code or config**

https://www.downshift-js.com/use-select#basic-usage

**What you did**:

Focus the basic select menu and press space

**What happened**:

The menu did not open and the page scrolled down.

**Problem description**:

It seems like with the release of v7, the select no longer will open when pressing space/enter like it's supposed to based on the [ARIA spec](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html).  Other shortcuts like arrow down to work properly and will open the select select menu.

**Comment by silviuaavram** [comment]
On it. Thanks for reporting!
