### ISSUE TITLE
Open menu when input is focused using multiselect

### ISSUE THREAD

**Issue by haleybarlar** [downshift-js/downshift#1433]
- `downshift` version: 6.1.9
- `node` version: 16.17.0
- `yarn` version: 1.22.19

**Relevant code or config**

```javascript
          <div {...getComboboxProps()}>
            <input
              {...getInputProps(getDropdownProps({ preventKeyAction: isOpen, onFocus: openMenu }))}
              placeholder={placeholder}
            />
          </div>
```

**Problem description**: I'm trying to get the menu to open when the input is focused without using a toggle button. Passing `onFocus: openMenu` to `getDropdownProps` works, but it then prevents me from selecting an item 🤨

Is there a good way to do this?

**Comment by haleybarlar** [comment]
I found a hack by including a toggle button that's the height/width of the input and putting an opacity of 0 on it. Probably not the best way to do it, but it works!

**Comment by silviuaavram** [comment]
Hi! Update to 7.0.1 and you get the behaviour for free. Let me know if it works out as you'd expect. Thanks!

**Comment by haleybarlar** [comment]
@silviuaavram That's exactly what I was looking for. Thank you!!
