### ISSUE TITLE
Unable to see the selected result of input 

### ISSUE THREAD

**Issue by MuhammadAakash** [downshift-js/downshift#1435]
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```
**Browser Details and Operating System**:
- Chrome Version 107.0.5304.110 (Ubuntu)
- Ubuntu 22.04

**What you did**:
I just opened the website of downshift and on this page https://www.downshift-js.com/use-combobox/, I got an issue that is shown in the screenshot below.
**What happened**:
in the result section, the "Select a Book" text is hidden under the Input or maybe under a UI tag.

![image](https://user-images.githubusercontent.com/64223049/200126196-198d5584-1923-49d8-9bff-e1387c905c77.png).
**Reproduction repository**:

**Problem description**:
The result section of this page has some CSS issues on this tag where we are showing "Select a Book" or when any book is selected from the input then this text is under the input tag "You have selected To this book"
**Suggested solution**:
The text should be visible in every case whether any option is selected from the input field or if there is no selection.

**Steps to Reproduce**:
- Go to [useCombobox](https://www.downshift-js.com/use-combobox/) this page.
- And go to the end of this section https://www.downshift-js.com/use-combobox#controlling-state.
- On the end, you found a Result container having the input + dropdown.
- You found the issue there that "Select a book" text is hidden under input.
- [Detailed screenshots](https://www.awesomescreenshot.com/image/34232604?key=9befd7a423631d9d42e6c608c8b094fa)

And at last, I Would love to work on this issue.

**Comment by silviuaavram** [comment]
Not sure what example are you referring to. Can you provide more details? Browser? Example mentioned? Any other repro steps?

**Comment by MuhammadAakash** [comment]
@silviuaavram Please check again I have updated the Issues Description. Please check

**Comment by silviuaavram** [comment]
Oh, the menu is added on top on of the text that shows selection.

I don't think it's a big issue. Adding it on top of the combobox is a bit weird. I would rather leave it like this and consider something like a helper text. Like [this example](https://mui.com/material-ui/react-select/#labels-and-helper-text)
