### ISSUE TITLE
Using combobox with checkboxes (bypass filter of selected items)

### ISSUE THREAD

**Issue by Jbmanllr** [downshift-js/downshift#1437]
Is there any way to have the selected items from the combobox to not be filtered out? I tried bypassing the filter from the examples, but it disables the search functionality...

Or this is not controlable, and i should go with the useSelect example (the only one with checkboxes), and add my own search component for  the UI?

Thanks !

**Comment by silviuaavram** [comment]
Which example are we referring to?

**Comment by Jbmanllr** [comment]
> To which example are we referring to?

MultipleComboBox

But thats good, i bypassed the filtering like this

const filterSelected = false

const items = filterSelected 
      ? React.useMemo(() => getFilteredBooks(selectedItems, inputValue),
        [selectedItems, inputValue],
      ) 
      : React.useMemo(() => getFilteredBooks(null, inputValue),
        [inputValue],
      )
      const {

**Comment by silviuaavram** [comment]
I still don't know which one. https://www.downshift-js.com/use-combobox#basic-multiple-selection this?

Also it's not clear to me what exactly is the issue you are facing.

**Comment by Jbmanllr** [comment]
> I still don't know which one. https://www.downshift-js.com/use-combobox#basic-multiple-selection this?
> 
> Also it's not clear to me what exactly is the issue you are facing.

The one named: function MultipleComboBoxExample ..

Problem resolved thanks.

**Comment by silviuaavram** [comment]
Well, the filtering is done in the function
```js
  function getFilteredBooks(selectedItems, inputValue) {
    const lowerCasedInputValue = inputValue.toLowerCase()

    return books.filter(function filterBook(book) {
      return (
        !selectedItems.includes(book) &&
        (book.title.toLowerCase().includes(lowerCasedInputValue) ||
          book.author.toLowerCase().includes(lowerCasedInputValue))
      )
    })
  }
```
So just remove the `!selectedItems.includes(book)` and it should continue to show them in the menu.

**Comment by Jbmanllr** [comment]
> Well, the filtering is done in the function
> 
> ```js
>   function getFilteredBooks(selectedItems, inputValue) {
>     const lowerCasedInputValue = inputValue.toLowerCase()
> 
>     return books.filter(function filterBook(book) {
>       return (
>         !selectedItems.includes(book) &&
>         (book.title.toLowerCase().includes(lowerCasedInputValue) ||
>           book.author.toLowerCase().includes(lowerCasedInputValue))
>       )
>     })
>   }
> ```
> 
> So just remove the `!selectedItems.includes(book)` and it should continue to show them in the menu.

Yes, thanks, thats even better ! I changed that  :)
