### ISSUE TITLE
Error with 'compute-scroll-into-view' dependency

### ISSUE THREAD

**Issue by rodrijl** [downshift-js/downshift#1449]
Hello, I'm having an error with downshift because a dependecy has been updated and it's breaking when I try to install downshift.
Looks like scroll-into-view dependency has been updated https://github.com/scroll-into-view/compute-scroll-into-view/releases/tag/v1.0.20 and now the imports are diferents.

This is the error: 
"export 'default' (imported as 'computeScrollIntoView') was not found in 'compute-scroll-into-view'

I'm using last version of downshift and have tried older versions too with the same result. 

Thanks in advance

**Comment by MaryThumma** [comment]
even after removing node_modules we're having same issue. 

Attempted import error: 'compute-scroll-into-view' does not contain a default export (imported as 'computeScrollIntoView')

**Comment by AmlanRoutray** [comment]
Hello, we are facing the same issue our project we are getting the following error:

`Attempted import error: 'compute-scroll-into-view' does not contain a default export`

Tried deleting the node_modules and do a npm install but the issue persists. There are multiple packages in the project which has downshift as peer dependencies and we are stuck with this error.

Thanks  in advance.

**Comment by silviuaavram** [comment]
I'll try to update the dependency. Not sure what happened, they did change the API in 2.0 https://github.com/scroll-into-view/compute-scroll-into-view/compare/v1.0.20...v2.0.0 but not sure why it fails on our end, since we request ^1.17.0.

**Comment by silviuaavram** [comment]
Can you try using version 7.1.3-alpha.0 and let me know if it's fixed? Thanks!

**Comment by silviuaavram** [comment]
@MaryThumma @AmlanRoutray ^^

**Comment by MaryThumma** [comment]
@silviuaavram  - 7.1.3-alpha.0  also giving same error. 
Attempted import error: 'compute-scroll-into-view' does not contain a default export (imported as 'computeScrollIntoView')

which version of compute-scroll-into-view have the fix ?

**Comment by silviuaavram** [comment]
Oups, I think I forgot something. Can you try `7.1.3-alpha.1` please?

These are the changes https://github.com/downshift-js/downshift/pull/1464.
