### ISSUE TITLE
Reordering items by drag&drop

### ISSUE THREAD

**Issue by rodbs** [downshift-js/downshift#1461]
Is it possible to reorder items in the multiselect using drag and drop as in `react-select`? I haven't seen this feature anywhere.

Is there any easy workaround to implement it? or would it need to be fully implemented in the code (using a library like  `floating-ui`?

**Comment by silviuaavram** [comment]
Reordering them via DnD is totally up to you. Just make sure to update the order of the selectedItems via the prop passed to useMultipleSelection.

**Comment by rodbs** [comment]
Ok, I'm using `@dnd-kit` and it seems to work; I'm having some issues with the events, though ...

**Comment by silviuaavram** [comment]
make sure to call the getter props like this:

getSelectedItemProps({onKeyDown: theOtherPossibleKeyDown, ...})

Will close this one. If there is a possible issue in downshift let us know. Thanks!
