### ISSUE TITLE
Resetting control on touchend outside Downshift is not always helpful

### ISSUE THREAD

**Issue by JohnThomson** [downshift-js/downshift#1465]
- `downshift` version: 3.2.10
- `node` version: 16.13.1
- `npm` (or `yarn`) version: 1.22.17

**What you did**:
 Used Downshift to create a language chooser. (You can see it at bloomlibrary.org, source at https://github.com/BloomBooks/BloomLibrary2) The 'menu' is a list of languages that match a filter. It is always displayed. It worked very nicely on non-touch devices (thanks!). Then we tested it on Android and IOS...

**What happened**:
If the user touches anything outside the Downshift component on a touch device, the Downshift component resets. The filter contents are lost and the full, unfiltered language list re-appears.
On IOS, these DOM changes are apparently interpreted as coming before the mousemove event that Safari generates at the end of a tap. Safari decides that the user must be given a chance to see the modified DOM and cancels the mouse up and click events. As a result, all our buttons were taking two taps to operate them!

You can see the behavior at https://codesandbox.io/s/simple-downshift-example-forked-jfd9w7, which I adapted from one of your examples. Type some letters into the box, then click the big red blob underneath it...the downshift component resets! (To my surprise, it's happening even on Windows/Chrome; I expected it would only happen on touch devices.)

**Problem description**:
I don't think Downshift should completely reset like this whenever someone taps somewhere else.

**Suggested solution**:
We worked around it by passing an argument to downshift:

```
environment={{
                        addEventListener: () => {},
                        removeEventListener: () => {},
                        document,
                    }}
```

But we might be sorry if a later version of Downshift uses some event listeners that we want!

A partial solution would be to suppress the reset behavior, which I think is mainly intended to close the menu, when defaultIsOpen is true. But it would be better still if you could just close the menu (assuming defaultIsOpen is false), without clearing the input box...preferably without even requiring it to be re-rendered. That might involve an API change, I'm not sure.

Sorry not to be more helpful...but this cost us roughly two days of debugging effort before I figured out why our buttons weren't working, so even if it's not something you want to fix, maybe the report will help someone.

**Comment by silviuaavram** [comment]
You should consider https://www.downshift-js.com/use-combobox. It does not reset inputValue on blur. Downshift always did that, there was no change in its behaviour in the past many years.

If you really really still want to use Downshift component try using [stateReducer](https://github.com/downshift-js/downshift#statereducer). Capture `blurInput` state change type and return `{...changes, inputValue: state.inputValue}`.

But still, you should switch to the new hook.

Thanks and let us know if your issue is fixed.

**Comment by JohnThomson** [comment]
Thanks for the suggestion. Things are working OK for us for now with the environment kludge. I've made a note to explore use-comboBox if we need to work on this area of the code again.
