### ISSUE TITLE
issue on iPhone (Safari + VoiceOver): calling `onClick` from `getItemProps` returns incorrect item from dropdown

### ISSUE THREAD

**Issue by vitbon** [downshift-js/downshift#1470]
- `downshift` version: 6.1.7
- `node` version: 12.16.3
- `npm` (or `yarn`) version: 6.14.4

**What you did**:
```
     const getItemPropsCurrent = getItemProps({
          index,
          item,
          ...(isMobileDevice && {
              onClick: () => null,
          }),
      });
      const {onClick} = getItemPropsCurrent;

      return (
          <li
              key={`${matched[index].value}${index}`}
              className={cnb(css.item)}
              {...getItemPropsCurrent}
              onTouchStart={
                  isMobileDevice
                      ? onClick.bind()
                      : () => null
              }
          >
```

**What happened**:
on my iPhone with turning on VoiceOver, I clicked on the `5 row` item from the dropdown menu. But in the input field received the incorrect `4 row` item. The mobile works correctly without VoiceOver.

**Problem description**:
1. Issue just appears when I turn on the VoiceOver screen reader.
2. Also I can't choose an item from the dropdown on iPhone with the VoiceOver with a click or double click event.

**Suggested solution**:
Could I have the possibility to check an `isVoiceOverRunning` function or something like this?

**Comment by silviuaavram** [comment]
Can you provide a full sandbox? I don't know what hook you are using and cannot test this otherwise, since your code is custom. You can make `isMobileDevice` in your example. Thanks!
