### ISSUE TITLE
stateReducer API documentation out of sync?

### ISSUE THREAD

**Issue by saveman71** [downshift-js/downshift#1481]
- `downshift` version: 7.3.2
- `node` version: 19

Hello,

I feel like the docs and examples for `stateReducer` might be out of sync with the actual API?

```js
// This works
useCombobox({
  stateReducer: (_state, {type, changes}) => {
    return changes;
  },
});

// This is what I read on the README.md and website, and it doesn't work.
useCombobox({
  stateReducer: (_state, changes) => {
    return changes;
  },
});
```

Did I miss something?

**Comment by silviuaavram** [comment]
I think our documentation should be correct. Where exactly did you find those usages, maybe we missed something.

https://www.downshift-js.com/use-combobox#state-reducer
https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox#statereducer

**Comment by silviuaavram** [comment]
You are referring to the Downshift docs, not the useCombobox hook ones.

The hooks are newer, and they are the ones that should be used. We still have Downshift around but it's not updated anymore.

**Comment by saveman71** [comment]
Gotcha, hadn't realized the hooks had a similar, but different API.
