### ISSUE TITLE
Unable to create single-select and multi-select components with rendered select menus in Dialog

### ISSUE THREAD

**Issue by annpaytak** [downshift-js/downshift#1491]
Hi! Is there any possible way to create single-select and multi-select components with rendered select menus in Dialog (for ex. with @radix-ui/react-dialog Dialog component)
so that the input with the arrow button on click toggles select menu in dialog, where you can select, and after that - close. 
also without breaking the accessibility ☝️

attached code sandbox link in which made select with Dialog but it is not working correctly: 
https://codesandbox.io/p/sandbox/modest-flower-6ou9k4

- `downshift` version: 7.6.0
- `node` version: 18.14.1
- `npm` (or `yarn`) version: yarn 1.22.19

**Relevant code or config**

```javascript
```

**What you did**:
in my project, I need to create single and multi-selects with select menus opened in Dialog for tablet or mobile view.

**What happened**:
I faced a lot of issues doing that, starting with multi-select opening with dialog but single select is not triggered, ending with broken accessibility on both.

**Reproduction repository**:
https://codesandbox.io/p/sandbox/modest-flower-6ou9k4

**Problem description**:
for multi-select I used useMultipleSelection + useCombobox hooks
for single-select I used useSelect hook
Select menu in Dialog is not opening correctly on both of them and accessibility is broken

**Suggested solution**:
Select menu in Dialog is opening correctly on both of them and accessibility works

**Comment by silviuaavram** [comment]
@annpaytak somehow the sandbox does not work for me, cannot pick a version for downshift.

Have you checked if the select you are rendering is in a custom environment (iframe)? if so, take a look at https://www.downshift-js.com/use-combobox#custom-window.

Let me know if you figured it out, thanks!
