### ISSUE TITLE
Is the hook documentation out of sync? 

### ISSUE THREAD

**Issue by yuvi-pc** [downshift-js/downshift#1496]
- `downshift` version: 7.6.0
- `node` version: 16.13.0
- `npm` (or `yarn`) version:  1.22.19

**Relevant code or config**
The example here https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useSelect/basic-multiple-selection.js shows
```
   case useSelect.stateChangeTypes.MenuKeyDownEnter:
   case useSelect.stateChangeTypes.MenuKeyDownSpaceButton:
```
however, when using it with typescript, these state are not present. Hence asking if they are not upto date?

**Comment by silviuaavram** [comment]
The example is incorrect, we should fix it in the https://github.com/downshift-js/downshift-examples repo. Could you contribute with a PR?

**Comment by ThomDevine** [comment]
The examples in the README links have further degraded. There are no examples in the linked CodeSandboxes any more, just a "downshift examples" info page with three links.  The first one opens another CodeSandbox inside of the current CodeSandbox.

I'm not a current user, just trying to get a feel for the library.

**Comment by silviuaavram** [comment]
@ThomDevine on the info page with three links there is also additional text describing what you need to do to view the examples.

**Comment by SaiMaheshwarReddy** [comment]
Is this still open ?, I would like to contribute, can @silviuaavram or someone give a little more context on what is the issue and where to fix it. Thanks

**Comment by silviuaavram** [comment]
Yes, please do. It's about the example in the issue description, some state changes need to be replaced with the correct ones. The example is in a separate repo.
