### ISSUE TITLE
Is there a way to use left/right arrows for navigation in a combo box?

### ISSUE THREAD

**Issue by sgrund14** [downshift-js/downshift#1501]
I have a UI like this, where when I use the left/right arrows i want the black outline to move left/right for the selected item

<img width="180" alt="Screenshot 2023-05-11 at 12 08 11 AM" src="https://github.com/downshift-js/downshift/assets/14083701/f32e0062-029b-48b7-ae60-f5120692b77f">

Currently the keyboard navigation from `useCombobox` only works with the up/down arrows, but in this case the left/right might feel more intuitive. Is it possible to add left/right arrow handlers to update the `highlightedIndex`? Didn't see a `useCombobox.stateChangeTypes.InputKeyDownArrowLeft/Right`

**Comment by sgrund14** [comment]
ah, of course, that would take mess with the left/right arrows in the input itself ...

**Comment by SpookyJelly** [comment]
I'm trying to create something similar to yours, how did you implement it?
