### ISSUE TITLE
a11y custom message getters aren't used

### ISSUE THREAD

**Issue by jviall** [downshift-js/downshift#1507]
- `downshift` version: 7.6.0
- `node` version: 18.5.0
- `npm` (or `yarn`) version: yarn v1.22.19

**Relevant code or config**
[Code Sandbox](https://codesandbox.io/p/sandbox/dazzling-shape-4fkk3f?file=%2Fsrc%2FSelect.test.tsx%3A13%2C2)
(Open a terminal in the sandbox to run `yarn test` command, which reproduces the issue)

**What you did**:
I provided both `getA11ySelectionMessage` and `getA11yStatusMessage` props, expecting them to be called and for a status element with `role="status"` to be present in the DOM, as [the code here](https://github.com/downshift-js/downshift/blob/master/src/set-a11y-status.js#L26) seems to be responsible for.

**What happened**:
According to my tests (which are reproduced in the codesandbox), neither custom getters are ever called.

**Reproduction repository**:
https://codesandbox.io/p/sandbox/dazzling-shape-4fkk3f?file=%2Fsrc%2FSelect.test.tsx%3A13%2C2

**Problem description**:
Element with aria role="status" is not rendered when using both `useSelect` and `useCombobox` hooks
**Suggested solution**:

**Comment by silviuaavram** [comment]
I think your environment is using an iframe to render the select. Please use the `environment` prop in this case. 

https://www.downshift-js.com/use-combobox#custom-window

**Comment by jviall** [comment]
> I think your environment is using an iframe to render the select. Please use the `environment` prop in this case.
> 
> https://www.downshift-js.com/use-combobox#custom-window

I'm pretty positive it is not, also neither is the codesandbox which reproduces the behavior?

**Comment by jviall** [comment]
> > I think your environment is using an iframe to render the select. Please use the `environment` prop in this case.
> 
> > 
> 
> > https://www.downshift-js.com/use-combobox#custom-window
> 
> 
> 
> I'm pretty positive it is not, also neither is the codesandbox which reproduces the behavior?

@silviuaavram did you see the reproduction in the sandbox?

**Comment by silviuaavram** [comment]
If I use getA11yStatusMessage in the docsite example / corresponding sandbox, it works.

If your tests are rendering the dom in an iframe, then it should be passed to the hook via `environment`. I don't know what else is the cause. The docsite works fine.
