### ISSUE TITLE
tabbing to next focusable element when combobox menu is open

### ISSUE THREAD

**Issue by sgrund14** [downshift-js/downshift#1516]
- `downshift` version: 7.6.0
- 
https://github.com/downshift-js/downshift/assets/14083701/7ed03509-4d1c-4ec2-802e-86025db6db82

**Problem description**:

as seen in the screenshot, when the combobox menu is open, tabbing to the next input stop working. it unfocuses the element, closes the menu, and actually moves the focus to a modal higher up in the component tree, strangely. However, when the menu is closed, tabbing works as expected. 

wondering if anyone's run into this behavior before, or if there is a standard way of dealing with it.

**Suggested solution**:
focus should switch to the next input when the menu is open

**Comment by silviuaavram** [comment]
There is little we can do to investigate this issue without an environment to reproduce the issue. Can you create a sandbox?
