### ISSUE TITLE
Focus should not be triggered if menu is not opened (WCAG)

### ISSUE THREAD

**Issue by boris-brtan** [downshift-js/downshift#1522]
Focus should not be triggered if menu is not opened initially. 

https://github.com/downshift-js/downshift/blame/d7bf4988e10db09f3e09cde78384391826433c6a/src/hooks/useCombobox/index.js#L157

suggestion without other cases knowledge
```diff
- if (initialIsOpen || defaultIsOpen || isOpen) {
+ if (initialIsOpen && defaultIsOpen || isOpen) {
```

**Comment by silviuaavram** [comment]
Not sure I understand what this implies.

If menu is not opened initially, the input will not be focused.

And by initially, we consider a `true` value for either one of the 3 props above.

**Comment by boris-brtan** [comment]
yes, I did not try newest version but for 5.4.2
- initialIsOpen: false
- defaultIsOpen: true
will keep menu closed but input is focused which breaks WCAG consistency

**Comment by silviuaavram** [comment]
Ok, I got it. It's a valid bug. It is a corner case, but still valid.

However, the fix proposed is not the one to go with, since if you pass the initialIsOpen value as true, it will not get focused if defaultIsOpen is undefined.

Working on a fix right now, thank you for reporting the issue!
