### ISSUE TITLE
Add an useCombobox.stateChangeType.InputKeyDownBackspace event

### ISSUE THREAD

**Issue by bdharrington7** [downshift-js/downshift#1523]
- `downshift` version: 8.0.0
- `node` version: 16.16.0
- `npm` (or `yarn`) version: 8.11.0

**Relevant code or config**

```javascript
useMultipleSelection({
    initialSelectedItems,
    onStateChange: ({ type, selectedItems }) => {
      console.log('useMultipleSelection onStateChange:type', type, selectedItems)
    },
    stateReducer: (state, actionAndChanges) => {
      const { type, changes } = actionAndChanges
      console.log('useMultipleSelection stateReducer:type', type, changes, state)
      return changes
    }

useCombobox({
    inputValue,
    items,
    stateReducer(state, actionAndChanges) {
      const { changes, type } = actionAndChanges
      console.log('useCombobox stateReducer:type', type, changes)
    },
    onStateChange: ({ inputValue, type, selectedItem, ...rest }) => {
      console.log('useCombobox onStateChange:type', type, inputValue)
    },
```

**What you did**:
I'm looking for an event that fires when the backspace key is pressed, while the menu is open. I've noticed users will press backspace when the input box is empty (to delete the just added item) but this only works if the menu is _closed_. If the menu is open, no events fire. 

The only workaround I could find was to detect if the `inputValue` was empty and close the menu manually if this was the case (in the `onStateChange` hook of `useCombobox`):

```javascript
switch (type) {
        case useCombobox.stateChangeTypes.InputChange:
          setInputValue(inputValue)
          if (inputValue) {
            if (items.length) {
              setHighlightedIndex(0)
            }
          } else {
            closeMenu()
          }
```

but I feel this is a substandard user experience, as I want to present all options available if the `inputValue` is empty.

If you use these two hooks in sample repo, there are no logs fired when the `inputValue` is empty, and the menu is open.

**Suggested solution**:
Add a stateChangeType in useCombobox that fires when backspace is pressed

**Comment by silviuaavram** [comment]
We cannot add a state type if that does not change the combobox state in the hook logic.

What you can do is add the following:
```js
        <input {...getInputProps({onKeyDown(e) {
          if (e.key === 'Backspace' && isOpen && inputValue === '') {
            closeMenu()
          } 
        }})} />
```

Let me know if you need anything else. Thanks for using downshift!
