### ISSUE TITLE
[useSelect] Toggle button lost focus

### ISSUE THREAD

**Issue by IAluI** [downshift-js/downshift#1537]
- `downshift` version: 8.1.0
- `node` version: 20.5.1
- `npm` version: 9.8.0

**Relevant code or config**

See repo.

**What you did**:
I use `useSelect` hook (like `basic usage` example) and select an item with the mouse.

**What happened**:

Toggle button lost focus after click on item.

**Reproduction repository**:

https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/hooks/useSelect/basic-usage.js

**Problem description**:

When pointerDown event fired on item when toggle button lost focus.

**Suggested solution**:

Prevent default behavior of  pointerDown event on items. Like it do for [useCombobox](https://github.com/downshift-js/downshift/blob/90d6d7208c61132c01868473c6dfac3a05e92076/src/hooks/useCombobox/index.js#L330C13-L330C33).

**Comment by silviuaavram** [comment]
Should be released with 8.2.1
