### ISSUE TITLE
Getting React Downshift to work nicely with react-virtualized?

### ISSUE THREAD

**Issue by lancejpollard** [downshift-js/downshift#1565]
On the latest `downshift`, I am not able to figure out how to use `getMenuProps` properly with `react-virtualized`. Any ideas how it can work with it, or if it doesn't work with that, what virtualization technique would work with it?

Here is the question in much more detail: https://stackoverflow.com/questions/77761029/is-getmenuprops-necessary-in-react-downshift-autocomplete-library

Thank you for your help! This library has been pretty nice to use so far! Hoping to make the most of it.

**Comment by silviuaavram** [comment]
I see you figured it out. Also make sure you always render the menu element, even if it's closed, like we illustrate in all our examples.

Also, consider `useCombobox` since that's the new way to create an accessible combobox following the ARIA 1.2 pattern. Thanks!
