### ISSUE TITLE
useComboBox always grabbing focus on render

### ISSUE THREAD

**Issue by FredrikMWold** [downshift-js/downshift#1574]
- `downshift` version: 8.3.2
- `node` version: v18.19.0
- `npm` (or `yarn`) version: 10.2.3

**Relevant code or config**

```javascript
  useEffect(() => {
    if (isInitialMount) {
      return
    }

    previousResultCountRef.current = items.length
  })
  // Focus the toggle button on first render if required.
  useEffect(() => {
    const focusOnOpen = getInitialValue(props, 'isOpen')
    if (focusOnOpen && toggleButtonRef.current) {
      toggleButtonRef.current.focus()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
```

**What you did**:

**What happened**: Since useRef returns an object the if statment will always be true

**Reproduction repository**:

**Problem description**: When rendered the component always grabs focus

**Suggested solution**: `if (isInitialMount)` -> `if (isInitialMount.current)`

**Comment by PhilipSampson** [comment]
Agreed, this is a problem for me too. Certainly looks to be attributable to the 8.3.1 -> 8.3.2 update.

**Comment by Powerplex** [comment]
This is also bugged on `useSelect`, we updated our dropdown to use Downshift `8.3.2` and now it focuses the last dropdown on the page (and scrolls it into view): https://sparkui.vercel.app/?path=/docs/components-dropdown--docs


https://github.com/downshift-js/downshift/assets/2033710/78033851-54ed-4e12-bb61-b7e8a054b8db

**Comment by silviuaavram** [comment]
Will fix this one tomorrow unless someone else creates a PR first.
