### ISSUE TITLE
Disabled items are highlighted and are selectable by pressing enter after input value change

### ISSUE THREAD

**Issue by jsvossen** [downshift-js/downshift#1599]
- `downshift` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
useCombobox({
    isItemDisabled: () => true,
    defaultHighlightedIndex: 0,
    ...
})
```

**What you did**:

1. Set defaultHighlightedIndex={0} with items that are disabled.
2. Entered some text in the input field

**What happened**:
This is related to the bug I filed earlier (https://github.com/downshift-js/downshift/issues/1584)
The disabled items are now properly disabled on open, but after entering text the first one is automatically highlighted and can be selected by pressing enter.
![downshift-bug](https://github.com/downshift-js/downshift/assets/13246592/febb5b2a-7810-45a0-a7b5-821aa7efe8e9)

**Reproduction repository**:
https://codesandbox.io/p/sandbox/determined-euler-jllv45?file=%2Fsrc%2Findex.tsx%3A19%2C58

**Problem description**:

defaultHighlightedIndex should not be able to select items that are disabled.

**Suggested solution**:
Check isItemDisabled before applying highlighted styles or returning the selected item.

**Comment by nakulnagariy** [comment]
You could use something like this:

```js
useCombobox({
      stateReducer(_, actionAndChanges) {
        const { changes, type } = actionAndChanges;
        switch (type) {
          case useCombobox.stateChangeTypes.InputKeyDownEnter:
          case useCombobox.stateChangeTypes.ItemClick:
            const isItemDisabled = changes?.selectedItem?.disabled;
            if (!isItemDisabled && changes.selectedItem) {
              handleItemClick(changes.selectedItem);
              /**
               * have a custom function for handling click event
               */
              const newChanges = {
                ...changes,
                inputValue: filterValue,
              };
              return {
                ...newChanges,
                isOpen: isMultiSelect, // keep the menu open after selection.
                highlightedIndex: changes.selectedItem
                  ? options.indexOf(changes?.selectedItem)
                  : 0, // workaround to stay on the same place.
              };
            } else {
              /**
               * For disabled item, just keep the menu open and dont select it
               */
              return {
                isOpen: isMultiSelect,
                highlightedIndex: changes.selectedItem
                  ? options.indexOf(changes?.selectedItem) + 1
                  : 0, // workaround to stay on the same place.
              };
            }
```

**Comment by jsvossen** [comment]
@nakulnagariy Yes, the reducer is what we're doing right now as a workaround until downshift is able to fix the bug on their end. I'm just hoping we can clean this up at some point, especially since we don't actually need a custom reducer for anything else.

**Comment by silviuaavram** [comment]
Thanks for reporting it! Will look into it.

**Comment by silviuaavram** [comment]
We are going to fix all the possible cases on our end, however we might not be able to do anything when it comes to filtering, because of the order of events.

Open the dropdown by input change, state change, check if defaultHighlightedIndex item is disabled, if not make it highlighted, but then if you filter the items and that item is not on the same position, and instead you have an item that's not disabled, it will not get highlighted because of that previous disabled check.
