### ISSUE TITLE
Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by endaquigley** [downshift-js/downshift#1608]
**Relevant code or config:**

Issue exists in the Downshift docs.

**What you did**:

- In Chrome, visit the [useSelect](https://www.downshift-js.com/use-select) page.
- Open Chrome DevTools > Issues.

**What happened**:

<img width="675" alt="Screenshot 2024-06-05 at 14 13 16" src="https://github.com/downshift-js/downshift/assets/753515/a84a200a-8b4f-4066-bff7-ce90702b8d7c">

**Problem description**:

Incorrect use of \<label for=FORM_ELEMENT\>

The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.

To fix this issue, make sure the label's for attribute references the correct id of a form field.

**Suggested solution**:

Not sure if this is a false positive as the component still seems to work as intended.

**Comment by silviuaavram** [comment]
Hi. Which examples, exactly? The ones I checked work.
<img width="1348" alt="Screenshot 2024-06-05 at 16 56 31" src="https://github.com/downshift-js/downshift/assets/11275392/7e8df1bd-e540-4092-84ee-10de414733c0">

**Comment by endaquigley** [comment]
Hi @silviuaavram,

Yes, the components work as expected but we still get the following error in the DevTools issues panel:

<img width="2108" alt="Screenshot 2024-06-05 at 15 05 54" src="https://github.com/downshift-js/downshift/assets/753515/c9b7da96-b705-490f-b783-618cce127457">

**Comment by silviuaavram** [comment]
Well, devTools may be wrong. Specifically here, there are no issues, the ids match, the click and focus technique works, not sure what we can do about it.

**Comment by silviuaavram** [comment]
Maybe, just maybe, it complains that the target is a div, not a form element.

Now, to be honest, I don't think we need the `for` here in the label markup. If I remember we manually focus the div on label click, and we also use aria labelledby on the div in order to get the markup from the label.

If I'm correct I propose to fix it by removing the for attribute, update the unit tests, and check that the click/focus and label works as before. Let me know if you want to create a PR. Thank you!

**Comment by silviuaavram** [comment]
That’s true, we performed this change a few versions ago. Consequently I
would try the implementation without the for attribute and double check if
it’s working properly from the a11y point of view.

**Comment by endaquigley** [comment]
I updated my previous comment shortly after posing it as I forgot to mention what happens when you remove the `htmlFor` attribute from the `label` element.

---

Removing the `htmlFor` attribute from the `label` element causes another issue:

```
A <label> isn't associated with a form field.
```

**Comment by silviuaavram** [comment]
Closing since we can't do any relevant fix here, and the end result is actually what we want.
