### ISSUE TITLE
Document Types for Passing Getter-Props Down to Other Components

### ISSUE THREAD

**Issue by rjray** [downshift-js/downshift#1611]
- `downshift` version: 9.0.6

**Problem description**:

Using Downshift to create a complex component, I wanted to pass some of the getter-props I received from the call to `useCombobox` down to sub-components. However, it is not clear how to properly type these values when declaring the interface for the sub-components that receive them.

**Comment by silviuaavram** [comment]
Well, for instance, `getInputProps` returns `UseComboboxGetInputPropsReturnValue`, which is 
```ts
export interface UseComboboxGetInputPropsReturnValue
  extends GetInputPropsReturnValue {
  'aria-activedescendant': string
  'aria-controls': string
  'aria-expanded': boolean
  role: 'combobox'
  onClick: React.MouseEventHandler
}
```

I believe we have good support for Typescript, and we also export the types with the hooks. Thanks!
