### ISSUE TITLE
Cursor position jumps to the end of input when state is controlled outside the hook

### ISSUE THREAD

**Issue by pirkkahuhtala** [downshift-js/downshift#1620]
- `downshift` version: 9.0.8
- `node` version: 18
- `npm` (or `yarn`) version: 

**What you did**:

I try to control the state outside the hook.

**What happened**:

Whenever I write something to the input and then move my cursor to the beginning of the string
and type something new the cursor jumps to the end of the string. If I let the hook control the state there is no issue with it.

**Reproduction repository**:
https://codesandbox.io/p/sandbox/silent-worker-vzyycm

**Problem description**:
The cursor jumps to the end of the input

**Suggested solution**:
The behaviour would be the same wether the state is controlled internally or externally.

**Comment by silviuaavram** [comment]
We cannot fix this, unfortunately. Maybe you can find a workaround.

https://github.com/downshift-js/downshift/issues/217

**Comment by pirkkahuhtala** [comment]
Thank you! I'll try it out.
