### ISSUE TITLE
useCombobox: HighlightedIndex and Items are not in sync

### ISSUE THREAD

**Issue by christinaheidt** [downshift-js/downshift#1623]
- `downshift` version: 9.0.7
- `node` version: 20.9.0
- `yarn` version: 4.4.0

**Relevant code or config**

```javascript
  const [inputItems, setInputItems] = useState(items)
  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    getInputProps,
    highlightedIndex,
    getItemProps,
  } = useCombobox({
    items: inputItems,
    isItemDisabled: (item) => item.length > 10,
    defaultHighlightedIndex: 0,
    onInputValueChange: ({inputValue}) => {
      setInputItems(
        items.filter((item) =>
          item.toLowerCase().startsWith(inputValue.toLowerCase()),
        ),
      )
    },
  })
```

**What you did**:
- Added a defaultHighlightedIndex: 0
- Added a isItemDisabled method

**What happened**:
The highlightedIndex is always one step behind the item list. E.g. when searching for a disabled item the first time the list gets reduced to just that item but the highlighted index is still at value 0 instead of being -1. Furthermore when searching for a value that doesn't exist in the list the application will run into an exception with the second update:
![image](https://github.com/user-attachments/assets/07ed5950-b838-4e23-83b5-7ce61f6d4dca)

![combobox](https://github.com/user-attachments/assets/7c41e7cf-1e4a-440f-9a59-34c57a33e987)

**Reproduction repository**:
https://codesandbox.io/p/sandbox/musing-williams-jwq6vz?file=%2Fsrc%2Fhooks%2FuseCombobox%2Fbasic-usage.js&moduleview=-1

**Problem description**:
See what happened

**Suggested solution**:
The items and the index should update at the same time

**Comment by Bluebberies** [comment]
> * `downshift` version: 9.0.7
> * `node` version: 20.9.0
> * `yarn` version: 4.4.0
> 
> **Relevant code or config**
> 
> ```js
>   const [inputItems, setInputItems] = useState(items)
>   const {
>     isOpen,
>     getToggleButtonProps,
>     getLabelProps,
>     getMenuProps,
>     getInputProps,
>     highlightedIndex,
>     getItemProps,
>   } = useCombobox({
>     items: inputItems,
>     isItemDisabled: (item) => item.length > 10,
>     defaultHighlightedIndex: 0,
>     onInputValueChange: ({inputValue}) => {
>       setInputItems(
>         items.filter((item) =>
>           item.toLowerCase().startsWith(inputValue.toLowerCase()),
>         ),
>       )
>     },
>   })
> ```
> 
> **What you did**:
> 
> * Added a defaultHighlightedIndex: 0
> * Added a isItemDisabled method
> 
> **What happened**: The highlightedIndex is always one step behind the item list. E.g. when searching for a disabled item the first time the list gets reduced to just that item but the highlighted index is still at value 0 instead of being -1. Furthermore when searching for a value that doesn't exist in the list the application will run into an exception with the second update: ![image](https://private-user-images.githubusercontent.com/13622595/362264985-07ed5950-b838-4e23-83b5-7ce61f6d4dca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI0NjYsIm5iZiI6MTcyOTY5MjE2NiwicGF0aCI6Ii8xMzYyMjU5NS8zNjIyNjQ5ODUtMDdlZDU5NTAtYjgzOC00ZTIzLTgzYjUtN2NlNjFmNmQ0ZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNDEyMDM0NmUwMTEzZWU1OGM5M2I4YzkwYzJmNGRkY2FiNGRkMzQ4NzBkM2RhOWMxOWNmZTM4NmE0NmE1YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xVgu94Jy3VphGB8CN82yZXeN-dwYZgoaF7lOq6GaHCQ)
> 
> ![combobox](https://private-user-images.githubusercontent.com/13622595/362269128-7c41e7cf-1e4a-440f-9a59-34c57a33e987.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI0NjYsIm5iZiI6MTcyOTY5MjE2NiwicGF0aCI6Ii8xMzYyMjU5NS8zNjIyNjkxMjgtN2M0MWU3Y2YtMWU0YS00NDBmLTlhNTktMzRjNTdhMzNlOTg3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NDBiYzBhZWYzYWUwY2Q0ZGE1Nzk1MGYwYTc3ZWI3NmQ4YjQ2MDQxZjc4N2ZkMTg0YmYzZTNiYTMxYmE0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.onygveXKApjDAFoGTYAi5Qwv3OUmdzirPZwyC_BEPcU) [ ![combobox](https://private-user-images.githubusercontent.com/13622595/362269128-7c41e7cf-1e4a-440f-9a59-34c57a33e987.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI0NjYsIm5iZiI6MTcyOTY5MjE2NiwicGF0aCI6Ii8xMzYyMjU5NS8zNjIyNjkxMjgtN2M0MWU3Y2YtMWU0YS00NDBmLTlhNTktMzRjNTdhMzNlOTg3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NDBiYzBhZWYzYWUwY2Q0ZGE1Nzk1MGYwYTc3ZWI3NmQ4YjQ2MDQxZjc4N2ZkMTg0YmYzZTNiYTMxYmE0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.onygveXKApjDAFoGTYAi5Qwv3OUmdzirPZwyC_BEPcU) ](https://private-user-images.githubusercontent.com/13622595/362269128-7c41e7cf-1e4a-440f-9a59-34c57a33e987.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI0NjYsIm5iZiI6MTcyOTY5MjE2NiwicGF0aCI6Ii8xMzYyMjU5NS8zNjIyNjkxMjgtN2M0MWU3Y2YtMWU0YS00NDBmLTlhNTktMzRjNTdhMzNlOTg3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NDBiYzBhZWYzYWUwY2Q0ZGE1Nzk1MGYwYTc3ZWI3NmQ4YjQ2MDQxZjc4N2ZkMTg0YmYzZTNiYTMxYmE0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.onygveXKApjDAFoGTYAi5Qwv3OUmdzirPZwyC_BEPcU) [ ](https://private-user-images.githubusercontent.com/13622595/362269128-7c41e7cf-1e4a-440f-9a59-34c57a33e987.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI0NjYsIm5iZiI6MTcyOTY5MjE2NiwicGF0aCI6Ii8xMzYyMjU5NS8zNjIyNjkxMjgtN2M0MWU3Y2YtMWU0YS00NDBmLTlhNTktMzRjNTdhMzNlOTg3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NDBiYzBhZWYzYWUwY2Q0ZGE1Nzk1MGYwYTc3ZWI3NmQ4YjQ2MDQxZjc4N2ZkMTg0YmYzZTNiYTMxYmE0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.onygveXKApjDAFoGTYAi5Qwv3OUmdzirPZwyC_BEPcU)
> 
> **Reproduction repository**: https://codesandbox.io/p/sandbox/musing-williams-jwq6vz?file=%2Fsrc%2Fhooks%2FuseCombobox%2Fbasic-usage.js&moduleview=-1
> 
> **Problem description**: See what happened
> 
> **Suggested solution**: The items and the index should update at the same time

All you need to do is to update your own code in these areas;

change this

` {isOpen &&
          inputItems.map((item, index) => (
            <li
              style={{
                backgroundColor: highlightedIndex === index ? '#bde4ff' : '',
                opacity: isItemDisabled(item) ? 0.3 : 1,
              }}
              key={`${item}${index}`}
              {...getItemProps({item, index})}
            >
              {item}
            </li>
          ))}`

to this

`{isOpen && inputItems.length > 0 &&
          inputItems.map((item, index) => (
            <li
              style={{
                backgroundColor: highlightedIndex === index ? '#bde4ff' : '',
                opacity: isItemDisabled(item) ? 0.3 : 1,
              }}
              key={`${item}${index}`}
              {...getItemProps({item, index})}
            >
              {item}
            </li>
          ))}`
          
 and also update the isItemDisabled function to this
 
 `const isItemDisabled = (item) => item && item.length > 10;`

**Comment by silviuaavram** [comment]
I hope @Bluebberies comment solved it, @christinaheidt . Closing.

**Comment by KrzysztofKarol** [comment]
@silviuaavram shouldn't the typings be fixed?

```diff
-isItemDisabled?(item: Item, index: number): boolean
+isItemDisabled?(item?: Item, index: number): boolean
```

https://github.com/downshift-js/downshift/blob/59d3498faafd3c3b4832a20dab7485502ce67284/typings/index.d.ts#L342
