### ISSUE TITLE
useCombobox: `__input_blur__` state change is not triggered when `isOpen` is controlled

### ISSUE THREAD

**Issue by okonet** [downshift-js/downshift#1624]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I've been chasing an issue that is very similar to this https://github.com/downshift-js/downshift/issues/1262 that is happening when `isOpen` is in controlled mode. After some research I found this code:

https://github.com/downshift-js/downshift/blob/59d3498faafd3c3b4832a20dab7485502ce67284/src/hooks/useCombobox/index.js#L103C13-L108

This `if` condition prevents the `onBlur` to be triggered on the input when the combobox is being closed via another component behaviour (I'm using floating-ui to control the prop). So when I click outside, floating-ui updates the prop and `isOpen` set to false so the combobox menu is closed but the blur event is never fired. We rely on the state reducer to change the state in the blur phase, so this part got broken. The fix would be to remove the `if` condition completely since it's not necessary in this case I think.

I think that `useSelect` uses the same code so probably it should be done also. 

I'm not sure if it's worth creating a repro case but I'm happy to do so if you think it's necessary. I'm also happy to submit a PR if that would help.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/downshift/dist/downshift.cjs.js b/node_modules/downshift/dist/downshift.cjs.js
index 690d8ed..9c32705 100644
--- a/node_modules/downshift/dist/downshift.cjs.js
+++ b/node_modules/downshift/dist/downshift.cjs.js
@@ -3122,13 +3122,11 @@ function useCombobox(userProps) {
     }
   });
   var mouseAndTouchTrackers = useMouseAndTouchTracker(environment, [toggleButtonRef, menuRef, inputRef], React.useCallback(function handleBlur() {
-    if (latest.current.state.isOpen) {
       dispatch({
         type: InputBlur,
         selectItem: false
       });
-    }
-  }, [dispatch, latest]));
+  }, [dispatch]));
   var setGetterPropCallInfo = useGetterPropsCalledChecker('getInputProps', 'getMenuProps');
   // Reset itemRefs on close.
   React.useEffect(function () {
diff --git a/node_modules/downshift/dist/downshift.esm.js b/node_modules/downshift/dist/downshift.esm.js
index ac35a55..0c3dc5c 100644
--- a/node_modules/downshift/dist/downshift.esm.js
+++ b/node_modules/downshift/dist/downshift.esm.js
@@ -3109,13 +3109,11 @@ function useCombobox(userProps) {
     }
   });
   var mouseAndTouchTrackers = useMouseAndTouchTracker(environment, [toggleButtonRef, menuRef, inputRef], useCallback(function handleBlur() {
-    if (latest.current.state.isOpen) {
       dispatch({
         type: InputBlur,
         selectItem: false
       });
-    }
-  }, [dispatch, latest]));
+  }, [dispatch]));
   var setGetterPropCallInfo = useGetterPropsCalledChecker('getInputProps', 'getMenuProps');
   // Reset itemRefs on close.
   useEffect(function () {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by silviuaavram** [comment]
The conditions there are actually making the hook work as expected. The changes may fix your usage, but they will break all others.

Maybe you need to change your use case in this case. Usually if you need to directly control stuff, like in this case the open state, you need onStateChange, instead of the reducer. Using both for the same reason may trigger unwanted things.

Use stateReducer if you want to surgically alter the state before its updated. Use controlled props and onChange if you need to control the state from elsewhere.

I cannot give more info as I don't have details about your implementation but I hope it help.s
