### ISSUE TITLE
Most properties in the StateChangeOptions ts interface should be optional

### ISSUE THREAD

**Issue by dovidweisz** [downshift-js/downshift#417]
* `downshift` version: 1.30.1
* `node` version: 8.5.0
* `npm` (or `yarn`) version:  Yarn 1.1.0

## Problem description:

The only required property on the [StateChangeOptions](https://github.com/paypal/downshift/blob/18b91795101930747819fa7274f0855183671bf9/typings/index.d.ts#L94) interface that should be required is `type`. All other properties should be optional.

This is a problem when using [`stateReducer`](https://github.com/paypal/downshift#statereducer), and you want to restructure your own version of the state you're returning. The compiler complains that it can't be assigned to `StateChangeOptions`.

### Code:

```ts
// given this function the ts compiler will throw an error saying the signature doesn't match
const stateReducer = (stateAndProps, changes) => {
    const { type } = changes;
    if( type === clickItem ) {
        // If the item to be selected has `allowSelection = true` return `changes`
        // ... otherwise return a new obj with just the type
        return changes.selectedItem.allowSelection? changes : {type};
    }
}
```
Simply making the properties optional would be easy, but would be a breaking change.  The same block of code would fail `"selectedItem" might not be defined`. (This is easily fixed by adding `!` after `.selectedItem`, but it is still a breaking change. )

## Suggested solution:

We create a permanent (breaking) fix for the next major version: Make those properties optional.

We also create a temporary change on top of it, that that can be entered in to a minor release: 

```ts
// New `RequiredStateChangeOptions` is the equivilant of the old `StateChangeOptions`
type RequiredStateChangeOptions = Required<StateChangeOptions>;

// Replace all instances of `StateChangeOptions` with the required version besides for
// the signature for `stateReducer` which will now look like this:

(state: DownshiftState, changes: RequiredStateChangeOptions ) => StateChangeOptions
```

**Comment by dovidweisz** [comment]
I have my changes ready [here](https://github.com/dovidweisz/downshift) and [here](https://github.com/dovidweisz/downshift/tree/temp-avoid-breaking-change).

Now I need to test it 😲

**Comment by stereobooster** [comment]
Hi @dovidweisz checkout https://github.com/paypal/downshift/blob/next/typings/index.d.ts

**Comment by dovidweisz** [comment]
@stereobooster Thank you for pointing that out to me.

What is the reasoning for using `|null`? It wouldn't solve _my_ issue, because i would still need to reconstructure the entire object; just with `null`s.

Also, generic for item bothered me at first. (What if i have more than one item type) But it's growing on me.

**Comment by stereobooster** [comment]
This does make sense

```ts
interface StateChangeOptions<Item> extends Partial<DownshiftState<Item>> {
  type: StateChangeTypes;
}
```

but this is not precise equivalent on JS code, which is ok from my POV

```js
stateToSet.type = stateToSet.type || Downshift.stateChangeTypes.unknown
```

You can open PR (against `next`) and we can start discuss changes.

Did I miss any of your questions? It seems you found all answers on your own.

**Comment by dovidweisz** [comment]
@stereobooster Are there tests for Typescript?

**Comment by dovidweisz** [comment]
@stereobooster You're right. `stateToSet.type` Should also be optional.

**Comment by stereobooster** [comment]
> Are there tests for Typescript?

Current tests are primitive. I'm not sure how to improve this at the moment. One of the ideas was to rewrite library in TypeScript or Flow. See this discussion: https://github.com/paypal/downshift/issues/400
