### ISSUE TITLE
Downshift producing empty input on blur if nothing is selected

### ISSUE THREAD

**Issue by Morton** [downshift-js/downshift#574]
- `downshift` version: 2.1.4
- `node` version: 10.7.0
- `npm` (or `yarn`) version: 6.1.0

**Relevant code or config**
Any usage of downshift. I assume this behaviours is on purpose.

**What you did**:
After opening a page using downshift I input text into the downshift-input but instead of selecting an item I blur this input (click somewhere on the page).

**What happened**:
After blurring the input it will be empty again.

**Reproduction repository**:
Downshift examples have this behaviour.

**Problem description**:
Actually whenever changing the text of the input without selecting an item but blurring, it will revert back to the text of the still selected item. In case no item is selected it will be empty. This is expected behaviour (normal <select> works similar) but there are cases you want to modify these behaviours (or have a UI designer disagreeing with this behaviour ;] ).

**Suggested solution**:
I think the best way to tackle this is to allow onStateChange to modify the changes (either changing the arguments object or returning a modified version). I would create a PR for this but wanted to pitch the idea in order to get feedback first.

**Comment by kentcdodds** [comment]
lol, I just realized that the typeahead example doesn't actually use a state reducer. It's even simpler than that. I hope it's helpful in any case :)
