### ISSUE TITLE
Fix typescript tests

### ISSUE THREAD

**Issue by kentcdodds** [downshift-js/downshift#595]
Based on research from @franklixuefei I'm pretty sure we're just waiting for cypress 3.1.1 to be released, then we can upgrade and the typescript tests can be re-enabled.

**Comment by kentcdodds** [comment]
@franklixuefei, do you think this is ready yet?

**Comment by franklixuefei** [comment]
@kentcdodds Yes! I saw you bumped up the version for `cypress` to 3.1.4, which already includes the `jQuery` dependency fix. https://github.com/cypress-io/cypress/releases/tag/v3.1.1

Feel free to uncomment the typescript test script.

**Comment by kentcdodds** [comment]
Looks like they're still failing (maybe a new error now?)

**Comment by kentcdodds** [comment]
Here's the failing build: https://travis-ci.org/paypal/downshift/builds/475157908

**Comment by franklixuefei** [comment]
Yes this is a new error. Taking a look tonight.

Frank
