### ISSUE TITLE
Updated props are not received in onChange handler

### ISSUE THREAD

**Issue by GuidovdRiet** [downshift-js/downshift#610]
**Relevant code or config**

```javascript
onChange(lang) {
    const { slug } = this.props.context; // always stays the initial value
    Router.push(`/page?slug=${slug}&lang=${lang}`, `/${lang}/${slug}`);
 }

<Downshift
        id="lang-switcher"
        items={languages}
        defaultSelectedItem={activeItem}
        defaultHighlightedIndex={activeIndex}
        onChange={this.onChange}
>

```

**Problem description**:
Updated props are not received in onChange handler. 

const { slug } = this.props.context; 

The slug value is not updated on prop change in context. Is it possible to pass the onChange method a second argument?

**Suggested solution**:
On render pass the onChange(param1, param2).

**Comment by GuidovdRiet** [comment]
`import withContext from '../../context/withContext';

class LangSwitcher extends Component {
  constructor() {
    super();
    this.onChange = this.onChange.bind(this);
  }

  onChange(lang) {
    const {
      context: { slug },
    } = this.props;
    Router.push(`/page?slug=${slug}&lang=${lang}`, `/${lang}/${slug}`);
  }

  render() {
    const {
      context: { languages },
      router: {
        query: { lang },
      },
    } = this.props;
    const [activeItem] = languages.filter(i => i.slug === lang);
    const activeIndex = languages.indexOf(activeItem);
    return (
      <Downshift
        id="lang-switcher"
        items={languages}
        defaultSelectedItem={activeItem}
        defaultHighlightedIndex={activeIndex}
        onChange={this.onChange}
        stateReducer={this.stateReducer}
      >
        {({
          getToggleButtonProps,
          getItemProps,
          isOpen,
          highlightedIndex,
          selectedItem,
        }) => (
          <div>
            <button {...getToggleButtonProps()} type="button">
              {selectedItem || lang}
            </button>
            {isOpen &&
              languages.map((language, index) => (
                <div
                  {...getItemProps({
                    key: language.slug,
                    item: language.slug,
                    style: {
                      backgroundColor:
                        highlightedIndex === index ? 'lightgray' : 'white',
                      fontWeight: selectedItem === language ? 'bold' : 'normal',
                    },
                  })}
                >
                  {language.slug}
                </div>
              ))}
          </div>
        )}
      </Downshift>
    );
  }
}`

**Comment by mfix22** [comment]
@GuidovdRiet in this case couldn't you just compare `lang` with `this.props.router.query.lang` to see if it had changed? In fact you are probably always going to be able to compare the change with some prop manually, which is super common in React code 🙂
