### ISSUE TITLE
Look into accessibility issues

### ISSUE THREAD

**Issue by kentcdodds** [downshift-js/downshift#617]
Ryan Florence mentioned that lots of combobox components (like downshift) get some things wrong:

- "escape" when navigating the list vs. escape when typing
- selecting the autocompleted portion
- ~not autocompleting the wrong async results that come back in the a different order than they went out~ (we can't do anything about this because we don't deal with loading the items).

Let's look into whether we're getting these things wrong and see about fixing that.

**Comment by silviuavram** [comment]
Escape right now clears our `selectedInput` but once ARIA will bump its version then the behavior should change.

We should support autocomplete too, adding the text in the input as the user moves through the options.

**Comment by silviuaavram** [comment]
Will close this since we already have https://github.com/downshift-js/downshift/issues/889 and https://github.com/downshift-js/downshift/issues/719 for tracking.
