### ISSUE TITLE
onChange of MaskInput is not triggered inside Downshift

### ISSUE THREAD

**Issue by aaa-magenic-eleazarj** [downshift-js/downshift#623]
- `downshift` version: 2.0.20
- `node` version: v6.11.1
- `npm` (or `yarn`) version:  3.10.10

**Problem description**:
Hi, Good day!

I have implemented a simple downshift app that search for phone number or extension. 
It basically search a phone number and once you select an item it will populate the phone and it's extension .
One thing I've noticed, at the first load of page, and I search and select a phone number, after the extension field is populated and I try to clear out the extension field (by highlighting) then presses Delete/Backspace, onChange event is not being triggered. 

But after clearing it's value for the second time, onChange is being triggered.
This is the sample link to illustrate the issue. 
https://codesandbox.io/s/2jrj567mn

My assumption is it happens because the state of two dropdowns are not in sync.
I've tried using selectedItem and assign it's value from the state, so that the selectedItem of both dropdowns are the same but it doesn't solve the issue. 

May I know your thoughts on this?

**Comment by EleazarJusto** [comment]
Hi, does anyone has thought on this issue? Thank you
