### ISSUE TITLE
React ref to the input in the render prop breaks on Safari 12.

### ISSUE THREAD

**Issue by hally9k** [downshift-js/downshift#631]
- `downshift` 3.1.5:
- `node` version: 10.8.0
- `npm` (or `yarn`) version: 1.12.3
- `iOS Safari 12`

**What you did**:
I am having trouble handling the focus of the input while developing an autocomplete on iOS Safari 12.
The basic task is to blur the input of my autocomplete when making a selection from the menu. This ensures the keyboard closes etc.

**What happened**:
I originally made a react ref on the input in the render prop and just called blur in the onChange handler, which works fine on Chrome but fails in Safari. The ref doesn't exist for some reason.
I tried passing the ref through prop getters but that didn't make a difference. 

I hacked it for now by using `document.activeElement.blur()` 😬 

Is there a best practice way to surface refs from your render props in downshift?

**Comment by silviuavram** [comment]
if it works on Chrome and not on Safari, not sure if it's related to Downshift.

if you can dig into it and provide info, it would be great :)

**Comment by lilrooness** [comment]
Also seeing this issue in safari IOS 11 and 12. The field remains in focus after selecting an option and unless you select a different component first, you cannot re-open the dropdown
