### ISSUE TITLE
When providing initialSelectedItem, onSelect, onChange, onStateChange and stateReducer are not called

### ISSUE THREAD

**Issue by montogeek** [downshift-js/downshift#659]
- `downshift` version: 3.2.0
- `node` version: v10.11.0
- `npm` (or `yarn`) version: 6.5.0

**Relevant code or config**

```javascript
<Downshift
      onStateChange={(changes, state) => console.log(changes, state)}
      onChange={(selectedItem, rest) => console.log(selectedItem, rest)}
      onSelect={option => {
        console.log(option);
        props.input.onChange(option);
      }}
      stateReducer={(state, changes) => console.log(state, changes)}
      itemToString={option => (option ? _.get(option, props.searchKey) : "")}
      initialSelectedItem={props.initialValue}
      // selectedItem={props.initialValue}
    >{()}
</Downshift>
```

**What you did**:

Added `initialSelectedItem` to `Downshift`.

**What happened**:

State/events callbacks are not called.

**Reproduction repository**:
https://codesandbox.io/s/8ynqpmmpk9

**Problem description**:

Currently when passing `initialSelectedItem`, state/events props are not called.
By reading the code, this is the current behaviour: https://github.com/downshift-js/downshift/blob/master/src/downshift.js#L138.

My use case is:
I am optionally providing a default value (via URL, a slug) to a dropdown with search, so users can use URLs to prefill the form.
This form is connected to `redux-form`, which is the `props.input.onChange` call from my example, it works just fine when the user *click* an item from the list.

**Suggested solution**:

Call these state/events props when providing `initialSelectedItem`.

I can do a PR to add it, but in the meantime, It is there a workaround?

**Comment by silviuavram** [comment]
yes they are called https://codesandbox.io/s/9lv48pkw74

**Comment by silviuavram** [comment]
`stateReducer={(state, changes) => console.log(state, changes)}` be careful with this, as you don't return anything. Read the documentation for it.

**Comment by montogeek** [comment]
@silviuavram Already tried without it.

**Comment by silviuavram** [comment]
@montogeek I have no idea what you did in your code, cannot help you much I'm afraid.

I tried to repro in the combobox.js (our testing example) with the following code:
```
 <Downshift
          onStateChange={(changes, state) => console.log(changes, state)}
          onChange={(selectedItem, rest) => console.log(selectedItem, rest)}
          onSelect={option => {
            console.log(option);
            this.handleChange(option)
          }}
          itemToString={option => typeof(option) === 'string' ? option : ""}
          initialSelectedItem={'Blue'}
>
```

Every handler is called and console logs are shown. Hope that code above helps you in digging further.

**Comment by montogeek** [comment]
@silviuavram Thanks, will check!
