### ISSUE TITLE
Cannot Clear Input Field When Pressing Enter In Specific Scenarios

### ISSUE THREAD

**Issue by vedantroy** [downshift-js/downshift#662]
- `downshift` version: ^3.2.2
- `node` version: Don't know how to find
- `npm` (or `yarn`) version: 6.5.0

**Relevant code or config**

```
class App extends Component {

  state = {
    suggestions: [
      { value: 'apple' },
      { value: 'pear' },
      { value: 'orange' },
      { value: 'grape' },
      { value: 'banana' },
    ]
  }

  render() {
    return (
      <Search
        items={this.state.suggestions}
        onValueSelected={chosenValue => {
          const newSuggestions = this.state.suggestions.filter(item => item.value !== chosenValue)
          this.setState({
            suggestions: newSuggestions
          })
        }}
      />
    )
  }
}
```

```
class Search extends React.Component {

    constructor(props) {
        super(props)
        this.inputElement = null
    }


    inputElementKeyPress = e => {
        const values = this.props.items.map(item => item.value)
        //Clear input field if a legitimate entry is selected
        if (e.nativeEvent.charCode === 13) {
            if (values.indexOf(this.inputElement.value) > -1) {
                //If you comment this line, then the search box will
                //successfully clear
                this.props.onValueSelected(this.inputElement.value);
                this.inputElement.value = "";
            }
        }
    }

    render() {
        return (
            <Downshift
                onChange={selection => alert(`You selected ${selection.value}`)}
                itemToString={item => (item ? item.value : '')}
            >
                {({
                    getInputProps,
                    getItemProps,
                    getLabelProps,
                    getMenuProps,
                    isOpen,
                    inputValue,
                    highlightedIndex,
                    selectedItem,
                }) => (
                        <div>
                            <label {...getLabelProps()}>Enter a fruit</label>
                            <input
                                ref={ref => this.inputElement = ref}
                                onKeyPress={this.inputElementKeyPress}
                                {...getInputProps()}
                            />
                            <ul {...getMenuProps()}>
                                {isOpen
                                    ? this.props.items
                                        .filter(item => !inputValue || item.value.includes(inputValue))
                                        .map((item, index) => (
                                            <li
                                                {...getItemProps({
                                                    key: item.value,
                                                    index,
                                                    item,
                                                    style: {
                                                        backgroundColor:
                                                            highlightedIndex === index ? 'lightgray' : 'white',
                                                        fontWeight: selectedItem === item ? 'bold' : 'normal',
                                                    },
                                                })}
                                            >
                                                {item.value}
                                            </li>
                                        ))
                                    : null}
                            </ul>
                        </div>
                    )}
            </Downshift>
        );
    }
}
```

**What you did**:
I want the input field to clear itself when a legitimate value (a value that is among the suggestions provided in the drop down) is in the input field and the user hits enter. Afterwards, I want the suggestion to be removed from the list of suggestions.

**What happened**:
While the suggestion is removed, as expected, the input field is not cleared. This only happens if this line: `this.props.onValueSelected(this.inputElement.value);` is uncommented.

**Reproduction repository**:
https://codesandbox.io/s/jv56mr9nl9

**Problem description**:

**Suggested solution**:

**Comment by silviuavram** [comment]
The behaviour you are describing is standard search dropdown behaviour. You can convince yourself [here](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html).

If you want to clear the `inputValue` when you pick a value from the list, you should use `inputValue` as controlled prop, by passing it to `Downshift` from your `Search` component (maybe a property in the state). And in the `onChange` prop from `Downshift` you can set that variable to empty string. Once you do that, its new value will be sent do Downshift as prop, it will clear the input content.

```
<Downshift
    onChange={selection => {
        setState({ yourVariable: '' })
    }}
    itemToString={item => (item ? item.value : '')}
    inputValue={this.state.yourVariable}
>
```

Something like this should work. Let me know :)

**Comment by vedantroy** [comment]
Thank you for the response. I tried implementing your advice, but the input field ended up being always empty (e.g--nothing could be typed). I have made a fork of the original repository, here: https://codesandbox.io/s/jprzwpx3ly

**Comment by silviuavram** [comment]
Yes, that is expected. I forgot to mention you should also change your variable each time Downshift does it. You have `onInputValueChange` for that. To recap:
- have your own `inputValue` on the state of `Search`
- pass it to `Downshift` as a prop, so you control it.
- in `onInputValueChange`, update your `inputValue` with the new one from `Downshift` by setting your state with the new one.
- in `onChange`, do whatever you want and also set the state for `inputValue` to empty string. This way, it will preserve it as `selectedItem` but your `inputValue` will be clear.

I think there is enough info in the documentation as well, you just need to read it a bit more. You can also use `stateReducer` to tweak `Search` + `Downshift` in any way you see fit. Good luck and let me know if it works :)

**Comment by vedantroy** [comment]
Thanks. I applied the advice in your post and resolved the issue. The completed example can be found here: https://codesandbox.io/s/jprzwpx3ly

**Comment by bigfoot31** [comment]
For future readers: if you are trying to clear the input field. You must do two things. Control the inputValue using your own state as mentioned. **Plus, set `selectedItem` to null**. Otherwise the search area will still have content, visually.
