### ISSUE TITLE
How best to add before/after arrows to downshift dropdown

### ISSUE THREAD

**Issue by KatherineGraham** [downshift-js/downshift#663]
downshift version - 3.2.2
node version - 9.9.0
npm version - 5.6.0

This really isn't an issue but a question. I created a dropdown using this sandbox as a guide. https://codesandbox.io/s/zrm0oonoop

I was wondering if there was an easy built in way to add before/after arrows to the dropdown to signify when it is opened closed and if anyone had done it before. I was having issues adding it. I've attached pictures of what I am trying to make it look like with the arrows. I'm not sure if this is the best place to ask that question but I wasn't sure where else on the web to go to figure it out. So far I've really enjoyed my experience with downshift.

Thanks.

![screen shot 2019-02-06 at 5 12 49 pm](https://user-images.githubusercontent.com/38301720/52384489-88997300-2a32-11e9-8e45-cc093338fc5a.png)
![screen shot 2019-02-06 at 5 12 39 pm](https://user-images.githubusercontent.com/38301720/52384490-8a633680-2a32-11e9-9ed3-16fffc73729a.png)

**Comment by silviuavram** [comment]
Hello @KatherineGraham . I believe there are many ways to create that arrow. In the example you provided I think it's an HTML symbol https://stackoverflow.com/questions/6041209/html-character-codes-for-this-or-this

You can also use Icon Fonts, but that will require you download the whole file for only one icon. Not really efficient.

Another option is to use a SVG icon for a chevron. You can probably find many icons on the internet.

That being said, whatever you choose, you will probably wrap it in a HTML element (button with icon, icon, span, etc.) As long as you use `getToggleButtonProps()` on that element, similarly to how you use the other get methods from Downshift, you should achieve what you are looking for. You can see how it's used in our `combobox.js` example from the tests, only there it's an actual button, not the arrow thingy you are looking for.

Hope this helps :) good luck!
