### ISSUE TITLE
Feature Request: Reset downshift state when inputValue changes

### ISSUE THREAD

**Issue by bkilrain** [downshift-js/downshift#664]
- `downshift` version: 3.1.12
- `node` version: 8.11.1
- `npm` (or `yarn`) version: 5.6.0

**Relevant code or config**

```javascript
```

**What you did**:

I'm using Downshift to render the dropdown for an autocomplete component. The `defaultHighlightedIndex` is set to `0` so that there is always a 'highlighted' item in the dropdown. 

**What happened**:

If I hover an item lower in the list (index 4 or 5), however, and type to filter out possible items to a number less than the highlightedIndex, the `highlightedIndex` state does not update to ensure a highlighted item is still rendered in the dropdown.

**Steps to Reproduce**:

[Code Sandbox Link](https://codesandbox.io/s/74y7y4j6rx)

1. Type 'a' into the input
1. Hover over the last item in the list to set the highlightedIndex
1. Type 'p'
1. Notice the highlightedIndex doesn't update to highlight the top item

**Suggested solution**:

Right now, I'm calling `reset()` on every input change to get around this. As far as changes to the library, perhaps we could compare the highlightedIndex with the itemCount to make sure a highlighted item is being rendered at all times? Or add the inputChange event to cases where downshift's state is reset. Can anyone think of a usecase where they don't want downshift state to reset on inputChange?

**Comment by silviuavram** [comment]
Thank you for the improvement request @bkilrain . I'd be happy to see this solved in our library so every user can benefit from it. Are you up for a Pull Request? :)

**Comment by bkilrain** [comment]
Yep - I'm happy to take this on. To be clear, we just want to reset Downshift state when `inputValue` changes?

**Comment by silviuavram** [comment]
I don't think we need to do all of that. As I understand, the issue is to reset only the highlightedIndex to the defaultHighlightedIndex each time the input value changes. Am I correct? 

Resetting the whole state will probably mean other state stuff reset which we may not want to reset, like the selected item.

**Comment by bkilrain** [comment]
Ok - fair enough.

**Comment by kilrain** [comment]
Hey there - I've completed the fix but I'm getting [this error](https://github.com/pedronauck/docz/issues/596) when I run the `setup` script. I'll cut a PR anyways... just want to let you know.

Also, I'll submit from my work github account. Thanks!
