### ISSUE TITLE
Handle custom element IDs on Downshift children (list items, list, input etc)

### ISSUE THREAD

**Issue by silviuavram** [downshift-js/downshift#667]
At the moment the code assumes that the IDs it is adding are permanent. But if the user will change them to fulfil certain scenarios, some functionalities will be broken.

For instance, a user added custom element id on the `<li>` elements, and the scroll to element functionality was broken, as it could not find the element to scroll to.

I can see 2 options:
- handle custom IDs if the user overrides them.
- use another element attribute different from `id` for the combobox, listbox, label, etc.

**Comment by babzcraig** [comment]
@silviuavram if this is till open, I'd like to take it on. I can start with taking a look at the two approaches you mentioned here (and any others that come to my mind) and figuring out pros and cons of each approach.

**Comment by silviuavram** [comment]
closing, just found that we already have an `id` prop for overriding the default ones.
