### ISSUE TITLE
Remove History autofill box

### ISSUE THREAD

**Issue by joyguy55** [downshift-js/downshift#668]
- `downshift` version: 2.0.18
- `node` version: 8.9.1
- `npm`  version: 6.4.1

I just want the option to remove or disable the history box pictured below with res and response. As I don't need it for this specific use case. 

<img width="250" alt="screen shot 2019-02-12 at 10 23 13 am" src="https://user-images.githubusercontent.com/14304220/52655082-9fb3e700-2eb0-11e9-9ac4-be8eb68cd517.png">

It's possible that your documentation just isn't very clear in this specific case. I looked through it pretty thoroughly to see if this was already an option. 

Is this already an option? or is this a option that doesn't exist yet?

**Comment by silviuavram** [comment]
Hello. I am not sure what history box you refer to in that picture. But we don't really handle rendering of stuff, that's your job. We just give you methods to make whatever it is you're rendering accessible. So not sure how I can help here.

**Comment by sandroweb** [comment]
![image](https://user-images.githubusercontent.com/260201/59061345-af00db00-8879-11e9-960f-5b97c8c0597f.png)
###### _Legend: First list is my custom list. The second list is the browser autoFill._

How I can to disable the browser autoFill?
