### ISSUE TITLE
Autocomplete with Multiple select after typing character (.)

### ISSUE THREAD

**Issue by straightforwardprog** [downshift-js/downshift#670]
Hello I'm using downshift to build a query, so i need to have multiple autocomplete system without style, for example i choose the first value after typing dot or space the datasource of autocomplete should change and when i select a value it is concatenated to the previous input String.  i don't know how to do that with downshift cause when i type (.) the menu doesn't show up.

Example 
Year.Month.day

**Comment by silviuavram** [comment]
I think I understand what you want. Maybe you can add custom handler for input key, and when you get space or dot, you save the value in your custom string variable, and then reset the state of the dropdown, so you can begin a fresh search.

You can also have your variable as an array of strings, and show it in front end as a concatenation, and you will have the advantage of being able to add another handler for the input key, detect delete or backspace when input is empty, and will delete parts of the already saved query as a result.

Are we kind of on the same page?
