### ISSUE TITLE
Error when using hooks in an inline render function

### ISSUE THREAD

**Issue by rodgobbi** [downshift-js/downshift#673]
Before anything, thanks for the awesome library!

- `downshift` version: 3.2.2
- `node` version: 9.3.0
- `yarn` version: 1.10.1

**Relevant code or config**
![image](https://user-images.githubusercontent.com/3410227/52973307-61c92e00-339c-11e9-940b-6c955cb14851.png)

**What you did**:
Used an inline render function as only child of `Downshift` component.  

**What happened**:  
`Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)`
![image](https://user-images.githubusercontent.com/3410227/52973627-73f79c00-339d-11e9-8551-7e19e340c96e.png)

**Reproduction repository**:  
Reproducing seems straightforward, but if it's just happening to me I'll try to create a repo for that.

**Problem description**:
When trying to use React hooks on the scope of the render function, React throws an error.

**Suggested solution**:
Allow using hooks inside the render function.

**Comment by k15a** [comment]
You can only use hooks in React components and they have to be called unconditionally in the same order every render. Read more about that here: https://reactjs.org/docs/hooks-rules.html

If you want to use the hooks in the render function you can create a new component and move the hooks into the new component. Then you use that component in your render function from Downshift. Probably the easier way is to move the Hooks into the component where you render Downshift.

**Comment by rodgobbi** [comment]
Hi @k15a , thanks for the help, I tried both while developing and it worked:
> you can create a new component and move the hooks into the new component.
and
> move the Hooks into the component where you render Downshift
And from what I analysed I was respecting the hook constraints, is just that this error can show when some other library is not yet compatible in some way with hooks, not just analysed but I tested, moved the same code using hooks from the Downshift render function to the upper render function that was rendering Downshift and it worked.
Definitely not a major issue because those workarounds are possible, it's just that is a bit more verbose and I was doing some prototyping and trying out of the component that I was implementing, besides that I got a bit confusing while using it wondering if I was using hooks incorrectly.

**Comment by rodgobbi** [comment]
@k15a understanding better hooks now I see that it won't be able to use hooks in the render props of `Downshift`, because it's called inside a class component
