### ISSUE TITLE
How is Typescript generic with isMulti supposed to work?

### ISSUE THREAD

**Issue by Amnesthesia** [downshift-js/downshift#684]
- `downshift` version: 2.2.3
- `node` version: 10.11.0
- `npm` (or `yarn`) version: yarn 1.10.1
- `typescript` version: 3.3.1

Curious how the `Item` generic is supposed to work when using isMulti? When using `isMulti` for a multi-select or multi-autocomplete component, `selectedItem` will always be a single item, and `setState` will accept only single items. If you pass in an array of any type as the generic to any of the DownshiftProps, things will *sort of* seem okay, except now `itemToString` claims to provide you with an array of items (which is not true).

When `isMulti` is set, the types no longer seem to be correct?

**Comment by silviuavram** [comment]
hello :) I don't think we support this prop anymore. maybe it was supported in the past, I really have no idea. Downshift now is only single search. I also know[ this example ](https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fordered-examples%2F04-multi-select.js&moduleview=1)that provides some details on how to use it for multiple selection.
