### ISSUE TITLE
Possible to use arrow keys when dropdown opens on hover

### ISSUE THREAD

**Issue by Pau1fitz** [downshift-js/downshift#688]
- `downshift` 3.2.2:
- `node` version: 11.3.0
- `npm` (or `yarn`) version: 6.4.1

**Relevant code or config**

```javascript

const Nav = () => {
    const [isOpen, setIsOpen] = useState(false);
    return (
        <div>
            <Dropdown
               onMouseEnter={() => setIsOpen(true)}  
               onMouseLeave={() => setIsOpen(false)}  
               isOpen={isOpen}
            />
        </div>
     );
}

const Dropdown = ({ isOpen, items }) => (
  <Wrapper>
    <Downshift>
      {({ getMenuProps, getItemProps }) => (
        <div>
          {isOpen ? (
            <Menu {...getMenuProps()}>
              {items.map(item => {
                return (
                  <MenuItem
                    {...getItemProps({
                      key: item.name,
                      item
                    })}
                  >
                    {item.name}
                  </MenuItem>
                );
              })}
            </Menu>
          ) : null}
        </div>
      )}
    </Downshift>
  </Wrapper>
);
```

**What you did**:

My dropdown downshift menu opens when a user hovers on a parent component. I want to set up my component to allow the user to use the arrow keys to navigate the dropdown when it is open. I am using `getMenuProps` and `getItemProps`, but they are not being triggered as the dropdown opens on hover.

**Comment by silviuavram** [comment]
what do you mean not triggered? not rendering? since you are using custom React components in that example, not sure what is happening there. can you please detail what is expected to happen and what is happening?

**Comment by Pau1fitz** [comment]
@silviuavram thanks for your response. 

I mean that usually when you click on the button, are enter input for the dropdown it will change the `isOpen` state and the user can use their keyboard to navigate the items in the dropdown. However, as I am opening the menu manually when the user `hover`s over the button so the internal Downshift `isOpen` is never triggered. 

Take this [example](https://codesandbox.io/s/7oxn01wkk6). When the user clicks on 'Select a book' button the dropdown opens and the user can use the keyboard to navigate the dropdown. However, I am not opening the dropdown on a click, it opens when the user hovers over the 'Select a book' button.

Does this make sense?

**Comment by silviuavram** [comment]
hmm, if you want it to open on hover, you need to pass a onHover (or whatever relevant listener you need) as a parameter to `getToggleButtonProps`. in that callback, set a variable on the state of your wrapper component, and use that variable as controlled prop `isOpen` by passing it to Downshift. Are we on the same page? :D

**Comment by Pau1fitz** [comment]
hahah, we are close enough. i think you understand what I mean, but I will have to play around with the implementation that you have described 😁
