### ISSUE TITLE
Mouse interferes with keyboard navigation in Safari (#240 repeat)

### ISSUE THREAD

**Issue by caleb** [downshift-js/downshift#690]
This looks like the same issues as #240 but in Safari (for macOS) only. This bug is fixed in Firefox and Chrome. I am running on Safari 12.0.3.

When the mouse cursor is hovered over the menu and the user scrolls the list with their keyboard, the item under the mouse cursor becomes the highlighted item after the user stops using the arrow keys.

I reproduced it on a forked codesandbox of the examples listed in the README (all I did was upgrade the version of downshift):
https://codesandbox.io/s/3r0472p5pq (The example I used was the `ordered-examples/02-complete-autocomplete.js` demo).

Here is a video of the issue in action:
https://nyc3.digitaloceanspaces.com/mojo-tools-development/downshift%20keyboard%20mouse%20interfere%20in%20safari%20%23240.mp4

- `downshift` version: 3.2.7
- `node` version: 10.15
- `npm` (or `yarn`) version: 1.12.3

Here is the code from the above example:

```javascript
// This is a more complete example of an autocomplete component
// with custom styling, filtering of objects, and more.
// Much of the irrelevant bits are in the ../shared file.
// which you may also want to become familiar with as many
// examples will use those as well.
import React from 'react'
import Downshift from 'downshift'
import {
  Label,
  Menu,
  ControllerButton,
  Input,
  Item,
  ArrowIcon,
  XIcon,
  css,
  itemToString,
  getItems,
} from '../shared'

class App extends React.Component {
  render() {
    return (
      <div
        {...css({
          display: 'flex',
          flexDirection: 'column',
          marginTop: 50,
        })}
      >
        <Downshift
          onChange={selection =>
            alert(
              selection
                ? `You selected ${itemToString(selection)}`
                : 'selection cleared',
            )
          }
          itemToString={itemToString}
        >
          {({
            getLabelProps,
            getInputProps,
            getToggleButtonProps,
            getMenuProps,
            getItemProps,
            isOpen,
            clearSelection,
            selectedItem,
            inputValue,
            highlightedIndex,
          }) => (
            <div {...css({width: 250, margin: 'auto'})}>
              <Label {...getLabelProps()}>Find a Star Wars character</Label>
              <div {...css({position: 'relative'})}>
                <Input
                  {...getInputProps({
                    isOpen,
                    placeholder: 'Enter a name',
                  })}
                />
                {selectedItem ? (
                  <ControllerButton
                    onClick={clearSelection}
                    aria-label="clear selection"
                  >
                    <XIcon />
                  </ControllerButton>
                ) : (
                  <ControllerButton {...getToggleButtonProps()}>
                    <ArrowIcon isOpen={isOpen} />
                  </ControllerButton>
                )}
              </div>
              <div {...css({position: 'relative'})}>
                <Menu {...getMenuProps({isOpen})}>
                  {isOpen
                    ? getItems(inputValue).map((item, index) => (
                        <Item
                          key={item.id}
                          {...getItemProps({
                            item,
                            index,
                            isActive: highlightedIndex === index,
                            isSelected: selectedItem === item,
                          })}
                        >
                          {itemToString(item)}
                        </Item>
                      ))
                    : null}
                </Menu>
              </div>
            </div>
          )}
        </Downshift>
      </div>
    )
  }
}

export default App
```

**Comment by silviuavram** [comment]
If you write a new mail in Gmail, and start writing in To input text, you will see the same behavior in their Dropdown of suggestions. Which brings up the question: if you highlight one item by keyboard and another one by mouse, which one is the actually highlighted item

I think the current behavior is acceptable, one highlighted item is enough, and this behavior is generally available everywhere. I doubt Gmail uses Downshift.

**Comment by caleb** [comment]
The problem is that the mouse cursor disappears and still interferes with keyboard selection.

If the user didn’t intend to select an item with the mouse (just hovered the mouse over the menu to scroll it maybe), this behavior would seem confusing.

**Comment by caleb** [comment]
On Safari on MacOS the cursor disappears, which makes it confusing when the invisible mouse cursor “gets in the way” with keyboard navigation.

I can investigate a solution, but since this is a repeat of a bug that was already fixed, it seems that being consistent across browsers would be preferable. Of course if the solution is not viable it’s something that I can live with.
