### ISSUE TITLE
How to reset the input when an item is clicked

### ISSUE THREAD

**Issue by bonbonio** [downshift-js/downshift#691]
Hello,

I am using DownShift as a search input, with the results shown underneath as ListItems with a {Link/React-Router-v4} component.

I want to reset the contents of the search when I click the ListItem - is there a specific callback or lifecycle I could use? The search appears on all pages.

Couldnt see this use case in any examples.

**Comment by silviuavram** [comment]
there are a couple of them actually. take a look at what `onChange` and `onSelect`.
