### ISSUE TITLE
Downshift controlled props being ignored / overridden

### ISSUE THREAD

**Issue by zxti** [downshift-js/downshift#692]
- `downshift` version: 3.2.6
- `node` version: 10.15.1
- `npm` (or `yarn`) version: 1.13.0

**Relevant code or config**
```
inputValue={text}
```

**What you did**:
All I did was make the 01-basic-example controlled on its inputValue.

Try typing in some characters and then blurring.

**What happened**:
Downshift forcefully resets the inputValue.

**Reproduction repository**:
https://codesandbox.io/s/q7jw24nn99

**Problem description**:
Downshift doesn't obey the controlled prop.

**Suggested solution**:
Obey the controlled prop! :)

BTW wonderful library, though this behavior seems to be a surprise given the goals of the library.

**Comment by zxti** [comment]
Actually, this is not specific to inputValue, e.g. selectedItem is also ignored.  And not only onBlur, but on selection as well.

**Comment by silviuavram** [comment]
interesting. can you debug where the problem is? maybe somewhere in `internalSetState`. I am on vacay now :D

**Comment by zxti** [comment]
I set a breakpoint in my itemToString callback.

Stack trace:

```
    at Downshift._this.selectItem:

     _this.internalSetState(Object(_babel_runtime_helpers_esm_extends__WEBPACK_IMPORTED_MODULE_1__["default"])({
        isOpen: _this.props.defaultIsOpen,
        highlightedIndex: _this.props.defaultHighlightedIndex,
        selectedItem: item,
        inputValue: _this.props.itemToString(item)
      }, otherStateToSet), cb);

    at Downshift._this.selectItemAtIndex:

      _this.selectItem(item, otherStateToSet, cb);

    at anonymous function:

      _enabledEventHandlers[onSelectKey] = callAllEventHandlers(customClickHandler, function () {
        _this.selectItemAtIndex(index, {
          type: clickItem
        })
```

The issue seems to be simply that Downshift is ignoring inputValue and just blindly setting (via internalSetState) the inputValue to the itemToString().

Also I think #653 is a symptom of this issue.

**Comment by zxti** [comment]
BTW, when blurring in the codesandbox example, be sure to click far down to ensure you're clicking completely outside the autocomplete, and not just to the right (which I guess is still considered inside the autocomplete - the example doesn't have any proper styling).

**Comment by silviuavram** [comment]
I managed to look at what you are doing. Yes, you control the prop, but you just refresh it with what Downshift gives you as standard behaviour. Which, in this case, is empty string. So yes, you control it, but with what we give you as part of our default behaviour.

So ... it works as expected.
