### ISSUE TITLE
How to use DownshiftInterface?

### ISSUE THREAD

**Issue by zxti** [downshift-js/downshift#693]
It seems very convenient to have a type-parameterized Downshift, so I can check that the items I pass in/out of Downshift are of the correct item type.  Seems like there should be a simple answer, but what's the correct way to use this / to get a type-parameterized Downshift component?

**Comment by silviuavram** [comment]
Well, if you use TypeScript, we have support for types.

**Comment by zxti** [comment]
Yes, I'm referring to the Typescript types.

**Comment by jetpacmonkey** [comment]
The default `Downshift` export is typed as `DownshiftInterface<any>`. Is there a way to use `DownshiftInterface` with a narrower item type that isn't `any`? I assume that's what @zxti is asking.

**Comment by jetpacmonkey** [comment]
My workaround:

```tsx
import DownshiftComponent, { DownshiftInterface } from 'downshift';
function getDownshift<T>() {
  return DownshiftComponent as DownshiftInterface<T>;
}

function MyComponent() {
  const Downshift = getDownshift<MyItem>();
  return <Downshift>
    //...
}
