### ISSUE TITLE
How to disable onBlur?

### ISSUE THREAD

**Issue by AlexCppns** [downshift-js/downshift#696]
-  `downshift`: 3.1.8,
- `node`: v10.7.0
- `yarn`: 1.13.0

**Problem description**:

Is there a way to disable/override the onBlur behavior? Right now I have a modal window closing when I click on it because it's bound to the autocomplete elements.

**Comment by silviuavram** [comment]
if you are talking about the `onBlur` from the input, you should be able to find how written in the documentation, on how to override handlers. ihttps://github.com/downshift-js/downshift#event-handlers

**Comment by AlexCppns** [comment]
@silviuavram I just found the way to override the onBlur handler but I am still unable to prevent the suggestions from closing, is there an option I could use for that?

**Comment by silviuavram** [comment]
not sure where the closing part is triggered, and I don't know what exactly your example is, can you create a code sandbox?
