### ISSUE TITLE
Enable Cypress E2E tests back into Travis CI

### ISSUE THREAD

**Issue by silviuavram** [downshift-js/downshift#704]
I thought I could fix it fast but I spent some time without finding a solution to it.

So far, I think there is something with a js file missing when you run `npm run docs:serve` and after a few seconds it will throw an error with `Unexpected token <`.

Since the cypress task will run docs:serve to have the docs ready for the tests, the test run itself will fail.

I need someone brave enough to help me fix it.

**Comment by rincedd** [comment]
Hi @silviuavram,

I'm looking into this issue now. Do you have more details on the failure scenario? I currently just enabled the Cypress tests on CI and got a green run on Travis for my branch https://github.com/rincedd/downshift/tree/cypress-on-ci: 

> 7[test:cypress] ────────────────────────────────────────────────────────────────────────────────────────────────────
[test:cypress]                                                                                                     
[test:cypress]   Running: combobox.js...                                                                  (1 of 1) 
[test:cypress] 
[test:cypress] 
[test:cypress]   combobox
    ✓ can select an item (2021ms)
    ✓ can arrow up to select last item (307ms)
    ✓ can arrow down to select first item (882ms)
    ✓ can down arrow to select an item (535ms)
    ✓ resets the item on blur (620ms)
    ✓ can use the mouse to click an item (430ms)
    ✓ does not reset the input when mouseup outside while the input is focused (712ms)
    ✓ resets when bluring the input (323ms)
    ✓ does not reset when tabbing from input to the toggle button (392ms)
    ✓ does not reset when tabbing from the toggle button to the input (298ms)
    ✓ resets when tapping outside on a touch screen (354ms)
    ✓ does not reset when swiping outside to scroll a touch screen (351ms)
[test:cypress] 
[test:cypress] 
[test:cypress]   12 passing (7s)
[test:cypress] 
[test:cypress] 
[test:cypress]   (Results)
[test:cypress] 
[test:cypress]   ┌───────────────────────────┐
[test:cypress]   │ Tests:        12          │
[test:cypress]   │ Passing:      12          │
[test:cypress]   │ Failing:      0           │
[test:cypress]   │ Pending:      0           │
[test:cypress]   │ Skipped:      0           │
[test:cypress]   │ Screenshots:  0           │
[test:cypress]   │ Video:        false       │
[test:cypress]   │ Duration:     7 seconds   │
[test:cypress]   │ Spec Ran:     combobox.js │
[test:cypress]   └───────────────────────────┘
[test:cypress] 
[test:cypress] 
7[test:cypress] ====================================================================================================
[test:cypress] 
[test:cypress]   (Run Finished)
7[test:cypress] 
[test:cypress] 
[test:cypress]       Spec                                                Tests  Passing  Failing  Pending  Skipped 
[test:cypress]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[test:cypress]   │ ✔ combobox.js                               00:07       12       12        -        -        - │
[test:cypress]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[test:cypress]     All specs passed!                           00:07       12       12        -        -        -  
[test:cypress] 
[test:cypress] 
[test:cypress] INFO: Gracefully shutting down. Please wait...
[test:cypress] npm run test:cypress --silent exited with code 0

It might be related to different versions of transient dependencies. As there is no package-lock.json or similar, the CI builds potentially use different versions on subsequent runs.

**Comment by silviuavram** [comment]
Hey, thanks for looking into this! It's strange, my runs always ended up with a server/docs related failure and the run would fail. I did not try to look into them for a while, but I will try to do it this weekend.

Let's make sure that the there are no differences in dependencies or something similar. If updates related to libraries used helped fix the problem, that would be cool! Will get back to you once I try to do another run myself.

**Comment by rincedd** [comment]
It seems to happen only sometimes. I got a couple of green runs and some red ones with the `Unexpected token <` error. It could be related to running the tests on the documentation page. Perhaps loading the web fonts or other resources fails once in a while. You would get an `Unexpected token <` when the server responds with an HTML error page but the browser expected, e.g.,  a web font. 

I'll continue investigating.

**Comment by silviuavram** [comment]
Fixed by https://github.com/downshift-js/downshift/pull/724
