### ISSUE TITLE
Migrate to Typescript?

### ISSUE THREAD

**Issue by sibelius** [downshift-js/downshift#705]
- `downshift` version: latest
- `node` version: 10
- `npm` (or `yarn`) version: 1.15.2

**Relevant code or config**

```javascript
```

**What you did**:

**What happened**:

**Reproduction repository**:

**Problem description**:
The code is not typed, so it is hard to maintain

**Suggested solution**:
Migrate code to TypeScript

**Comment by kentcdodds** [comment]
What makes you say it's hard to maintain?

**Comment by sibelius** [comment]
it boils down to this tweet https://twitter.com/mdiep/status/1116418826848153601

```jsx
We have lots of ways to catch issues:

1. Compiler error
2. Unit test
3. Integration test
4. PR comment
5. Manual QA
6. User feedback
````
I want to move some errors from unit tests to compile/typecheck errors
Types also improves code completion dx

I think the most complexity of this package is because it handles both control and uncontrolled values

Hooks based api could help in this matter, like the below codesandbox:

https://codesandbox.io/s/zrz77yj19m

```
function useControlledState(value, onChange) {
  const state = useState(value);
  return onChange ? [value, onChange] : state;
}
```

downshift.js has more than 1k of lines, maybe we can split a bit to make it easy to understand

**Comment by kentcdodds** [comment]
I'm no longer maintaining the package, so it's not my decision. But if I were, then I would totally rewrite the whole thing in hooks and it would be amazing. These patterns are WAY simpler with hooks.

**Comment by silviuavram** [comment]
Rewriting with hooks is something I am currently looking into. It will take some time as I am new to hooks, but after talking to Kent about the advantages I am excited to work on this.

As for Typescript, I don't know. Will consider it, but certainly not for the current library.

**Comment by iamandrewluca** [comment]
This does not help? :)
https://github.com/downshift-js/downshift/blob/master/typings/index.d.ts

**Comment by silviuavram** [comment]
Writing downshift-hooks in JS for now. TS may bring some advantages but probably to teams of more than 5 people. Just writing it by myself is easier in JS.

https://github.com/silviuavram/downshift-hooks

**Comment by creatyvtype** [comment]
+1 on migrating to ts. The current type definitions leave much to be desired. Getting bad errors related to the current type definition for `getItemProps`, which has a bad ts definition from when y'all made v2.0.0. Rather than just patching it, which is part of what @sibelius means with it being harder to maintain, the best solution is to type all of this out. It really wouldn't be that hard. Will gladly participate with that as a side project if you green light me to do it. But only if the PR will seriously be considered and integrated

**Comment by silviuavram** [comment]
I will not migrate to TS anytime soon, will rather focus on adding hooks to the project and improving them.

Please improve the types if needed, but I think that right now they should be correct.

**Comment by iamandrewluca** [comment]
@silviuavram https://github.com/downshift-js/downshift/pull/863
