### ISSUE TITLE
[Question] Popover menu?

### ISSUE THREAD

**Issue by universse** [downshift-js/downshift#711]
Hi, is it recommended to use Downshift for popover menus in terms of accessibility?

Something like this (from ProductHunt)
![image](https://user-images.githubusercontent.com/15166715/57189735-d267fb80-6f44-11e9-913a-cb5db8157275.png)

**Comment by alexandernanberg** [comment]
I don't think that downshift is really built for that. I'd advise you to look at https://ui.reach.tech/menu-button or similar instead!
