### ISSUE TITLE
Bug: Input gets replaced with last autocomplete value on blur

### ISSUE THREAD

**Issue by 0xR** [downshift-js/downshift#714]
This can be reproduced on the demo here: https://downshift.netlify.com

**What you did**:
* Select a color using the autocomplete
* Replace the text with something else
* Click outside the input to trigger a blur event

**What happened**:
The input is now replaced by your autocomplete value.

**Expected**
The input of the value should remain then same when a blur event occurs.

**Comment by silviuavram** [comment]
Actually, on blur, if there is a highlighted index, it should be selected.

https://github.com/downshift-js/downshift/issues/679

You can check the design pattern on the Aria website. Also if you can code a fix for this, that would be super helpful!

**Comment by 0xR** [comment]
I know, but there is no highlighted index. This is a bug.

**Comment by silviuavram** [comment]
Probably this fix will require more than a simple change in the way we handle `value`.

I am unable to code this bit at the moment but I can help you with a review if you decide to fix this issue and also maybe the select by blur. Thank you!

**Comment by aaronnuu** [comment]
This sound more like a UX issue than a bug to me. You haven't selected a new value, the current one is still in the component state. Did backspacing the first letter of your selection actually de-select the value, what about if you remove the last letter? In my opinion the input value should reflect the currently selected value on blur.

This kind of behaviour override can be implemented in user space reasonably easily.

>Actually, on blur, if there is a highlighted index, it should be selected.
Is this actually current behaviour? I don't find this to be the case in any of the examples...

**Comment by silviuavram** [comment]
@aaronnuu no, it's not current behaviour, it's suggested behaviour in https://downshift-hooks.netlify.com/dropdown. I will implement it in the hook in the future but I also implemented for the select hook https://downshift-hooks.netlify.com/dropdown

**Comment by drzajwo** [comment]
Hi,
Any updates or way to workaround this bug?

**Comment by silviuavram** [comment]
as a workaround you can probably just set the inputValue to something else on input blur, should be possible. I am adressing this by default in useCombobox so you can build that branch (it's wip) and see if it satisfies your case. And if anyone wants to fix this in `Downshift` you can create a PR for it and I will review it. https://github.com/downshift-js/downshift/pull/812

**Comment by silviuavram** [comment]
Check `useCombobox` at https://downshift.netlify.com/ and see if this happens there as well. Thanks!

**Comment by 0xR** [comment]
It happens on https://downshift.netlify.com/tests/combobox as well.

The workaround by managing the state outside of downshift is not a great solution, downshift should manage its own state.

I don't think this issue is solved and I don't think it should be closed.

**Comment by silviuavram** [comment]
Not there. Here: https://downshift.netlify.com/hooks/use-combobox
