### ISSUE TITLE
Autocomplete: when i click outside, it resets value of input.

### ISSUE THREAD

**Issue by giva9712** [downshift-js/downshift#717]
How to disable this action?

`import React, { useState } from "react";
import PropTypes from "prop-types";
import Downshift from "downshift";
import {
  TextField,
  Paper,
  MenuItem,
  InputAdornment,
  IconButton,
  Icon
} from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";
import deburr from "lodash/deburr";

const suggestions = [
  { label: "Afghanistan" },
  { label: "Aland Islands" },
  { label: "Albania" },
  { label: "Algeria" },
  { label: "American Samoa" },
  { label: "Andorra" },
  { label: "Angola" },
  { label: "Anguilla" },
  { label: "Antarctica" },
  { label: "Antigua and Barbuda" },
  { label: "Argentina" },
  { label: "Armenia" },
  { label: "Aruba" },
  { label: "Australia" },
  { label: "Austria" },
  { label: "Azerbaijan" },
  { label: "Bahamas" },
  { label: "Bahrain" },
  { label: "Bangladesh" },
  { label: "Barbados" },
  { label: "Belarus" },
  { label: "Belgium" },
  { label: "Belize" },
  { label: "Benin" },
  { label: "Bermuda" },
  { label: "Bhutan" },
  { label: "Bolivia, Plurinational State of" },
  { label: "Bonaire, Sint Eustatius and Saba" },
  { label: "Bosnia and Herzegovina" },
  { label: "Botswana" },
  { label: "Bouvet Island" },
  { label: "Brazil" },
  { label: "British Indian Ocean Territory" },
  { label: "Brunei Darussalam" }
];

const useStyles = makeStyles(theme => ({
  root: {
    flexGrow: 1,
    height: 250
  },
  container: {
    flexGrow: 1,
    position: "relative"
  },
  paper: {
    position: "absolute",
    zIndex: 1,
    marginTop: theme.spacing(1),
    left: 0,
    right: 0
  },
  chip: {
    margin: theme.spacing(0.5, 0.25)
  },
  inputRoot: {
    flexWrap: "wrap"
  },
  labelRoot: {
    color: "#FFF"
  },
  inputInput: {
    width: "auto",
    flexGrow: 1
  },
  divider: {
    height: theme.spacing(2)
  },
  InputAdornment: {
    position: "absolute",
    right: "17px"
  }
}));

function getSuggestions(value, { showEmpty = false } = {}) {
  const inputValue = deburr(value.trim()).toLowerCase();
  const inputLength = inputValue.length;
  let count = 0;

  return inputLength === 0 && !showEmpty
    ? []
    : suggestions.filter(suggestion => {
        const keep =
          count < 5 &&
          suggestion.label.slice(0, inputLength).toLowerCase() === inputValue;

        if (keep) {
          count += 1;
        }

        return keep;
      });
}

function renderInput(inputProps) {
  const {
    InputProps,
    InputLabelProps,
    classes,
    ref,
    clearSelection,
    name,
    inputValue,
    ...other
  } = inputProps;
  console.log(other);
  return (
    <TextField
      {...other}
      InputProps={{
        inputRef: ref,
        classes: {
          root: classes.inputRoot,
          input: classes.inputInput
        },
        ...InputProps,
        endAdornment:
          inputProps.inputProps.value != "" ? (
            <InputAdornment position="end" className={classes.InputAdornment}>
              <IconButton
                edge="end"
                onClick={clearSelection}
                aria-label="Toggle password visibility"
                // onClick={handleClickShowPassword}
              >
                <Icon className={"fas fa-times"} />
              </IconButton>
            </InputAdornment>
          ) : null
      }}
      InputLabelProps={{
        classes: {
          root: classes.labelRoot
        },
        ...InputLabelProps
      }}
      name={name}
      value="2222"
    />
  );
}

function renderSuggestion(suggestionProps) {
  const {
    suggestion,
    index,
    itemProps,
    highlightedIndex,
    selectedItem
  } = suggestionProps;
  const isHighlighted = highlightedIndex === index;
  const isSelected = (selectedItem || "").indexOf(suggestion.label) > -1;

  return (
    <MenuItem
      {...itemProps}
      key={suggestion.label}
      selected={isHighlighted}
      component="div"
      style={{
        fontWeight: isSelected ? 500 : 400
      }}
    >
      {suggestion.label}
    </MenuItem>
  );
}
renderSuggestion.propTypes = {
  highlightedIndex: PropTypes.number,
  index: PropTypes.number,
  itemProps: PropTypes.object,
  selectedItem: PropTypes.string,
  suggestion: PropTypes.shape({ label: PropTypes.string }).isRequired
};

const Autocomplete = props => {
  const classes = useStyles();
  return (
    <div>
      <Downshift
        
        id="downshift-options"
      >
        {({
          clearSelection,
          getInputProps,
          getItemProps,
          getLabelProps,
          getMenuProps,
          highlightedIndex,
          inputValue,
          isOpen,
          openMenu,
          selectedItem,
          reset
        }) => {
          const { onBlur, onChange, onFocus, ...inputProps } = getInputProps({
            onChange: event => {
              if (event.target.value === "") {
                clearSelection();
              }
            },
            onFocus: openMenu,
            onBlur: event => {
              event.preventDefault();
            },
            placeholder: props.placeholder
          });

          return (
            <div className={classes.container}>
              {renderInput({
                fullWidth: true,
                classes,
                label: props.label,
                name: props.name,
                InputLabelProps: getLabelProps({ shrink: true }),
                InputProps: { onBlur, onChange, onFocus },
                inputProps,
                inputValue,
                clearSelection
              })}

              <div {...getMenuProps()}>
                {isOpen ? (
                  <Paper className={classes.paper} square>
                    {getSuggestions(inputValue, { showEmpty: true }).map(
                      (suggestion, index) =>
                        renderSuggestion({
                          suggestion,
                          index,
                          itemProps: getItemProps({ item: suggestion.label }),
                          highlightedIndex,
                          selectedItem
                        })
                    )}
                  </Paper>
                ) : null}
              </div>
            </div>
          );
        }}
      </Downshift>
    </div>
  );
};

Autocomplete.propTypes = {
  label: PropTypes.string,
  placeholder: PropTypes.string
};

export default Autocomplete;
`

**Comment by silviuavram** [comment]
You can try to use `stateReducer`, catch the `Downshift.stateChangeTypes.blurInput` state change, and return whatever you want there to be your new state. Does it make sense?

**Comment by etairi** [comment]
@silviuavram Thanks, this works. However, when the user clicks outside the input field, the change type that is executed is not `Downshift.stateChangeTypes.blurInput`, instead it is `Downshift.stateChangeTypes.mouseUp`.
