### ISSUE TITLE
Error while using with React.lazy

### ISSUE THREAD

**Issue by rakshans1** [downshift-js/downshift#725]
- `downshift` version: 3.2.10
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

https://codesandbox.io/s/simple-downshift-example-ji7s4

**What you did**:
Trying to use React.lazy to lazyload downshift. On component unmount it is giving me this error
Uncaught TypeError: Cannot read property 'removeEventListener' of undefined

**What happened**:
![image](https://user-images.githubusercontent.com/12949352/60754785-e2af5c00-a003-11e9-9c2f-e254f1cc10b8.png)

**Reproduction repository**:

**Comment by silviuavram** [comment]
I don't know. I will leave it open in case someone can help.

**Comment by kentcdodds** [comment]
Pretty sure this'll fix it: https://github.com/downshift-js/downshift/pull/738

**Comment by kentcdodds** [comment]
For the record, I'm not sure what's going on either.

**Comment by arihantverma** [comment]
@rakshans1 Kent's PR solves it.

@silviuavram, I want to find why this is happening ( for exploratory purposes ). Though I do not know what to start looking for. I want a cue regarding that. Could you help me out?

On the error breakpoint ( in `componentWillUnmount` of Downshift ) looking at `this.props`, one can find that only the user inputted props to Downshift in the example, namely **onChange**, **itemToString** and **children** remain. All the other props aren't there. Destructuring seems to be solving it. I want to figure out what is happening, but don't know what to look for where and how. I could use some help.

**Comment by silviuavram** [comment]
@rakshans1 I don't have bandwidth to work on this, if you want to dig into it, good luck!

I am focusing on downshift hooks at the moment.

**Comment by rakshans1** [comment]
@silviuavram v3.2.12 fixed the issue
