### ISSUE TITLE
Dropdown menu is not interactive with keyboard in Safari and firefox

### ISSUE THREAD

**Issue by neveenatik** [downshift-js/downshift#729]
- `downshift` version: 3.2.10
- `node` version: codesandbox
- `npm` (or `yarn`) version: codesandbox

**Relevant code or config**

```javascript
class Downshift extends Component {
  ...
  ...
  ...
  buttonHandleClick = event => {
    event.preventDefault()
    // handle odd case for Safari and Firefox which
    // don't give the button the focus properly.
    /* istanbul ignore if (can't reasonably test this) */
    if (
      !isReactNative &&
      this.props.environment.document.activeElement ===
        this.props.environment.document.body
    ) {
      event.target.focus()
    }
    ...
    ...
    ...
  }
  ...
  ...
  ...
}

```

**What you did**:
 Created a simple text dropdown component with downshift.

**What happened**:

While the dropdown menu is fully interactive in Chrome, it is buggy in Safari and firefox.

**Reproduction repository**:
https://codesandbox.io/s/downshift-issue-79cmc

**Problem description**:
In Safari and firefox, the button is not being focused on click if click is on a child (ie. the image in the created sandbox). which prevents keyboard event handlers on button from firing, making the dropdown menu not interactive with keyboard arrow up, arrow down , enter keys.

**Suggested solution**:
Adjust the current button click event handler to make sure the button is focused in case a child element has been clicked.

```javascript
buttonHandleClick = event => {
  event.preventDefault()
  // handle odd case for Safari and Firefox which
  // don't give the button the focus properly.
  /* istanbul ignore if (can't reasonably test this) */
  if (
       !isReactNative 
       && this.props.environment.document.activeElement ===
       this.props.environment.document.body
    ) {
       /* suggestion is to make the focus on currentTarget instead of target
       ** to make sure that the focus is on the button
       */
       event.currentTarget.focus()
      }
  ...
}
```

**Comment by silviuavram** [comment]
Hello. I don't think I want to change anything in that handler for now. I think you can apply focus manually on the button using onClick on the icon, for this corner case.

Also consider trying out https://downshift-hooks.netlify.com/ for this Dropdown Selection example. I am actively working on it and should cover the aria-specification 100% for this type of widget, without you needing to do any other stateful logic.

Let me know if this helps.

**Comment by GonchuB** [comment]
@silviuavram but is it expected that the handler might behave differently in different browsers? in other words, should the user take care of cross-browser compat of downshift-js features?

Not trying to push for a rushed change, but wanting to understand where the root of this issue might lie

**Comment by neveenatik** [comment]
@silviuavram 
I agree that this is not a big issue but I won't consider it a corner case. It is very common to have an icon in the button. Currently I have an extra handler that keeps focus on the button.

**Comment by silviuavram** [comment]
@neveenatik use `style={{pointerEvents: 'none'}}` in your `<img>`.

https://codesandbox.io/s/downshift-issue-icon-in-button-zuzqu

Source: https://stackoverflow.com/questions/29814709/click-event-not-fired-on-button-with-svg-element-in-safari

**Comment by silviuavram** [comment]
@GonchuB we are striving to get consistent results on all combinations of OS + Browser + Screen Readers.

Sometimes it's not up to Downshift, as we are trying to follow ARIA guidelines. If we can help in handling some inconsistencies then ok, but we should not aim to hack too much.

**Comment by silviuavram** [comment]
Since you are using the Dropdown pattern please consider trying out the selection hook at https://downshift-hooks.netlify.com/ as it should implement the ARIA spec 100% and will land in this repo as soon as I am confident it's done.

**Comment by GonchuB** [comment]
@silviuavram epic thanks so much
