### ISSUE TITLE
Errors "You returned a non-DOM element. You must specify a refKey in getRootProps"

### ISSUE THREAD

**Issue by voronianski** [downshift-js/downshift#731]
- `downshift` version: 3.2.10
- `node` version: 8.15.1
- `npm` (or `yarn`) version: 6.4.1
- `emotion` version: 10.0.10

## Problem

I'm using emotion element as a root one for downshift with specified `refKey` -
```js
const containerStyles = css`
  label: dropdown__container;
  width: 100%;
`;
const Container = styled('div')(containerStyles);

// ...

<Container {...getRootProps(
  {
    refKey: 'ref',
    ...ariaLabelProps
  }
)}>
{/* ... */}
</Container>
```

but downshift keeps complaining - 

```bash
downshift: You returned a non-DOM element. You must specify a refKey in getRootProps
downshift: You must apply the ref prop "ref" from getRootProps onto your root element.
```

**Comment by silviuavram** [comment]
Hello. Consider reading the documentation about this and let me know afterwards if it works.

https://github.com/downshift-js/downshift#getrootprops

**Comment by aaronnuu** [comment]
Emotion by default passes all props from your `styled` component down to the component you're wrapping, unless it's a string component in which case it only passes valid HTML props down. You will either need to wrap that div into another component and style that, or pass a [custom prop forwarder](https://emotion.sh/docs/styled#customizing-prop-forwarding) and let the `ref` prop through.

```js
import isPropValid from '@emotion/is-prop-valid'
import styled from '@emotion/styled'

const containerStyles = css`
  label: dropdown__container;
  width: 100%;
`;

const Container = styled('div', {
  shouldForwardProp: prop =>
    isPropValid(prop) || prop === 'ref'
})(containerStyles)

function MyComponent (props) {
  const myRef = React.useRef(null);

  return (
    <Container {...getRootProps(
      {
        ref: myRef,
        refKey: 'ref',
        ...ariaLabelProps
      }
    )}>
      {/* ... */}
    </Container>
  )
}
```

**Comment by silviuavram** [comment]
Don't forget to put something in that Ref, otherwise getRootProps gets null.

**Comment by aaronnuu** [comment]
Actually thinking about it a bit react will just take that ref and apply it to the `<Container />` and return a ref to that.

This sounds like a good use for the `forwardRef` API.

```js
import React from 'react';
import Downshift from 'downshift';
import isPropValid from '@emotion/is-prop-valid'
import styled from '@emotion/styled'

const containerStyles = css`
  label: dropdown__container;
  width: 100%;
`;

const Container = React.forwardRef(styled('div', {
  shouldForwardProp: prop =>
    isPropValid(prop) || prop === 'ref'
})(containerStyles))

function MyComponent (props) {
  const myRef = React.useRef(null);

  return (
    <Downshift>
      {({ getRootProps }) => (
        <Container {...getRootProps({
            ref: myRef,
            refKey: 'ref',
            ...otherProps
        })}>
          {/* ... */}
        </Container>
      )}
    </Downshift>
  )
}
```

One caveat - not tested. Pretty sure this will work though...

**Comment by silviuavram** [comment]
@voronianski did the answers above help?

**Comment by voronianski** [comment]
@silviuavram the issue is solved on my side, it was some weird tests configuration issue. Thanks for suggestions anyways!

**Comment by voronianski** [comment]
@aaronnuu I used your suggestion and it worked. Anyways

**Comment by silviuavram** [comment]
https://github.com/downshift-js/downshift/pull/744 maybe after this will land it will work.

**Comment by silviuavram** [comment]
I will close this since https://github.com/downshift-js/downshift/pull/756 landed. Let me know if it still does not work.

**Comment by joeboylson** [comment]
Worked for me! I used:

```
    <Downshift
      onChange={handleSelection}
      itemToString={item => (item ? item.value : '')}
    >
      {({
        ...
        getRootProps,
      }) => (
        <div>
          <label {...getLabelProps()}>Enter a fruit</label>
          <div {...getRootProps(undefined, { suppressRefError: true })}>  // <==== HERE
            <input {...getInputProps()} />
          </div>
          ...
    </Downshift>
```

**Comment by silviuaavram** [comment]
Hi! Consider updating to `useCombobox`!
