### ISSUE TITLE
Testing Downshift + Material UI Autocomplete seems awkward 

### ISSUE THREAD

**Issue by redbugz** [downshift-js/downshift#732]
- `downshift` version: 3.2.10
- `node` version: 10
- `npm` (or `yarn`) version: ?

**Relevant code or config**

https://codesandbox.io/embed/material-demo-czy87

**What you did**:

Using the example code here:
https://material-ui.com/components/autocomplete

I was trying to test Downshift + material-ui together with react testing library.

**What happened**:

```
Found multiple elements with the text of: /Country1/

(If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).

<body>
  <div>
    <div
      class="makeStyles-root-1"
    >
      <div
        aria-expanded="false"
        aria-haspopup="listbox"
        aria-labelledby="downshift-simple-label"
        class="makeStyles-container-2"
        role="combobox"
      >
        <div
          class="MuiFormControl-root MuiTextField-root MuiFormControl-fullWidth"
        >
          <label
            class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink"
            data-shrink="true"
            for="downshift-simple-input"
            id="downshift-simple-label"
          >
            Country1
          </label>
          <div
            class="MuiInputBase-root MuiInput-root makeStyles-inputRoot-5 MuiInput-underline MuiInputBase-fullWidth MuiInput-fullWidth MuiInputBase-formControl MuiInput-formControl"
          >
            <input
              aria-autocomplete="list"
              aria-invalid="false"
              aria-labelledby="downshift-simple-label"
              autocomplete="off"
              class="MuiInputBase-input MuiInput-input makeStyles-inputInput-6"
              id="downshift-simple-input"
              placeholder="Search for a country (start with a)"
              type="text"
              value=""
            />
          </div>
        </div>
        <div
          aria-labelledby="downshift-simple-label"
          id="downshift-simple-menu"
          role="listbox"
        />
      </div>
```
**Reproduction repository**:

**Problem description**:

There are multiple elements described by the label, so `getByLabelText` returns multiple results, the input and 2 wrapper divs. You can of course just use `getAllByLabelText` and filter the results for just the input element, but that seems awkward, so making sure that isn't the only approach and there isn't a better way.

**Suggested solution**:
It's not clear to me if the way downshift adds multiple `aria-labelledby` elements with the same label is the problem, or the material-ui demo isn't doing things the best way, or if `getByLabelText` should be smarter, or if there needs to be some kind of helper function written to simplify this testing interaction that will be very common with Downshift+TextField.

**Comment by silviuavram** [comment]
Hello. From the https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html we will have `aria-labelledby` on `input` and `ul`. Or only on `ul` as long as the `label` has the `for` attribute that points to the id of the `input`. Maybe we need to remove it from the `combobox` wrapper. You can try to do it, create a PR and test with screen readers, see if it's working better / the same.

But, as far as your test is considered, I don't encourage using those getters in this care. Instead add `data-testid` attribute and use the main getter of RTL, by test ID.

**Comment by redbugz** [comment]
> But, as far as your test is considered, I don't encourage using those getters in this care. Instead add `data-testid` attribute and use the main getter of RTL, by test ID.

RTL specifically discourages the use of `data-testid` except in rare circumstances. So I would be more inclined to have a better `getBy` function than use testid. 

I will review the aria docs and structure and see what the best combination of structure and RTL get function seems to be.

**Comment by silviuavram** [comment]
You are right, but you need a better possibility if you want to avoid it.

Does your input have a placeholder? You can query that if so.
