### ISSUE TITLE
TypeScript: definitions missing `preventDownshiftDefault`

### ISSUE THREAD

**Issue by osdiab** [downshift-js/downshift#734]
- `downshift` version: 3.2.10
- `node` version: 12.4.0
- `npm` (or `yarn`) version: yarn 1.16.0

**Relevant code or config**

```typescript
          <input
            {...getInputProps({
              onKeyDown: event => {
                if (event.key === "Enter") {
                  // Prevent Downshift's default 'Enter' behavior.
                  // error: Property 'preventDownshiftDefault' does not exist on type 'KeyboardEvent'.ts(2339)
                  event.nativeEvent.preventDownshiftDefault = true;
                }
              }
            })}
          />
```

**What you did**:

Included the code above

**What happened**:

TypeScript error because the type of `event` is inferred to be a `React.KeyboardEvent<HTMLImputElement>`, which is missing that `preventDownshiftDefault` field

**Reproduction repository**:

**Problem description**:

The type of the event in the callback of `onKeyDown`'s `nativeEvent` field, should include `preventDownshiftDefault` as a `boolean`

**Suggested solution**:

It's rough because `React.KeyboardEvent` is defined as:

```
    interface KeyboardEvent<T = Element> extends SyntheticEvent<T, NativeKeyboardEvent> {
    // ...
```

That `NativeKeyboardEvent` field needs to be edited to include it, but it's not configurable in `KeyboardEvent`. So React's typings ought to have some way to modify that before this can be resolved in a kosher way.

**Comment by osdiab** [comment]
For now, the workaround is to use a type suggestion on `event.nativeEvent`, like `(event.nativeEvent as any).preventDownshiftDefault = true`.

**Comment by silviuavram** [comment]
You can also have `event['preventDownshiftEvent']` or `event.nativeEvent['preventDownshiftEvent']`. This is just probably a convenient way of telling Downshift not to execute its handlers apart from your own. I don't think we want to create another type wrapper over Event for that.

**Comment by silviuavram** [comment]
I will leave this open and if someone wants to create a PR that can fix this, then I'll gladly review it. Thanks!

**Comment by silviuaavram** [comment]
I don't think this is feasible. I get why it's important, but not really doable, sorry. Closing.

**Comment by samtgarson** [comment]
@silviuaavram I've had a really easy time implementing a multi-select combobox, kudos!

This is the only thing that has been off so far. I just wanted to leave a note to say that as far as I could tell, this should be possible to implement?

By omitting the relevant event handlers from the type accepted by `getInputProps` and overwrite them with your own modified handlers which accept e.g. 
```
onKeyDown: (e: KeyboardEvent<HTMLInputElement> & { preventDownshiftDefault?: boolean })
```
