### ISSUE TITLE
Show dropdown only if input contains certain characters

### ISSUE THREAD

**Issue by abelmark** [downshift-js/downshift#735]
- `downshift` version: 3.2.10
- `node` version: v10.15.3
- `npm` (or `yarn`) version: 6.9.0

I'm curious if there is a need for a feature for conditional rendering of the dropdown list.  For example

// pseudocode
if (input.includes('${') {
  showDropdown
} else {
  dontShowDropdown;
}

I'm needing this functionality for a project I'm working on.  We're trying to implement string interpolation in our app from a pre-determined list of variables that we would like to show once the user starts typing '${' (or whatever).  I started writing some code to do this myself, but was pushed towards this library due to it's flexibility, accessibility and ease of use.  

Is this something that is currently possible?  If not is this a feature that people could use?

**Comment by lovelandnoah** [comment]
Was this ever figured out?

I'm trying to implement Downshift that only permits Alphanumeric characters, but I cannot find any means to do this or documentation that shows where in the process to implement this.

**Comment by silviuaavram** [comment]
Not sure how downshift obstructs this in any way. You can have anything you want in your input, you can open the menu when you want, you are in control of the items filtering process.
