### ISSUE TITLE
Root ref

### ISSUE THREAD

**Issue by kserjey** [downshift-js/downshift#743]
- `downshift` version: 3.2.10
- `node` version: 11.12.0
- `yarn` version: 1.15.2

**Problem description**:

I want to get root element reference, but when I set `ref` thought `getRootProps`, inner `_rootNode` becomes `undefined` and it's broke downshift logic. As a temporary solution, I use downshift ref to get root element reference.

**Comment by silviuavram** [comment]
I don't understand. You want the ref to what? The first item rendered (`combobox` element)?

**Comment by kserjey** [comment]
I have a component to render dropdowns. It works similarly to [Popper](https://material-ui.com/api/popper/) from material-ui. `anchorEl` takes an element reference that used to set the position of the dropdown. When I try to get root ref:

```jsx
function MyComponent({ value, itemToString, onChange }) {
  const containerRef = useRef();
  
  return (
    <Downshift
      selectedItem={value}
      itemToString={itemToString}
      onChange={onChange}
    >
      {({
        isOpen,
        getRootProps,
        getInputProps,
        getToggleButtonProps,
        getMenuProps,
        getItemProps,
        openMenu,
      }) => (
        <Container {...getRootProps({ ref: containerRef })}>
          <Input
            {...getInputProps({
              readOnly: true,
              value: value ? itemToString(value) : '',
              onFocus: openMenu,
            })}
          />
          <ToggleButton {...getToggleButtonProps()}>
            {isOpen ? <ChevronUpIcon /> : <ChevronDownIcon />}
          </ToggleButton>
          <Dropdown
            {...getMenuProps({
              open: isOpen,
              anchorEl: containerRef.current,
            })}
          >
            {options.map((item, index) => (
              <Option
                {...getItemProps({
                  key: itemToValue(item),
                  item,
                  highlighted: highlightedIndex === index,
                })}
              >
                {itemToString(item)}
              </Option>
            ))}
          </Dropdown>
        </Container>
      )}
    </Downshift>
  );
}
```

It breaks downshift (in particular mouseUp logic), because inner `this._rootRef` becomes `undefined`.

As a temporary solution, I use downshift ref to get `_rootRef` value:

```jsx
function MyComponent({ value, itemToString, onChange }) {
  const downshiftRef = useRef({});
  
  return (
    <Downshift
      ref={downshiftRef}
      selectedItem={value}
      itemToString={itemToString}
      onChange={onChange}
    >
      {({
        isOpen,
        getRootProps,
        getInputProps,
        getToggleButtonProps,
        getMenuProps,
        getItemProps,
        openMenu,
      }) => (
        <Container {...getRootProps()}>
          <Input
            {...getInputProps({
              readOnly: true,
              value: value ? itemToString(value) : '',
              onFocus: openMenu,
            })}
          />
          <ToggleButton {...getToggleButtonProps()}>
            {isOpen ? <ChevronUpIcon /> : <ChevronDownIcon />}
          </ToggleButton>
          <Dropdown
            {...getMenuProps({
              open: isOpen,
              anchorEl: downshiftRef.current._rootNode,
            })}
          >
            {options.map((item, index) => (
              <Option
                {...getItemProps({
                  key: itemToValue(item),
                  item,
                  highlighted: highlightedIndex === index,
                })}
              >
                {itemToString(item)}
              </Option>
            ))}
          </Dropdown>
        </Container>
      )}
    </Downshift>
  );
}
```

**Comment by silviuavram** [comment]
https://github.com/downshift-js/downshift#getrootprops

As a usage example of what you probably need, go to https://downshift-hooks.netlify.com/

Go to `useSelect` and in the examples check the last 2 (Stardust and Material). You need to get the ref out of `getRootProps` by destructuring and pass it to your component, which needs to handle it. That way everyone will have access to that ref, Downshift + whatever you have there.

```jsx
            const { innerRef, ...accessibilityRootPropsRest } = getRootProps(
              { refKey: 'innerRef' },
              { suppressRefError: true },
            )

            return (
              <YourComponent ref={innerRef} {...accessibilityRootPropsRest}>
```

Good luck!

**Comment by kserjey** [comment]
No, in your example `innerRef` is a function used to set `_rootNode` inside Downshift. I need to get reference on root element. [Here](https://codesandbox.io/s/downshift-root-ref-oftgg) is detailed example of what I mean.

I can use something like this with `useSelect` hook, but it looks messy:

```
import React, { useRef, useMemo } from 'react';

function setRef(ref, value) {
  if (typeof ref === 'function') {
    ref(value);
  } else if (ref) {
    ref.current = value;
  }
}

function useForkRef(refA, refB) {
  return useMemo(() => {
    if (refA == null && refB == null) return null;
    return (refValue) => {
      setRef(refA, refValue);
      setRef(refB, refValue);
    };
  }, [refA, refB]);
}

function MyComponent() {
  const myRef = useRef();
  const { innerRef, ...rootProps } = getRootProps({ refKey: 'innerRef' });
  const handleRef = useForkRef(myRef, innerRef);
  return <RootContainer ref={handleRef} {...rootProps}/>
}
```

**Comment by silviuavram** [comment]
Hi, I removed all the conditional param you were passing to `getRootProps` and it seems to work. Can you try?

https://codesandbox.io/s/downshift-root-ref-wrbo9

**Comment by kserjey** [comment]
Eh... It was the example of the broken logic. As I told you, I need to have this reference! I need to get access to a root element. You can check out the pull request, maybe it's more clear what I mean.

**Comment by silviuavram** [comment]
Ok, I now understand. I thought that we already have that, we have it in `getMenuProps` as well.

Can you add yourself to the contributors list and re-run the build? I will merge it afterwards, thank you!

**Comment by kserjey** [comment]
Done! 👌 

But there was a problem. `kcd-scripts` threw an error: `Unknown script "contributors"`. I installed `all-contributors-cli` and used it instead of `npm run add-contributor`.
