### ISSUE TITLE
Focus input on button click?

### ISSUE THREAD

**Issue by mnpenner** [downshift-js/downshift#751]
- `downshift` version: 2.2.3
- `node` version: 12.2.0
- `npm` (or `yarn`) version: yarn 1.17.3

**Relevant code or config**

```typescript
export default function ComboBox() {
    return (
        <Downshift
            stateReducer={stateReducer}
            itemToString={itemToString}
            defaultHighlightedIndex={0}
            children={p => <span><ComboBoxInner {...p}/></span>}
        />
    )
}

class ComboBoxInner extends React.Component<ComboBoxProps, ComboBoxState, ComboBoxSnapshot> {
    ...
    
    render() {
        const {isOpen, getInputProps, getMenuProps, inputValue, getItemProps, highlightedIndex, selectedItem, setState, closeMenu, getToggleButtonProps} = this.props;

        return <>
            <Button innerRef={this.container} {...getToggleButtonProps()} >{selectedItem ? selectedItem.text || selectedItem.option : "Please Choose"}<Arrow isOpen={isOpen}/></Button>

            {isOpen && <EndOfBody>
                <Menu innerRef={this.menu}>
                    <SearchWrap>
                        <SearchInput {...getInputProps({placeholder: 'Filter...'})} innerRef={this.input} />
                        <StyledSearchIcon/>
                    </SearchWrap>
                    <MenuList {...getMenuProps({refKey: 'innerRef'})}>
                        ...
                    </MenuList>
                </Menu>
            </EndOfBody>}
        </>
    }
}
```

Looks like:

![](https://i.imgur.com/dAPCWzB.png)

**Problem description**:

When I click on my `<Button>`, the menu opens as expected/desired, but I'd like it to also focus my `<SearchInput>`. How can I do this?

**Suggested solution**:

Add `refKey` option to `getInputProps` and have `getToggleButtonProps` do it automatically, possibly with option to override for others that don't desire this.

**Comment by aaronnuu** [comment]
You could add an onClick that focuses the input imperatively? This would require you to always render the menu + input (you should be doing this anyway)

From the docs on `getMenuProps`:
>Please keep in mind that menus, for accessiblity purposes, should always be rendered, regardless of whether you hide it or not. Otherwise, getMenuProps may throw error if you unmount and remount the menu.

```
<Button
  {...getToggleButtonProps({
    onClick: () => this.input.current.focus()
  })}
/>
```

**Comment by silviuavram** [comment]
Integrating this patter in `useCombobox`.
