### ISSUE TITLE
werong typescript of setHighlightedIndex ?

### ISSUE THREAD

**Issue by eretica** [downshift-js/downshift#753]
- `downshift` version: 3.2.10
- `node` version: 10.15.1
- `npm` (or `yarn`) version: yarn

**What you did**:

i will clear highlight Index
use this function => `setHighlightedIndex `

try like this ` setHighlightedIndex(null) `
it will work
but this function argument of index type is only number

https://github.com/downshift-js/downshift/blob/931d87611a9480b7f1ae28dd3b4bdb110ef55553/typings/index.d.ts#L181-L185

**What happened**:

setHighlightedIndex(null)  is work. but types is number only

**Suggested solution**:

Before

https://github.com/downshift-js/downshift/blob/931d87611a9480b7f1ae28dd3b4bdb110ef55553/typings/index.d.ts#L181-L185

After

```ts
setHighlightedIndex: (
    index: number | null,
    otherStateToSet?: Partial<StateChangeOptions<Item>>,
    cb?: Callback,
  ) => void
```

**Comment by silviuavram** [comment]
I would leave it as it is, why do you need null for? You can add -1, it should be ok from the consistency point of view.

For instance Array.indexOf returns -1 if the item is not in the array. In our case, index is related to an array as well. So maybe -1 makes sense.

Why do you think null is better? What value does it add?

**Comment by eretica** [comment]
i feel -1 is not good for setter.
`indexOf` -1 is at least for undefined.
i think *Set(null) is better mean for clear 

When null is available, it is easy to determine that it is for clearing

**Comment by silviuavram** [comment]
I think that, for now, -1 is a good enough negation for a number based state value.

Thanks for your input!
