### ISSUE TITLE
State remains open after selecting an item by pressing "Enter" when using useSelect to make a controlled component.

### ISSUE THREAD

**Issue by philipnilsson** [downshift-js/downshift#762]
- `downshift` version: 3.3.1
- `node` 8.10:
- `npm` (or `yarn`) version: yarn 1.9.4

**Relevant code or config**

https://codesandbox.io/s/downshift-hooks-example-e8jk8

**What you did**:

I've created a component for a style guide that needs to be able to have `selectedItem` controlled from a parent component. See `Wrapper` in above example.

**What happened**:

Everything works as expected expect that the menu remains open after selecting an item with the "Enter" key.  I.e.

 - Visit above sandbox (Chrome 76 on MacOS)
 - Open the `Elements` menu in the example.
 - Select an item and press the `Enter` key.

The menu does not close as expected. (Item is correctly selected)

When debugging this by logging internal state transitions using the `stateReducer` prop, I see that the "toggle button click" event is fired twice.

```js
    // I provided this for debugging only.
    stateReducer: (s, c) => {
      console.log('c.type', c.type);
      return c.changes;
    },
```

![image](https://user-images.githubusercontent.com/2103391/64722516-e6150700-d4ce-11e9-9bc5-14b4b0c93632.png)

**Suggested solution**:

I haven't had time to debug this further, other than noticing that if I move the `useState` declaration into the `DropdownSelect` component I get the correct behaviour.

**Comment by silviuavram** [comment]
the issue is how the whole controlled thing is implemented, will work on this and see if I can fix it properly. Thanks for reporting it!

**Comment by silviuavram** [comment]
You can use `stateReducer` as a workaround for now.

**Comment by silviuavram** [comment]
Also @philipnilsson use the codesandbox with downshift instead of downshift-hooks. Just updated the readme with it. Thanks!

https://codesandbox.io/s/useselect-usage-53qfj

**Comment by philipnilsson** [comment]
Just deployed the new version to production today. Works great. Thanks for the hard work @silviuavram!
