### ISSUE TITLE
useSelect typescript typing are wrong

### ISSUE THREAD

**Issue by CodeWitchBella** [downshift-js/downshift#763]
- `downshift` version: 3.3.1
- `node` version: 10.16.3
- `npm` (or `yarn`) version: 6.9.0

**Relevant code or config**

[Example in typescript playground](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoUSWOAbyIDsATJKAXzm1wKPRgFomuMpXDR4tAK4BnJAGUkAGyQYOXPPiEB3BtIAWwTDBEVMkhhmAQGcACI4w2hguUYAFAEo6FOHDTXpCR9fOGBpAHkwJAYAGmDfWVcYJCYASWSQOPIQuABzJBgAFQhc3OUAIUkYGGsABQdpLJz8mAAZFAAjJXqIMEb4vIKAWWjJHr6mkINcvUVgGeS05iQAD0nfFvSkEHH+7LgOAF44GXklFRg3WmAM6QAuOF6YK102D2CiGEkoGzcBgB4mMAAG4APgGvn+ik6SjoADoES12l1FLtPGxQQBhPQQCCyOAoGznEDRGB3f4AemhKPB+xy-w6VRqNloCLhLWKpQqTLqDXRoNoiQuKS2eAAPmKCABRZQkhgwaT4NiUxnVay0nKQySKeGI4ajNEeDiBACeykOtDlkjkMDNSGkGIhIWuESiNgAZO6nTkni9pHCQCgwG43L7rDFQssVl5DqC4H86Zr6XNvUm4KbzbRU2m4NNZvM9ItUlG4Icy5GWCs4AB+OgddAAa1yOHMTExEEU0Ae+AAxB0WAAWTCYJVwB60NjZzWTxM53wNpAmi0AAwAJLQwww2OvgFG2MuZ3PNay9TBRWjrhkHpuI7vK29D0e4Bqn74N2BntZH0fKXMXzmPCNJ1KW1f84EpIEwWCd5yBnCh-F0eBN2kUs4AAbWCfAADkkA-cxgEkEB8EmfBakUKprAIoiSIAQRJKBgDQKjiMwzFvmYkjylYBc5kIlj9nwTEUDmTBoAYDjMKlXdAiQXcJIEgAxVgQHk3x8BGZZlGBVSCCwiAUR0-B2i0RgmL4kiECqPRWFEqAgXMzDbEkDpxIcgSFE6aBckM8oID0Bi3LUgAJFBpGkQyRhuBhWEM2wUCgEBAhQJhnkCggEAgUl8lc6jWN6VhxLM3KBKw4AcRy-i1IU5QcG0tL1Lxfw6uKtTWhBZToEMwpomisLdyQSqCHCXJCXtaRrH4gBdeCAngK0bTtFDjizfZAxWILZIWbsACYAAZdrAFZBogYEbM7LQAE1uxQCjBq0YAUr0bsAEYAFYDqOyZIHCz8GGujpxvI5JBsDKBvL+uBdsmDpoBYKBijAB4oeCes0CbFtmG7LQDGBrI4PIRg4bcf57F6JwXAuOAKVBCMhDQQjSXZAoZW2UlyhNVImDcQhcWMQCgA) (copied directly from [first example in useSelect documentation](https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#usage))

**What you did**:

Copied code directly from first example in docs

**What happened**:

```
Argument of type '{ items: string[]; }' is not assignable to parameter of type 'UseSelectInterface<unknown>'.
  Object literal may only specify known properties, and 'items' does not exist in type 'UseSelectInterface<unknown>'.
```

**Reproduction repository**:

Reproduction typescript playground is linked above

**Problem description**:

There are several problems here:
1. useSelect typings declare that it is function that accepts UseSelectInterface which is wrong. It should accept UseSelectProps
2. most of fields in UseSelectProps should be optional
3. Another problem is that useSelect.stateChangeTypes is not correctly typed

**Suggested solution**:

Change
```ts
export function useSelect<Item>(
  props: UseSelectInterface<Item>,
): UseSelectReturnValue<Item>
```

to

```ts
export function useSelect<Item>(
  props: UseSelectProps<Item>,
): UseSelectReturnValue<Item>
```

But I am not sure what to do with stateChangeTypes (which change above would not fix).

My currect workaround [in TS playground](http://www.typescriptlang.org/play/?esModuleInterop=true&jsx=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoUSWOAbyIDsATJKAXzm1wKPRgFomuMpXDR4tAK4BnJAGUkAGyQY4KaXBlIAKgAt5SlTAA0AVVkLlGAAo4w0sxcMZkMSVAYA1FIslIOXHj4QgDuDNK6wJgwIhQwAJ5gSHAKIMAAwtBEGOYGVjAAPNoAfHAAvHAAFBRwcGB20gBccNYosMA+BbmWRrYQ9kXFxcYUAJTlpd3OMK7uXj5+gxQUmJIMGMAQDHAAInahDD0YleO0NXAA9BdwMJEawBr6RDcQnMAAHjf6cABGOADWSG2WiO8ASYGADAA5hoDhEovB4fY4CFgLc4I1+NVyLU0FtpPAQdNylUtHo8kY1BoUAx4uN1FVUhkskYpvkCgSoJCocVRuc8eEJOdag8APJJBgjHG1OCyfJIJgASRgSBAUplcChSBg2ggUKhygAQpIYDAtn17OqZVqYAAZFA-JQWhzCzXagCyQMkzqttUiUN0imAAZVSuYSHevrdMGVqp95w4FSJ+UqtDRqqacH6ME24TYfOlRDcHiqroKTGAADdiq7agVFA6lHQAHStm32x2KZ0nNjFdK6CAQWRqbaGEBAmCNAoXBudmvSjUFH4ms3bWit5s23X6o0r80NHvFWhyowK2N4AA+F4IAFFlOOGDBpPg2NPl6atvONXXJIoW22PS9btRg4Al4mUMpaAfSQ5ASZRpF7WsZTTaRxSBOAADIMKQjVs1zaRmxAFAwEqSo8K2Yw4EhFh3nGMpSmxb8mLgetgBw5iwIgs4F2Ypj-UDYNdFDRVw0+MpxKo0S4AAfjoH50H+KEcDWJhMkUaBmnwABiH4WAAFkwTAXwxOg2HYpizJ43jakBeJIIAAwAElociGDYZzqIjNh7Ms6zv3XACYxVEBuzTYLmlcyjPPefNfL8uAv3i2oXLAHMtjivzpyDRLeNGECkOnX8cpYi4K2rc4C0sigBQJLNUvwkkAG1znwAA5JBUrWYBJBAfArXwaxfFXbrev6gBBccuTQEa+pa9J3Bm-rDVYQEgx62bpXwdIfCiaAGEWlqb0hAkkEhA7NoAMVYNJ1v6z1w2UStztqNqIE7Z6CHtEJGGm26WoQE0nkwaAKz+zadkkH59rBl6FAdaAoQ+-BDQgXQuRhggAAl1GkJHPTRBhWCRnY2hAAkUCYHMMfwBAIAnLVodGub+lYfbfqZzbWuAAdGY2l6LuUHAnup90hzxYWOZe20q2u6Ake0IFCekXHCb5ghRShGkkGVrYNoAXWq-F4Gg2DwO1kluNqIj3kx06Q00gAmAAGJ2wHeNWIErVhMHUkIAE1NJQE0IDV1FKd0TSAEYAFZXfdq1IFxtKGEDn5pAgIakDVoioERlO4Cdq0fhB1hdTAZpC-OeS0EU5TmE0kJIhVDaqvIRgWCgSoCj2foDlBS5hjgIQ0B6idN21O9VQnQ14kVJhKkIQcYjyoA)

**Comment by silviuavram** [comment]
Thank you for reporting this! Will take a look but can you create a PR with the fix? maybe you will be faster, I am currently working on fixing https://github.com/downshift-js/downshift/issues/762

**Comment by CodeWitchBella** [comment]
Submitted as #765

**Comment by silviuavram** [comment]
awesome, thanks a lot! this will be a breaking change and I'd batch it up with a v4 release.

There is also https://github.com/downshift-js/downshift/pull/748 that is a breaking change.

Maybe we can batch these 2 together? What do you think about the other one?

**Comment by CodeWitchBella** [comment]
Maybe. While this technically is breaking change the previous version is so broken that you literally cannot use it with typescript without casting to any or similar so I wouldn't worry too much about it being breaking.

**Comment by Xiphe** [comment]
I second @CodeWitchBella. This was really confusing to me after installing downshift in a new cra-app with TS.

**Comment by silviuavram** [comment]
I am merging this today or tomorrow as a fix. @CodeWitchBella can you install kcd scripts globally and try to run that contributors script again?
