### ISSUE TITLE
getA11yStatusMessage doesn't run on mount, only on update

### ISSUE THREAD

**Issue by MarkFalconbridge** [downshift-js/downshift#764]
getA11yStatusMessage doesn't run on mount, only on update therefore the message isn't present in the DOM when first mounted.

- `downshift` version: 3.3.1 (I believe it affects all versions)

**What you did**:
Mounted the component

**What happened**:
The result of getA11yStatusMessage  isn't in the DOM.

**Problem description**:

This is easy to witness in the https://codesandbox.io/s/zKE37vorr or https://codesandbox.io/s/53y8jvpj0k examples. Load the example and inspect the DOM, the status message is missing from the DOM. As soon as you open the dropdown it appears.

**Suggested solution**:
Assuming the message is meant to be present in the DOM at all times the simple fix would be to run the code that adds it on mount as well as on update.

**Comment by silviuavram** [comment]
Yes, it runs on update. I don't think it should announce anything on mount, you will get an announcement when the page loads no matter where you are on the page.

Can you provide a use case you want this to happen?

**Comment by MarkFalconbridge** [comment]
Yes, that's a very good point. I'll close the issue.
