### ISSUE TITLE
useSelect does not cycle through list on arrows down/up

### ISSUE THREAD

**Issue by filipjnc** [downshift-js/downshift#766]
- `downshift-hooks` version: 0.8.0
- `node` version: 8.11.3
- `npm` (or `yarn`) version: 6.11.3

**What you did**:
1. Open the online example: https://codesandbox.io/s/downshift-hooks-example-ew0em
2. Open the list
3. Click arrow down/up indefinetely

**What happened**:
List stops at first/last item in the list.

**Reproduction repository**:
https://codesandbox.io/s/downshift-hooks-example-ew0em

**Problem description**:
Arrow up on first item should go to last item, arrow down on last item should go to first item.

**Suggested solution**:
Implement same behavior as in the Downshift component.

**Comment by silviuavram** [comment]
For select components, the ARIA example is without circular navigation. But you can pass the `circularNavigation` to the hook to achieve the result you want.

https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#circularnavigation

Good luck!

**Comment by filipjnc** [comment]
My bad for not reading the docs carefully enough! Excellent to provide an option to set that, love it.
