### ISSUE TITLE
downshift-hooks error in 0.8.1

### ISSUE THREAD

**Issue by filipjnc** [downshift-js/downshift#767]
- `downshift` version: 0.8.1
- `node` version: 8.11.3
- `npm` (or `yarn`) version: 6.11.3

**What you did**:
1. Opened the online example
2. Bumped downshift-hooks from 0.8.0 to 0.8.1

**What happened**:
Errors out.

**Reproduction repository**:
https://codesandbox.io/s/downshift-hooks-example-ew0em

**Comment by silviuavram** [comment]
hi, try https://codesandbox.io/s/53qfj instead. Updating the link in the docs now. Thanks!

**Comment by filipjnc** [comment]
Great to be able to use the same package now. Thank you!
