### ISSUE TITLE
stateReducer object mismatch

### ISSUE THREAD

**Issue by iswara108** [downshift-js/downshift#773]
- `downshift` version: 3.3.1
- `node` version: 
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript

```

**What you did**: I followed the example on the README: https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#statereducer

**What happened**: The button did not open the suggestions.

**Reproduction repository**: https://codesandbox.io/s/useselect-usage-fss6l

Please see lines 23 and 28 in index.js (I had to change "changes" into "changes.changes" for it to work, borrowing from the example on the readme file of stateReducer.

**Problem description**: 

**Suggested solution**: It looks like the return value "changes" should be swapped into : "changes.changes"

**Comment by iswara108** [comment]
The original code is:

```
function stateReducer(state, changes) {
  // this prevents the menu from being closed when the user selects an item with a keyboard or mouse
  switch (changes.type) {
    case useSelect.stateChangeTypes.MenuKeyDownEnter:
    case useSelect.stateChangeTypes.ItemClick:
      return {
        ...changes,
        isOpen: state.isOpen,
        highlightedIndex: state.highlightedIndex,
      }
    default:
      return changes
  }
}
```

But it doesn't work.

The code which does work is:

```
function stateReducer(state, changes) {
  // this prevents the menu from being closed when the user selects an item with a keyboard or mouse
  switch (changes.type) {
    case useSelect.stateChangeTypes.MenuKeyDownEnter:
    case useSelect.stateChangeTypes.ItemClick:
      return {
        ...changes.changes,
        isOpen: state.isOpen,
        highlightedIndex: state.highlightedIndex,
      }
    default:
      return changes.changes
  }
}
```

**Comment by silviuavram** [comment]
Oups you are right! Will change docs and add a codesandbox for that example too. Thank you!

**Comment by silviuavram** [comment]
@iswara108 is the PR fixing the issue as you expect? :)

**Comment by iswara108** [comment]
Sorry, I have to focus on other topics and I cannot check at the moment.
Just wanted to bring this to your attention since I happened to notice the
issue.
