### ISSUE TITLE
Unexpected selection when clicking outside an open menu when using useSelect

### ISSUE THREAD

**Issue by philipnilsson** [downshift-js/downshift#780]
- `downshift` version: 3.3.4
- `node` version: 8.10

**Relevant code or config**

https://codesandbox.io/s/useselect-usage-53qfj

**What you did**:

- Click the button to open the menu.
- Highlight an item in the menu.
- Click *outside* the menu.

**What happened**:

The highlighted item was selected, even though the click is targetted outside the menu. (This is different from when using the non-hook downshift render-prop component).

**Problem description**:

The item should instead not be selected.

**Suggested solution**:

I suspect this is pretty straightforward, but haven't looked into a solution.

**Comment by phinoppix** [comment]
I encountered this problem too while building a custom dropdown box.  As a workaround, you can utilize the `stateReducer` to accept the selected item for certain interactions only.
```javascript
const customStateReducer = (state, change) => {
  switch (changes.type) {
    case Downshift.stateChangeTypes.keyDownEnter:
    case Downshift.stateChangeTypes.clickItem:
      return {
        ...changes.changes  // I wonder if this this is the intended structure for this parameter
      };
    default:
      return {
        ...changes.changes,
        selectedItem: state.selectedItem
      };
  }
}

// In your component,
const {...} = useSelect({
  items,
  stateReducer: customStateReducer
})
```

If you are using Typescript, the code above will break because `changes: UseSelectStateChangeOptions` does not contain `changes` attribute.

**Comment by jazzfog** [comment]
Same problem - mouse hover over opened menu and click outside results in an unwanted item selection.

**Comment by silviuavram** [comment]
Ok, this seems like the reducer needs an update. It should keep selection on Blur by Tab/Shift Tab but needs not to select on outside click.

**Comment by silviuavram** [comment]
@jazzfog @philipnilsson @phinoppix @wilcoxmd is the PR fixing it? Is it behaving as you would expect?
