### ISSUE TITLE
Downshift multiselect handling pre existing selected items

### ISSUE THREAD

**Issue by sanjaysai1184** [downshift-js/downshift#782]
- `downshift` version: 3.2.10
- `node` version: 12.4.0
- `npm` (or `yarn`) version: 6.9.0

**Relevant code or config**

```javascript
```

**What you did**:
My multi select component renders some pre-selected items. When I try to add another item, the pre-selected items are supposed to be disabled and not let me add them.
**What happened**:
The pre-selected items are still active and I can add them again which is causing the component to crash because they both have same key.

Encountered two children with the same key ..
**Reproduction repository**:

**Problem description**:

**Suggested solution**:

**Comment by silviuavram** [comment]
Hi, can you share a code sandbox with this scenario? We can figure it out better with the code in front of us. Thanks!
