### ISSUE TITLE
Add useAutocomplete hook

### ISSUE THREAD

**Issue by cmeeren** [downshift-js/downshift#783]
I noticed that [downshift-hooks](https://github.com/silviuavram/downshift-hooks) had been merged into this repo now, and that `useSelect` was added in 3.3.0. Hooray! I'm sure you don't need an issue to remember to implement the other hooks, but I couldn't find one and just wanted to say that I for one am really looking forward to `useAutocomplete`. 👍

**Comment by silviuavram** [comment]
Hi, thank you for mentioning it! Yes, `useAutocomplete` is next in line, I am pushing to get a prototype for it in November. Will update everyone on the progress.

**Comment by silviuavram** [comment]
work in progress at https://github.com/downshift-js/downshift/pull/812 will let you know when it's in review state. you can share your thoughts on this in the meantime though :)

**Comment by cmeeren** [comment]
Thanks. Unfortunately I'm full up for the foreseeable future. I don't even have the capacity to properly care for the projects I maintain. Furthermore, with the recent (still experimental) [Autocomplete MUI component](https://material-ui.com/components/autocomplete/) it seems I'll probably use that going forward.

Thanks anyway, and good luck with the implementation! :)

**Comment by silviuavram** [comment]
Almost finished development in https://github.com/downshift-js/downshift/pull/812 .

**Comment by silviuavram** [comment]
Code already in https://github.com/downshift-js/downshift/commit/bb699eab015c857007b462ed5071cb1d91e095c1 will be released tomorrow as 4.0.0.
