### ISSUE TITLE
Error linting: error  Definition for rule 'react/jsx-no-useless-fragment' was not found  react/jsx-no-useless-fragment

### ISSUE THREAD

**Issue by epeicher** [downshift-js/downshift#786]
- `downshift` version: v3.3.4
- `node` version: v10.15.2
- `npm` (or `yarn`) version: 6.4.1

**Relevant code or config**

```javascript
npm run lint
```

**What you did**:

`npm run setup`

**What happened**:
```
error  Definition for rule 'react/jsx-no-useless-fragment' was not found  react/jsx-no-useless-fragment
```
![image](https://user-images.githubusercontent.com/3519124/66255679-d663a800-e786-11e9-89bc-1b9ae4327c58.png)

**Reproduction repository**:

**Problem description**:
Error linting files

**Suggested solution**:
Upgrading the version of `eslint-plugin-react` to `7.16.0`

PR already submitted to fix this PR - #784

**Comment by silviuavram** [comment]
Hi, I don't have this issue, maybe you should do a cleanup of your cache, delete node modules and npm install again.

**Comment by epeicher** [comment]
Hi, I tríed that but still got the error, that rule is used by the downshift eslint config but it was added in version `15` of the upgraded package, you can have a look at the linked PR #784 to see what requires to be updated

**Comment by dhovart** [comment]
I just cloned the repo (willing to contribute a PR), ran `npm run setup` and this appeared as well.

**Comment by silviuavram** [comment]
Ok, builds are hitting it as well. I did some digging and probably updating kcd-scripts will fix it. Will create a PR that updates dependencies soon. Hold on tight!
