### ISSUE TITLE
add-contributor script not working

### ISSUE THREAD

**Issue by epeicher** [downshift-js/downshift#787]
- `downshift` version: v3.3.4
- `node` version: v10.15.2
- `npm` (or `yarn`) version: 6.4.1

**Relevant code or config**

```javascript
npm run add-contributor
```

**What you did**:
Run `npm run add-contributor`

**What happened**:
An error was returned `Error: Unknown script "contributors".`

![image](https://user-images.githubusercontent.com/3519124/66255770-efb92400-e787-11e9-9af0-3939fbb04dc7.png)

**Reproduction repository**:

**Problem description**:
The `contributors` script was deleted from `kcd-scripts` in version 1.9 which is the version used by `downshift`

**Suggested solution**:
Implement a new way to add contributors or add the [all-contributors](https://allcontributors.org/) bot

**Comment by epeicher** [comment]
A PR to notify users about it has been created: #785  but I would be keen on helping with a proper solution to this

**Comment by silviuavram** [comment]
not sure if it's a problem with `Downshift` or `kcd-scripts`. @kentcdodds can you help?

**Comment by kentcdodds** [comment]
Now that there's [a bot](https://allcontributors.org/docs/en/bot/usage), I removed that script and just use the bot 😀

**Comment by silviuavram** [comment]
Ok, maybe we can also add the bot and join the future! Thanks Kent!

**Comment by silviuavram** [comment]
@all-contributors please add @epeicher for bug
