### ISSUE TITLE
useSelect(): getLabelProps() does not return 'htmlFor' identifier

### ISSUE THREAD

**Issue by jazzfog** [downshift-js/downshift#789]
- `downshift` version: 3.3.4
- `node` version: 8.11.3
- `npm` (or `yarn`) version: 1.16

**What you did**:
Attempted to link `<label>` and `<button>` elements

**What happened**:
I am trying to use `useSelect()` hook in my project but it does not seem like `getLabelProps()` returns `htmlFor` to link the label with the handler `button`.

Example from the documentation: https://codesandbox.io/s/53qfj

![Screenshot from 2019-10-08 21-34-53](https://user-images.githubusercontent.com/3300853/66452003-aed53f80-ea13-11e9-9903-28b19a05bf70.png)

**Problem description**:

`getLabelProps()` did not return `htmlFor` value.

**Suggested solution**:

`getLabelProps()` should return `htmlFor` value identical to `id` from `getToggleButtonProps()`.

**Comment by silviuavram** [comment]
thank you! seems legit, when you click on the label, the focus should go on the button.

I can take this but if you can do it faster, code it up with tests then I can review!

**Comment by silviuavram** [comment]
After testing this, clicking the label will result in a click on the button. Is this something we want? Is there anywhere something similar?
