### ISSUE TITLE
useSelect: add onSelect parity from old render props

### ISSUE THREAD

**Issue by gstauffer-toast** [downshift-js/downshift#793]
- `downshift` version: 3.3.4
- `node` version: v8.16.0
- `npm` (or `yarn`) version: 1.16.0

**Relevant code or config**

```javascript
  const {
    selectedItem,
    ... // other props omitted
  } = useSelect({ 
    items: options
})

  // this doesn't work!! I need (or maybe want?) to call the item _every time its clicked!_
  // because useEffect uses the output state of useSelect (`selectedItem`) it
  // will only change when a new item is selected. The alternative is to omit it from the
  // dependencies, which causes it to call on every re-render
  useEffect(() => {
    selectedItem && onSelected(selectedItem)
  }, [onSelected, selectedItem])
```

**Problem description**:
When using `useSelect` for a non-select component, we lose the functionality for a stateless, menu-like, dropdown. I will admit - it is in the name.. it is use**Select** after all. That said, it would be nice if we can add some way of indicating that an item has been clicked. This will give us parity with the [Downshift's existing onSelect callback](https://github.com/downshift-js/downshift#onselect).

**Suggested solution**:
Add an `onSelect` as a passed in prop to `useSelect`. It should have the same hooks as the existing `onSelect` from react props, but be called any time there is an action on the dropdown items.

It would change the above sample to look something like:
```javascript
  const {
    ... // other props omitted
  } = useSelect({
    items: options,
    onSelect: (option) => {
        if (option.action) option.action()
    }
})
```

Adding this new select callback allows `useSelect` to handle a simple dropdown use-case, without needing any state. Though it may be better to just make a `useDropdown` hook as well. Let eknow what you think!

**Comment by gstauffer-toast** [comment]
I did not read the docs. Deleting this now.

**Comment by gstauffer-toast** [comment]
I am going to re-open this issue however, as I think that this would be a useful feature. While `stateReducer` is a good work around, I think this would be quite useful

**Comment by silviuavram** [comment]
Hey @gstauffer-toast isn't `onSelectedItemChange` prop covering your use case ?

**Comment by gstauffer-toast** [comment]
@silviuavram it unfortunately does not work, because it will not re-fire the event if the same item is clicked (https://github.com/downshift-js/downshift/blob/66bc9ea2f0a941214ecffc84cbfce541ab8f5ad7/src/hooks/useSelect/__tests__/props.test.js#L463)

**Comment by silviuavram** [comment]
oh, I understand now. Do you want to create a PR to fix this?

**Comment by gstauffer-toast** [comment]
Sure, I can try and post a PR later this week

**Comment by gstauffer-toast** [comment]
@silviuavram I added a PR to add an `onItemSelected` callback here: https://github.com/downshift-js/downshift/pull/816

**Comment by silviuaavram** [comment]
I don't think I will add another prop for this. Can be worked around in a `stateReducer` by catching `MenuKeyDownEnter, MenuKeyDownSpaceButton or ItemClick`.
