### ISSUE TITLE
Select Item based on external action

### ISSUE THREAD

**Issue by iamchathu** [downshift-js/downshift#798]
- `downshift` version: `^3.3.4`
- `node` version: `v10.15.3`
- `npm` (or `yarn`) version: `1.17.3`

**Relevant code or config**

```js

```

**What you did**:

Need a way to type code input and based on the code set selectedItem on the downshift list

**What happened**:

Saw there is an action called selectItem but couldn't think of a way to use it.

**Reproduction repository**:
https://codesandbox.io/s/simple-downshift-example-jboow

**Problem description**:
Need a way to type code input and based on the code set selectedItem on the downshift list.

**Suggested solution**: A way to externally update selectedItem

**Comment by silviuavram** [comment]
`selectItem` is a callback returned by Downshift which you can call with the item you want to select.
