### ISSUE TITLE
useSelect missing getInputProps

### ISSUE THREAD

**Issue by yunyu** [downshift-js/downshift#800]
- `downshift` version: ^3.3.4
- `node` version: v10.16.3
- `npm` (or `yarn`) version: 1.19.1

**Relevant code or config**

```javascript
const { getInputProps } = useSelect();
```

**What you did**:

Expecting that getInputProps is returned by useSelect(), like it is with the <Downshift /> ~HOC~ children render prop

**What happened**:

getInputProps isn't returned from useSelect()

**Suggested solution**:

getInputProps should be returned from useSelect()

**Comment by silviuavram** [comment]
Why do you expect that? `useSelect` is for a `<select>` there is no `input` in that element.

There is no HOC either, Downshift is a component that accepts a render prop.

**Comment by yunyu** [comment]
Sorry about the terminology mixup. That said, the role of a <select> is a purely semantic issue. Some implementations include typeahead support (such as in [react-select](https://react-select.com/home)), and currently it is impossible to build a typeahead-style select without using the render prop APi.

**Comment by silviuavram** [comment]
useSelect is used for a <select>
Downshift component is used for the combobox autocomplete. Can be used to create a <select> as well but you need do to a lot of stuff on the side.

select and autocomplete have enough differences (accessibility and functionality) to make me want to create separate hooks for each. useAutocomplete will join this library at some point.

the idea is that I want each hook to be used as out-of-the-box as possible. from my experience, developers have a hard time to meet accessibility requirements on their own, and having a straightforward solution that will provide not only that but also the functionality of the widget will make everyone happy.

**Comment by yunyu** [comment]
Ok, thanks a lot for explaining the roadmap. Should this issue be closed?
