### ISSUE TITLE
useSelect: make docz playgrounds work with codesandbox

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#809]
On https://downshift.netlify.com/hooks/use-select/usage https://downshift.netlify.com/hooks/use-select/variations the Docz Playgrounds should properly export the code to codesandbox.

Now it throws an error when `Open in Sandbox` button is clicked.

**Comment by EOstling** [comment]
@silviuavram is anybody working on this? If not I would like to :)

**Comment by silviuavram** [comment]
Go ahead! It will be awesome to have them working!

**Comment by EOstling** [comment]
Is there a way to test if my changes work locally?

**Comment by silviuavram** [comment]
Not sure, I did not dig into the docz very much. But we have netlify
deploys on PRs right? You can try through that I suppose.

**Comment by silviuaavram** [comment]
Not relevant anymore
