### ISSUE TITLE
clearSelection() trigger onSelect()

### ISSUE THREAD

**Issue by PoLuca** [downshift-js/downshift#820]
- `downshift` version: 3.2.6
- `node` version: v10.14.1
- `npm` (or `yarn`) version:6.4.1

**What you did**:
I use the `clearSelection()` function on input
`
onChange: (event) => {				
	if (event.target.value === "") {
		clearSelection();
	}										
}
`

**What happened**:
Downshift run `onSelect()` function

**Reproduction repository**: 

**Problem description**:
When i clear input with `clearSelection()`,  the `onSelect()` function was runned but the `selectedItem` param was null

**Suggested solution**:
in your downshift.js you should change line 363
`
 isItemSelected = newStateToSet.hasOwnProperty('selectedItem')
`
in
`
 isItemSelected = newStateToSet.hasOwnProperty('selectedItem') && newStateToSet.hasOwnProperty('selectedItem') !== null
`

**Comment by silviuavram** [comment]
I don't want to assume the value of items passed by the users, if he wants to select a null then why should I stop him?

Is this an issue that is breaking a use case for you? If so then we can think of another way to do it. Also a code sandbox is better to check for solutions.
