### ISSUE TITLE
useSelect: highlight by character keys not working when CapsLock is on

### ISSUE THREAD

**Issue by silviuavram** [downshift-js/downshift#825]
- `downshift` version: 3.4.1

**What you did**:
Open select that is using useSelect.
Have Caps on.
Try to highlight items using character keys.

**What happened**:

No item was highlighted. Items should be highlighted even with Caps on.

**Suggested solution**:

Probably keysSoFar should be saved as lowercased.

**Comment by weyert** [comment]
Yeah, looks like the reducer needs to be updated for this? I can have a look at it tomorrow

**Comment by silviuavram** [comment]
This should fix it https://github.com/downshift-js/downshift/pull/799/commits/61cfaf494b913d90b464580ed112b229ed9e2e60#diff-a14b8b714fa72386088b0720de667d7fR51
