### ISSUE TITLE
Menu does not close on itemClick if label-tag is wrapping a useSelect-hook component

### ISSUE THREAD

**Issue by NicolaiF** [downshift-js/downshift#835]
- `downshift` version: 3.4.2
- `node` version: 12.13.0
- `npm` (or `yarn`) version: 1.19.1

**Relevant code or config**
Here is the CodeSandbox with the issue reproduced: https://codesandbox.io/s/frosty-river-ey6e9?fontsize=14&hidenavigation=1&theme=dark

**Problem description:**
In my current project, labels are a wrapping component to possible components in need for a label. However, this leads to a bug where the menu is not closeable on item click. 
A console.log of the StateReducer shows that immediately after `__item_click__`, the toggle-button action `__togglebutton_click__` occurs.

**Comment by silviuavram** [comment]
I'm afraid this is a big no-go. Wrapping an element in a <label> will tie that element to the label. It's ok in the case of checkboxes, inputs or selects (native), but when wrapping a structure like ours, with list and items, it's going to break it. It won't act as a label only for the button (which is probably what we want) but for the whole list with items. Chaos!

We need to figure out another way to label our widget. Labels don't necessarily need to wrap an object.  There is <label for="labelled-element">, there is <input aria-labelledBy="label-element">, and these are actually used in `Downshift`.
