### ISSUE TITLE
Wrong ts typing of UseSelectProps.stateReducer

### ISSUE THREAD

**Issue by saitonakamura** [downshift-js/downshift#838]
- `downshift` version: 3.4.2
- `node` version: unrelated
- `npm` (or `yarn`) version: unrelated

**Relevant code or config**

```typescript
import { useSelect } from 'downshift'

useSelect({
  stateReducer: (state, actionAndChanges) => {
    return actionAndChanges.changes // Property 'changes' does not exist on type 'UseSelectStateChangeOptions<T>'
  }
}) 
```

**Problem description**:
Wrong typings

**Suggested solution**:
Fix the typings

**Comment by silviuavram** [comment]
Hi, is this the same issue as https://github.com/downshift-js/downshift/issues/836?

**Comment by saitonakamura** [comment]
No, it's separate one,  I'm also working on the fix, just decided to split the concerns

**Comment by silviuavram** [comment]
awesome, thanks! Will take a look at them soon. Are the typings for useSelect going to be fixed now? I remember merging a fix for them some time ago, thought that was enough.

**Comment by saitonakamura** [comment]
Well, I'm not entirely sure, cause this is just two places I happened to stumble upon, maybe there's more. I'm not too familiar with the codebase to make a clear statement.
