### ISSUE TITLE
useSelect hook ignores when `stateReducer` changes

### ISSUE THREAD

**Issue by anilanar** [downshift-js/downshift#849]
- `downshift` version: 3.4.7
- `node` version: 11.12.0
- `npm` (or `yarn`) version: 1.19.2

**Relevant code or config**

```javascript
const [ignore, setIgnore] = useState(false);

useSelect({
  ...
  stateReducer: useCallback((state, { type, changes }) => ignore ? state : changes, [ignore]),
});

useEffect(() => setTimeout(() => setIgnore(true), 1000), []);
```

**What you did**:
Basically, I have a `stateReducer` that behaves differently based on my own component's state/props.

**What happened**:
The new `stateReducer` is simply ignored.

**Problem description**:
`useCallback` in `useSelect`'s implementation is used wrong.

**Suggested solution**:
Apparently, `useSelect` is not linted by `eslint-plugin-react-hooks`; because `props.stateReducer` is not passed to the dependencies array in `useEnhancedReducer` function in `hooks/utils.js`.
The only suggestion I have is to use the hooks  linter and fix `useSelect` implementation accordingly. The linter will guide you through all mistakes/problems.

**Comment by silviuavram** [comment]
Hi, can we have a codesandbox with your issue? it may also be related to your `useCallback`.
