### ISSUE TITLE
please stop unpublishing versions

### ISSUE THREAD

**Issue by travi** [downshift-js/downshift#864]
we all recognize that publishing bad versions happens, but please don't unpublish. instead, it is much better to publish a new version that is a revert of the bad change. you can always mark the bad version as deprecated, but unpublishes break the builds of projects that have already pulled in the new version. even if you unpublish quickly, there are projects that have already pulled in the new version because of automated dependency management driven by webhooks that are fired as soon as the new version is published. if you publish a new version instead of unpublishing the bad one, those projects that are automated to that level will pull in the fix quickly instead of being left broken.

**Comment by silviuavram** [comment]
Sorry for the issues caused, I hope it won't happen again. And if it does will mark it as deprecated instead.

**Comment by travi** [comment]
thanks. like i said, totally understand bad things happening and the scramble to make them not bad anymore. just wanting to make the impact of unpublishing visible to hopefully encourage a revert and republish instead.

thanks for the work keeping the project moving forward.

**Comment by silviuavram** [comment]
Thank you for understanding and advice.

My intention was to release a breaking change, 4.0.0, but instead I got 3.5 and 3.6, and I think it was because when I squashed the PR, I had to overwrite the commit description with the PR description, so semantic release would pick up the BREAKING CHANGE: lines.

I kept the commit this time, and tomorrow will kick a manual release, this time with the BREAKING CHANGE: lines in the commit.

**Comment by travi** [comment]
yeah, rewriting history when merging does cause issues with semantic-release's ability to understand the changes. one of my biggest wishes on the github side is to have the ability to prevent history rewrites in a release branch and when merging that into master for the full release. i usually stay away from squashing, but have certainly caused myself issues by rebasing when merging in cases like this.

good luck with getting the release the rest of the way out there
