### ISSUE TITLE
[useSelect] Selecting an option does not close the menu

### ISSUE THREAD

**Issue by raunofreiberg** [downshift-js/downshift#880]
- `downshift` version: 4.0.0
- `node` version: n/a
- `npm` (or `yarn`) version: n/a

**Relevant code or config**

https://codesandbox.io/s/useselect-usage-mn1de (repo example)

**Problem description**:
When top-level wrapper element is `label`, selecting an option from the menu does not close the menu. Possibly because of the `label` triggering another re-open? 

**Suggested solution**:
Not sure if this is incorrect usage of `useSelect`, but semantically it should be correct to wrap the elements with a `label`.

**Comment by silviuavram** [comment]
You are wrapping the whole HTML in a label (button, span, list, items), so semantically that's not correct.

We assume that you will use the label separately that is why we are linking it with the toggle button using `htmlFor`. But if you want to wrap it, then only wrap the button in a label, like this.

```jsx
    <div>
      <label {...getLabelProps()}>Choose an element:
        <button {...getToggleButtonProps()}>
          {selectedItem || "Elements"}
        </button>
      </label>
      <ul {...getMenuProps()} style={menuStyles}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              {...getItemProps({ item, index })}
            >
              {item}
            </li>
          ))}
      </ul>
    </div>
```
