### ISSUE TITLE
[useCombobox] clicking an item won't trigger custom stateReducer

### ISSUE THREAD

**Issue by jorgemoya** [downshift-js/downshift#881]
- `downshift` version: 4.0.2
- `node` version: 10.17.0
- `npm` (or `yarn`) version: 1.19.1

**Relevant code or config**

```javascript
  // is not called when an item is clicked
  function handleStateReducer(
    state,
    actionAndChanges,
  ) {
    console.log(actionAndChanges.type); 

    return actionAndChanges.changes;
    }
  }
```

**What you did**:

I'm using the Combobox hook and was expecting clicking an item to call my custom `stateReducer` with an action of `type === __item_click__` like it does in `useState`.

**What happened**:

Clicking on an item selects the item but the custom `stateReducer` isn't called. All other actions seem to work fine.

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-u772l

**Problem description**:

Custom `stateReducer` is not being called when an item is clicked.

**Suggested solution**:

Call custom `stateReducer` when an item is clicked.

**Comment by silviuavram** [comment]
I found what the issue is and will create a fix. Managing focus is sometimes a pain. We probably need to do the same technique as in `downshift.js` with `targetWithinDownshift`.

**Comment by jorgemoya** [comment]
I also noticed custom `onClick` won't trigger if bound to an `item`. I'm wondering if this is related.

**Comment by silviuavram** [comment]
Created a PR with the fix, maybe you can check the `onClick` scenario as I did not check it so far, I am writing unit tests for the fix. Thanks!

**Comment by jorgemoya** [comment]
@silviuavram Can confirm that the `onClick` bug is also fixed.

**Comment by silviuavram** [comment]
Sweet. Added a docs section for `useCombobox` and `stateReducer` as well. Will merge it once the tests pass. Thanks for the help, it was a great catch!
