### ISSUE TITLE
ItemClick action is not triggered in StateReducer with useCombobox hook

### ISSUE THREAD

**Issue by matyushen** [downshift-js/downshift#884]
- `downshift` version: 4.0.0
- `node` version: codesandbox
- `npm` (or `yarn`) version: codesandbox

**Relevant code or config**

```javascript
function stateReducer(state, actionAndChanges) {
  switch (actionAndChanges.type) {
    case useCombobox.stateChangeTypes.InputKeyDownEnter:
        console.log("InputKeyDownEnter");
        return actionAndChanges.changes;
    case useCombobox.stateChangeTypes.ItemClick: 
      console.log("ItemClick"); // This will never be logged
      return actionAndChanges.changes;
    default:
      return actionAndChanges.changes;
  }
}
```

Another test reducer shows that `__item_click__` action type will never be logged on item click

```javascript
function stateReducer(state, actionAndChanges) {
  console.log(actionAndChanges.type);
  return actionAndChanges.changes;
}
```

**What you did**:
I tried to use `stateReducer` with `useCombobox` hook to prevent the input field's value from changing when an item is selected. It's a custom use case where I want the input field to not change when an item is selected.

**What happened**:
Custom reducers' `useCombobox.stateChangeTypes.ItemClick` never fires when an item is clicked. While the `InputKeyDownEnter` action workes fine.

**Reproduction repository**: https://codesandbox.io/s/usecombobox-usage-1rf28

**Problem description**: `ItemClick` action in `stateReduces` doesn't fire. There's probably a mismatch somewhere. The action obviously triggers, because the item selection works properly. But it can't be overridden in a custom reducer. 

**Suggested solution**: I scanned the code but couldn't find anything. Any suggestions will be highly appreciated!

**Comment by jorgemoya** [comment]
Same issue as #881
