### ISSUE TITLE
FindDomNode will be deprecated.

### ISSUE THREAD

**Issue by rajzik** [downshift-js/downshift#909]
- `downshift` version: 4.0.7
- `node` version: 13.7.0
- `npm` (or `yarn`) version: 6.13.6

**Relevant code or config**

```javascript
<React.StrictMode>
  <Downshift>
     { /* any implementation. */ }
  </Downshift>
</React.StrictMode>
```

**Problem description**:

React will warn you about the deprecation of findDomNode. Is it possible to stop using it?

**Comment by silviuavram** [comment]
It makes sense, we will take a look and try to fix all deprecated mentions. Thanks!

**Comment by silviuaavram** [comment]
Hmm I don't see any `findDomNode` in our code.🧐

**Comment by rajzik** [comment]
@silviuaavram my bad, there was an issue with strict mode logger, it was pointing at downshift but it was caused by material-ui. Sorry about that.
