### ISSUE TITLE
TypeScript and StateChangeTypes

### ISSUE THREAD

**Issue by StanBright** [downshift-js/downshift#918]
- `downshift` version: 4.0.8
- `node` version: v13.6.0
- `npm` (or `yarn`) version: 6.13.4
- `typescript`: 3.7.5

**Relevant code or config**

```javascript
const ignoreStateReducerChanges = (changes: StateChangeOptions<string>) => {
  return changes.type === StateChangeTypes.blurInput
}
```

**What you did**:

Added some logic in a `stateReducer` function that depends on the supplied `changes.type`.

**What happened**:

App works in development and do NOT in production.

**Problem description**:

When using TypeScript and the relevant `StateChangeTypes` enum, the values
are strings. Then, when compiled in production, the compiled application code will still depend on the same enum strings. However, production downshift code depends on `productionEnum.macro.js` that will use numbers for StateChangeTypes. 

**Suggested solution**:

Do not use `NUMBER`s in `productionEnum.macro.js` when generating production enums.

**Comment by StanBright** [comment]
Hey @kentcdodds, @alexandernanberg do you guys think there's an option not to use numbers for the enums here https://github.com/downshift-js/downshift/blame/446958e8fc78b2831d911d6fce4a93e067d887ee/src/productionEnum.macro.js#L15? 

As described in the issue above, the use of numbers seems a showstopper for TypeScript users.

**Comment by silviuavram** [comment]
For us in FluentUI it's working:

```tsx
  getHighlightedIndexOnArrowKeyOpen = (
    changes: StateChangeOptions<ShorthandValue<DropdownItemProps>>,
  ): number => {
    const isArrowUp = changes.type === Downshift.stateChangeTypes.keyDownArrowUp
    const isArrowDown = changes.type === Downshift.stateChangeTypes.keyDownArrowDown
    ....
```

**Comment by StanBright** [comment]
@silviuavram thanks mate, this seems like an interesting case. If I'm not wrong, it's working for you, as you are using `Downshift.stateChangeTypes` directly, and that is "statically" defined in the sources. There is no TypeScript "compilation" happening in production in this context.

However, I bet that if you try using the TS enum directly, it will not work in production. You can try it yourself. 

```javascript
// here => importing the enum from supplied typings (that get compiled to strings. always)
import { StateChangeTypes } from 'downshift'

  getHighlightedIndexOnArrowKeyOpen = (
    changes: StateChangeOptions<ShorthandValue<DropdownItemProps>>,
  ): number => {
   // changes.type will be an integer in production VS a string for `StateChangeTypes.keyDownArrowUp`
    const isArrowUp = changes.type === StateChangeTypes.keyDownArrowUp
    const isArrowDown = changes.type === StateChangeTypes.keyDownArrowDown
    ...
```

**Comment by silviuavram** [comment]
Yeah, that makes sense, but we should use these change types in TS like in JS. We have the TS types just to help us out with the `changes` param (like in the example above). We probably will keep all of this as it is, unless the original creators have better ideas. Thank you for your input!

**Comment by StanBright** [comment]
I think that the nature of TS Enums (when compiled to JS) cannot be compatible with the quirky use of `Downshift.stateChangeTypes` that is different in dev and prod.

I'd suggest advising TS users that they **can't and should not use** `StateChangeTypes`. Something like a compatibility notice. For example, I lost several hours debugging this, and it'd be good to prevent that happening to others. Giving the raising adoption of TS.

**Comment by StanBright** [comment]
@silviuaavram, I'm not following every commit. Should we understand that this issue is fixed given that it is being closed? 

p.s. thanks for taking care of it!

**Comment by akinnee** [comment]
This confused me for a bit as well. What's the benefit of making the values different depending on NODE_ENV? Both values end up in `dist` anyway, so it doesn't save space.
