### ISSUE TITLE
onSelectedItemChange not called on reset

### ISSUE THREAD

**Issue by stramel** [downshift-js/downshift#920]
- `downshift` version: `^4.0.7`
- `node` version: `12.13.0`
- `npm` (or `yarn`) version: `^1.21.1`

```
// NOTE: Simplified for effect
{() => {
  const [value, setValue] = useState()
  return <Select selectedItem={value} onSelectedItemChange(setValue} items={[]} />
}}

// ....

const Select = (props) => {
  const { reset, ... } = useSelect(props)
  
  return (
    <>
      <button onClick={reset}>Reset</button>
      // ...
    </>
  )
}
```

**What you did**: Called `reset` from a button click, I expected my `onSelectedItemChange` handler to be called.

**What happened**: `onSelectedItemChange` was not called. This breaks my controlled component.

**Problem description**: A controlled `useSelect` implementation where I use `reset`, it doesn't call the `onSelectedItemChange` handler so the `selectedItem` never resets.

**Suggested solution**: Call `onSelectedItemChange` handler on `reset`. 

Currently, I'm working around this by doing, 

```
const resetSelectedItem = () => {
  if (onSelectedItemChange) onSelectedItemChange(undefined)
  reset()
}
```

**Comment by mufasa71** [comment]
@stramel I can't reproduce this anymore with 4.0.8 https://codesandbox.io/s/frosty-river-squc2

**Comment by stramel** [comment]
@mufasa71 I'm still running into issues. Seeing some strange things happening in my setup.

I will try to get a CSB to reproduce the errors. Right now CSB is currently not working correctly.

**Comment by stramel** [comment]
@mufasa71 Seems CSB is working now. https://codesandbox.io/s/focused-bird-xjz05

There are 2 errors that I'm noticing:

1. Clicking "reset" does not actually reset the controlled select.
2. After focusing the select, pressing a key (ie. "b") the state changes to "banana" but then immediately reverts to "apple"

**Comment by mufasa71** [comment]
@stramel Now i am able to reproduce it
1. I think this is expected behavior, `defaultSelectedValue` should be null or some item, but you pass undefined, when i change it to null it works as expected, but may be i miss something
2. Looks like a bug, i will investigate more later

**Comment by stramel** [comment]
@mufasa71 you're correct. Using `null` for `defaultValue` does work. This feels like a strange API choice since not passing it would be the same as `undefined`.  I will use `defaultValue ?? null` for now. 

Would you like me to file a separate issue for the other bug?

**Comment by mufasa71** [comment]
@stramel Yes please create separate issue for case 2. I will try to fix it. Thanks
