### ISSUE TITLE
[useSelect]: Controlled Select reverts state on keypress

### ISSUE THREAD

**Issue by stramel** [downshift-js/downshift#922]
- `downshift` version: 4.0.8
- `node` version: 12.13.0
- `npm` (or `yarn`) version: 1.21.1

**What you did**:

Created a controlled Select based on `useSelect`.

**Reproduction repository**:

https://codesandbox.io/s/laughing-wu-r1wuq

**Problem description**:

After focusing the select, pressing a key (ie. "b") the state changes to "banana" but then immediately reverts to "apple"

Broke out this from #920 

/cc @mufasa71

**Comment by silviuavram** [comment]
Hi. Can you take a look at the sandbox again I think you have a bug there.

And as far as the question is concerned, isn't this expected? If you control the selectedItem and pass it 'apple', then of course it's going to show 'apple'.

**Comment by mufasa71** [comment]
@silviuavram Do you mean case 1 or case 2?

**Comment by silviuavram** [comment]
Then maybe I did not understand the issue sorry. Probably all the logic of controlled prop/default/onChange is not 100% working for all cases but we should get there step by step.

I will look at the PR you sent @mufasa71

**Comment by stramel** [comment]
@silviuavram What bug are you referring to? 

In #920, my issue was that the `reset` wasn't reverting. @mufasa71 explained that I needed to use `null` for `defaultSelectedItem` instead of `undefined`. (https://codesandbox.io/s/focused-bird-xjz05)

In this issue, the `selectedItem` reverts after pressing a key. For instance in my CSB: "apple" is selected when it loads. If you then focus the Select and press the letter "b" to select "banana", it selects the item but then reverts back to "apple".

**Comment by stramel** [comment]
@silviuavram @mufasa71 This doesn't seem to fix the issue. Tried upgrading both locally and on CSB, both fail. 

Updated to 4.0.10 https://codesandbox.io/s/laughing-wu-r1wuq

**Comment by mufasa71** [comment]
@stramel https://codesandbox.io/s/thirsty-ishizaka-emxlz
I checked and for me it works, when i start to type words it highlights correct one. Pressing enter selects correct value for me. Can you check again?

**Comment by stramel** [comment]
@mufasa71 That's strange. I definitely did the update last time and it didn't work. But it did this time both locally and in CSB. Thank you for your help!
