### ISSUE TITLE
[useSelect] calls onSelectedItemChange on every event when selectedItem is passed in and not memoized

### ISSUE THREAD

**Issue by TLadd** [downshift-js/downshift#927]
- `downshift` version: 4.0.8 - 4.0.10
- `node` version: 10.16.3
- `npm` (or `yarn`) version: yarn 1.21.3

**Relevant code or config**

```javascript
import React from "react";
import { render } from "react-dom";
import { useSelect } from "downshift";
import { menuStyles } from "./utils";

function DropdownSelect() {
  const [value, setValue] = React.useState(1);

  const items = [
    { label: "Neptunium", value: 1 },
    { label: "Plutonium", value: 2 },
    { label: "Americium", value: 3 }
  ];

  const selectedItem = items.find(item => item.value === value);

  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps
  } = useSelect({
    items,
    onSelectedItemChange: changes => {
      console.log("CALLING onSelectedItemChange", changes);
      if (changes && changes.selectedItem) {
        setValue(changes.selectedItem.value);
      }
    },
    selectedItem
  });
  return (
    <div>
      <label {...getLabelProps()}>Choose an element:</label>
      <button {...getToggleButtonProps()}>
        {selectedItem.label || "Elements"}
      </button>
      <ul {...getMenuProps()} style={menuStyles}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item.value}${index}`}
              {...getItemProps({ item, index })}
            >
              {item.label}
            </li>
          ))}
      </ul>
      {/* if you Tab from menu, focus goes on button, and it shouldn't. only happens here. */}
      <div tabIndex="0" />
    </div>
  );
}

render(<DropdownSelect />, document.getElementById("root"));
```

**What you did**:
Running the above, open the menu, arrow key around. 

**What happened**:

Observe that `CALLING onSelectedItemChange` gets logged every render.

**Reproduction repository**:

https://codesandbox.io/s/useselect-usage-8txzh

**Problem description**:

From 4.0.7 to 4.0.8, `onSelectedItemChange` started being called every render if selectedItem is passed in. It looks like it has to do with the selectedItem changing references, since if I move the `items` declaration outside of the component body, it no longer occurs. i.e. this does not result in all of the `onSelectedItemChange` calls:

```javascript
import React from "react";
import { render } from "react-dom";
import { useSelect } from "downshift";
import { menuStyles } from "./utils";

const items = [
  { label: "Neptunium", value: 1 },
  { label: "Plutonium", value: 2 },
  { label: "Americium", value: 3 }
];

function DropdownSelect() {
  const [value, setValue] = React.useState(1);
  const selectedItem = items.find(item => item.value === value);

  const {
    isOpen,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps
  } = useSelect({
    items,
    onSelectedItemChange: changes => {
      console.log("CALLING onSelectedItemChange", changes);
      if (changes && changes.selectedItem) {
        setValue(changes.selectedItem.value);
      }
    },
    selectedItem
  });
  return (
    <div>
      <label {...getLabelProps()}>Choose an element:</label>
      <button {...getToggleButtonProps()}>
        {selectedItem.label || "Elements"}
      </button>
      <ul {...getMenuProps()} style={menuStyles}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item.value}${index}`}
              {...getItemProps({ item, index })}
            >
              {item.label}
            </li>
          ))}
      </ul>
      {/* if you Tab from menu, focus goes on button, and it shouldn't. only happens here. */}
      <div tabIndex="0" />
    </div>
  );
}

render(<DropdownSelect />, document.getElementById("root"));
```

**Suggested solution**:

Not sure yet. You can get around this in userland by using useRef to ensure your items (and therefor selectedItem) don't change references. The previous behavior was a bit friendlier though, since you didn't have to worry about it. I assume this is also related to moving the callOnChangeProps into `useEffect`.

**Comment by silviuavram** [comment]
Do you think that reverting 4.0.8 useEffect and figuring out another fix
for that will help?

**Comment by TLadd** [comment]
I'm not sure. Moving the call to `callOnChangeProps` into a `useEffect` seemed like the proper fix to me since the effects needed to be run outside of render. I'm not quite sure how else those warnings could be fixed, but maybe there is a way. This is an unintended change of behavior as a result of that change though. For me, the current behavior (calling `onSelectedItemChange` on every render) is worse than the previous behavior (a warning when used in conjunction with some libraries),so  we could revert until we can figure out either

- a way to fix this issue while still using useEffect
- another way to address the warning

That way people are free to upgrade, although the warning for some may come back if that is a bigger issue for them. This behavior was bad for me where I'm using the onChange of a select to trigger a network request. Currently, I'm pinned on 4.0.7 and I use the following workaround to prevent the warning:

```
  const { push } = useHistory();
  const [selected, setSelected] = useState();
  const items = ["/about", "/users", "/"];
  const {
    getToggleButtonProps,
    isOpen,
    getMenuProps,
    getItemProps
  } = useSelect({
    onSelectedItemChange: changes => {
      setSelected(changes.selectedItem);
    },
    items
  });

  useEffect(() => {
    if (selected) push(selected)
  }, [selected, push])
```

So internally in Downshift, everything works as it did before, but I'm ensuring the side effect doesn't get run until after render by using the intermediary `selected` state and trigger an effect on that value changing.

So all that to say, my personal preference would be to revert https://github.com/downshift-js/downshift/pull/912 until we can come up with a fix for that and this issue. @mufasa71, you might be interested in this discussion.

**Comment by silviuavram** [comment]
I will probably do that tomorrow, I prefer to live with a warning for now rather than having broken behavior.

Will re-open the warning issue and will also add a few unit tests. Maybe you guys can help me figure out all the relevant test cases around this controlled + onChange + default/initial props. I have added tests for some scenarios in useSelect / useCombobox props suite but we are still exposed.

**Comment by mufasa71** [comment]
@TLadd IMO this is expected behavior, you moved `selectedItem` into controlled property and re-create new reference to `selectedItem` each time

```
const items = [{ label: "Neptunium", value: 1 }] // on each render new array
const selectedItem = items.find(item => item.value === value) // new reference to selectedItem calls onSelectedItemChange
```
moving `items` out of render solved the issue.

@silviuavram now the question, what is desired and how we should treat such cases?

**Comment by silviuavram** [comment]
Clearly I don't like it how it behaves since 4.0.8. I am trying https://downshift.netlify.com/hooks/use-select#controlling-state in the codesandbox. I added a console log in the onSelectedItemChange from useSelect. I am selecting an item with 'C', so I am updating the selected item.

With the controlled selectedItem, I am performing another selection that does not update the controlled selected item (item that does not start with C). onSelectedItemChange called with that selection, everything fine, my controlled item does not change. When I re-open the dropdown however, I get a random onSelectedItemChange with the item that I am controlling.

This is not what I am expecting and did not occur before 4.0.8. The issue @TLadd is discussing is probably also related to this one I am describing. I am still in favour of reverting these changes and ask for a better fix of the warning. At least I am sure that the controlled props logic works.

**Comment by TLadd** [comment]
@mufasa71 One could certainly consider it expected behavior depending on their definition of an item changing. Strictly speaking, the items and the selectedItem are changing every render, so it makes sense to call onSelectedItemChange in that sense. The problem is that this isn't what the library considered a change prior to this version, so that's a breaking change that would only be appropriate in a major version. 

As to what should be the expected behavior, the way it works in 4.0.7 is a bit more friendly, so it would be my preference. Although it's easy to move the items out of render in this case and maintain referential equality, items will oftentimes be dynamically loaded from a server and then it will be necessary to store the items using useRef (or perhaps useMemo but it doesn't guarantee referential equality like useRef does). It's asking a bit more of users to manage this, so maintaining the old behavior would be ideal in my opinion.

**Comment by silviuavram** [comment]
I reverted it. I will talk to @layershifter from my team and I am confident we will get a that warning fixed as well. Thank everyone!

**Comment by mufasa71** [comment]
@TLadd Yes this part is confusing for me, I believe not only me :) . I expect `onSelectedItemChange` to be called every time `selectedItem` change both controlled and uncontrolled version. But yeah if its breaking changes its better to revert commits of course.
