### ISSUE TITLE
[useSelect]: keypress on toggle button selecting disabled items

### ISSUE THREAD

**Issue by stramel** [downshift-js/downshift#936]
- `downshift` version: 4.1.0
- `node` version: 12.13.0
- `npm` (or `yarn`) version: `yarn` 1.21.1

**Relevant code or config**

```
{isOpen && (
	<ul {...getMenuProps()}>
    	{items.map((item, index) => {
        	return (
            	<li
                  key={index}
                  {...getItemProps({ item, index, disabled: item.disabled })}
                >
                  {itemToString(item)}
                </li>
            );
        })}
    </ul>
)}
```

```
<Select
	defaultSelectedItem={{ name: "banana" }}
    selectedItem={value}
    onSelectedItemChange={({ selectedItem }) => setValue(selectedItem)}
    items={[
    	{ name: "apple" },
        { name: "banana" },
        { name: "cherry" },
        { name: "grape", disabled: true },
        { name: "orange" }
    ]}
/>
```

**What you did**:

Set the item to `disabled` to prevent selection.

**What happened**:

When focusing the toggle button AND menu is closed and pressing the character of a disabled item, it allows selection.

**Reproduction repository**:

https://codesandbox.io/s/nice-wright-87xuo

**Problem description**:

Disabled items are able to be selected using the character keypress on toggle button.

**Suggested solution**:

Prevent this behavior 😛

**Comment by silviuavram** [comment]
Indeed, this is a hole I am aware of and I don't know how to fix it and keep current `disabled` API. We are passing the `disabled` prop on each item, but this means the menu has to be opened for that.

You can work around this by having your own disabled logic and checking with `stateReducer` if you are selecting item by `useSelect.stateChangeTypes.ToggleButtonKeyDownCharacter` action type. If your logic says it's disabled, then don't return the `selectedItem`.
