### ISSUE TITLE
Control isOpen on hover

### ISSUE THREAD

**Issue by TerrySlack** [downshift-js/downshift#939]
- `downshift` version: ^3.2.10
- `node` version: 13.6.0
- `npm` (or `yarn`) version: yarn 1.21.1

**Problem description**:
Is it possible to open and close the downshift menu on hover?  I cannot seem to find a solution for this.

**Comment by silviuavram** [comment]
There is a setIsOpen callback given to you by Downshift, you can use that
in your onHover. Depending if you have a select or a combobox, maybe you
can also give the hooks a try 👍

**Comment by silviuavram** [comment]
Oups my bad, the method you are looking for is openMenu. Sorry about that.

**Comment by TerrySlack** [comment]
I did actually find them shortly after posting.  Currently, I have the menu opening, on hover, using onMouseEnter being passed into getToggleButtonProps.
And within the callback for onMouseEnter, I use openMenu.

However, how would I then put an onMouseLeave on the displayed menu itself?  So the menu opens on hovering an icon, and I'd like it to close if my the mouse is not hovering over it.

I'm not sure which method to call, on the menu itself, like I used with getToggleButtonProps.
Is it getRootProps()?  And if so, would you be able to provide an example of its use?

**Comment by silviuavram** [comment]
There is also `getMenuProps` and you can add any other listener there as well. However be careful when you blur with keyboard for instance, as you need to control that scenario as well.

The behavior you want is not really standard, so you need to cover all the custom scenarios yourself. Good luck! Let us know how it goes.

**Comment by TerrySlack** [comment]
I'm not sure this is an unusual case.  I want the menu to open on hover of an icon, instead of click and close when the menu itself loses focus, not the icon.  That make sense?
Thanks for the feedback.  Everything works as expected.  My one wish is that the documentation had examples for each thing it explains.  And where can I find docs on using hooks?

**Comment by silviuavram** [comment]
We can probably create an example in the docsite. https://downshift.netlify.com/
