### ISSUE TITLE
[useSelect] when passing selectedItem as prop it does not update from choosing in dropdown

### ISSUE THREAD

**Issue by supersabillon** [downshift-js/downshift#940]
- `downshift` version: 5.0.0
- `node` version: 8.15
- `npm` (or `yarn`) version: 6.11.3

**Relevant code or config**

```javascript
function DropdownSelect(props) {
  const itemToString = option => option.label;
  const {
    isOpen,
    selectedItem,
    getToggleButtonProps,
    getLabelProps,
    getMenuProps,
    highlightedIndex,
    getItemProps
  } = useSelect({
    itemToString,
    items,
    selectedItem: props.selectedItem
  });
  return (
    <div>
      <label {...getLabelProps()}>Choose an element:</label>
      <button {...getToggleButtonProps()}>
        {selectedItem ? itemToString(selectedItem) : "Select Month..."}
      </button>
      <ul {...getMenuProps()} style={menuStyles}>
        {isOpen &&
          items.map((item, index) => (
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              {...getItemProps({ item, index })}
            >
              {item.label}
            </li>
          ))}
      </ul>
      {/* if you Tab from menu, focus goes on button, and it shouldn't. only happens here. */}
      <div tabIndex="0" />
    </div>
  );
}

function ParentApp() {
  const [value, setValue] = useState();
  return (
    <div>
      <button onClick={() => setValue({ label: "December", value: "december" })}>
        Set Value to December
      </button>
      <DropdownSelect selectedItem={value} />
    </div>
  );
}

```

**What you did**: 
Tried to change selected item from a parent component, and then tried to update from dropdown menu.

**What happened**:
It updates selectedItem but choosing from dropdown doesn't update.

**Reproduction repository**:
https://codesandbox.io/s/useselect-usage-t1i2y?fontsize=14&hidenavigation=1&theme=dark

**Problem description**:

**Suggested solution**:

**Comment by silviuavram** [comment]
Can you update to 4.0.10, 4.1.0 or 5.0.0 and see if it still reproduces? Thanks!

**Comment by supersabillon** [comment]
> Can you update to 4.0.10, 4.1.0 or 5.0.0 and see if it still reproduces? Thanks!

just upgraded, also in the example as well: https://codesandbox.io/s/useselect-usage-t1i2y?fontsize=14&hidenavigation=1&theme=dark

still seeing the issue. I see its probably because Im setting selected item like this:
```
useSelect({
    itemToString,
    items,
    selectedItem: props.selectedItem
  })
```
but im not sure of a better way to control the componet from a different component, while still having the Select component work as expected

**Comment by mufasa71** [comment]
I think you need also implement `onSelectedItemChange` and `setValue` inside it. Hope it helps

**Comment by supersabillon** [comment]
> I think you need also implement `onSelectedItemChange` and `setValue` inside it. Hope it helps

hello @mufasa71, which prop provides the `setValue` func? couldn't find it in the docs,  I tried using `selectItem` but i'm getting "too many re-renders" error

```js
    onSelectedItemChange: (changes) => {
      selectItem(changes.selectedItem)
    }
```

**Comment by mufasa71** [comment]
@supersabillon yours `setValue`

```
useSelect({
  selectedItem: value,
  onSelectedItemChange: ({ selectedItem }) => {
    setValue(selectedItem)
  }
})
```

**Comment by silviuaavram** [comment]
Will consider this as closed. Thanks for replying!
