### ISSUE TITLE
[useCombobx] Attaching `openMenu` to input's `onFocus` won't open menu when toggle is clicked

### ISSUE THREAD

**Issue by jorgemoya** [downshift-js/downshift#941]
- `downshift` version: 5.0.0
- `node` version: 10.17.0
- `yarn` version: 1.19.1

**Relevant code or config**

```javascript
<Input
  {...getInputProps({
    onFocus: openMenu,
  })}
/>
```

**What you did**:

Attach `openMenu` to my input's `onFocus`.

**What happened**:

Menu won't open if toggle button is clicked.

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-z0j3d

**Problem description**:

Menu opens when input is directly focused but not when the toggle button is clicked. Only found the issue with `openMenu` so far.

**Comment by jorgemoya** [comment]
I've narrowed down the issue: 

When clicking on the `toggle button` I get the following two action types in this order: `__function_open_menu__` followed by `__togglebutton_click__`. I would kind of expect `__togglebutton_click__` to run first.

The reason why the menu doesn't open is because of:

https://github.com/downshift-js/downshift/blob/master/src/hooks/useCombobox/reducer.js#L135.

`isOpen` gets toggled to `false`.

**Comment by silviuavram** [comment]
Nice catch! Thank you for the PR. Can we unit-test this so we will not run into similar issues in the future?

Maybe we can add unit tests for all getter functions, in the hooks test suite, after the preventDownshift ones. Make sure that the downshift behavior occurs before user behavior.

What do you think?

**Comment by silviuavram** [comment]
Will keep this open for now.

**Comment by jorgemoya** [comment]
Will take a look at the unit tests.
