### ISSUE TITLE
Any way to interact with downshift from outside React?

### ISSUE THREAD

**Issue by e-gaulue** [downshift-js/downshift#943]
Dear community,

We've got an HTML page with forms and our own data. In this page we call a React page application that goes in an iframe. We have no way to access or modify this React code that show several downshift controlled input boxes. But we have access to our code.

From our code we tried to change the value of the downshift input generated by React. The shown input value is right in the input but we don't manage to "submit" it.

`iFramedocument.getElementById("test-downshift-input").value = "New value";`

Is there a trick we can do?

**Comment by silviuavram** [comment]
I am not sure how. Downshift lets you access and change its state but you said you have no control of what happens in that code. And tricks like DOM manipulation will not work, as Downshift will keep track of state internally.

**Comment by e-gaulue** [comment]
That's what I though about it. I tried trigger `change` or `blur` but without success.

Our React third party application is like a complex calculator, you give it inputs and it gives a result. We have no trouble getting the result with javascript code from the main page, but for the moment users have to answer forms (with select and input boxes), that give a first result, then they have to copy/paste those results in the React part. We just wanted to avoid that.

I didn't look if I could find a way to access a kind of Downshift instance object from window (little bit like ref). If possible, maybe from there, I could then setState.

**Comment by silviuavram** [comment]
I still don't know how to tackle this use case, it's pretty difficult without any code sandbox / example :(
