### ISSUE TITLE
Add custom onClick to a Combobox Item

### ISSUE THREAD

**Issue by ncesar** [downshift-js/downshift#947]
- `downshift` version: 5.0.0
- `node` version: latest
- `npm` (or `yarn`) version: latest

**Relevant code or config**
https://codesandbox.io/s/usecombobox-usage-urhsi
To reproduce, just add an onClick with a simple console.log to a ```li``` and it won't trigger when clicking on an item.

**What you did**: I tried to add an onClick event to a combobox item

**What happened**: The onClick is not being called

**Reproduction repository**: https://codesandbox.io/s/usecombobox-usage-urhsi

```
const onClick = () => console.log('oi');
            <li
              style={
                highlightedIndex === index ? { backgroundColor: "#bde4ff" } : {}
              }
              key={`${item}${index}`}
              onClick={onClick}
              {...getItemProps({ item, index })}
            >
```
If I try to create the onClick above ```...getItemProps``` it wont work. But if I move the onClick below ```...getItemProps```, the onClick is called but the combobox itself will not work properly.

**Comment by silviuavram** [comment]
Ciao! You are getting your onClick overriden by the one returned by `getItemProps`, there are details about how to use in the [documentation](https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox#event-handlers).

**Comment by ncesar** [comment]
Sorry for not looking enough, thank for your time and commitment here <3

**Comment by Noorullah-Ahmadzai** [comment]
@ncesar  @silviuaavram 
Thank You so much guys! This help me out!
