### ISSUE TITLE
Docs and Readme refresh

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#948]
Will add this item for tracking, as I am looking to do some changes to the docsite. The list so far is:

- check optional properties of getter functions and add stuff like `ref` with explanation.
- add similar examples for `useCombobox` as in `useSelect` in the docsite.
- Re-write the beginning of the Readme to better explain what Downshift is (component, hooks).

**Comment by 779g** [comment]
Would it be possible to update codesanbox example for useMultipleSelection ? Thanks

**Comment by silviuaavram** [comment]
@779g updated with newest alpha.
