### ISSUE TITLE
[Question/Request - useCombobox] Is there a way to make part of the value appear(autocomplete) in the input?

### ISSUE THREAD

**Issue by ncesar** [downshift-js/downshift#950]
I'm sorry if the title isn't clear enough, I wasn't sure how to ask or call this function.
What I trying to do is a behavior like this:
![image](https://user-images.githubusercontent.com/29064514/74864007-95cb8c00-532d-11ea-82aa-ff3e8e3c4761.png)
If I type "_Co_", the input will suggest the rest. Is there any way to do this? I read the docs but found nothing.

- `downshift` version: latest
- `node` version: latest
- `npm` (or `yarn`) version: latest

**Comment by silviuavram** [comment]
We don’t support that but if you go through the issues there is a ticket
for this task, so we are tracking it. Nobody picked it up yet so it
probably will not land in the next month, but maybe later.
