### ISSUE TITLE
[hooks]: Suggestion: keep dropdown open when clicking outside the document

### ISSUE THREAD

**Issue by jorgemoya** [downshift-js/downshift#955]
- `downshift` version: 5.0.3

I'm trying to debug an element inside the select and can't do it when trying to inspect it because it detects my click on chrome tools and closes the dropdown. I'm sure there are other reasons of why it would be expected for the dropdown to remain open.

Was wondering if this is an expected and deliberate behavior or if is something that we want to change?

**Comment by silviuavram** [comment]
You can try 2 things:
- keep `isOpen` true via controlled prop.
- in DevTools, Elements, right-click on the menu element, Break On, and then make it break on whatever you feel it's relevant there. You should be able to tweak it in order to trigger breakpoint with the menu open :)

**Comment by EddyVinck** [comment]
I am running into this as well. I tried using `onsStateChange` but without success.

```js
  const { getDropdownProps, addSelectedItem, removeSelectedItem, selectedItems } = useMultipleSelection({
    initialSelectedItems: [items[0]]
  });
  const { isOpen /* , ...other properties */ } = useSelect({
    items,
    onStateChange(changes) {
      switch (changes.type) {
        case useSelect.stateChangeTypes.ItemClick:
          return {
            ...changes,
            isOpen: true
          };
        default:
          return changes;
      }
    }
  });
```

The thing is, the `ItemClick` is actually running and thus returning the state, but it seems it still gets overridden somewhere. I haven't used this library a lot in the past, but this is the first time I'm using the hooks and I am a little confused as to why this isn't working.

<details>
<summary>full code here</summary>

```jsx
import React from 'react';
import { useSelect, useMultipleSelection } from 'downshift';

export const MultiSelect = ({ items, label = 'Choose an environment', children }) => {
  const { getDropdownProps, addSelectedItem, removeSelectedItem, selectedItems } = useMultipleSelection({
    initialSelectedItems: [items[0]]
  });
  const { isOpen, getToggleButtonProps, getLabelProps, getMenuProps, highlightedIndex, getItemProps } = useSelect({
    items,
    onStateChange(changes) {
      switch (changes.type) {
        case useSelect.stateChangeTypes.ItemClick:
          return {
            ...changes,
            isOpen: true
          };
        default:
          return changes;
      }
    }
  });

  return (
    <Box>
      <Label mb="sm" {...getLabelProps()}>
        {label}
      </Label>
      <Button {...getToggleButtonProps(getDropdownProps({ preventKeyAction: isOpen }))}>{children}</Button>
      <List {...getMenuProps()} position="absolute" bg="black" css={{ zIndex: 3 }}>
        {isOpen &&
          items.map((item, index) => (
            <ListItem              
              key={`${item}`}
              {...getItemProps({
                item,
                index,
                onClick() {
                  if (selectedItems.includes(item)) {
                    return removeSelectedItem(item);
                  }
                  addSelectedItem(item);
                }
              })}
            >
              {item}
              <Checkbox readOnly checked={selectedItems.includes(item)} />
            </ListItem>
          ))}
      </List>
    </Box>
  );
};
```

</details>

**Comment by silviuaavram** [comment]
@EddyVinck I think you actually want to use `stateReducer`. `onStateChange` is used for triggering actions based on the state that changed. If you want to tweak the actual state change, then `stateReducer`.

https://www.downshift-js.com/use-select#state-reducer
