### ISSUE TITLE
Updating Downshift.defaultHighlightedIndex does not update the render prop

### ISSUE THREAD

**Issue by adrienharnay** [downshift-js/downshift#956]
- `downshift` version: 4.0.8
- `node` version: 12.14.1
- `npm` (or `yarn`) version: yarn 1.21.1

**Relevant code or config**

```javascript
<Downshift defaultHighlightedIndex={value}>
  {({ highlightedIndex }) => <div>{highlightedIndex}</div>
</Downshift>
```

**What you did**:

Update `value` from 0 to 9 (I have 10 options).

**What happened**:

`highlightedIndex` does not update. Downshift's state reducer is invoked, but nothing changes (especially not `state.highlightedIndex`).

**Reproduction repository**:

https://codesandbox.io/s/quirky-chandrasekhar-98q59?fontsize=14&hidenavigation=1&theme=dark

**Problem description**:

Editing defaultHighlightedIndex can be useful, e.g. when you have a component for picking dates, and Downshift is used to pick the time. Depending on the date, the "suggested time" could be different. Right now, it's not updating `highlightedIndex` from the render props

**Suggested solution**:

I guess `highlightedIndex` should update and this is a bug

**Comment by silviuavram** [comment]
`defaultHighlightedIndex` is there to provide a value after each `reset` action. Like selecting an item for instance. Or hitting `Escape` in the input. Or calling the `reset` method received by the render prop. It's like a fallback value.

Maybe what you want is to control `highlightedIndex` directly, so use your own stateful `highlightedIndex` and pass it down as a prop to Downshift. In combination with onStateChange or stateReducer you should achieve your logic.

Good luck!

**Comment by adrienharnay** [comment]
Ah, I see. Thanks!
