### ISSUE TITLE
useCombobox's onStateChange is called with props that didn't change, without `type`

### ISSUE THREAD

**Issue by lewisl9029** [downshift-js/downshift#963]
- `downshift` version: 5.0.3
- `node` version: n/a
- `npm` (or `yarn`) version: n/a

**Relevant code or config**

https://codesandbox.io/s/usecombobox-usage-lmim4

**Problem description**:

I added a onStateChange handler to the useCombobox example that logs the changes arg in the sandbox above.

According to the docs, the function should only get called with pieces of state that actually changed, and have a `type` prop. 

Unfortunately, it actually gets called with all the props every time, and it doesn't actually have a type prop.

**Comment by olavgu** [comment]
I have the same problem with the newest version of DS (5.0.3)

**Comment by silviuavram** [comment]
You are right on the first part, it should be called only with the state that is actually changed. We should look into that.

As for the `type` I believe you are referring to the `stateReducer` instead of `onStateChange`.

**Comment by lewisl9029** [comment]
Hmm interesting, maybe that part is a documentation issue then?

https://github.com/downshift-js/downshift/tree/master/src/hooks/useCombobox#onstatechange

> changes: These are the properties that actually have changed since the last state change. This also has a type property which you can learn more about in the stateChangeTypes section.

**Comment by silviuavram** [comment]
Great! We should look how it’s called for Downshift component, if it has a type there. Depending on that we should either change the hooks implementation or the documentation.

**Comment by lewisl9029** [comment]
https://codesandbox.io/s/simple-downshift-with-getrootprops-example-98jwh

Looks like the component version of downshift does include a `type` for `onStateChange`.

**Comment by silviuavram** [comment]
https://github.com/downshift-js/downshift/pull/967 review please?
