### ISSUE TITLE
[Object, Object] selection with useComboBox

### ISSUE THREAD

**Issue by stoplion** [downshift-js/downshift#964]
`"downshift": "^5.0.3",`
`"node": "10.17.0",`
`"yarn": "1.22.0"`

How do you get the selected value when using `useComboBox` when you collection looks like..

``` 
[
{
    label: 'some label',
    value: 'some value',
 },
{
    label: 'some label',
    value: 'some value',
 },
{
    label: 'some label',
    value: 'some value',
 }
]
```
Whenever I select something I get `[Object, Object]`.

**Comment by silviuavram** [comment]
Hi! Get it from where exactly?

**Comment by stoplion** [comment]
the menu
![image](https://user-images.githubusercontent.com/231343/75910183-45126380-5e02-11ea-9600-4fc43725821a.png)
![image](https://user-images.githubusercontent.com/231343/75910201-4fccf880-5e02-11ea-9aed-a86526f72021.png)

**Comment by silviuavram** [comment]
What are you printing? Can we have a codesandbox with that example?

**Comment by stoplion** [comment]
I'll put together a demo

**Comment by stoplion** [comment]
https://codesandbox.io/s/usecombobox-variations-state-reducer-tggfw
Trying to figure out where I can let the selectedItem to know to use *.label

**Comment by stoplion** [comment]
```
const comboProps = useCombobox({
    items: inputItems,
    stateReducer,
    itemToString: item => (item ? item.label : ''),
    onInputValueChange: ({
      inputValue
    }) => {
      const filteredItems = items.filter(item => {
        return item.label.toLowerCase().startsWith(inputValue.toLowerCase());
      });
      setInputItems(filteredItems);
    }
  });
```

Figured it out. Using `itemToString`
