### ISSUE TITLE
Object.entries used for hooks is not supported on IE

### ISSUE THREAD

**Issue by louisaspicer** [downshift-js/downshift#970]
- `downshift` version:  ^3.2.6
- `node` version: 12.14.1
- `npm` version: 6.13.4

**Relevant code or config**

```javascript
TypeError: Object.entries is not a function. (In 'Object.entries(Pe)', 'Object.entries' is undefined)
```

**Problem description**:
 IE crashes if app implements the `useSelect` hook because of its use of `Object.entries`.

**Suggested solution**: Use polyfill mentioned here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
```javascript
if (!Object.entries) {
  Object.entries = function( obj ){
    var ownProps = Object.keys( obj ),
        i = ownProps.length,
        resArray = new Array(i); // preallocate the Array
    while (i--)
      resArray[i] = [ownProps[i], obj[ownProps[i]]];
    
    return resArray;
  };
}
```

**Comment by silviuavram** [comment]
Or maybe a better option is to use Object.keys and refactor the use of Object.entries. Are you up for a PR? :)

**Comment by louisaspicer** [comment]
Sure! I'll give it a go

**Comment by silviuavram** [comment]
Closing this as fixed by lhttps://github.com/downshift-js/downshift/pull/971
