### ISSUE TITLE
[useCombobox] Return null for selectedItem when inputValue becomes empty string

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#976]
- `downshift` version: 5.0.5

**Problem description**:

Probably it makes sense to clear the `selectedValue` once the `inputValue` becomes empty. Having a `selectedItem` with an empty input is confusing.

**Suggested solution**:
On InputChange state event, check if `selectedItem` is defined and `inputValue` is empty. If condition applies, also return `null` for `selectedItem`.

Already `selectedItem` is made null when user clears the input with `Escape`, so the case when user removes the input by Delete/Backspace should also remove the `selectedItem`.

Should be released as breaking change as it is breaking behaviour.

**Comment by netcoding87** [comment]
Is there a solution for the suggested way? I encountered the same problem: Clearing the input with Delete/Backspace does not clear the `selectedItem`. Having a dropdown where the `selectedItem` is visually highligted makes it a little bit weird for the user

**Comment by ryanrouleau** [comment]
Encountering the same. Should be fixed
