### ISSUE TITLE
Downshift swallows Esc key presses when hosted in a dialog

### ISSUE THREAD

**Issue by MarkFalconbridge** [downshift-js/downshift#978]
- `downshift` version: 5.0.5
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:
We are hosting downshift in a <dialog> element. The dialog should close when the Esc key is pressed.

**What happened**:
Downshift input/togglebutton elements have Esc key handling code which call preventDefault on those events irrespective of whether the dropdown is open or not. Because preventDefault is called those Esc key presses don't reach the dialog and so the dialog doesn't close.

**Reproduction repository**:
https://codesandbox.io/s/downshift-examples-m4fsb
Navigate to and run the 02-complete-autocomplete.
Click the button to open the dialog containing Downshift.
Notice that when the downshift input is focused the dialog doesn't close when the Esc key is pressed.
If you click elsewhere in the dialog and then press the Esc key the dialog closes as desired.

**Problem description**:

**Suggested solution**:

**Comment by silviuavram** [comment]
Can you `preventDownshiftDefault` when `input` is clear? Will that work?

**Comment by MarkFalconbridge** [comment]
Yes, I wondered the same thing myself. I think it might.

**Comment by silviuaavram** [comment]
Re-open this if you think we should change something on our end.
