### ISSUE TITLE
hooks: pass Event in the onChange handlers

### ISSUE THREAD

**Issue by silviuaavram** [downshift-js/downshift#986]
**Problem description**:

Have onChange handlers behave as in any react event handler. Our handlers should be similar to:
```javascript
// desired state
onSelectedItemChange = (event, {selectedItem, type}) => { ... } 

// current state
onSelectedItemChange = ({selectedItem, type}) => { ... }
```

**Suggested solution**:

Pass `event` in dispatch `action` and use that in `callOnChangeProps` for all handlers (`onStateChange`, `onIsOpenChange` etc).

This is a breaking change, as it will add the `event` as first parameter to these handlers, and the second parameter will be the current first one (changes + type).

Typescript typing should also be updated.

Since we already have https://github.com/downshift-js/downshift/pull/985 that contains breaking changes to handlers, these should be both included in a breaking changes release (v6).

**Comment by francoserio** [comment]
Sorry, what happened with this?

**Comment by silviuaavram** [comment]
Nothing, there just wasn't any demand for it. If you need it and willing to create a PR, we can re-open it.
