### ISSUE TITLE
Setting highlightedIndex to certain value upon tabbing out of input

### ISSUE THREAD

**Issue by LukasDeco** [downshift-js/downshift#989]
- `downshift` version: 5.0.0
- `node` version:  ">=10.13 < 13.0.0
- `npm` (or `yarn`) version:  yarn 1.12.3

**Relevant code or config**

trying to use a stateReducer like so:
```
 const downShiftStateReducer = (state, changes) => {
    switch (changes.type) {
      case Downshift.stateChangeTypes.blurInput:
        console.log(state.highlightedIndex);
        return {
          ...changes,
          highlightedIndex: state.highlightedIndex,
        };
      default:
        return changes;
    }
```

In order to maintain the `highlightedIndex` set in the `onChange` handler in `getInputProps` like this:
```
`setHiglightedIndex(0)`
```
And then in `onKeyDown`, `highlightedIndex` is always null :(

**Problem description**:
`highlightedIndex` is always getting set to `null` when I tab out of an input. I'm trying to be able to set it to 0 in the `onChange` handler, and then when I tab out be able to use that `highlightedIndex` in the `onKeyDown` handler.

**Comment by silviuaavram** [comment]
But if you are tabbing out why would you need `highlightedIndex`? The menu will get closed, right?
