### ISSUE TITLE
Typings in useMultipleSelection: getSelectedItemProps (item vs selectedItem)

### ISSUE THREAD

**Issue by mattleonowicz** [downshift-js/downshift#998]
- `downshift` version: 5.1.0
- `node` version: irrelevant
- `npm` (or `yarn`) version: irrelevant

Docs, examples and typings are inconsistent. Sometimes getSelectedItemProps accepts object with `item` and sometimes `selectedItem`. Looking into source I think it should be `selectedItem`, but I'm not sure

**Comment by silviuaavram** [comment]
Yes, it should be `selectedItem` to avoid confusion with the `item` from the other hooks/component. Where do we have inconsistency? Can you create a PR to patch things up?

**Comment by silviuaavram** [comment]
Closing, thank you for the fix!

**Comment by silviuaavram** [comment]
@all-contributors please add @mattleonowicz for code
